### ISSUE TITLE
Feature Request: See what items are checked out to an Asset

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4774] opened 2018-01-09 19:56 UTC
#### Feature Request

On an asset that has other assets checked out, view what asset tags (and details about these assets are checked out to the asset). 

item-000556 has item-000555 and item-000554 checked out to it. 

item-000556 can be checked out to users/assets/locations as normal

**Comment by snipe** [comment] 2018-01-10 14:19
Duplicate of #4705

**Closed by snipe** 2018-01-10 14:19 UTC
Labels: ♥ feature request
