### ISSUE TITLE
Confirm asset delivery emails being sent with categories disabled

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4203] opened 2017-10-11 21:14 UTC
The issue is even with categories being set to not email "Confirm asset delivery" notifications they are still being sent. 

Workaround 
Change (.env) to be

vi /var/www/html/snipeit/.env 
MAIL_DRIVER=smtp
to
MAIL_DRIVER=log

and reload cache

php artisan config:clear

**Comment by snipe** [comment] 2017-10-11 21:15
Duplicate of #4165

**Closed by snipe** 2017-10-11 21:15 UTC
