### ISSUE TITLE
LDAP Sync Error

### ISSUE THREAD

**Issue by brosevelt** [snipe/snipe-it#5005] opened 2018-02-12 22:00 UTC
#### Expected Behavior (or desired behavior if a feature request)

Using LDAP to sync users based on 3 separate OUs representing 3 separate locations.  

-----

#### Actual Behavior

When going to "People" and choosing the LDAP Import and selecting the location, synchronization hangs for about 30 seconds then gives "Whoops, looks like something went wrong."

My LDAP Settings in Snipe:

-LDAP is enabled and I am able to Test LDAP Sync and Test LDAP Login with my LDAP Bind Username from Snipe Settings successfully.

**LDAP SSL certificate validation:** checked
**Base Bind DN:** DC=mydomain,DC=com
**LDAP Filter:** &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
**Username Field:** samaccountname
**Last Name:** sn
**LDAP First Name:** givenname
**LDAP Authentication query:** samaccountname=
**LDAP Version:** 3
**LDAP Email:** mail

In "Settings > Locations", the LDAP Search OU format I'm using is:
OU=Employees,OU=Location1,OU=Country,DC=mydomain,DC=com

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
_Fresh_

- Version of Snipe-IT you're running
_v4.1.11-pre build 3299 (g3acf5f7)_

- Version of PHP you're running
_7.0.22-0ubuntu0.16.04.1_

- Version of MySQL/MariaDB you're running
_mysql Ver 14.14 Distrb 5.7.21_

- What OS and web server you're running Snipe-IT on
_Ubuntu 16.04 with Apache/2.4.18_

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_Git clone command from documentation_

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
_(1/1) ErrorException: Trying to get property of non-object in LdapSync.php_
-[LDAP Error.pdf](https://github.com/snipe/snipe-it/files/1717855/LDAP.Error.pdf)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
_mydomain.com/users/ldap_

- If a stacktrace is provided in the error, include that too.
_NA_

- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
_Can't configure LDAP in demo_

- Include any additional information you can find in `storage/logs` and your webserver's logs.
_no errors in storage/logs_

- Include what you've done so far in the installation, and if you got any error messages along the way.
_No errors in setting up snipe or anything. First error appeared when trying to set up LDAP and LDAP Search OUs in locations._

- Indicate whether or not you've manually edited any data directly in the database
_Have not manually made changes_

Please note, I'm not what I would call a "Linux expert" by any means.  I have set up a few Snipe Instances via Ubuntu but never on version 4 or higher.  I've had LDAP working on previous installations using the "older method" but for some reason cannot get this one to successfully import.  Thank you so much for taking any time to help out.

**Comment by snipe** [comment] 2018-02-14 05:09
Duplicate of #4923. We have a possible fix out on the develop branch, if that's something you can pull down easily.

**Closed by snipe** 2018-02-14 05:09 UTC
Labels: ldap

**Comment by brosevelt** [comment] 2018-02-14 16:35
Just changed the code as referenced and it worked great.  Thanks!
