### ISSUE TITLE
Currency Problem in Assets

### ISSUE THREAD

**Issue by chreichwein** [snipe/snipe-it#5392] opened 2018-04-18 09:58 UTC
[x ] I have enabled debug mode
[x ] I have read checked the Common Issues page
Fresh install
Snipe IT Version v4.2.0 - build 3479 (master)
PHP 7.1
MariaDB 10.0
Windows Server 2012 R2 IIS
GitHub installation

Here is my localization setting:
![image](https://user-images.githubusercontent.com/36449487/38925491-0f2e8a74-4300-11e8-88e2-12869868bc9c.png)

My currency is EURO, so if I set a purchase cost, it will be look like "10,50" with a comma not a point.
I can't use a comma here see screenshot:
![image](https://user-images.githubusercontent.com/36449487/38924882-612745a2-42fe-11e8-8b5e-2b7187dc4142.png)

If I use a point like "10.50" it gives me a total wrong price: 
![image](https://user-images.githubusercontent.com/36449487/38924960-93ec9d0c-42fe-11e8-9877-d0b8e12388cc.png)

In the accessories I have the same issue but its a bit different. I can use a comma but then the price gonna  change like in the assets. I set "100,50" and it makes "10050.00"
![image](https://user-images.githubusercontent.com/36449487/38925203-33ca454a-42ff-11e8-8dd8-e3c1700269ee.png)
If I use a point here like "100.50" then it works, i get the correct price.

In the DB it's correct, I even see it like it should be with a comma: 
![image](https://user-images.githubusercontent.com/36449487/38925354-a80bde78-42ff-11e8-9b82-0aac4e9fa6f9.png)

Can you guys help me to fix this issue? 
It would be nice if I can use a comma and get the correct price format.

Thanks :-)

**Comment by snipe** [comment] 2018-04-23 21:18
Duplicate of #4930

**Closed by snipe** 2018-04-23 21:18 UTC
