### ISSUE TITLE
Accessory checkout error with acceptance-bug?

### ISSUE THREAD

**Issue by Yenh** [snipe/snipe-it#1881] opened 2016-03-24 20:01 UTC
Hi Snipe:
I got an error when I do accessory checkout with acceptance enable.
There are no issue on asset checkout with acceptance enable.
Please help.

System Info:
Cent O.S 7
httpd  2.4.6-40.el7.centos
Snipe-IT v2.1.0-55-g701c16f
PHP 5.4.16
Laravel 4.2.17

![snipe-bug](https://cloud.githubusercontent.com/assets/18057744/14029320/c0d48bd8-f1d7-11e5-8638-acc05a1881b0.png)

**Comment by snipe** [comment] 2016-03-24 20:03
Duplicate of https://github.com/snipe/snipe-it/issues/1834

**Comment by snipe** [comment] 2016-03-24 20:04
Acceptance isn't actually supposed to work at all for accessories, only assets.

**Closed by snipe** 2016-03-24 20:03 UTC
Labels: duplicate

**Comment by Yenh** [comment] 2016-03-24 20:08
Thanks for the help.
