### ISSUE TITLE
When importing assets from CSV with custom fields, blank values populated with previously used values

### ISSUE THREAD

**Issue by liquidfire228** [snipe/snipe-it#4798] opened 2018-01-11 18:10 UTC
#### Expected Behavior (or desired behavior if a feature request)

Importing from a csv with custom fields, expected behavior would be that blank values (that are not on required fields) would end up in the system as blank.
-----

#### Actual Behavior

Values that are blank are filled in with a seemingly random value, that has appeared before in another row. If the entire column is blank (exactly 0 rows are utilizing that column at all), then the value will accurately be a blank.

This is completely breaking importing from csv with custom fields for me!

I am on version v4.1.8-pre - build 3034 (master)

-----
I believe I have identified exactly where this bug came from. Glancing at the code in AssetImporter.php, there is commented out line that should be setting custom field value to an empty string when that particular custom field isn't set for that row. By commenting this out, I think it is using values from previous rows as it never gets zeroized anywhere. 

 ```
  protected function handle($row)
    {
        // ItemImporter handles the general fetching.
        parent::handle($row);

        if ($this->customFields) {

            foreach ($this->customFields as $customField) {
                $customFieldValue = $this->array_smart_custom_field_fetch($row, $customField);
                if ($customFieldValue) {
                    $this->item['custom_fields'][$customField->db_column_name()] = $customFieldValue;
                    $this->log('Custom Field '. $customField->name.': '.$customFieldValue);
                } else {
                    // This removes custom fields when updating if the column doesn't exist in file.
                    // Commented out becausee not sure if it's needed anywhere.
                   //  $this->item['custom_fields'][$customField->db_column_name()] = '';
                }
            }
        }
```

It looks like this bug was introduced in (More importer fixes #4516). 

https://github.com/snipe/snipe-it/pull/4516/files#diff-150dcbfb168dda1f9171ca23506c12b1

The comment accompanying the change doesn't make sense, the original line was never "removing custom fields" as far as I can tell it was simply making sure the value was properly reset/zeroized on a row by row basis if that particular row didn't have a value for that column.

I simply removed the comment on my local instance of AssetImporter.php, and everything is working exactly as expected now.

**Comment by snipe** [comment] 2018-01-16 05:43
@dmeltzer - can you take a peek?

**Comment by EarlRamirez** [comment] 2018-01-18 20:26
@liquidfire228 I am seeing the same behaviour looks like this may be a bug.

**Comment by tarrahg** [comment] 2018-03-13 13:35
I am also seeing the same behavior.

**Comment by Metal0gic** [comment] 2018-03-27 19:42
i'm also seeing this behaviour and uncommenting this line fixed it.

**Comment by dmeltzer** [comment] 2018-03-27 22:53
Hello,

Thanks for reporting this issue and suggesting a fix.

The fix suggested causes a regression, however.  If you perform a future import to update assets and do not include the custom field in the import, the value will be dropped from the database (See ImporterTest@testUpdateAssetIncludingCustomFields--which breaks with this change).

I'll look into a more complete fix for this shortly--until then, please be aware of the potential issues your changes may cause.

**Closed** 2018-03-29 02:02 UTC
Labels: :question:  not sure if bug, importer
