### ISSUE TITLE
App shows wrong version

### ISSUE THREAD

**Issue by SebastianStuepp** [snipe/snipe-it#1429] opened 2015-12-02 15:34 UTC
Hi,

after upgrading to the latest version 2.0.6, my application now shows "Snipe-IT version	v2.0.5-pre-191-g948be5c"

I downloaded the zip file, replaced all files on the server and ran the upgrade commands:

 php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

Everything works and I checked some of the new functions, like LDAP settings, that moved to the settings page now, and all looks good. Just the version is displayed wrong?
![snipeit](https://cloud.githubusercontent.com/assets/16120414/11535078/8979b8de-9912-11e5-88dc-2fda4c009a8a.PNG)

**Comment by brianjking** [comment] 2015-12-02 16:36
@SebastianStuepp looks to be a duplicate of https://github.com/snipe/snipe-it/issues/1405

**Closed** 2015-12-02 19:49 UTC
