### ISSUE TITLE
Allow the saving of Custom Reports in the WebUi

### ISSUE THREAD

**Issue by jkmiller-fastly** [snipe/snipe-it#7281] opened 2019-07-22 14:41 UTC
**Server (please complete the following information):**
 - Snipe-IT Version - v4.6.3 build 3876 (g5db5134ae)
 - OS: [e.g. Ubuntu, CentOS] - Ubuntu
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version - 7.0.33-0ubuntu0.16.04.5

**Is your feature request related to a problem? Please describe.**
Currently, I run certain reports, per location, device, status. When I am trying to order for an office that is remote I pull a report with certain criteria. Instead of always have to reproducing the report being able to save a report query in the WebUI along with sharing it or making it a private query would be bice. 

**Describe the solution you'd like**
I would like to see a button that says "Save Report" Then after clicking Save Report, have the ability to make it a private report or a public report. Then under the Reports Category would be Saved reports, which you can click on and view all private and public reports. 

**Describe alternatives you've considered**
Snap shotting the report fields and saving in a Google Doc or Confluence page

**Additional context**
Jamf has a decent reporting feature, but looking to be able to quickly query things, with clickable links, and maybe even being able to turn these links in a Dashboard.

**Comment by snipe** [comment] 2019-08-15 08:39
Duplicate of #4616

**Closed by snipe** 2019-08-15 08:39 UTC
