### ISSUE TITLE
Attempting to delete a consumable generates error 

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1222] opened 2015-10-05 13:19 UTC
```
Error: admin/consumables/message.assoc_users
```

![screenshot10-5-1509 19](https://cloud.githubusercontent.com/assets/6786817/10281392/2cb256cc-6b42-11e5-9057-b87171ae4607.png)

**Comment by ddreier** [comment] 2015-10-05 14:10
Duplicate of #1136 :)

**Closed** 2015-10-06 21:45 UTC
Labels: duplicate
