### ISSUE TITLE
[feature request] Filter from listall

### ISSUE THREAD

**Issue by Aaranaw** [snipe/snipe-it#2888] opened 2016-11-07 11:56 UTC
Hello, please could you implement a filter at the list all menu, there is the exist sort option, however I would like to be able to, for example, show only Desktops and Laptops categories and exclude monitor and server categories.

Thank you.

**Comment by grandmamoses** [comment] 2016-11-09 06:59
I like this, Having filter options in the "List All", based on asset fields would be very useful.

Thanks!

**Comment by snipe** [comment] 2017-03-29 12:34
Closing as duplicate of #1728

**Closed by snipe** 2017-03-29 12:34 UTC
Labels: feature request
