### ISSUE TITLE
[Request] When changing an asset's model, don't clear custom fields if has the same fieldset 

### ISSUE THREAD

**Issue by quacktacular** [snipe/snipe-it#5036] opened 2018-02-16 17:31 UTC
#### Expected Behavior (or desired behavior if a feature request)

Let's say an asset has a custom fieldset with fields for CPU, RAM, Storage and Group. If we change model to one with same custom fieldset, the data in custom fields should be preserved.

Use case: we have hundreds of assets imported from a spreadsheet--and many of the models were misspelled or duplicated (MacBook Pro 13", mac book pro 2015, MacPro early 2015: these are all the same phyiscal model). I want to select one model for all of these without losing custom field data.  

-----

#### Actual Behavior

Currently when editing an asset's model on the Asset Update page, changing the model causes custom fields to be cleared. Even if the custom fieldset attached to the new model is the same.

**Comment by snipe** [comment] 2018-02-16 19:26
Duplicate of  #4993

**Closed by snipe** 2018-02-16 19:26 UTC
