### ISSUE TITLE
Feature Request: Custom field for new User

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5326] opened 2018-04-09 08:29 UTC
Hello Snipe-IT Dev Team

It would be great if we can add custom fields for users (new users etc..).
- area
- etc..

I hope you will implement this feature in new versions.

Kind regard,

Flavio

**Comment by snipe** [comment] 2018-04-09 21:06
Duplicate of #4261

**Closed by snipe** 2018-04-09 21:06 UTC
