### ISSUE TITLE
No download button for files uploaded against a License

### ISSUE THREAD

**Issue by itsupportcmsukorg** [snipe/snipe-it#5538] opened 2018-05-15 08:30 UTC
- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to download files that have been uploaded against a License, the download buttons are absent. 

**To Reproduce**
1. Go to 'Licenses section'
2. Select a license
3. Upload a file
4. Unable to download the file, button missing

Repeatable on Snipe DEMO site version v4.3.0 - build 3559 (master)

**Expected behavior**
A download button available similar to Assets section.

**Screenshots**
![snipe_license_file_download](https://user-images.githubusercontent.com/15633547/40045375-0aa66e04-5822-11e8-9973-4f81d63c6ee4.png)

**Server (please complete the following information):**
 - Snipe-IT Version **v4.3.0 - build 3586 (master)**
 - OS: **Debian 8.4**
 - Web Server: **Apache**
 - PHP Version **5.6.33+deb8u1**

**Comment by snipe** [comment] 2018-05-16 20:08
Duplicate of #5501

**Closed by snipe** 2018-05-16 20:08 UTC
