### ISSUE TITLE
Checkout Component/Asset to Asset

### ISSUE THREAD

**Issue by ideaman24** [snipe/snipe-it#2236] opened 2016-07-08 16:46 UTC
I have a situation where I am tracking some hotspots and laptops. Each hotspot is designated to a specific laptop that changes users. I am looking to checkout the hotspot to an asset. I can do it through License or the new Component feature in v3, however components do not let you track serial numbers. I can use License, however I am trying to keep it organize properly.

**Comment by dmeltzer** [comment] 2016-07-11 17:02
Is it more reasonable for components to be able to have serial numbers or for assets to be checked out to assets? My feeling is the former... not sure what others think.

**Comment by ideaman24** [comment] 2016-07-11 18:16
The way components are setup, I think that asset-asset would be more reasonable. However, I would still consider a video card a component, and I may track each individual card to the asset it is in.

**Comment by skleinau** [comment] 2016-08-22 11:49
Hello,

having a serial number field in components would be a great advantage. Right now we have a huge overhead by managing components as assets due to the need of tracking the serial.

Quite often this leads into inconsistencies as the machine itself get checked in but a video card or ssd is forgotten to be checked in again. Having the components being seized and assigned to the asset would resolve this issues.

Thanks
Stefan

PS: The header of the thread might be miss leading ;)

**Comment by vHouseChris** [comment] 2016-11-18 15:51
I second ideaman24's thoughts! I would find the ability to create asset-asset relationships a big plus. Or having a larger set that could combine multiple assets. We put several serialized assets together in a kit. If the assets could be checked out to a "kit" or "set" and the set in turn checked-out to a user. Although I suppose this can somewhat be accomplished with bulk checkout. But without a "Set:Asset" relationship, you couldn't run a report that would bring up which assets are currently assigned to a particular set.

**Comment by skleinau** [comment] 2016-11-21 07:49
Hello,

thanks for implementing the Serial Number field into components but as my team just got back to me, I have to back the other comments in this thread. The issue is the same as with licenses where we are not able to track licenses per seat (yes, there are licenses that need a specific key per seat and are not CCU).

So components would best to be setup to be also categorized by model (like with assets).

Thanks
Stefan

**Comment by razmi** [comment] 2016-12-19 08:38
Hello,

Firstly, thanks for this wonderful snipe-IT. I also agreed with ideaman24 and vHouseChris. Having that function for asset - component relationships will be really great!

**Comment by DavidGuder** [comment] 2017-02-13 13:16
+1 for the feature to checkout assets to assets. We have different assets that work together as a unit like a mother board and a daughter board in the lab, they need to be inventoried seperately but at the end tey are put together and work as one. the possibility to connect assets would be awsome!

Cheers
David

**Comment by arsen0** [comment] 2017-02-17 18:41
+1 for that feature, really important.
If we're going to checkout a component to an asset, we obviously need to be able to check it back in.
Thanks a lot

**Comment by longchihang** [comment] 2017-02-23 16:01
Hi all, I have modified the official v3.6.3 build 15 source. I changed the component as asset, and the new component  can choose the base model from Asset Model (I changed the menu to Asset/Component Model) .  Moreover, I also fix the #2336 (Component cannot be unassigned from an asset) problem. I added a "checkin" button to the Compoent of Asset view.
![capture1](https://cloud.githubusercontent.com/assets/22152420/23266820/ddcd8bae-fa23-11e6-9e4b-65a5ccd9d805.PNG)
![capture2](https://cloud.githubusercontent.com/assets/22152420/23266832/e366dfa2-fa23-11e6-8f62-7df722bbaf11.PNG)
![capture3](https://cloud.githubusercontent.com/assets/22152420/23266835/e653e87c-fa23-11e6-9abb-de2f4a3f76e5.PNG)
![capture4](https://cloud.githubusercontent.com/assets/22152420/23266839/e8ff9206-fa23-11e6-97a2-99a6ecfdc272.PNG)

Download the patch file [https://github.com/longchihang/snipe-it/blob/master/snipeit_compoent-as-asset_diff-path_for%20v3.6.3%20build%2015.zip](url)
unzip to replace the original files of v3.6.6 build 15. And run the "add-fields-for-compoent-as-asset.sql" to insert fields to database.

**Comment by arsen0** [comment] 2017-03-01 21:13
In which stable release will that be included ?

**Comment by longchihang** [comment] 2017-03-04 14:52
Hi arsen0, I am not the main contributor. I just a user to mod to suit my company request. If you want to try this mod, just download the zip file and extract to snipeit folder (maybe /var/www/html/snipeit in CentOS), and run the "add-fields-for-compoent-as-asset.sql" to modify the table in DB.

**Comment by snipe** [comment] 2017-03-11 00:55
Is there any reason this wasn't done as a pull request?

**Comment by longchihang** [comment] 2017-03-11 05:31
snipe, I just worry that I have changed many codes and will affect your design.

**Comment by TonisOrmisson** [comment] 2017-05-04 07:55
+1 for the feature to checkout assets to assets.
A simple case. Phones/tablets have SIM cards. Then the Phone is replaced and the SIM travels to another device. So SIM needs to be able to be checked-in and checked out again to another device. 

It really seems easiest if an asset could be simply checked out to another asset. Also this enables the SIM to have custom fieldsets (phone, number, operator etc).

**Comment by Samgarr** [comment] 2017-08-31 14:11
+1 for this feature

**Comment by snipe** [comment] 2017-08-31 23:28
Checking out assets to other assets (and locations) is in the upcoming v4

**Closed by snipe** 2017-08-31 23:28 UTC
Labels: feature request

**Comment by arsen0** [comment] 2017-08-31 23:43
Do you have an approximate release date ?

Thanks
