### ISSUE TITLE
How to checkin components for reassign to another machine.

### ISSUE THREAD

**Issue by ashirv** [snipe/snipe-it#2958] opened 2016-11-22 09:10 UTC
I would like request you please create a option for Checkin (same as like accessories/asset )component for reassign to another machine. We frequently upgrade and degrade machine's memory (RAM) based on the requirements. I hope for your immediate response on this matter.

Thank you.

**Comment by snipe** [comment] 2016-11-22 22:13
Closing as duplicate of https://github.com/snipe/snipe-it/issues/2878

**Closed by snipe** 2016-11-22 22:13 UTC
