### ISSUE TITLE
Link Custom Fields to existing models/data

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1590] opened 2016-01-06 17:13 UTC
is it possible  to link custom field with users? indeed i would like to add another classification for users for Ex. user can be either local staff or international ..

**Comment by snipe** [comment] 2016-01-07 10:31
That is not currently possible.

**Comment by snipe** [comment] 2017-10-19 10:14
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:14 UTC
Labels: advanced, backend, php, roadmap
