### ISSUE TITLE
Check out more than one accessory and consummable at a time

### ISSUE THREAD

**Issue by thehockeygeek** [snipe/snipe-it#2796] opened 2016-10-21 13:41 UTC
Feature Request
#### Expected Behavior (or desired behavior if a **feature request**)

When checking out consumables or accessories. Add a field/ability to check out more than one. (Add a quantity field)

---
#### Actual Behavior

Currently must continually check out one at a time. This is fine until a technician has a mass deployment. It would save a lot of time.

**Comment by vipbk09** [comment] 2016-11-21 06:09
I'm needing the function as you.

**Comment by rustydahlin** [comment] 2017-05-26 15:32
Any advancement on this? This would be a big feature for our Agency.

**Comment by raakhtar** [comment] 2017-11-15 15:37
When will it be added ? @snipe

**Comment by Weaksid** [comment] 2017-12-07 13:30
I also think this should be added as a feature. It's a little hard to get accurate reports when you need to sign out 40 of something like batteries (yes, we give out batteries sometimes for tech stuff) to someone and the only way to do it is do checkout 40 times or modify the total amount after checking one out. Looks like I found a request for this in Dec of 2015 while searching for a status of this type of request.

Thank you for your hard work on this project.

**Comment by stahlei** [comment] 2017-12-12 09:13
Would be a great feature!!

**Comment by snipe** [comment] 2018-04-05 03:11
Duplicate of #1046

**Closed by snipe** 2018-04-05 03:11 UTC
Labels: :heart: feature request, :woman_technologist: ready for dev

**Comment by Trog3r** [comment] 2018-04-24 19:25
Looks like there are three requests for this (#1046, #1511, & #2796), but they were all closed because they were duplicates :) I'm thinking one of these should stay open??

Oh and I also up vote this request as it would be very helpful.
