### ISSUE TITLE
LDAP Issues in Snipe IT

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1508] opened 2015-12-21 14:55 UTC
After LDAP is configured and sync.
1. We are able to see the users imported But if next time a particular user is deleted from active directory. Again if we ll sync the users and the problem the user which is deleted in Active directory will not be remove from snipe it users. I think @snipe it may be a bug. or you have any other way.
If i go and delete it directly i will get error msg. 
The error snapshot is below.
![capturldapdele](https://cloud.githubusercontent.com/assets/16305213/11933040/6b73d72c-a81f-11e5-9590-e4f6ee310ff4.JPG)

And in above picture you see red mark. I have loaded the icon buts its not appearing 
@snipe what is pixel your accepting for that icon. I tried with all pixel like 16*16, 32*32, 24*24 and even higher pixel also 64*64 128*128. But icon is not loading up.
Can u help me out of this?

Final Problem and doubt i have after LDAP users sync to snipe it database. Whether user can login in user ldap account? @snipe i want know whether its possible. I tired to login with Ldap credential. its failed. How the username should be written Example ind/mahesh or mahesh@ind.com or mahesh.. (Note Ind is my domain name)
I tired all things it wont login using LDAP authentication @snipe this all my issue. Please help out of this?

**Comment by snipe** [comment] 2015-12-22 08:08
Please check your user permissions by finding your currently logged in user and checking the Permissions Tab in the Users section. Make sure Super Admin is checked.

**Comment by mahesh2471990** [comment] 2015-12-22 15:12
@snipe Thank You so much. It worked. User i can delete.
What about that Icon in homepage is not appearing  and whether the most important LDAP user login?
After i imported user whether user can login using their own Active Directory Credential??? Actually @snipe it didnt work.

**Comment by mahesh2471990** [comment] 2015-12-24 06:58
@snipe Hello i am waiting for your solution.. Can u help me out from those problems

**Comment by snipe** [comment] 2015-12-24 08:51
http://docs.snipeitapp.com/manual/user-management/index.html

**Comment by snipe** [comment] 2015-12-24 08:52
I have no idea why your icon isn't showing up. Logo upload works fine.

**Comment by mahesh2471990** [comment] 2015-12-24 11:08
@snipe IS there is any certain size or resolution or format for that?

**Comment by mahesh2471990** [comment] 2015-12-28 08:03
The most important LDAP user login?
After i imported user whether user can login using their own Active Directory Credential??? Actually @snipe  it didnt work.  Can u help me regarding this.

**Comment by mahesh2471990** [comment] 2015-12-28 11:40
@snipe I am finding day by day many bugs and improvement required in LDAP.. we should work on this very hard. Today another Issue i found.   
Sync LDAP users.
Scenerio 1
IF WE SYNC A BULK USERS FROM LDAP ACTIVE DIRECTORY.
Later if i do any change in User attribute in Active Directory. then we sync again.. change will not reflect on  LDAP users list in Snipe IT (Peoples). 

@snipe I know you are busy. can u atleast assign to your colleague who work on SNipe IT. Know well about ldap.
Because I am stuck with all those LDAP problems. In production environment. @snipe please help to out? 

ISSUES in LDAP
1 Not able to Login snipe IT using LDAP users credential
>>>>> When i login username and password using LDAP username and password. snapshot below. user was Imported from Ldap and password used is Users active Directory password. Does it  work using Active Directory users password.
![44](https://cloud.githubusercontent.com/assets/16305213/12018063/5d84858e-ad84-11e5-8144-a9e30a54ca40.jpg)
 
2 Bulk Delete wont work in SHOW DELETED USER (Snapshot Below)
![1](https://cloud.githubusercontent.com/assets/16305213/12017820/7b7f1606-ad81-11e5-9b63-482391585f53.JPG)
 
>>> after Clicking Show Deleted users
>>>> I marked all users and Bulk delete Clicked on GO (snapshot below)

![22](https://cloud.githubusercontent.com/assets/16305213/12017832/a6547dc6-ad81-11e5-80ed-c33bd6401d19.jpg)
 
>>>After Click Go you can see the Snapshot  below its asking for? 

![33](https://cloud.githubusercontent.com/assets/16305213/12017929/c59b15b8-ad82-11e5-92e0-17e6272710d1.jpg)

3 Indian Currency Required. and Main problem during LDAP Sync. I have sync success fully and users are imported. IF i do any change in Active Directory Users Attribute.and again i will sync in LDAP users In snipe IT. the modified made in attribute should be changed or reflected to user. But it didnt work/ Change wouldnt be updated. IT may be added for roadmap or any other configure should i work.

**Comment by snipe** [comment] 2016-01-06 03:38
#1 should be resolved in 2.1.0-pre. We still do not update attributes though. Users are skipped if they already exist. The only thing that updates is the password stored in the database.

#2 "Bulk Delete wont work in SHOW DELETED USER (Snapshot Below)" - If you're already on the Deleted Users page, those users have already been deleted. What are you expecting to have happen here, exactly? If you're getting a 500 error, you have to provide logs. We have no way of knowing what the issue is without them.

#3 Indian Rupee was already added.

**Comment by snipe** [comment] 2016-01-06 03:38
Also please do not list multiple issues in a single ticket. One ticket per issue.

**Closed** 2016-01-06 03:38 UTC

**Comment by mahesh2471990** [comment] 2016-01-06 07:05
@snipe Thank You.
After this up gradation successfully done,  i will test it properly again. I will get u back. If any other isuue
