### ISSUE TITLE
Backup issue - xxdb.sql directory does not exist.

### ISSUE THREAD

**Issue by Litan7** [snipe/snipe-it#1898] opened 2016-03-30 01:51 UTC
#### Expected Behavior (or desired behavior if a feature request)

Backup manually from Admin > Backup

-----

#### Actual Behavior

Whoops!
Server Error: 500 (Internal Server Error)

However model images can be backup successfully.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v2.1.0-47-g39f40a3 
- What OS and web server you're running Snipe-IT on
Windows 7 Pro + XAMPP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation, XAMPP, Composer, created empty DB etc., by following the guide on website
- If you're getting an error in your browser, include that error
Server Error: 500 (Internal Server Error)
However model images can be backup successfully.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
The Backup feature only
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
This feature has been disabled for this installation.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[01:41:46] LOG.error: exception 'InvalidArgumentException' with message 'The "C:\xampp\htdocs\snipeit\app\storage/dumps/2016033014146-db.sql" directory does not exist.' in C:\xampp\htdocs\snipeit\vendor\symfony\finder\Symfony\Component\Finder\Finder.php:677
Stack trace:
#0 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(285): Symfony\Component\Finder\Finder->in('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\snipeit\vendor\chumper\zipper\src\Chumper\Zipper\Zipper.php(361): Illuminate\Filesystem\Filesystem->directories('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\snipeit\vendor\chumper\zipper\src\Chumper\Zipper\Zipper.php(157): Chumper\Zipper\Zipper->addDir('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\snipeit\app\commands\SystemBackup.php(55): Chumper\Zipper\Zipper->add('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): SystemBackup->fire()
#5 C:\xampp\htdocs\snipeit\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#6 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#7 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Console\Application.php(101): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#8 [internal function]: Illuminate\Console\Application->call('snipe:backup')
#9 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Artisan.php(57): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Foundation\Artisan->__call('call', Array)
#11 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Foundation\Artisan->call('snipe:backup')
#12 C:\xampp\htdocs\snipeit\app\controllers\admin\SettingsController.php(232): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#13 C:\xampp\htdocs\snipeit\app\controllers\admin\SettingsController.php(232): Illuminate\Support\Facades\Artisan::call('snipe:backup')
#14 [internal function]: Controllers\Admin\SettingsController->postBackups()
#15 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postBackups', Array)
#17 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'postBackups')
#18 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postBackups')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#21 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\snipeit\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#27 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#28 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#29 C:\xampp\htdocs\snipeit\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#30 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\snipeit\public\index.php(49): Illuminate\Foundation\Application->run()
#32 {main}

 InvalidArgumentException

The "C:\xampp\htdocs\snipeit\app\storage/dumps/2016033014146-db.sql" directory does not exist.
Open: C:\xampp\htdocs\snipeit\vendor\symfony\finder\Symfony\Component\Finder\Finder.php

     
            foreach ((array) $dirs as $dir) {
                if (is_dir($dir)) {
                    $resolvedDirs[] = $dir;
                } elseif ($glob = glob($dir, GLOB_BRACE | GLOB_ONLYDIR)) {
                    $resolvedDirs = array_merge($resolvedDirs, $glob);
                } else {
                    throw new \InvalidArgumentException(sprintf('The "%s" directory does not exist.', $dir));
                }
            }
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment] 2016-03-30 02:19
Duplicate of https://github.com/snipe/snipe-it/issues/1483 and https://github.com/snipe/snipe-it/issues/1747

**Closed by snipe** 2016-03-30 02:19 UTC
