### ISSUE TITLE
snipe-it installation issue 

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#581] opened 2015-03-02 09:31 UTC
Dear All ,

 i am facing the following issue while installation of snipe-it  on Centos 6.5 .please help me to figure out the problem .i use mysql 5.5

ErrorException (E_UNKNOWN)

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select * from `settings` where `settings`.`id` = 1 limit 1) (View: /var/www/html/snipe-it-1.2.5/app/views/backend/layouts/default.blade.php) (View: /var/www/html/snipe-it-1.2.5/app/views/backend/layouts/default.blade.php)

**Comment by madd15** [comment] 2015-03-02 10:24
Same as #582

**Comment by snipe** [comment] 2015-03-04 22:06
Closing as duplicate of #582

**Closed by snipe** 2015-03-04 22:06 UTC
Labels: duplicate
