### ISSUE TITLE
Software subscription

### ISSUE THREAD

**Issue by liceng** [snipe/snipe-it#6347] opened 2018-10-19 08:26 UTC
Snipe-IT version: v4.6.4 build 3881 (g522dc1db2)
OS: Ubuntu 16.04
Web: Apache
PHP: 7.0.30

A lot of software today is being sold as "subscription" licenses and as such it would be very helpful to be able to register software licenses with subscription costs, and subscription length (monthly, quarterly,  yearly, etc).
An example of this could be Office365 licenses, Adobe, Autodesk etc - more and more software today is moving from perpetual licenses to subscription based.

**Comment by snipe** [comment] 2018-10-19 09:13
Duplicate of #5673

**Closed by snipe** 2018-10-19 09:13 UTC
