### ISSUE TITLE
Manager Option Needed more things

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#5734] opened 2018-06-22 08:11 UTC
Snipe-IT Version 4.4.0
    OS: Windows Server 2016
    Web Server: IIS
    PHP Version 5.56

**Is your feature request related to a problem? Please describe.**
When Manager login as normal user. He is able to see his **view assigned asset**. **but he should also able to view this user information (i mean all users reporting to him).** 
That time Purpose of Manager role will be used properly in Snipe IT tool.
Now if we add a manager to the user what is the use? (Nothing rather than permissions)
**Describe the solution you'd like**
I would like to tell you to add one more option whoever is a manager who log-in will be able to view reported USERS assets.

Example see the screenshot. I am a manager now. I see my checkout assets by default. I want to add one more option like requested below image. 
Add Reported User assets soemthing like that. Once you click you can information of Reported users assets also.
The manager should be view only this Team assets, Rather than that usually Managers will be only concern of this team members and assets used by them. Because every assets approved by managers in company. 

![capture1](https://user-images.githubusercontent.com/16305213/41764279-3bbf465e-761e-11e8-9406-277934bd7812.JPG)

**Describe alternatives you've considered**
See when any user is a manager. once he has been added as manager to any user then by default that option should come. So manager role will be considered.

**Additional context**
Ldap should capture the user's Manager from Active directory also. or else we have added manually the managers for all the user. It difficult if we have more 500 users?

@snipe @uberbrady I need your support.

**Comment by snipe** [comment] 2018-06-27 10:38
Duplicate of  #2853

**Closed by snipe** 2018-06-27 10:38 UTC
