### ISSUE TITLE
Asset Model Drop down looks odd

### ISSUE THREAD

**Issue by spsdevice** [snipe/snipe-it#4665] opened 2017-12-20 20:45 UTC
#### Expected Behavior (or desired behavior if a feature request)
Before, models categories and manufacturers were all under different drop down selections, now it looks like there's only one for model and everything is compacted into it. I have no problem with this, but the layout seems a bit buggy. Not really an issue, more like a request. 

-----

#### Actual Behavior

Everything seems to compacted in the drop down menu when creating an asset. It's basically hard on the eye for visual aspects. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode No
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.1.8
- Version of PHP you're running php7.0
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error, just a layout issue
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

![image](https://user-images.githubusercontent.com/32550757/34227984-f32f0954-e583-11e7-9ff2-6457e8c95ecc.png)

**Comment by snipe** [comment] 2017-12-20 20:52
The only bug here is that the manufacturer name is listed twice, but that's a duplicate of #4663

**Comment by snipe** [comment] 2017-12-20 20:52
The only bug here is that the manufacturer name is listed twice, but that's a duplicate of #4663

**Closed by snipe** 2017-12-20 20:52 UTC
