### ISSUE TITLE
Error 500 when try to add an asset

### ISSUE THREAD

**Issue by ftp21** [snipe/snipe-it#1913] opened 2016-04-01 09:58 UTC
Hello,
When i try to add an asset i receive this Stack Trace:

[2016-04-01 11:55:18] production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsTo::associate() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in /var/www/snipeit/app/controllers/admin/AssetsController.php on line 104 and defined' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php:203
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php(203): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', '/var/www/snipei...', 203, Array)
#1 /var/www/snipeit/app/controllers/admin/AssetsController.php(104): Illuminate\Database\Eloquent\Relations\BelongsTo->associate(NULL)
#2 [internal function]: Controllers\Admin\AssetsController->postCreate()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []

How i can fix?

**Comment by snipe** [comment] 2016-04-01 10:37
Duplicate of https://github.com/snipe/snipe-it/issues/1872

**Closed by snipe** 2016-04-01 10:37 UTC
