### ISSUE TITLE
Feature request for Components

### ISSUE THREAD

**Issue by KumarPOnline** [snipe/snipe-it#6093] opened 2018-08-16 06:10 UTC
**Server (please complete the following information):**
 - Snipe-IT Version : Version v4.6.3 - build 3866
 - OS: [e.g. Ubuntu, CentOS] : Ubuntu 16.04 LTS
 - Web Server: [e.g. Apache, IIS] : Apache 2.4
 - PHP Version : PHP 7.0

**Is your feature request related to a problem? Please describe.**
We are using Components for maintain **HDD/SSD && RAM && SMPS**. In these things, Serial number will be different for each product. But at same time **Manufacturer, Model and Capacity** may be same.
But to maintain clear asset, we should have to add these things to components, else we don't get clear history of the asset.

We can add this to asset list to maintain these things but, It's really hard to maintain which asset (Desktops / laptops) have which components. And it'll give wrong results in our reports too.

**Describe the solution you'd like**
By adding these additional details to Components,
1. We can get clear history of the Components with Asset.
2. We can maintain warranty status of the Components, as it usually comes with 3 to 5 years for HDD.
3. We can get report based on it's model, where we can schedule the up-gradations if we needed.

So, It's really grateful to **Manufacturer, Model and Capacity** to components. In case of RAM we can add it's Frequency too.

**Describe alternatives you've considered**
For this, We can add these things as forms. If possible, we can add this as field-set if applicable.

**Additional context**

**Comment by snipe** [comment] 2018-08-16 21:33
Duplicate of #4421

**Closed by snipe** 2018-08-16 21:33 UTC

**Comment by KumarPOnline** [comment] 2018-08-17 04:59
Hello @snipe 

I've read the previous request that you marked with number #4421 . But they requested about multiple serial number only. But they didn't mentioned about component manufacture, model number and other properties (storage, frequency, RPM etc.) of the component. The component asset maintenance should have these things. So I request you to reopen this thread.
