### ISSUE TITLE
Feature Request Easy Installer

### ISSUE THREAD

**Issue by jrtoman** [snipe/snipe-it#592] opened 2015-03-03 16:41 UTC
Bitnami will develop this for us free of charge granted it gets enough votes.

https://bitnami.com/contest?utm_source=bitnami&utm_medium=badge&utm_term=snipe-it&utm_campaign=Application%2BContest&product=snipe-it#voted

**Comment by snipe** [comment] 2015-03-05 01:08
Closing as duplicate of #585

**Closed by snipe** 2015-03-05 01:08 UTC
Labels: duplicate
