### ISSUE TITLE
Asset Categories Viewing issues

### ISSUE THREAD

**Issue by snazy2000** [snipe/snipe-it#5453] opened 2018-04-30 13:47 UTC
#### Expected Behavior (or desired behavior if a feature request)

It limits the amount of Categories shown on dashboard or to allow the page to not be a fixed height of 400px

-----

#### Actual Behavior

![image](https://user-images.githubusercontent.com/1378836/39430246-3d0174aa-4c85-11e8-841b-8a0bbb33590f.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - NA
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - NA

-----
#### Provide answers to these questions:

- Version of Snipe-IT you're running 4.2.0
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  - yes

**Comment by snazy2000** [comment] 2018-04-30 13:50
Could also have a scroll bar like this

![image](https://user-images.githubusercontent.com/1378836/39430431-ba1611c6-4c85-11e8-9515-2392c9e8a375.png)

This was achieved by adding .table-responsive around the bootstrap-table div.

**Comment by leebaggaley** [comment] 2018-05-01 19:36
looks like this relates to my request: https://github.com/snipe/snipe-it/issues/5431

**Comment by snipe** [comment] 2018-05-02 04:28
Duplicate of #5431

**Closed by snipe** 2018-05-02 04:28 UTC
