### ISSUE TITLE
Print asset labels for accessories

### ISSUE THREAD

**Issue by AukeTembrink** [snipe/snipe-it#4714] opened 2018-01-02 16:34 UTC
Is it possible or planned to print labels/barcodes for accessories, too? We need to create labels and barcodes for accessories and components.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Yes
- Version of Snipe-IT you're running 
v4.1.9 - build 3128 (master)
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 LTS

**Comment by snipe** [comment] 2018-01-10 02:49
Duplicate of #3957

**Closed by snipe** 2018-01-10 02:49 UTC
