### ISSUE TITLE
custom fields encrypted (even if it's not)

### ISSUE THREAD

**Issue by rzhumadi** [snipe/snipe-it#2703] opened 2016-09-28 19:28 UTC
#### Expected Behavior (or desired behavior if a feature request)

When user has no admin privileges, but has full access to Assets (create,view,edit delete assets etc.), user should be able create Assets if custom fields is not encrypted. 

-----

#### Actual Behavior

New Assets cannot be created because SnipeIt shows that CUSTOM field is encrypted (even if its not encrypted). Basically unencrypted CUSTOM fields also showing up as encrypted, when creating new Assets(in case when user has full access to assets, but not admin). 
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
 It's impossible to reproduce it on demo site.

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  
          v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on
   Cent OS 7.0
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
    Install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.  
      Nothing
- Indicate whether or not you've manually edited any data directly in the database
      No

**Comment by snipe** [comment] 2016-09-28 21:46
Duplicate of #2607

**Closed by snipe** 2016-09-28 21:46 UTC
