### ISSUE TITLE
Unable to delete a "Consumable" after it has been assigned.

### ISSUE THREAD

**Issue by cbbowman** [snipe/snipe-it#1149] opened 2015-09-04 19:33 UTC
Attempt to delete a consumable that has been assigned to a user, receive error message: "Error: admin/consumables/message.assoc_users "

No apparrent way to "de-associate" the consumable with the user.

**Comment by snipe** [comment] 2015-09-09 21:05
Duplicate of #1136

**Closed by snipe** 2015-09-09 21:05 UTC
