### ISSUE TITLE
May i request to have a printable acceptance form once the users accepted the asset. Thank You

### ISSUE THREAD

**Issue by paulo1624** [snipe/snipe-it#5595] opened 2018-05-24 13:56 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment] 2018-05-24 20:47
Duplicate of #4651

**Closed by snipe** 2018-05-24 20:47 UTC
