### ISSUE TITLE
IP and MAC addresses for some assets

### ISSUE THREAD

**Issue by abazeed** [snipe/snipe-it#877] opened 2015-06-28 14:23 UTC
* It would be very helpful if I can add IP and MAC addresses for some kinds of assets like PCs and network printers and devices.
* One asset could have more than one IP address or MAC address.
* It could be managed when adding the Asset Category, because each category has its own character,  so PCs need special field differs from monitors and other devices.

* We can pre-define some special fields which are mostly needed and used.
* Or make it public, like: 5 special field, so I can choose the field name and data type.
* Or make it opened, so I can add special fields as much as I need.

**Comment by abazeed** [comment] 2015-06-28 14:27
It should be added here -after Type-, so I could choose the special fields during creating my categories.

![capture1](https://cloud.githubusercontent.com/assets/11146126/8396710/e2d8308e-1dc2-11e5-980a-a46e5425e577.PNG)

**Comment by snipe** [comment] 2015-06-28 15:40
MAC address is already available as an option, on the asset model level.

**Comment by abazeed** [comment] 2015-06-28 19:10
I couldn't find it, maybe you meant the Serial No.?

**Comment by vsposato** [comment] 2015-06-28 20:19
No, you must go to the Asset Model and enable the MAC Address field. Once you do that, then any asset of that model will automatically get the MAC Address field. I don't know how you would handle multiple MAC / IP addresses on a single record without separating it into its own separate related domain. 

@snipe Do you think it makes sense to separate 'network' off into its own domain to attach to the asset?

**Comment by abazeed** [comment] 2015-06-28 21:19
@vsposato thanks, I've got it.
In my company we have 2 intranet networks which are totally separated, one of them is dedicated for financial dept. where they are connected to there Oracle server. The other one for other departments, but some of accountants need to use both networks on there PCs, so we have some machines with 2 network ports.

**Comment by abazeed** [comment] 2015-06-28 21:27
Sometimes we need to have a report of free IPs, or the used IPs.
I think it's good to have the flexibility to add some special field for some kinds of assets, but as an IT department assets management system, I think it should handle IPs, MAC addresses, Service Tags, Network Names and....
So, you could make it fixed or opened fields, and it could be related to the asset category or the asset model. Up to you..

**Comment by ESWBitto** [comment] 2015-07-07 20:34
@abazeed why would you want to track IP addresses especially in the scenario that you have given. You "should" be having a time limit on leases for your IP addresses. Tracking them would cumbersome.

**Comment by abazeed** [comment] 2015-07-08 13:09
* Suppose I took some machines back to my store, I should release there IP addresses so I can use them later with other machines.
* In case of installing new machines, I need to have a list of used IPs to avoid conflict.
* In rare cases, I could have an IP conflict.

Last thing, this is an "IT" Assets Management System, it's obvious to handle IP addresses, I think :relaxed:.

**Comment by ESWBitto** [comment] 2015-07-08 15:16
@abazeed Do you not have a DHCP server assigning your IP addresses?

**Comment by abazeed** [comment] 2015-07-09 13:15
We're using static IPs in our company.
The major thing I need here is refusing to add an IP that's already reserved by another asset, so it could by one field (or 2 in case of 2 IPs) with a UNIQUE attribute.

**Comment by joeykhan** [comment] 2015-08-19 00:09
Also like the idea! We re growing and use ip&Mac binding via the dhcp server

**Comment by snipe** [comment] 2015-11-04 13:13
Closing as duplicate of #98 which is in progress

**Closed by snipe** 2015-11-04 13:13 UTC
Labels: advanced, backend, duplicate, enhancement, under consideration

**Comment by svcgithubtestoil** [comment] 2021-07-12 18:33
This would be a huge help in keeping server related infromation in one place. Hate having to keep a spreadsheet of thises.

Would be nice if you could do CIDR design of the IP listings. Maybe tie it to DNS ?

**Comment by uberbrady** [comment] 2021-07-12 20:01
We already have custom fields, and support both IP addresses and MAC Addresses as field types in our custom fields system for assets. You can add as many of those fields as your database will support (4096-ish if memory serves?) to an individual fieldset. However, we don't support CIDR ranges (192.168.0.0/16 for example). But those would fit just fine in a text field.

Is there a use case I'm not considering, @svcgithubtestoil ?

**Comment by wkulesza** [comment] 2022-06-18 20:44
Bumping this issue. If there's IP address and if this is assets management, would it be possible to be able to periodically ping those ip addresses to see if they're responsive and indicate this in the assets view  (asset reachable/not reachable)?
