### ISSUE TITLE
Ticket function

### ISSUE THREAD

**Issue by hainh1984** [snipe/snipe-it#6914] opened 2019-04-16 10:00 UTC
Dear Support,

As I see 1 PHP source they have Ticket Function.

It's very usefull, we should develop it..

Please see attached photo

![image](https://user-images.githubusercontent.com/49678480/56200500-2334b480-6069-11e9-8e3f-dbff780971e2.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment] 2019-04-16 19:07
Duplicate of #663

**Closed by snipe** 2019-04-16 19:07 UTC
