### ISSUE TITLE
Feature request: Bulk Checkout to Locations and Assets

### ISSUE THREAD

**Issue by Ombre007** [snipe/snipe-it#5013] opened 2018-02-14 09:37 UTC
#### Expected Behavior (or desired behavior if a feature request)

- Bulk Checkout the possibility to checkout to a location or an asset
- Bulk Checkin
-----

#### Actual Behavior

- Bulk Checkout only possible to a person
- Bulk Checkin is not available at the moment

**Comment by lostmydog** [comment] 2018-02-14 15:45
+1 for this. Would be nice to have a checkbox for bulk checkout called "Reassign Assets?", checking this would allow the user to simply assign all of their asset regardless of their current status. This would mean that if one of the assets was already checked out, it would automatically check the item in and then assign it to the intended person/place. Only issue I see arising is what to do with an asset that is input that currently has a non-deployable status. Maybe after the bulk checkout, a change-log showing the user everything that changed. This would also mean that any non-deployable asset would be reassigned to a deployable type.

**Comment by captain-hack** [comment] 2018-02-14 21:54
+1 as well. Now that we can check out to locations I have a ton of assets that need to assign to a room/building.

**Comment by worthy92** [comment] 2018-02-18 00:11
+1 Yes please!

**Comment by xarly** [comment] 2018-03-07 12:18
+1 👍  and up :)

**Comment by gitthismoney** [comment] 2018-03-12 16:07
+1

**Comment by BHollowell** [comment] 2018-03-13 21:10
+1 for me as well. This will make it a lot easier to manage since there's no option to check out assets to locations during the import process (at least as best I can determine via my testing).

**Comment by wizard210** [comment] 2018-03-22 14:30
+1. If this were possible it would make my decision of snipe vs Asset Tiger so much easier.

**Comment by BHollowell** [comment] 2018-03-22 18:39
Quick update to those looking for an easy way to do this until this feature request is implemented...

You can use the mysql CLI and run the following 4 commands to check out assets to a specific location:

UPDATE `assets` SET `assigned_to` = '' WHERE `id` = '';
UPDATE `assets` SET `location_id` = '' WHERE `id` = '';
UPDATE `assets` SET `assigned_type` = 'App\\Models\\Location' WHERE `id` = '';
UPDATE `assets` SET `last_checkout` = '' WHERE `id` = '';

Just be sure to update your assigned to and location id values in these commands to match the DB ID for the location you wish to check the assets out to.

In my case I had already imported location information with the assets, so I was able to reference the value of an existing cell to pull these automatically. This looked like this:

UPDATE `assets` SET `assigned_to` = rtd_location_id WHERE `id` = '';
UPDATE `assets` SET `location_id` = rtd_location_id WHERE `id` = '';
UPDATE `assets` SET `assigned_type` = 'App\\Models\\Location' WHERE `id` = '';
UPDATE `assets` SET `last_checkout` = '' WHERE `id` = '';

**Comment by joepitt91** [comment] 2018-03-31 18:11
I'm glad I searched as I was just about to raise the same feature request.

I have 300 odd assets to check out to 4 locations, would be so much easier to be able to go:

1. Bulk Checkout
2. Location
3. Select Location
4. Speed through assets with a Barcode scanner (like with build audit)

Rather than this for every asset:

1. Click in Search box
1. Scan Barcode
2. Actions
3. Checkout asset
4. Location
5. Select Location
6. Checkout

**Comment by snipe** [comment] 2018-04-03 19:43
Duplicate of #3343

**Closed by snipe** 2018-04-03 19:43 UTC

**Comment by mankdhodi** [comment] 2018-06-06 10:45
@snipe Hi , Everytime i fetch asset from the csv file, it misses on the checked out to field and it turns out to be blank..I have also tried to map checked out to field with full name it converts the asset into user in the checked out to column and makes new entry of an user in the people section in navigation tree....It will be great if you can tell me the proper field name for this to map it to snipe/IT...
