### ISSUE TITLE
Asset/licence/accessory groups or packages

### ISSUE THREAD

**Issue by iainhallam** [snipe/snipe-it#6896] opened 2019-04-10 15:02 UTC
**Server (please complete the following information):**
 - 4.6.15
 - OS: Debian
 - Web Server: Apache
 - PHP Version: 7.0

**Is your feature request related to a problem? Please describe.**
When people join our company we always have to check out a set of assets, along with accessories and about 20 licences. These are always the same sets, and currently it looks as though we have to go through each list of things, manually checking them out.

**Describe the solution you'd like**
A way to group assets, licences, and accessories into packages that can be assigned together. The most important of these is to be able to group together a set of licences, then check out the group, which would assign one seat from each licence.

**Comment by iainhallam** [comment] 2019-04-10 15:05
It occurs to me that when you add a licence from the group, it would be good if that automatically checked out a seat from the new licence (or warned if there weren't enough seats). If you remove a licence, that should check in the seats this group of licences was assigned to.

**Comment by snipe** [comment] 2019-04-16 19:12
Duplicate of #563

**Closed by snipe** 2019-04-16 19:12 UTC
