### ISSUE TITLE
User location deleted during snipeit:ldap-sync job

### ISSUE THREAD

**Issue by tolleiv** [snipe/snipe-it#3134] opened 2017-01-05 12:06 UTC
#### Expected Behavior (or desired behavior if a feature request)

Hi,
the [documentation](https://snipe-it.readme.io/docs/ldap-sync-login) mentions that the location and location_id parameters are optional for the `snipeit:ldap-sync` job.

When leaving them out, I'd expect that the configured location for existing users isn't modified. 

-----

#### Actual Behavior

But actually leaving them empty will remove the setting from the existing users.

This is also contrary to the UI - when leaving out the option within the dropdown in the UI, the fields are not touched during the LDAP-sync

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode (<- not relevant, is it?)
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 
----> v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on:
----> Ubuntu Trusty, Apache 2.4, PHP 5.5.9
- What method you used to install Snipe-IT:
----> manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
----> No errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
----> CLI, User listing (/admin/users), LDAP Sync (/admin/users/ldap)
- If a stacktrace is provided in the error, include that too.
----> not relevant
- Any errors that appear in your browser's error console.
----> no errors
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
----> not sure
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
----> no related logs found
- Include what you've done so far in the installation, and if you got any error messages along the way.
----> basic installations and a few upgrades during the last months without any issues
- Indicate whether or not you've manually edited any data directly in the database
----> data was not edited in the database
-----
#### Thank you

Thanks for taking care :)

**Comment by topgunjim** [comment] 2017-01-05 17:55
I can confirm this is an issue as well. I believe the issue is the Console/Commands/Ldapsync.php where the $location variable is set to "new Location" when the --location or --location_id parameters are blank. I was able to make it work by changing the "new Location" to "null". 

Thank you @snipe for such a great tool!

**Comment by balasarius** [comment] 2017-03-24 14:59
Thanks, @topgunjim I was having the same issue and I followed your suggestion.

for the benefit of other, I altered the /app/Console/Commands/Ldapsync.php file by replacing the following at around line 81

```
        } else {
            $location = new Location;
        }
```
with 

```
        } else {
            $location = NULL;
        }

```

**Comment by VanillaNinjaD** [comment] 2017-03-24 15:47
@snipe

Has there been a pull request submitted to get this behavior in master?

Or has it already been addressed in V4?

**Comment by topgunjim** [comment] 2017-03-24 19:50
Glad to be of help @balasarius. This change is not in as of 3.6.4.

**Comment by snipe** [comment] 2017-08-25 14:05
I believe this is fixed in v4 on develop

**Closed by snipe** 2017-08-25 14:05 UTC
Labels: help-wanted, ldap
