### ISSUE TITLE
Allow checkout to owner as default

### ISSUE THREAD

**Issue by jimender2** [snipe/snipe-it#6123] opened 2018-08-24 02:41 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1

**Is your feature request related to a problem? Please describe.**
I am frustrated that we always have to put a user in to check out to. This takes up unneeded time on my and my teams part that we would like to minimize.

**Describe the solution you'd like**
I would like the person that something checks out to to be the owner of the device.  I essentially want one click checkout of items.

**Describe alternatives you've considered**
I have tried assigning to a person at the top of the stack ( a default person ) but that still takes time to do.

**Additional context**

This seems to be fairly easy to do. (create a new page and instead of having a dropdown menu it will have the owner of the device as default.  If someone would point me in the right direction that would be great.  Thank you.

**Comment by snipe** [comment] 2018-08-24 02:46
I'm not really clear on your use case here - can you elaborate a little more?

**Comment by jimender2** [comment] 2018-08-24 02:50
We are checking devices in and out everyday (we want it as fast as possible). Each person gets the same device everyday (they are the "owner". We want to make it so that they do not have to search for their name/ type their name everyday. Therefore I want it to either default to the owner or somehow make it faster.

**Comment by jimender2** [comment] 2018-08-24 02:55
It might also help you if I tell you that we have the users bring the device up to the checkout station which is manned by my team.  The team knows who everyone is and we just want to speed up the process

**Comment by snipe** [comment] 2018-08-24 08:11
There is no concept of a device owner in Snipe-IT (and that's not something we plan on adding.) This sounds like a possible duplicate of #5994 though.

**Closed** 2018-09-07 03:34 UTC
