### ISSUE TITLE
Not able to add field in Accessories

### ISSUE THREAD

**Issue by meenakshi03** [snipe/snipe-it#5966] opened 2018-07-26 03:54 UTC
**Server (please complete the following information):**
 - Snipe-IT Version - 4.6.3
 - OS: [e.g. Ubuntu, CentOS] -Windows 7
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version  - 7

**Is your feature request related to a problem? Please describe.**
yes,i am not able to add fields in accessories section 

**Describe the solution you'd like**
I want something like custom fields to be added in accessories

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment] 2018-07-26 04:14
Custom fields are only available to assets right now.

Closing as duplicate of #4261

**Closed by snipe** 2018-07-26 04:14 UTC

**Comment by meenakshi03** [comment] 2018-07-26 07:09
but what would be the file in which we can change to add one or two fields in the accessory tab

**Comment by snipe** [comment] 2018-07-26 09:44
There is no file you can change. It involves massive database and model changes, which is why we haven't done it yet. It's on the roadmap, but it's not something you can throw a few lines of code into.
