### ISSUE TITLE
Slack Issue - Checking out Licenses to Assets does not post

### ISSUE THREAD

**Issue by bricelabelle** [snipe/snipe-it#6490] opened 2018-12-07 19:41 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Checking out a license to a user sends to slack. Checking out a license to an asset does not.

**To Reproduce**

**Expected behavior**
Checking out licenses to users or assets should post to slack.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2018-12-07 19:48
This is effectively a duplicate of #6417. (Email notifications and slack notifications are governed by the same rules, and since an asset isn't a person and therefore doesn't have an email address, the notifications don't fire.)

**Closed by snipe** 2018-12-07 19:48 UTC

**Comment by bricelabelle** [comment] 2018-12-07 19:56
Is there a reason then that checking _in_ a license that is assigned to an asset still posts?  Also, any plans to develop something suggested here in request [6405](https://github.com/snipe/snipe-it/issues/6405)?

**Comment by snipe** [comment] 2018-12-07 19:58
That's an excellent question - I'll check.

**Comment by twsit988** [comment] 2019-11-01 07:43
Hi Snipe, I have the same question. I understand that an asset isn't a person so no notifications is sent but I also receive notifications on Slack when we check a license in that belonged to an Asset.
