### ISSUE TITLE
Feature Request: Scope Assets By Department/Location (Departmental Viewing)

### ISSUE THREAD

**Issue by paulhite** [snipe/snipe-it#5388] opened 2018-04-17 15:14 UTC
I know this has been brought up before, but most of the issues are stale, don't reference the latest multi-company support, or are for a slightly different scenario. Thought I would clarify our specific use case, which I feel is relatively common among larger orgs that want to use SnipeIT company-wide:

**We would greatly benefit from being able to scope views for users according to department or location.** 

Other departments (besides IT) really like SnipeIT and want to use it. However, they do not want other asset managers in other departments to have access to modify their assets or assign them out. We have tried setting up multi-company support, but it doesn't quite fit our use case. Multi-company support appears designed to run totally different companies that have their own unique assets and users. But departments only own _assets_ but they do not uniquely own _people_ (although people can be assigned), so this becomes problematic for us. A single user may need to be assigned a laptop from IT, a vehicle from Fleet, and a radio from Communications. Each department wants to issue something to the same user, but with the multi-company feature they do not share users. The only workaround is either to have all departments able to view/modify records for each other or to duplicate user accounts for each 'company', neither of which is a workable solution.

**Alternatively** it would be acceptable if we changed the scoping on multi-company setups to allow all companies to select from the entire unassigned user list, not just those assigned to their company, when assigning assets (or allow cross-company asset assignments). However, logically that makes less sense than setting up a version of multi-company support that is departmental instead.

I understand based on the previous responses that this is a big ask, as the development and ongoing cost of testing multi-department features with every release is non-trivial. I don't have any expectations of a solution in the near future, just hoping for some consideration down the line if I'm not alone in this feature request.

-----

- Version of Snipe-IT you're running: **4.2**
Similar requests: #4728 #1954 #3520

**Comment by calebsutton** [comment] 2018-04-23 22:33
I too would benefit from this feature.

**Comment by snipe** [comment] 2018-04-24 03:07
Duplicate of #1954

**Closed by snipe** 2018-04-24 03:07 UTC
