### ISSUE TITLE
Feature Request: Resend acceptance e-mail

### ISSUE THREAD

**Issue by jeffclay** [snipe/snipe-it#5048] opened 2018-02-19 22:37 UTC
#### Expected Behavior (or desired behavior if a feature request)

Button to resend acceptance e-mail. It makes sense to me for this button to be on the Unaccepted Assets report.

-----

#### Actual Behavior

Unable to resend acceptance e-mail.

-----
    Is this a fresh install or an upgrade? _upgraded last week_
    Version of Snipe-IT you're running _v4.1.11-pre - build 3307 (master)_
    Version of PHP you're running _7.1_
    Version of MySQL/MariaDB you're running _1:5.5.56-2.el7_
    What OS and web server you're running Snipe-IT on _CentOS 7_
    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) _manual installation, updated with update.php_
    What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  _/reports/unaccepted_assets_

**Comment by snipe** [comment] 2018-02-20 01:56
Duplicate of #4943

**Closed by snipe** 2018-02-20 01:56 UTC
