### ISSUE TITLE
Feature Request: Button for Accessoire to reduce Quantity

### ISSUE THREAD

**Issue by Baluga145** [snipe/snipe-it#5247] opened 2018-03-23 12:19 UTC
How do you guys handle accessoirs? An example for my scenario. We have 10 keyboards. Now i checkout a keyboard for an user. After a period of time the keyboard is broken. The only way I see is checkin the keyboard and remove form the quanity one item or I am wrong ?

![2018-03-23 11_55_58-accessories __ bunzl ch assets opera](https://user-images.githubusercontent.com/35063666/37828748-c515b272-2e9c-11e8-9994-3e8cd025809b.png)

It would be nice if we had something like a Button to easly add or remove an Accessoir.

**Comment by Jarli01** [comment] 2018-03-27 15:43
Going to add my own ticket to this one. . .

https://github.com/snipe/snipe-it/issues/5267

There needs to be some way to both increase and decrease the quantity it would seem.

**Comment by Jarli01** [comment] 2018-03-27 15:47
As for decreasing, the only reasonable way to "decrease" would be to check in the accessory, and dispose of it. 

And then check out another. But that is a record that should be accounted for, as an auditor might want to see how much money was "lost" within the usable life of any given accessory.

**Comment by snipe** [comment] 2018-04-06 00:10
Duplicate of #5173

**Closed by snipe** 2018-04-06 00:10 UTC
