### ISSUE TITLE
Domain/Hosting Record Tracking

### ISSUE THREAD

**Issue by alextheberge** [snipe/snipe-it#2702] opened 2016-09-28 19:05 UTC
Hello! I haven't installed or used this system yet. But I have used the demo and It's absolutely wonderful! I have a feature request; a feature that I can't seem to find anywhere. I consider domains and hosting as and important part of tracking for IT. Is there a plan to include that as a module?

Right now I have everything that this keeps track of in an excel spreadsheet, I want to move all this into the snipe it system, but how do I include the 15 sites we have. With several sub-domains and sometimes separate hosting providers.
- For domains I'd like to know date established, parked by, who  and what department purchased the domain, purchase price, expiration date, sub-domains and sites forwarded or not and to where.
- For hosting I'd  #like to know date purchased, who's the host, who purchased (person and department), domains and sub-domains attached, expiration, type of hosting.

Thank you for your consideration!
-Alex

**Comment by snipe** [comment] 2016-10-06 16:37
That's actually a feature I had originally intended to implement when I first created Snipe-IT.

**Comment by niladam** [comment] 2016-11-01 09:44
That's a really good idea! Looking forward to it. Any news ?

**Comment by snipe** [comment] 2016-11-01 16:47
No news. When there is news, we'look update the ticket

**Comment by snipe** [comment] 2017-02-01 20:03
This is actually a duplicate of #79

**Closed by snipe** 2017-02-01 20:03 UTC
Labels: feature request
