### ISSUE TITLE
Display the statistic of "Deployed" device

### ISSUE THREAD

**Issue by jassonxp** [snipe/snipe-it#4723] opened 2018-01-04 04:02 UTC
#### Expected Behavior (or desired behavior if a feature request)

Hi, can we have the option to view the number of devices has been "deployed", currently in "Assets by Status" we can see Ready to Deploy/Pending/Archived but not "Deployed".

Please advise.

Thank you for your time

**Comment by jmartins1** [comment] 2018-01-06 22:03
Jassonxp, I had the same issue. This is a glitch. Locate one of your checked out items then select UPDATE. Change its status to Deployed. This will reflect in the reports and Assets by Status on the dashboard. Currently the status field is not changing from "Ready to deploy" to "Deployed"

**Comment by tbradsha** [comment] 2018-01-08 14:14
This is by design (see #4538). Deployed assets are really in "ready to deploy" status + assigned, so they are included in the "ready to deploy" tally.

**Comment by jmartins1** [comment] 2018-01-08 14:36
This might be the case but it throws off the inventory. For example, my reports and status graph indicated I have over 400 items ready to deploy when in actuality I only had 43.

 

Thank you

**Comment by tbradsha** [comment] 2018-01-08 17:25
In its current state, "ready to deploy" does not mean it's not already deployed. It refers to assets, whether or not they are deployed, that are functional and deployable. If a laptop is assigned to someone and deployed, its status is still (by design) "ready to deploy". There is not a "deployed" status unless you created one yourself; "deployed" is a fake status that is really a "ready to deploy" status + assigned.

**Comment by jmartins1** [comment] 2018-01-08 17:59
This unfortunately is very confusing for the average user. The average user would expect that checking out an asset would indicate that the asset has been deployed and is no longer available for issue.

**Comment by jassonxp** [comment] 2018-01-09 06:39
Yes, I think so. 
The state "ready to deploy" vs "deployed" does not the same meaning. 
If we can get the status "deployed" so we can know how many computer "in use" and how many computer "available" to checkout to user. That's the case.

Hope that this issue can be fixed.

**Comment by snipe** [comment] 2018-01-10 02:35
> There is not a "deployed" status unless you created one yourself; "deployed" is a fake status that is really a "ready to deploy" status + assigned.

This is correct.

> This unfortunately is very confusing for the average user. 

This is how Snipe-IT has always worked. 

> If we can get the status "deployed" so we can know how many computer "in use" and how many computer "available" to checkout to user.

Adding a "deployed" status creates as many problems as it solves. If you have multiple Deployed statuses, you'll have to pick a Deployed status when you checkout (via UI or API). What happens if someone changes that status label to no longer be deployed?

I understand that this is something several people want, but it's not something I am considering at this time. The status label describes the physical state of the asset, not it's deployed status.

**Closed by snipe** 2018-01-10 02:35 UTC
