### ISSUE TITLE
*Feature Request* - Add button to regenerate asset acceptance email

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#3028] opened 2016-12-07 10:33 UTC
I think this would be really useful - to have a button whereby the asset acceptance email can be re-sent. Quite often we will look at the 'Unaccepted assets' report and find some old checkouts that haven't yet been accepted. We all know most users will say "er, what email" and then proceed to not find it!

If we could just hit 'resend acceptance email' that would be great. Or even the ability to regenerate the link which we could copy and paste in.

I have managed to regenerate the links manually by finding the correct ID number of the checkout action from the action_logs table but this is messy. Once handed over to our support, it's definitely not an option.

Just a thought....

**Comment by snipe** [comment] 2017-01-12 15:03
Duplicate of #2294

**Closed by snipe** 2017-01-12 15:03 UTC
Labels: feature request
