### ISSUE TITLE
Checkin date / Checkout date not recorded

### ISSUE THREAD

**Issue by SeriousMatters** [snipe/snipe-it#6235] opened 2018-09-26 17:17 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The current behaviour does not allow to record asset checkin/checkouts that happened in the past. Such as missed/forgotten checkouts or no Internet access on site. 

The asset history shows the timestamp of when the asset checkout/checkin were recorded in snipeit. History should shows the values entered in Checkout Date / Checkin Date fields instead.  In fact, it seems the fields are not used anywhere at all. the action_logs and asset_logs tables do not even have Checkout/Checkin Dates fields. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Assets'
2. Click 'Checkout' 
3. In the 'Checkout Date' field, enter a date in the past (such as last week)
4. Click 'Checkout'
5. Click the Asset you've just checked out
6. Go to 'History' tab
7. The checkout date shown is today rather than the entered date.

**Expected behavior**
Asset History should show the the values entered in the Checkout Date / Checkin Date field, not the timestamp. 

**Screenshots**
 - unnecessary, IMO

**Server (please complete the following information):**
Snipe-IT version: v4.6.4 - build 3881
PHP version: 7.2.10

**Desktop (please complete the following information):**
 - irrelevant

**Smartphone (please complete the following information):**
 - irrelevant

**Error Messages**
- none. it's a design issue

**Additional context**
- irrelevant

**Comment by SeriousMatters** [comment] 2018-09-27 11:14
OK, I've updated Snipe-IT version and php version as you requested.
Although it seems to affect all versions

**Comment by sid8000** [comment] 2018-09-27 11:18
same as #5105

**Comment by snipe** [comment] 2018-09-27 15:35
Duplicate of #5105

**Closed by snipe** 2018-09-27 15:35 UTC
