### ISSUE TITLE
Responsive/mobile website: Bad UI

### ISSUE THREAD

**Issue by UnlimitedCookies** [snipe/snipe-it#6876] opened 2019-04-02 15:23 UTC
**Describe the bug**
As seen in the attached screenshots, the UI-Items and the navbar are very bad sized/placed. The lists/tables are not very space efficient. Sometimes there's sideways scrolling.

**To Reproduce**
Go to any List item on a mobile device.
Also: You can use the built-in responsive testing tool from chrome to reproduce.
So far I have found no device/size where it aligns properly.

I think it's pretty self-explanatory.
I've made some drawings on the screenshots.

**Expected behavior**
Useable and good looking UI.

**Screenshots**
![Screenshot_20190402-162453](https://user-images.githubusercontent.com/49200216/55414004-b1d60b80-556a-11e9-98a9-c8a28223dc6b.png)
![Screenshot_20190402-164941](https://user-images.githubusercontent.com/49200216/55414006-b1d60b80-556a-11e9-8c05-081901036892.png)
![Screenshot_20190402-164906](https://user-images.githubusercontent.com/49200216/55414007-b1d60b80-556a-11e9-8401-3f1e42a616fa.png)
![InkedScreenshot_20190402-162453 - Edited_LI](https://user-images.githubusercontent.com/49200216/55414008-b1d60b80-556a-11e9-9170-7aee144f8904.jpg)
![InkedScreenshot_20190402-164941 - Kopie_LI](https://user-images.githubusercontent.com/49200216/55414009-b1d60b80-556a-11e9-9cea-74b6c97d42fb.jpg)
![InkedScreenshot_20190402-164906 - Kopie_LI](https://user-images.githubusercontent.com/49200216/55414010-b26ea200-556a-11e9-9877-4710b9c55e19.jpg)

**Server:**
 - Snipe-IT Version: v4.6.15 - build 4011 (master) 
 - OS: Ubuntu 18.04
 - Web Server: Apache/2.4.29 (Ubuntu)
 - PHP Version: 7.2.15-0ubuntu0.18.04.2

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.86 

**Smartphone:**
 - Device: Google Pixel 2 XL
 - OS: Android 9 (P)
 - Browser: Chrome
 - Version: 73.0.3683.90

**Additional context**
- Is this a fresh install or an upgrade? --> Fresh
- What OS and web server you're running Snipe-IT on --> mentioned above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> manual
- Indicate whether or not you've manually edited any data directly in the database --> no

Aside from this flaw I really like snipe-it!
**Thanks in advance!**

**Comment by UnlimitedCookies** [comment] 2019-06-01 15:53
Still relevant :(

**Comment by UnlimitedCookies** [comment] 2019-08-02 12:53
Sadly this is still relevant. 🤨

**Comment by UnlimitedCookies** [comment] 2019-10-01 15:03
... still relevant.

**Comment by UnlimitedCookies** [comment] 2019-12-01 14:47
Hasn't been fixed.

**Comment by UnlimitedCookies** [comment] 2020-01-30 14:52
Yep.

**Comment by UnlimitedCookies** [comment] 2020-03-30 15:06
actually, I don't think someone cares at this point.

**Comment by shelvacu** [comment] 2020-05-12 23:38
When I looked into using Snipe-IT, this was a huge turn-off for me. I am certainly interested in this, and I think this combined with #7036 would make an awesome mobile inventory system.

**Comment by UnlimitedCookies** [comment] 2020-08-29 17:13
meh

**Comment by UnlimitedCookies** [comment] 2020-12-25 20:04
Relevancy is underrated.

**Comment by QVinto** [comment] 2021-03-13 07:54
Snipe IT looks to be very good tool but mobile view is in a bad shape. This issue is opend for too long and it looks like nobody is gonna fix IT anyway :(

**Comment by snipe** [comment] 2021-06-03 16:45
We've made a lot of improvements to the mobile view over the past many months, as evidenced by the mobile view PRs that have been accepted. Please don't act like we're not paying attention. There are a lot of things to work on.

**Comment by tamasgal** [comment] 2021-06-27 13:11
We are currently also evaluating asset managers for our institute where we will manage thousands of assets and hundreds of scientists and Snipe-IT looks really nice so far!
However, the mobile experience is really far from ideal. I am considering to contribute a bit but my time (as those of others) is fairly limited.
I hope that the mobile UI will be improved soon. Especially for the self checkin/checkout, the mobile UI is crucial and the way it acts at this moment is very weird. Many UI elements are overlapping and unusable. I can't even click on Assets on the main page because the header is the way. 🙁
The user-menu for example shows the text in the same colour as the background of the menu, so none of the items are readable.

**Comment by snipe** [comment] 2021-06-28 03:17
@tamasgal we’re always willing to improve, if people are willing to be more specific with what’s wrong, so we can understand how to reproduce issues easily. If you can provide us with screenshots and workflows where we’re failing you, I’m very happy to direct dev resources to improve that.

**Comment by ryanmccartney** [comment] 2021-08-03 20:58
Hi there,

Here to reiterate the sentiments of @UnlimitedCookies. Snipe-IT is a great piece of software, many thanks for all the effort that goes into keeping it open source.

In a vague attempt to provide more specific areas where the mobile UI could be improved I've added a few screenshots.

The following screenshots are produced using the demo version of Snipe-IT with Chrome Dev tools and the view set to iPhone X.

<img width="442" alt="Screenshot 2021-08-03 at 21 37 31" src="https://user-images.githubusercontent.com/33418788/128082818-18d424fd-6e05-4dac-9cb6-85fd7cb7e95c.png">

When the left drawer is opened on mobile view it's not possible to collapse accordions. The open menu button is on the page content area rather than the navbar.

<img width="486" alt="Screenshot 2021-08-03 at 21 36 48" src="https://user-images.githubusercontent.com/33418788/128082825-c5e68a91-1d35-4e99-99d1-f10f0365e973.png">

On the assets list page or any page with tables, the view is pretty cluttered on mobile. Perhaps any actions should appear in a menu. And only show the thumbnail and asset name column in this view.

In my book, the single biggest win would be improving the navbar on mobile view. At the moment it's occupying nearly 1/3 of the screen real-estate with icons all over the place - maybe just showing the system logo, search button, add button and user avatar in one small bar could improve it?

On the whole, I can't overstate how great snipe-it is!

**Comment by IVIortis** [comment] 2022-04-24 06:53
Hi all, I seconding @ryanmccartney. Improving the navigation on mobile would be an awesome start. Maybe the whole "make snipe-it responsive" is a little too big for one issue and one could break it down to the smaller, more concrete, improvements that would help in the short run.

Just an idea.

**Comment by snipe** [comment] 2022-04-24 07:52
v6 already has a great deal of mobile improvements. I'm closing this for now. If anyone would like to test (and potentially PR against) the develop branch and break these down into smaller bites, that would be great.

**Closed** 2022-04-24 07:52 UTC
