### ISSUE TITLE
User Not assigned to License Seat that is checked out to Asset

### ISSUE THREAD

**Issue by FOOSAYS** [snipe/snipe-it#5524] opened 2018-05-11 13:10 UTC
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If an asset has not been checked out to a user before it is checked out to a license, the user field in the license seat remains empty, even after a user is assigned to the asset
Also, if the asset is redeployed to a new user, the license seat still remains checked out to the original user.

Checking the database I can see the following:
>> select id,name,assigned_to from assets where id=1 or id=4;
+----+---------------+-------------+
| id    | name              | assigned_to |
+----+---------------+-------------+
|  1    | ***-***-DT002 |                 1 |
|  4    | ***-***-LT044  |               32 |
+----+---------------+-------------+

>> select id,assigned_to, asset_id from license_seats where asset_id=1 or asset_id=4;
+-----+-------------+----------+
| id    | assigned_to | asset_id |
+-----+-------------+----------+
|  75  |        NULL    |        1     |
|  86  |             32    |        4     |
+-----+-------------+----------+

The only way to rectify this, is to check the license in, assign the asset to user, and then check license back out.

**To Reproduce**
create asset (but do not check out to user)
assign license to asset
check asset out to user
confirm user field of license seat still empty
check asset in and out to different user
confirm user field of license seat still assigned to original user

**Expected behaviour**
Would expect this field to be updated based on assets being checked in/out not just at the time of assigning the license

**Screenshots**
![image](https://user-images.githubusercontent.com/30470382/39920645-b9e467e2-550f-11e8-9015-8930008b9372.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.3.0 build 3586 (gec1fa8e90)
 - OS: Win Server 2012 R2
 - Web Server: IIS v6.2
 - PHP Version: 5.6.35

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 65.0.3325.181 (Official Build) (64-bit)

**Additional context**
- recently upgraded. Issue was seen in previous version too
- this issue is present on the online demo
- Have tried checking in and out license to asset, but same issue persists

**Comment by cslucian** [comment] 2018-05-14 06:40
I have signaled this issue also in the past:

#5155

**Comment by hctclyerly** [comment] 2018-05-14 13:08
I too agree and this issue needs to be addressed -- [5407](https://github.com/snipe/snipe-it/issues/5407)

**Comment by dmeltzer** [comment] 2018-07-23 14:59
I'm pretty sure this hasn't been actively fixed, should probably remain open.

**Comment by dmeltzer** [comment] 2018-07-23 23:39
I think I lied, this looks like a dupe of #4589

**Comment by FOOSAYS** [comment] 2018-07-25 09:03
@dmeltzer 
> I cannot reproduce it locally so I assume it was fixed.

I just tried below steps again on the live demo and the user field of the license is still empty. 

> Steps to reproduce the behavior:
> create asset (but do not check out to user)
> assign license to asset
> check asset out to user
> confirm user field of license seat still empty

**Comment by snipe** [comment] 2018-07-25 09:35
Duplicate of #5155

**Closed by snipe** 2018-07-25 09:35 UTC
Labels: :hand: bug, :woman_technologist: ready for dev

**Comment by hctclyerly** [comment] 2018-07-25 11:04
@dmeltzer - What if asset is already checked out to user. And then you want to assign license to asset, it also assigns to user, checking in asset, leaves license with user, rather than only with asset, as you originally intended. It only works if you assign license to asset prior to checkout.

On Jul 25, 2018, at 5:36 AM, snipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Duplicate of #5155<https://github.com/snipe/snipe-it/issues/5155>

**Comment by snipe** [comment] 2018-07-25 11:05
@hctclyerly this issue was marked as a duplicate of #5155 and will not be monitored. Please refer to issue #5155 for additional thoughts and questions.
