### ISSUE TITLE
Feature Request: Increase accessory quantity

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#5267] opened 2018-03-27 12:26 UTC
Not sure what better way to currently do this, short of adding whatever accessory quantity to the existing quantity that Snipe-IT has listed. 

![chrome_2018-03-27_08-19-27](https://user-images.githubusercontent.com/14837699/37966874-b1b43444-3197-11e8-9da6-fed37fb6cb64.png)

In the picture above, you can see the accessory (usb-c to digital av adapter). We don't purchase a lot of these, but likely will in the future. 

In order to add additional inventory to Snipe-IT you have to adjust the total quantity on hand. Changing Quantity from 5 to whatever new number we have. 

The process works, but is awkward. 

My recommendation is a "Up" arrow or other mechanism(the idea likely could use refinement) that allows increasing quantity by the number of clicks and request confirmation of the adjustment with the usual save mechanism. 

The reason I am making this recommendation, is by simply changing the quantity manually, you can actually have a negative value "on hand". This realistically can't occur as we can't hand out any accessories that we don't have on hand. 

![chrome_2018-03-27_08-24-08](https://user-images.githubusercontent.com/14837699/37967067-3f007d6c-3198-11e8-8854-ced6eac3f62e.png)

Let me know if you need anything else.

**Comment by snipe** [comment] 2018-04-06 00:10
Duplicate of #5173

**Closed by snipe** 2018-04-06 00:10 UTC
