### ISSUE TITLE
Creating New Group

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#902] opened 2015-07-08 19:42 UTC
I'm not sure if this is a bug or not. I've tried doing a search in the issues, but I can't find this issue so I'll post it here. Sorry if this has already been covered.

I'm on v1.2.7-master and I've created a couple of groups. One thing that seems to not be functioning correctly is after clicking save it stays on the page. You can click back and it will take you to the list of groups.

I didn't know if this is by design or not. It would seem that if you clicked save it would automatically take you to the group list.

**Comment by snipe** [comment] 2015-07-25 00:43
I think this was basically by design, but I agree it's a weird UX to have. This is fixed in 2.0

**Closed by snipe** 2015-07-25 00:43 UTC
