### ISSUE TITLE
Bulk Checkout Accessories

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5952] opened 2018-07-25 04:29 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.2
 - OS: Windows 10
 - Web Server: WAMP 3.3.1
 - PHP Version 7.2.4

**Is your feature request related to a problem? Please describe.**
Not a problem but more of extra steps to assign/checkout accessories to users

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/38576928/43179459-aaf7f4ca-9005-11e8-81ab-3ff513b8763d.png)
We bulk checkout assets to users laptops, physical phones, headsets etc using Bulk Checkout option under Assets but would like to see Accessories under Assets to checkout bag, mouse, security lock as well. Instead of placing Bulk Checkout under Assets, can it be on its own with icon between Dashboard and Assets perhaps with a shopping cart / trolley icon?

**Describe alternatives you've considered**
Current alternative is to click on Accessories, choose one by one accessory while checking out at a time to a user.

**Comment by snipe** [comment] 2018-07-25 09:37
Duplicate of #5665

**Closed by snipe** 2018-07-25 09:37 UTC
