### ISSUE TITLE
Email on check in doesn't work

### ISSUE THREAD

**Issue by TheBags** [snipe/snipe-it#5523] opened 2018-05-11 10:43 UTC
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

When I perform a check in, the user is not notified by email.
The Smtp doesn't receive the email.
The email works well during user cration.

Tnx,
Giovanni

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running - **v4.3.0 - build 3586 (master)**
- Version of PHP you're running - **7.0.28-0ubuntu0.16.04.1**
- Version of MySQL/MariaDB you're running - **mysql  Ver 14.14 Distrib 5.7.22**
- What OS and web server you're running Snipe-IT on - **NginX on Ubuntu 16.04.1 LTS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **git install**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **No errorr**
- If a stacktrace is provided in the error, include that too. - **No errorr**
- Any errors that appear in your browser's error console.  - **No errorr**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.  - **No errorr**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Raj22223** [comment] 2018-05-11 11:01
Is this happening after you updated to Version v4.3.0 - build 3586 (master) ?

**Comment by TheBags** [comment] 2018-05-11 11:04
I note this because I didn't received the email when i Checked in on of my asset.
I can't say if it stops to work after the upgrade :(

**Comment by snipe** [comment] 2018-05-11 18:37
Duplicate of #5470

**Closed by snipe** 2018-05-11 18:37 UTC
