### ISSUE TITLE
MAC address field not always appearing

### ISSUE THREAD

**Issue by thedaftbadger** [snipe/snipe-it#1043] opened 2015-08-11 11:04 UTC
I have an asset model created called "ProBook 6560b".

![screenshot_081115_120146_pm](https://cloud.githubusercontent.com/assets/13657363/9196211/d5427e0e-4020-11e5-80e3-5a511ce55e3b.jpg)

When creating a new asset I select this model first (before entering any data) and the MAC field is not shown.

![screenshot_081115_120214_pm](https://cloud.githubusercontent.com/assets/13657363/9196217/e573fde8-4020-11e5-8952-3e12c749ecf8.jpg)

This isn't the case for all asset models. I have other models with the MAC address field selected and they appear fine. I have tested in both Firefox and Chrome so I don't think this is a browser issue.

**Comment by thedaftbadger** [comment] 2015-08-11 14:11
After further investigation it seems that this field is now not showing for any Asset Model since upgrading to the latest release (non-dev).

**Comment by snipe** [comment] 2015-08-11 19:15
Not able to reproduce this on the demo.

https://demo.snipeitapp.com/hardware/models/6/view
is marked as having a MAC address.

Asset is of that model type, MAC address is shown.
https://demo.snipeitapp.com/hardware/218/edit

**Comment by thedaftbadger** [comment] 2015-08-11 19:17
It seems that after updating to the latest release any new asset model with MAC address field enabled is not showing.

**Closed** 2015-08-11 19:36 UTC
