### ISSUE TITLE
Feature Request: Multiple checkout options for consumables

### ISSUE THREAD

**Issue by dangerd1** [snipe/snipe-it#5280] opened 2018-03-28 22:27 UTC
#### Expected Behavior (or desired behavior if a feature request)
To allow users to check out multiple number of items.
(what you expect to happen goes here)
 For eg. if there's 20 rims of paper, would like to allow users to select or enter the number of rims to checkout. If the user wants to take out 5 rims from the 20, then the system should allow user to take out 5 items in one checkout session.
-----

#### Actual Behavior
(what actually happens goes here)
If a user wants to take out multiple items, user has to check out each item separately and repeat for that number of times. If user wants to check out 20 items, he has to go through it 20 times. This becomes time consuming.
-----

**Comment by snipe** [comment] 2018-04-05 00:53
Duplicate of #1820

**Closed by snipe** 2018-04-05 00:53 UTC
