### ISSUE TITLE
Feature Request - The ability to assign Consumables to assets

### ISSUE THREAD

**Issue by cslucian** [snipe/snipe-it#4582] opened 2017-12-06 14:55 UTC
#### Expected Behavior (or desired behavior if a feature request)

In our company we order print cartridges for 5 shared printers. I would be great if I could check-out cartridges to printers ( assets) not to a user.

-----

#### Actual Behavior

Consumables can be assigned only to users

-----

Thank You,

**Comment by TonisOrmisson** [comment] 2017-12-20 12:23
Or eg batteries to various devices ....

**Comment by amferreira** [comment] 2018-01-11 13:03
+1 👍

**Comment by wilsonlspacheco** [comment] 2018-01-31 13:59
+1 👍

**Comment by Mynty100** [comment] 2018-02-26 21:21
+1 (y)

**Comment by snipe** [comment] 2018-03-29 12:16
Duplicate of #1538. (I'm using #1538 as the reference since it seems to be the first time this feature was suggested.)

**Closed by snipe** 2018-03-29 12:16 UTC
Labels: :heart: feature request, :woman_technologist: ready for dev
