### ISSUE TITLE
"Whoops, looks like something went wrong." When Clicking on People. not able to create users. Any Solution ????

### ISSUE THREAD

**Issue by fileadda** [snipe/snipe-it#4603] opened 2017-12-09 11:32 UTC
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment] 2017-12-09 18:38
Unfortunately, you have not provided any details that will allow you to receive help

**Comment by Gelob** [comment] 2017-12-09 23:21
I would check that you have the latest version and if not, update. It could be caused by this bug that was fixed a few days ago. https://github.com/snipe/snipe-it/issues/4581

**Comment by fileadda** [comment] 2017-12-10 13:28
enabled App_debug = true 
after that i got an exact error .. 
![users_error](https://user-images.githubusercontent.com/20986701/33805278-12fcde14-dddc-11e7-8405-bb2ba283073d.PNG)

**Comment by fileadda** [comment] 2017-12-10 13:42
Snipe-IT version | v4.1.8-pre  build 3034 (g4f3c932)

**Comment by fileadda** [comment] 2017-12-10 14:22
Hai.. 

Problem Resolved my self. 

php function problem

![resolved2](https://user-images.githubusercontent.com/20986701/33805734-834ed3c8-dde3-11e7-9e31-33c97bea4ab6.PNG)

after correcting function name. it is working fine and awesome.

**Comment by Gelob** [comment] 2017-12-11 17:37
Great! that was fixed in this commit so you shouldn't have to edit it yourself. https://github.com/snipe/snipe-it/commit/dfb0c09c5101de1847528e9a658685f908f56f38

**Closed** 2017-12-11 21:48 UTC
