### ISSUE TITLE
User unable to check out licenses

### ISSUE THREAD

**Issue by blackout1231** [snipe/snipe-it#4598] opened 2017-12-07 20:35 UTC
#### Expected Behavior (or desired behavior if a feature request)
Gave test user full permissions to Create, Edit, Check out (etc) licenses, use should now be able to perform those functions
(what you expect to happen goes here)

-----

#### Actual Behavior
Test User is able to log in, can create, edit Licenses, however that user is unable to check out a License to an Asset or a User.
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode 
- [ Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.1.6 build 2963 (g83c8449)
- Version of PHP you're running 7.19
- Version of MySQL/MariaDB you're running 5.7.19/10.2.8
- What OS and web server you're running Snipe-IT on Windows Server 2012R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
License Checkout
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
-------------------------------------------------------------------
These are the errors

 403 Forbidden.

Sad panda. You are not authorized to do the thing. Maybe return to the dashboard, or contact your administrator. 
This action is unauthorized.

C:\wamp64\www\asset\vendor\laravel\framework\src\Illuminate\Auth\Access\HandlesAuthorization.php#28

Illuminate\Auth\Access\AuthorizationException
     */
    protected function deny($message = 'This action is unauthorized.')
    {
        throw new AuthorizationException($message);
    }
--------------------------------------------------------------------------------
Include any additional information you can find in app/storage/logs and your webserver's logs.
I have the log file, but it is huge, I can send if needed
SMTP errors which are not related
Indicate whether or not you've manually edited any data directly in the database
No
- Include what you've done so far in the installation, and if you got any error messages along the way.
I've ran the latest update (php upgrade-php via Git)
- Indicate whether or not you've manually edited any data directly in the database
Not that I can recall
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by blackout1231** [comment] 2017-12-07 21:00
array:4 [
  "ability" => "checkout"
  "result" => false
  "user" => 177
  "arguments" => "[0 => Object(App\Models\LicenseSeat)]"
]
error

error

User Permissions
{"superuser":"-1","admin":"1","reports.view":"1","assets.view":"1","assets.create":"1","assets.edit":"1","assets.delete":"1","assets.checkin":"1","assets.checkout":"1","assets.audit":"1","assets.view.requestable":"1","accessories.view":"1","accessories.create":"1","accessories.edit":"1","accessories.delete":"1","accessories.checkout":"1","accessories.checkin":"1","consumables.view":"1","consumables.create":"1","consumables.edit":"1","consumables.delete":"1","consumables.checkout":"1","licenses.view":"1","licenses.create":"1","licenses.edit":"1","licenses.delete":"1","licenses.checkout":"1","licenses.keys":"1","components.view":"1","components.create":"1","components.edit":"1","components.delete":"1","components.checkout":"1","components.checkin":"1","users.view":"1","users.create":"1","users.edit":"1","users.delete":"1","models.view":"1","models.create":"1","models.edit":"1","models.delete":"1","categories.view":"1","categories.create":"1","categories.edit":"1","categories.delete":"1","departments.view":"1","departments.create":"1","departments.edit":"1","departments.delete":"1","statuslabels.view":"1","statuslabels.create":"1","statuslabels.edit":"1","statuslabels.delete":"1","customfields.view":"1","customfields.create":"1","customfields.edit":"1","customfields.delete":"1","suppliers.view":"1","suppliers.create":"1","suppliers.edit":"1","suppliers.delete":"1","manufacturers.view":"1","manufacturers.create":"1","manufacturers.edit":"1","manufacturers.delete":"1","depreciations.view":"1","depreciations.create":"1","depreciations.edit":"1","depreciations.delete":"1","locations.view":"1","locations.create":"1","locations.edit":"1","locations.delete":"1","self.two_factor":"0","self.api":"0"}

**Comment by snipe** [comment] 2017-12-08 03:25
Duplicate of #4576

**Closed by snipe** 2017-12-08 03:25 UTC
