### ISSUE TITLE
Assign a OS license when Creating an Asset

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#959] opened 2015-07-27 20:29 UTC
Something I noticed importing some 40+ PCs, I had to create the asset, create the license, open the license, check out the seat to the asset. After doing this for about 3 machines, I decided to write some MySQL foo to update the `assets`, `licenses`, `license_seats`, and `asset_log` tables.

Also, in-so-doing the above, I noticed there's no way in the `asset_log` to actually log the Asset a license is checked out to, you can do this for users, just not assets.

**Comment by snipe** [comment] 2015-07-27 20:46
Duplicate of #855 and #831.

**Closed by snipe** 2015-07-27 20:46 UTC
