### ISSUE TITLE
Cannot sort out "Pending" items in 4.1.2

### ISSUE THREAD

**Issue by MacoWong** [snipe/snipe-it#4373] opened 2017-11-03 00:51 UTC
The pending items and deployed items are displayed even I choose to display pending items only.

![image](https://user-images.githubusercontent.com/32317020/32357054-31759a1e-c074-11e7-8870-0005b3dd5312.png)

**Comment by snipe** [comment] 2017-11-03 01:04
Is it possible you have some assets that were somehow deployed as pending (or their statues was changed to pending after they were already deployed?)

**Comment by MacoWong** [comment] 2017-11-03 07:08
yes, some of the assets status was changed to pending.

**Comment by snipe** [comment] 2017-11-05 00:07
@MacoWong If their statuses were changed to pending after they were checked out they will show as deployed. That's by design, because they haven't been checked in yet.

**Closed** 2017-11-07 19:45 UTC
Labels: not sure if bug
