### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for

### ISSUE THREAD

**Issue by jlrodriguez00** [snipe/snipe-it#4460] opened 2017-11-15 20:21 UTC
####SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for

hello I have a problem with the installation of snipe-it.
when you are creating the migration of the database the following error comes out

this installation is being done in windows 10

has been tested on both wampp and wampserver

is being used php artisan serve to run snipe-it

SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'labels_width' (SQL: alter table `settings` add `labels_per_page` tinyint not null default '30', add `labels_width` decimal(6, 5) not null default '2,625', add `labels_height` decimal(6, 5) not null default '1', add `labels_pmargin_left` decimal(6, 5) not null default '0,21975', add `labels_pmargin_right` decimal(6, 5) not null default '0,21975', add `labels_pmargin_top` decimal(6, 5) not null default '0,5', add `labels_pmargin_bottom` decimal(6, 5) not null default '0,5', add `labels_display_bgutter` decimal(6, 5) not null default '0,07', add `labels_display_sgutter` decimal(6, 5) not null default '0,05', add `labels_fontsize` tinyint not null default '9', add `labels_pagewidth` decimal(7, 5) not null default '8,5', add `labels_pageheight` decimal(7, 5) not null default '11', add `labels_display_name` tinyint not null default '0', add `labels_display_serial` tinyint not null default '1', add `labels_display_tag` tinyint not null default '1')

these are some screenshots

![sin titulo](https://user-images.githubusercontent.com/33701492/32857677-a2d26bf0-ca16-11e7-9f09-d4444062b0ad.png)

![sin titulo](https://user-images.githubusercontent.com/33701492/32857788-0cfbe36c-ca17-11e7-9917-8f895553b7c0.png)

This is the configuration of the .env

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:xt/JCnx3LWNveLGGKgUNaZS585TclMKnlr5yQvYzGLU=
APP_URL=http://127.0.0.1:8000
APP_TIMEZONE='UTC'
APP_LOCALE=es

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=snipeit
DB_USERNAME=josel
DB_PASSWORD=123456
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8
DB_COLLATION=utf8_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
REFERRER_POLICY=same-origin
ENABLE_CSP=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT-null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=daily
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
APP_CIPHER=AES-256-CBC

**Comment by snipe** [comment] 2017-11-15 21:17
Try setting your `APP_LOCALE=en`, run the migrations and ten you can set it back.

**Comment by snipe** [comment] 2017-11-15 21:17
Duplicate of #4002

**Closed by snipe** 2017-11-15 21:17 UTC

**Comment by jlrodriguez00** [comment] 2017-11-16 21:53
thanks for the help, I could install it.
and I would be grateful if you could help me with the configuration for the email

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=example@gmail.com
MAIL_PASSWORD=example_pass
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=example@gmail.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=example@gmail.com
MAIL_REPLYTO_NAME='Snipe-IT'

**Comment by sekroots** [comment] 2023-02-17 15:46
Hello. I am facing this issue using snipeit docker.

my .env:
APP_TIMEZONE=Europe/London  # you should change this to your timezone
APP_LOCALE=en # you should change this for the desired language


When I  open the system I got:
"
Illuminate\Database\QueryException
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'locale' (SQL: alter table `users` add `locale` varchar(5) null default 'en # you should change this for the desired language')
"
When I login into docker and run php artisan migrate I got:
"
root@8fdce0718222:/var/www/html# php artisan migrate
PHP Notice:  date_default_timezone_set(): Timezone ID 'Europe/London  # you should change this to your timezone' is invalid in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 49
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2016_03_10_133849_add_locale_to_users

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'locale' (SQL: alter table `users` add `locale` varchar(5) null default 'en # you should change this for the desired language')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +9 vendor frames
  10  database/migrations/2016_03_10_133849_add_locale_to_users.php:17
      Illuminate\Support\Facades\Facade::__callStatic()

      +22 vendor frames
  33  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
root@8fdce0718222:/var/www/html# "

Any help?
