### ISSUE TITLE
Feature Request: Filtering searches

### ISSUE THREAD

**Issue by seanmcilvenna** [snipe/snipe-it#4776] opened 2018-01-09 20:03 UTC
I would like to be able to filter on specific columns within the various listing screens. For example, I'd like to see all licenses by a specific vendor, or all "laptop" categoried assets.
We have 100s-1000s of assets and licenses, and although the "search" feature is helpful, it is still challenging to get a specific list of assets, licenses and components that I'm looking for.

**Comment by snipe** [comment] 2018-01-10 02:23
Duplicate of #3340

**Closed by snipe** 2018-01-10 02:23 UTC
