### ISSUE TITLE
Search bar at the top should be a general search instead of only for asset tags

### ISSUE THREAD

**Issue by brandenk514** [snipe/snipe-it#5960] opened 2018-07-25 14:00 UTC
**Server (please complete the following information):**
 - Snipe-IT Version: v4.5.0 
 - OS: Ubuntu 18.04 LTS
 - Web Server: Apache
 - PHP Version: 7.0

**Is your feature request related to a problem? Please describe.**
The search bar on the nav bar should be a general search and not specifically for asset tags.

**Describe the solution you'd like**
I would like to see the search bar at the top be a board search for users, assets, consumables, etc.

**Describe alternatives you've considered**
The search bar can be removed, therefore encouraging the user to use the search within each view.

**Comment by snipe** [comment] 2018-07-25 14:02
Duplicate of #3198

**Closed by snipe** 2018-07-25 14:02 UTC
