### ISSUE TITLE
Accept asset page doesn't redirect correctly for non-logged in users

### ISSUE THREAD

**Issue by niallmooney** [snipe/snipe-it#2377] opened 2016-08-01 22:47 UTC
#### Expected Behavior (or desired behavior if a feature request)

On clicking the link in the Confirm asset delivery email snipe-it. If the user isn't currently logged in the user should be redirected to the accept asset page once they have successfully authenticated.

-----

#### Actual Behavior

On clicking the link in the Confirm asset delivery email snipe-it. If the user isn't currently logged in the user is redirected back to the home page and not the accept asset page.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.1.0
- What OS and web server you're running Snipe-IT on: CentOS 6.8/Apache 2.2.15/PHP 5.6.24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual Installation
- If you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Accept Asset page for unauthenticated users.
- If a stacktrace is provided in the error, include that too: N/A
- Any errors that appear in your browser's error console: N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Unsure
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: N/A
- Include what you've done so far in the installation, and if you got any error messages along the way: Imported test assets and testing functionality of confirming assets.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by snipe** [comment] 2016-08-01 22:49
Duplicate of #2303

**Closed by snipe** 2016-08-01 22:49 UTC
