### ISSUE TITLE
FrontEnd Issue: Rescale images in view

### ISSUE THREAD

**Issue by rudashi** [snipe/snipe-it#2510] opened 2016-08-29 08:07 UTC
Problem with displaying images occurs in models/view.
Big images are not scaled when they are uploaded into AssetsModels.

**Comment by snipe** [comment] 2016-08-30 01:57
Screenshot please.

**Comment by rudashi** [comment] 2016-08-30 05:08
No problem.
![zrzut ekranu 2016-08-30 07 04 24](https://cloud.githubusercontent.com/assets/5038647/18076700/6960ebe6-6e80-11e6-9f2e-a697a3f13f09.png)

**Comment by snipe** [comment] 2016-08-30 06:25
I think this is a duplicate of https://github.com/snipe/snipe-it/issues/2488#issuecomment-242559016

**Comment by rudashi** [comment] 2016-08-30 13:04
You are right. It's HTML/CSS Problem.
I get quick fix for that:
file: view/models/view.blade.php
line: 97
change: 
`<li><img src="{{ config('app.url') }}/uploads/models/{{ $model->image }}" class="img-responsive"/></li>`

**Comment by snipe** [comment] 2016-08-30 13:05
Yep. Just haven't gotten around to it. If you want to throw that into a pull request, we'll accept it.

**Closed** 2016-08-30 14:35 UTC
