### ISSUE TITLE
Trusted Proxy not working after update to v3 - Mixed Content errors

### ISSUE THREAD

**Issue by drcryo** [snipe/snipe-it#2298] opened 2016-07-21 19:16 UTC
Let me first thank you guys for such a great piece of software, you made here. I very appreciate it and I'm working with it on daily basis.

But let's speak about that error I have. After successful upgrade to v3 (hour ago) from master branch, everything looks perfect until I've tried to access my instance through the reverse proxy. And Mixed Content problem is back.

Web is trying to access some static content thru http://, which ends with error, because our proxy denies it. I'm using HAproxy with unchanged setting, perfectly working with previous version (v2.1), so it sends correct HTTP Headers. I put correct IP address in my .env value. Even asterisk there is not helping.

Unfortunately there's no error in Apache logs, because connection is refused at HAproxy interface. I've tried changing APP_URL string, but no luck with that.

I would be glad for any guidance and thank you for it in advance. Also pardon me for my basic English.

**Comment by stevecookms** [comment] 2016-07-21 19:25
We have our instance setup with a reverse proxy as well (Version 3).

We had the same issue until we forwarded to port 443 to the internal site and setup a self signed cert on the internal web server running Snipe-IT.

**Comment by drcryo** [comment] 2016-07-21 20:22
@Steve, this should work, but just as temporary solution. It doubles SSL computing load and gets directly against meaning of Trusted Proxies module.
Nevertheless thank you for your suggestion.

**Comment by stevecookms** [comment] 2016-07-21 20:24
I totally agree.

**Comment by timwsuqld** [comment] 2016-08-11 00:02
Even with the correct 'APP_TRUSTED_PROXIES' we are also having this issue.

**Comment by timwsuqld** [comment] 2016-08-11 00:39
Maybe https://github.com/fideloper/TrustedProxy/issues/50 is related?

**Comment by gui81** [comment] 2016-11-16 05:20
I'm in the same boat.  I am new to snipeit, and am also setting up using official docker image, but cannot use it with my Apache server acting as the proxy, letting my Apache server handle SSL to the outside world.  APP_TRUSTED_PROXIES is set correctly.  Everything works fine if I don't use a proxy.

I have tried setting all of the following without luck in Apache:
        Header always set Content-Security-Policy: upgrade-insecure-requests
	Header always set Access-Control-Allow-Origin "*"
	Header always set Access-Control-Allow-Credentials true
	Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
	Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"
	RequestHeader set X-Forwarded-Proto "https"

upgrade-insecure-requests at least gets most of the assets working, even though they are directed to http instead of the expected https, but accessing anything at /api, /reports, etc... all return 401 (Unauthorized)/Response for preflight has invalid HTTP status code 401.

**Comment by jstoja** [comment] 2017-08-28 13:36
I'm having the same issues, and despite the documentation [about reverse proxying](https://snipe-it.readme.io/v3.6.2/docs/reverse-proxies) and [docker APP_URL](https://snipe-it.readme.io/v3.6.2/docs/docker) setup correctly, SnipeIT is the only service we're using that doesn't allow HTTPS to HTTP reverse proxying...
Has anyone managed to bypass this limitation?

**Comment by mnash04** [comment] 2017-08-30 17:03
ditto^. Using Apache reverse proxy -- following reverse proxy documentation on APP_TRUSTED_PROXIES and x forwarded proto https -- still no luck -- just a mixed content/unsafe script login page. snipe-it server works fine w/o reverse proxy, and the reverse proxy is configured correctly (for other sites that don't have mixed content issues). APP_URL is set to the reverse proxy URL. Using SnipeIT Version v3.6.6 build 1 / Apache 2.4.6. / Installed from GIT.

**Comment by jstoja** [comment] 2017-09-12 13:00
@mnash04 You mean by using the env var APP_TRUSTED_PROXIES ?

**Comment by jstoja** [comment] 2018-01-22 08:27
Nope, this is still happening.

**Comment by timwsuqld** [comment] 2018-05-07 21:42
@jstoja Are you still having issues with this?

**Comment by jstoja** [comment] 2018-07-12 20:38
they @timwsuqld I don't know, to be honest I'm not using snipe-it anymore.
You can probably try to reproduce it with this setup: `config is HTTPS reverse proxy -> HTTP snipe-IT`.

**Comment by snipe** [comment] 2018-07-12 21:09
We've released many new versions since this ticket was opened, including some changes to the proxy setup, so I'm going to close this for now. If its still a problem in 4.5, please open a new ticket.

**Closed by snipe** 2018-07-12 21:09 UTC
Labels: :hand: bug
