### ISSUE TITLE
After update to Version v4.3.0 Check in emails not working

### ISSUE THREAD

**Issue by Raj22223** [snipe/snipe-it#5470] opened 2018-05-03 10:44 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After update to Version v4.3.0 Check in emails not working

**Expected behavior**
When we tick mark the option check in email at category, it used to work now after the update emails not triggering after check in.

**Comment by snipe** [comment] 2018-05-03 11:05
Emails to whom? The admin, or the user that';s had an asset checked in?

Also, please don't delete the issue template questions in the future. They're there for a reason.

**Comment by sysnoo** [comment] 2018-05-03 19:48
Not Sure if it is related but I am having page with "Whoops, looks like something went wrong." only during checkin. Checkin email is not sent.
All good for checkout.
All was good with previous version.
The log is empty with no error or message.

Can this be caused because I made some manual change to the email template (Some additional text and footer)?

**Comment by snipe** [comment] 2018-05-04 03:33
I can't reproduce this - emails are firing for checkin and checkout for me.

**Comment by Raj22223** [comment] 2018-05-04 04:40
I tried with most of the categories, its not working for me, I am doing any thing wrong.

To get check in emails the following should be enabled right ?

1. Tick mark "Send email to user on checkin"
2. Email Alerts Enabled

**Comment by snipe** [comment] 2018-05-04 06:12
The category checkbox should be all you need. Are you sure the person its assigned to has an email address associated, and that email address is valid?

**Comment by Raj22223** [comment] 2018-05-04 08:52
_Are you sure the person its assigned to has an email address associated, and that email address is valid?_

Yes i am the person assigned and the email address is correct, to the same, I am receiving Check out emails, but not the check-in emails. this is happening after the upgrade

**Comment by Raj22223** [comment] 2018-05-11 11:41
#5523

**Comment by snipe** [comment] 2018-05-11 18:37
Again, I can't reproduce this at all.

**Comment by clmaliwat** [comment] 2018-05-21 15:33
Having the same issue with Emails not being sent upon checkin. This did not occur in previous versions. Started upon update to 4.3.0

**Comment by snipe** [comment] 2018-05-21 19:11
Okay, well I'm going to need screenshots here or something. As I've said, I can't reproduce it, and if I can't reproduce it, I can't fix it.

**Comment by snipe** [comment] 2018-05-21 19:11
Also can anyone pull the latest from master and tell me if you see it there as well?

**Comment by clmaliwat** [comment] 2018-05-21 23:11
Here are a group of screenshots: https://drive.google.com/drive/folders/1WBXiYgCsb4RTituoH7x5G2J6XZmdE8Um?usp=sharing

**Comment by snipe** [comment] 2018-05-21 23:16
@clmaliwat that error is telling you it's a [Gmail relaying error](https://support.google.com/a/answer/6140680?hl=en) - that doesn't have anything to do with Snipe-IT.

**Comment by clmaliwat** [comment] 2018-05-21 23:31
What’s the recommended roll back procedure?

**Comment by snipe** [comment] 2018-05-21 23:35
Depends how you installed it. But again, I'd be surprised if this fixes anything, as we didn't make any changes to the way we auth with the mail server. Why not just use sendmail and bypass trying to talk to Gmails servers?

**Comment by snipe** [comment] 2018-05-21 23:58
```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=snipe@snipe.net
MAIL_PASSWORD=XXXXXXXX
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=snipe+from@snipe.net
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR='phpchick+snipeitdemo@gmail.com'
```

<img width="682" alt="screen shot 2018-05-21 at 4 58 16 pm" src="https://user-images.githubusercontent.com/197404/40335398-34c37a74-5d18-11e8-9d41-0b60254f0085.png">


I just tested with these settings, and it works as expected. Why are you using smtp-relay?

**Comment by snipe** [comment] 2018-05-22 00:09
(Snipe.Net is a Gsuite email domain)

**Comment by clmaliwat** [comment] 2018-05-22 00:35
I had set it up as SMTP relay to not have to use an authenticated user and instead authenticate the public IP address of my server, which I do with many of my apps/devices that only send Email.

I just tested with an authenticated G Suite user and it's still not sending Email.

**Comment by snipe** [comment] 2018-05-22 00:43
You're sure you checked SPAM folder, etc? The only other suggestion I have is to recheck the account settings for "less secure" permissions, etc. https://snipe-it.readme.io/docs/configuration#section-using-gmail

Ultimately though, we didn't change anything with how Gmail/Gsuite works in this version.

**Comment by clmaliwat** [comment] 2018-05-22 00:49
Yes, Spam folder was checked multiple times over to no avail. Account does already have less secure options. I trust that you did not make any changes to G Suite SMTP validation because well, you can check that code fairly easily. It's just really strange.

Thanks for the support. I really appreciate the quick responses.

**Comment by clmaliwat** [comment] 2018-05-22 00:57
I'd like to try rolling back for the sake of testing. I installed with **composer.phar** and have been upgrading with **upgrade.php**

**Comment by clmaliwat** [comment] 2018-05-22 01:27
So I just re-installed my environment to the current version. Now the test Email sends fine when generating from https://url/admin/settings, but when performing check and checkout, users do not receive an Email.

**Comment by Raj22223** [comment] 2018-05-22 04:08
@snipe one thing I noticed, when there is tick mark for "Send email to user on checkin" under categories at the Check in page it should show the notification at the bottom as shown on the screen shot above right, but here the notification message is not displayed and check in email not triggered .

For me check out emails are working.

I am on v4.3.0 ( with Gmail SMTP) will post you the update after pulling the latest version.

![image](https://user-images.githubusercontent.com/34770213/40341594-aa47611c-5da3-11e8-8472-7c1cac3ea25e.png)
![image](https://user-images.githubusercontent.com/34770213/40341613-c2a0a926-5da3-11e8-9509-41b9911391ad.png)

**Comment by TheBags** [comment] 2018-05-22 13:15
I still have the same problem.
Snipeit send email at user creation but not at asset checkin/out.

looking at exim log (in tail), I can't see call during checkout/checkin.
The only generated email are the user registration one:
`2018-05-22 15:03:53 1fL6xD-0001xn-GF => giovanni.bagagli@gmail.com R=smarthost T=remote_smtp_smarthost H=smtp-relay.sendinblue.com [185.107.232.248] X=TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128 CV=yes DN="OU=Domain Control Validated,OU=EssentialSSL Wildcard,CN=*.sendinblue.com" A=cram_md5 C="250 Message queued as <d80ec10c5d621d39358fa1214272650a@snipeit.motork.io>"
2018-05-22 15:03:53 1fL6xD-0001xn-GF Completed`

Seems like no "send email" event was generated.

**Comment by TheBags** [comment] 2018-05-22 13:20
I don't have the blue box as in your example when I made a checkin
![screenshot from 2018-05-22 15-17-10](https://user-images.githubusercontent.com/2011000/40364721-4daeebac-5dd3-11e8-97b0-97b0013ace6f.png)

Every categories has the "send emailto user on checkin/checkout" selected
![screenshot from 2018-05-22 15-18-44](https://user-images.githubusercontent.com/2011000/40364829-86b823a0-5dd3-11e8-8e7c-1638eeff4091.png)

Tnx,
Giovanni

**Comment by clmaliwat** [comment] 2018-05-22 18:35
That's pretty much what I'm dealing with now.

**Comment by Raj22223** [comment] 2018-05-24 03:21
@clmaliwat is the issue resolved for you after the roll back ?

**Comment by clmaliwat** [comment] 2018-05-24 14:55
@Raj22223 I installed a new instance with the current version and now Emails are "generally working," but not checkin Emails. I'm pretty much in the same boat as @TheBags

**Comment by TheBags** [comment] 2018-05-25 08:55
a recap:
- Create account email --> works
- Scheduled alert email --> works
- CheckIn/Out email --> **_not working_**

**Version** v4.4.1 - build 3636 (master)

Giovanni

**Comment by D3nsha** [comment] 2018-06-29 15:24
v4.4.1 here, I have a similar issue. If the category has Acceptance Emails switched on, then the user will get Check-in/check-out emails. If Acceptance Emails are switched off, then Check-in/Check-out emails are not generated.

**Comment by TheBags** [comment] 2018-06-30 16:44
Probably @D3nsha found the problem.
On monday I'll check if it works.
Obviously the "Acceptance Emails" should be not connected with checkin/out emails.

Giovanni

**Comment by clmaliwat** [comment] 2018-07-02 17:28
Yep, this is definitely it. I just tested.

"Require users to confirm acceptance of assets in this category" is coupled with "Send Email to User on checkin/checkout"

If "Require users to confirm acceptance..." is not checked, the "Send email to user..." does not work, as @D3nsha has mentioned.

**Comment by Raj22223** [comment] 2018-07-06 04:41
Yes, Even the same happened for me I Just tested.

"Require users to confirm acceptance of assets in this category" is coupled with "Send Email to User on checkin/checkout"

@snipe could you please look in to this. Thanks in advance.

**Comment by mrjohnjones** [comment] 2018-07-09 15:09
To add to this, I just tested with a fresh/new install of v4.4.1 - build 3636 and can confirm that in order for the notifications to be sent for checkin/checkout, the option "Require users to confirm acceptance of assets in this category" must be enabled along with "Send Email to User on checkin/checkout".

**Comment by Raj22223** [comment] 2018-07-10 08:34
@snipe could you please check this

**Comment by mrjohnjones** [comment] 2018-07-10 19:57
Can anyone confirm if this has been fixed in 4.5.0?

**Comment by clmaliwat** [comment] 2018-07-10 22:40
@mrjohnjones I just tested 4.5.0 build 3701, and the issue persists.

**Comment by snipe** [comment] 2018-07-10 23:04
That's correct - if a fix were issued, this ticket would have been updated and it would have been noted in the release notes.

**Comment by snipe** [comment] 2018-07-17 04:02
This should be fixed on develop now and will be in the next release.

**Closed by snipe** 2018-07-17 04:02 UTC
Labels: :hand: bug, :woman_technologist: ready for dev

**Comment by Mafeercm** [comment] 2019-12-06 17:33
Hi,
My email configuration fine, test email function is working fine and users are able to receive when any assets are check out to them, but i need my admin  to receive the notifications for every check in and check out. this is not working for me, Kindly advise.

I have enabled email alert and Send email to user on checkin/checkout for all categories.

SnipeIT - Version v4.7.8
