### ISSUE TITLE
Feature Request - Custom Field for Licence

### ISSUE THREAD

**Issue by masterofdesaster2999** [snipe/snipe-it#4513] opened 2017-11-23 15:12 UTC
Desire Behavior 

Custom Fields for licence could be helpful to give more sorted informationen about them.

Information like: 
-Is it a permanent licence or a time based licence?  
-Solo place licence or Network licence?
-Version
-Serial number
and more

At the moment we place all information in the notice field. It is not really sorted and we have to write the information for each licence.

I think the easiest way to realize it is to implement a licence category.
That it is possible to add custom fields

Thanks

**Comment by snipe** [comment] 2017-11-30 03:37
Duplicate of #4261

**Closed by snipe** 2017-11-30 03:37 UTC
