### ISSUE TITLE
Part search in the Lookup by asset Tag field

### ISSUE THREAD

**Issue by davidmatthews85** [snipe/snipe-it#6283] opened 2018-10-03 10:06 UTC
If possible...

**Describe the solution you'd like**
Is it possible to be able to search on part matches in the Lookup by Asset Tag search box at the top?

At the moment having to go through Assets > All Assets and use the search field from there.

**Comment by snipe** [comment] 2018-10-03 10:28
Duplicate of #3198

**Closed by snipe** 2018-10-03 10:28 UTC
