### ISSUE TITLE
Departments permissions not working

### ISSUE THREAD

**Issue by Wyclef** [snipe/snipe-it#4584] opened 2017-12-06 23:43 UTC
#### Expected Behavior (or desired behavior if a feature request)

I have a group called "Managers" for whom I have disabled every right for "Departments".

"Departments" should not show up under "Settings" for a user under the "Managers" group.

-----

#### Actual Behavior

Not only does "Departments" show up under "Settings", the user can also create, edit, delete the departments even though he is in the "Managers" group only.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh Install**
- Version of Snipe-IT you're running **v4.1.8-pre - build 3034 (master)**
- Version of PHP you're running **7.0.25**
- Version of MySQL/MariaDB you're running **MySQL 5.6.37**
- What OS and web server you're running Snipe-IT on **Amazon Linux AMI and Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No errors**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Visiting Settings > Departments with account that has no rights to access it according to inherited group permissions**
- If a stacktrace is provided in the error, include that too. **None**
- Any errors that appear in your browser's error console. **None**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. **I don't have permission to put a user under a group.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. **None**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-12-06 23:48
Can you show me the rest of the permissions that group/user has?

**Comment by Wyclef** [comment] 2017-12-07 00:01
The group has all permissions except Super User, Users and Departments.

I disabled access to Admin and now it works as expected (i.e. Departments doesn't show up under Settings anymore.) However, I need Admin to allow the group to let him view the dashboard.

**Comment by snipe** [comment] 2017-12-07 00:34
Then it's working as expected, and that's a different request, duplicate of #4484.

**Closed by snipe** 2017-12-07 00:34 UTC
