### ISSUE TITLE
API endpoint to get assets assigned to a user also returns assets assigned to a location if the user and location IDs are the same

### ISSUE THREAD

**Issue by cofl** [snipe/snipe-it#6102] opened 2018-08-17 19:26 UTC
- [ ] I have enabled debug mode -- I do not have access to enable debug mode.
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The API endpoint for getting a user's assigned assets also returns assets assigned to a location if the user and location have the same ID.

**To Reproduce**

1. Check out an asset to a location. The ID for this location will be `$LOC_ID` below.
2. Execute an api reqest to `/api/v1/users/$LOC_ID/assets`.
3. The "rows" property will have the asset from step 1 as a member.

**Expected behavior**
The endpoint would return the a collection of the assets assigned to the just the user.

**Actual behavior**  
The endpoint returned a collection of the assets assigned to the user, and also to the location sharing the same ID as the user.

**Server (please complete the following information):**
 - Snipe-IT Version:  v4.6.3 - build 3866
 - OS: Ubunut 16.04.5 LTS
 - Web Server: Apache
 - PHP Version: 7.2.8

**Desktop (please complete the following information):**
 - OS: Windows 10 1709 build 16299.522
 - Browser: N/A -- using PowerShell
 - Version: 5.1.16299.522

**Error Messages**
- There is no error message.

**Additional context**
- I have checked the logs for a handful of the erroneous assets, and have not encountered a case where the asset had been assigned to the user, and then reassigned to a location.

The specific issue originally appeared while testing a C# wrapper to the API, but the results were duplicated with Invoke-RestMethod in PowerShell.

**Comment by cofl** [comment] 2018-08-17 19:35
I've done some more checking. The issue exists with MariaDB 10.0.34, but is not present with MariaDB 10.1.34 (though admittedly the environments are not identical).

**Comment by cofl** [comment] 2018-08-17 20:05
I'm going to try downgrading the database version on the second server, will update when that check is done.

**Comment by snipe** [comment] 2018-08-18 08:12
Duplicate of #6068

**Closed by snipe** 2018-08-18 08:12 UTC
