### ISSUE TITLE
Feature Request: Domain Name and Certificate Expiration Tracking

### ISSUE THREAD

**Issue by sarisdpreston** [snipe/snipe-it#3253] opened 2017-02-01 15:36 UTC
Hello,

It would be fantastic if Snipe-IT had the ability to track our purchased domain names and certificates along with their expiration dates. Also, if possible, be alerted when their expiration date is approaching.

Thanks!

**Comment by snipe** [comment] 2017-02-01 20:02
Duplicate of #79

**Closed by snipe** 2017-02-01 20:02 UTC
