### ISSUE TITLE
Accept and Sign for multiple assets at once

### ISSUE THREAD

**Issue by el-capitano** [snipe/snipe-it#5955] opened 2018-07-25 10:44 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
Each time you send an asset that requires acceptance the user has to Accept and sign, when the user is assigned multiple assets this becomes repetitive task that might make the user get bored of this.

**Describe the solution you'd like**
Select all assets that belong to specific user and send one email that contains the Accept and signature for all assigned assets, this could be an added feature to the one currently implemented in the system.

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment] 2018-07-25 11:01
Duplicate of #5947

**Closed by snipe** 2018-07-25 11:01 UTC
