### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by uknzaeinozpas** [snipe/snipe-it#4403] opened 2017-11-08 15:53 UTC
#### Expected Behavior (or desired behavior if a feature request)

Three small issues with the UI:
1. The settings menu item has a unnecessary rounded corner
![snipe_0](https://user-images.githubusercontent.com/22473767/32557859-a6267436-c4a3-11e7-9309-5fc085acc659.png)
2. All menu items that can be expanded are not clickable, all other are. E.g. if I click on licenses, the license view opens, if I click on assets, then the menu just roll up
3. If I minimize the "Assets by Status" widget the box wont roll up, just the content
![snipe_2](https://user-images.githubusercontent.com/22473767/32557866-ad50db84-c4a3-11e7-9ad1-99fdfb837fdb.png)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade** 

- Version of Snipe-IT you're running **v4.1.3 build 94 (gb6a14d2)**
- Version of PHP you're running **5.6**
- Version of MySQL you're running **5.7**
- What OS and web server you're running Snipe-IT on **Windows**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual with git**

**Comment by snipe** [comment] 2017-11-08 21:13
1 and 3 are fixed on develop. Number 2 is by design.

**Closed by snipe** 2017-11-08 21:13 UTC
