### ISSUE TITLE
Accept asset on checkout

### ISSUE THREAD

**Issue by worthy92** [snipe/snipe-it#5376] opened 2018-04-16 22:07 UTC
#### Expected Behavior (or desired behavior if a feature request)

When an asset is checked out (user is normally with me at the time) it would be good to allow it to get an option for it to be accepted there and then or for an email to the user to get sent. That way I can ensure that users accept the asset before taking it away and then it doesn't involve me having to chase them to accept it.

-----

#### Actual Behavior

Only an email is sent to the user. No feature to have them accept/sign for it there and then.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade - was fresh from V3.0
- Version of Snipe-IT you're running 4.2.0
- Version of PHP you're running 7.1.1
- Version of MySQL/MariaDB you're running 5.6.23
- What OS and web server you're running Snipe-IT on Windows Server 2012 R2 - IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Github
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Checking out asset to user
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-04-17 02:46
Duplicate of #3330

**Closed by snipe** 2018-04-17 02:46 UTC
