### ISSUE TITLE
Produce assets for consumables & option to checkout more than 1 quantity

### ISSUE THREAD

**Issue by JensRod** [snipe/snipe-it#7001] opened 2019-05-07 13:19 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: [MacOS ]
 - Web Server: [Apache]
 - PHP Version ? 

**Is your feature request related to a problem? Please describe.**
We have integrated Snipe-IT to our church, and so far we love it. We have a storage room where we have different consumables like cups, coffe, snakcs etc. Right now if you want to check out for example 200 cups out of 1000 you need to check out 1 and 1. 

Also it would be nice to be able to produce assets from the consumables page, so we can stick labels on a shelf, and when a team-member picked up the scanner, they could scan the label and it would automatically find that exact consumable and option to choose how many of that they wanted to check out. 
 
**Describe the solution you'd like**
If it was possible with a textfield where you could write how many of that consumable you liked to check out that would be great. And of course a warning if you tried to check out 200, but there we only 100 available.  

And add the generate label option to consumables, but maybe have a diffirent ID setup from the Asset page. 

**Describe alternatives you've considered**
It could be possible to just add cups to the asset page, but we think that the hole consumables page would just become useless, and you can not make more quantities of the exact asset. 

**Additional context**

**Comment by snipe** [comment] 2019-05-07 13:27
Duplicate of #5140 and #3957

**Closed by snipe** 2019-05-07 13:27 UTC
