### ISSUE TITLE
[feature request] more detailed license management options

### ISSUE THREAD

**Issue by ranX** [snipe/snipe-it#2662] opened 2016-09-22 10:41 UTC
Hello !
I found and started to use snipe-it because I need a solution for maintaining my company's licenses.
It already does a pretty neat job but why not enhance the features ... ;)
I think many Admins want to keep track of their licensing, to support them in software assessment and will welcome to be supported by snipe-it.

Neat features to have for software management, would be the ability to set "categories" and "models" (in this case software types) to make them selectable, when I store software information to snipe-it.
This is already possible for assets, so it might be extended to software ?
Another nice thing would be the option to create custom fields for software as well as this can already be done for assets.

Some examples about software information, where it would be nice to be able to record as categories:
let's take MS Office to clarify this
- what kind of licensing do I have at all ? commercial, open source
- what kind of MS licensing is used ? Box License, OEM, eOpen, 365
- what Subversion of make do I have ? Home & Business, Pro, Pro Plus
- what Subversion of year do I have ? 2010, 2013, 2016

It would also be nice to store information about the residence of these licenses (eg. sticker on the asset, Box License in the bosses safe, printed license document in my drawer etc.)
Last but not least it would be nice to store license documents eg. as PDF with the record of the license.

I'm aware that's alot ... ;)
I'd like to say "thank you" for reading my request and would be even more happy to see some of the above features in future releases.

In case I can contribute by testing on my local snipe-it install (Debian 8), I will be happy to do so !

Best Regards

ranX

P.S.: While entering more data I found two other "nice-to-haves"
- another field to distinguish between OS and Application license
- the option of "overdeploying" licenses plus visual (or even mail) notification, when licenses are exhausted or overused

**Comment by snipe** [comment] 2017-10-19 10:10
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:10 UTC
Labels: feature request
