### ISSUE TITLE
Feature Request: Checkout Consumable to Asset

### ISSUE THREAD

**Issue by wilsonlspacheco** [snipe/snipe-it#4946] opened 2018-01-31 13:03 UTC
#### Expected Behavior (or desired behavior if a feature request)

Im IT Tech from a Hosted Customer (it@introsys.eu)
We've been reading issues #4927, #4597,  #4582, #3507, #1538... but this (simple) feature apears doesn't exist yet.

We want checkout consumables to an asset (ex: printer), you can enable it? Its a very important feature to us and we believe it for other people too.

-----

#### Actual Behavior

Now i'm only able to checkout to user

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  
Hosted

- Version of Snipe-IT you're running 
v4.1.10 build 3249 (g8d3a214)

- Version of PHP you're running 
7.1.11

- Version of MySQL/MariaDB you're running N/A
- What OS and web server you're running Snipe-IT on N/A
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) N/A
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error N/A
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database N/A

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cslucian** [comment] 2018-01-31 13:57
Hi you can add issue #4582

**Comment by snipe** [comment] 2018-03-29 11:41
Duplicate of #4582

**Closed by snipe** 2018-03-29 11:41 UTC
Labels: :heart: feature request, :woman_technologist: ready for dev

**Comment by wilsonlspacheco** [comment] 2018-03-29 11:58
@snipe .. 

You closed our ticket #4946 (marked "ready for dev") as "duplicated" with ticket #4585 that isn't marked "ready for dev" ? .. We know this ticket was duplicated, we refered all tickets with this feature request in our description, since Dec 29, 2015... 

So.. whats the state of this feature now ? redy for dev or not?

**Comment by snipe** [comment] 2018-03-29 12:15
@wilsonlspacheco Ready for Dev just means that the feature as a concept has been approved by the maintainers, so that if someone wanted to work on it, the idea has as least been vetted. It doesn't actually mean it's been started. 

It's a ticket that gets duplicated frequently, and we just missed tagging it as ready for dev.

**Comment by Mynty100** [comment] 2018-05-02 03:55
This feature would be perfect as we are in a school and have many shared/network printers. 
Cheers.

**Comment by wilsonlspacheco** [comment] 2018-05-02 06:38
@Mynty100 i agree, network printers is a normal and standard scenario in 90% of schools and companies.. !

**Comment by slax-creator** [comment] 2021-05-04 08:04
Any update on this? Would be greatly appreciated.

**Comment by jarrodCoombes** [comment] 2022-02-09 18:11
Wondering if this feature is being considered or not? Would make sense in some environments (like mine) and for things that are not assigned to people (eg projector bulbs for mounted projectors).

**Comment by kristiannikolaev** [comment] 2022-05-03 11:14
I would love that feature! I want to checkout a toner (consumable) to a printer (asset) 🙏

**Comment by MikeArmstrong2** [comment] 2023-04-05 15:12
Another vote for this please

**Comment by rozhkoserhii** [comment] 2024-12-17 10:17
Do you plan to develop this feature ?

**Comment by davidpazo** [comment] 2025-05-05 09:50
i vote for add this feature to the project. Thank you in advance

**Comment by HyblerGroup** [comment] 2025-05-06 14:51
Would love this - mostly for printers but thats a big part of my assets
+1
