### ISSUE TITLE
Auto Increment Asset Tag for different categories

### ISSUE THREAD

**Issue by Domekologe** [snipe/snipe-it#5498] opened 2018-05-08 13:02 UTC
**Server (please complete the following information):**
 - Snipe-IT Version: 4.3.0
 - OS: Windows Server 2012R2
 - Web Server: IIS
 - PHP Version: 7.0.9

**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
It would be nice, to make an auto increment for the Asset Tag, for different Asset Categories.
In our example we have the categories Notebooks, Workstations, Mobile Phones.
The names are %Country%%Location%%Category%%InventoryNumber%
Example: GEMUCN111 (Germany, Munich, Notebook, Number 111)

So it would be very nice, if it's possible to make an such auto increment for different categories.
Actually, we must look for every new device, which number was the last one.

The list is actually (in the settings):

Asset IDs                                                 [checkbox]Generate auto-incrementing asset IDs 
Next auto-increment                                [int]
Prefix (Optional)                                       [textbox]
Length of asset tags, including zerofill      [int]

What it would be nice to have

Asset IDs                                                 [checkbox]Generate auto-incrementing asset IDs 
Asset Category                                        [listbox with the asset category]
Next auto-increment                                [int]
Prefix (Optional)                                       [textbox]
Length of asset tags, including zerofill      [int]

I hope it's understandable, my english is not the best.
Best Regards,
Domekologe

**Comment by snipe** [comment] 2018-05-08 13:07
Duplicate of #3286

**Closed by snipe** 2018-05-08 13:07 UTC
