### ISSUE TITLE
LDAP Information Missing/Not Importing

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3555] opened 2017-05-10 00:01 UTC
#### Expected Behavior (or desired behavior if a feature request)

When running a LDAP import, additional user info such as phone number and employee ID is imported with user account.

-----

#### Actual Behavior

When I run an LDAP import, the only info that comes across is first name, last name, and email address.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **3.6.4**
- What OS and web server you're running Snipe-IT on: **CentOS, Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **None**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **People page, LDAP import function.**
- If a stacktrace is provided in the error, include that too: **None**
- Any errors that appear in your browser's error console: **None**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): **LDAP not applicable to demo.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **Path not valid in current build**
- Include what you've done so far in the installation, and if you got any error messages along the way. **I verified the attributes in the LDAP settings match the actuall attributes in AD and verified information exists.**
- Indicate whether or not you've manually edited any data directly in the database: **No**

**Comment by snipe** [comment] 2017-05-16 02:39
Closing as duplicate of #3373

**Closed by snipe** 2017-05-16 02:39 UTC
