### ISSUE TITLE
Issue with page not showing content because of the "remembered last selected page"

### ISSUE THREAD

**Issue by construkted** [snipe/snipe-it#6682] opened 2019-02-05 11:13 UTC
#### Please confirm you have done the following before posting your bug report:

- [Not applicable] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The selected page on a section is remembered (sometimes) when navigating to another section. This sometimes results in an empty page because the new section does not the page number you were looking at on the previous section.

**To Reproduce**
1. Go to "All Assets" and navigate to a page number higher than the number of pages on e.g. the "All Ready to Deploy" section. If you have one page of RTD-assets, navigate to e.g. 2 or 3
2. Now, navigate to the "All Ready to Deploy" section
3. There is a possibility no records are shown, although there should be records in this section. 
   3a. If the issue does not occur after the first attempt, retry going to the "All Assets" section, select the next page, and navigate back to the RTD assets section. It seems like the page number is remembered every xx seconds, that's why it does not always occur.

**Expected behavior**
The Ready to Deploy assets should always be visible when navigating to the "All Ready to Deploy" section, no matter what page you selected in another section.

**Screenshots**

Assets in RTD: 
![image](https://user-images.githubusercontent.com/45853823/52270007-f87b0100-293f-11e9-9125-510dfc69446b.png)

Switch to another page in All Assets:
![image](https://user-images.githubusercontent.com/45853823/52270249-ad152280-2940-11e9-8965-3b3578e03ba7.png)

No assets in RTD now:
![image](https://user-images.githubusercontent.com/45853823/52270155-61627900-2940-11e9-86db-3de39aefb5f1.png)

Switch back to page 1 on All Assets, and the assets appear again.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version: 7.2.10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, IE, Firefox tested and confirmed
 - Version: Chrome 71.0.3578.98, IE/FF also latest

**Additional context**
- Is this a fresh install or an upgrade? Happens on fresh and upgraded install
- What method you used to install Snipe-IT? Manual as well as git version do this
- Indicate whether or not you've manually edited any data directly in the database - No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2019-02-05 21:21
Duplicate of #6341. This has been fixed and will be in the v5 release.

**Closed by snipe** 2019-02-05 21:21 UTC
