### ISSUE TITLE
[Feature Request] Asset Containers

### ISSUE THREAD

**Issue by nextonphotos** [snipe/snipe-it#2009] opened 2016-05-05 02:33 UTC
It would be helpful if we could create containers/cases in the system.

For example, my company is an event photography company.  We arrive on site at events and set up portable studios with backdrops, cameras, computers, etc.  Each set up, which we call a kit, consists of several cases.  Each case can contain several assets (like cameras, or printers) and several accessories (like cables or print catchers).

We would like to be able to assign everything within a case to a parent container and then we would like to put several containers into a parent container, or kit.  Then, when we assign a setup to a photographer, we can just assign the parent container in Snipe-IT to that user and all of its child containers, assets, and accessories automatically get assigned to that user as well.

When viewing a specific container, it would list all of its children, perhaps in a tree structure so child containers could be expanded to see their children as well.

This could almost be handled by the existing location system if locations could be assigned to users while cascading the assignment and if the proper views were implemented.

Is this something that would be useful to anyone else, or just us?

**Comment by CaptainNapalmSE** [comment] 2016-05-05 20:21
We have a similar situation for our remote users (it may be less in-depth than what you have, but it's still a pretty good bundle of things).  If we could link all of a remote user's assets into a single kit, that would be awesome.

**Comment by DocCmajor** [comment] 2016-05-19 20:25
This would be very helpful for me as well! I'm in the same boat as CaptainNapalmSE, being able to tag a charger to a laptop and give a full list of everything we expect back when someone leaves... would be awesome!

**Comment by dmeltzer** [comment] 2016-05-19 23:10
I think the idea of "kits" is at least partially addressed with components in v3.  You can assign "parts" to your asset with components, but they are more like accessories than they are assets themselves (no unique assetId).  This code might be able to be adjusted/repurposed relatively simply though to work with assets though, and I can see some uses for it certainly.

**Comment by snipe** [comment] 2016-05-19 23:13
We've gotten similar requests before. In concept, this works more like locations, where you can check out all of the things in a single location (specifically a child location) at one time. It's something we'll be working on once v3 is out.

**Comment by snipe** [comment] 2017-06-10 00:10
Closing as duplicate of #563

**Closed by snipe** 2017-06-10 00:10 UTC
Labels: feature request
