### ISSUE TITLE
Feature Request: Unique License Key Support

### ISSUE THREAD

**Issue by Domceru** [snipe/snipe-it#5302] opened 2018-04-02 22:57 UTC
#### Expected Behavior (or desired behavior if a feature request)

While we have some bulk license keys for certain programs, such as O365, we also have one-off keys for certain programs used on a smaller scale. So say for example, we have 5 Adobe Acrobat keys. It would be nice to create one group for Adobe Acrobat and create a "pool" of licenses for that product, and manually or automatically assign seats available based on how many licenses you assigned for that group. So basically, when you clicked checkout, it would pull one of the 5 available licenses, and list it for you to use. 

It could look something like this.
![capture](https://user-images.githubusercontent.com/26557133/38220312-2638fed8-369f-11e8-9d41-ef6c48a2eec8.PNG)

![capture2](https://user-images.githubusercontent.com/26557133/38220473-f6a3a41a-369f-11e8-8d67-a1ab5ed6769c.png)

-----

#### Actual Behavior

Currently, it seems the only way to do something like this would be to have 5 separate License groups for the same software, each assigned 1 seat available.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-04-02 23:03
Duplicate of #4729

**Closed by snipe** 2018-04-02 23:03 UTC
