### ISSUE TITLE
Save custom asset reports and email on schedule 

### ISSUE THREAD

**Issue by BarryCDV** [snipe/snipe-it#5664] opened 2018-06-06 11:11 UTC
v4.2.0 - build 3508 (master)

A way to Save Custom asset reports and email them on Schedule.

A way to do this would be insanely useful to me, there are a couple of reports I need to run and report on often, one every day and one every week. I would find it very, very useful If I could have this report waiting in my inbox for me in the mornings or on a Monday for example. 

I couldn't see a way to do this via the web console?

**Comment by snipe** [comment] 2018-06-06 20:28
Duplicate of #4616

**Closed by snipe** 2018-06-06 20:28 UTC
