### ISSUE TITLE
Feature Request: Custom Fields/Rename Fields

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#854] opened 2015-06-16 19:58 UTC
I'm hoping that in the future this will definitely be available. There are certain items that we need to be able to track. OS is a big one. I see that you can create a license with an amount of seats. I was thinking more of when creating an asset that you have this field already with a drop down to be able to select an OS.

Renaming fields would just be a bonus honestly.

**Comment by snipe** [comment] 2015-06-16 20:02
This might be a duplicate of #98?

**Closed** 2015-07-02 23:23 UTC
