### ISSUE TITLE
Feature Request: Ability to turn default fields on or off.

### ISSUE THREAD

**Issue by QuincyTech** [snipe/snipe-it#4480] opened 2017-11-17 19:57 UTC
#### Expected Behavior (or desired behavior if a feature request)

I don't need a supplier for every maintenance record, most will be internal.

-----

#### Actual Behavior

Want to assign new maintenance record but forced to pick a supplier.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  **Fresh**
- Version of Snipe-IT you're running    **v4.0.15 build 339**
- Version of PHP you're running           **7.1.7**
- Version of MySQL/MariaDB you're running    
- What OS and web server you're running Snipe-IT on    **Win10 Pro**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)   **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error     **/hardware/maintenances/create?asset_id=3**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.     **No**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.   **Yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database   **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-11-22 05:53
Duplicate of #4063

**Closed by snipe** 2017-11-22 05:53 UTC
Labels: ♥ feature request
