### ISSUE TITLE
Unable to update assets having custom fields with custom (regexp) format

### ISSUE THREAD

**Issue by Neepawa** [snipe/snipe-it#4379] opened 2017-11-04 16:54 UTC
#### Expected Behavior (or desired behavior if a feature request)

Field is validated against the user supplied regular expression. In my test case, I set the regexp to `.`, which matches anything.

-----

#### Actual Behavior

`ERROR: exception 'BadMethodCallException' with message 'Method [validate.] does not exist.' in /usr/share/ngin    x/html/snipeit/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1110#52 /usr/share/nginx/html/snipeit/vendor/fideloper/proxy/src/Trus    tProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))`

-----

#### Please confirm you have done the following before posting your bug report:

- [✓ ] I have enabled debug mode 
- [ ✓] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh install**
- Version of Snipe-IT you're running **Latest** (Version v4.1.2 build 48 (gd21c92f))
- Version of PHP you're running **5.6.31** (php56u from IUS repo)
- Version of MySQL/MariaDB you're running **5.5.56-MariaDB**
- What OS and web server you're running Snipe-IT on **CentOS 7, nginx**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Git clone**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **See above**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Asset Update** (`hardware/xx/edit`)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: **Yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. **Normal install; nothing out of the ordinary,**
- Indicate whether or not you've manually edited any data directly in the database **No.**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-11-05 00:03
That's not really a bug, it's just how laravel validation works. I am about to push a PR that should help make that cleared. (Also this is kind of a duplicate of #4236)

**Closed by snipe** 2017-11-05 00:03 UTC
