### ISSUE TITLE
No accesories under selected category

### ISSUE THREAD

**Issue by ernestasen** [snipe/snipe-it#1858] opened 2016-03-16 10:36 UTC
I would like to see the list of accessories that I have when I press on category that is set to type "Accessory".

When I go to category list, I see that there is line like this:
Category         Type                Assets
Headphones	Accessory	8

When I press on that category, I can't see the accessories that make this number 8. This is the message I get: "No matching records found". However, if I do the same on category that is set to "Asset", I can see the list of items. 

Setup information:
Snipe-IT v2.1.0-41
Ubuntu 14.04.4 LTS
Apache/2.4.7
Installed using install.sh

**Comment by snipe** [comment] 2016-03-16 10:37
Duplicate of https://github.com/snipe/snipe-it/issues/1634

**Closed by snipe** 2016-03-16 10:37 UTC
Labels: duplicate
