### ISSUE TITLE
Implement "Sub-assets"

### ISSUE THREAD

**Issue by Freaksed** [snipe/snipe-it#965] opened 2015-07-27 22:02 UTC
It would be nice to be able to assign assets to each other. Use case being components in a computer. This would be great to be able to assign video cards to a system in the scenario that you change the card in a computer.

**Comment by madd15** [comment] 2015-07-27 22:08
Duplicate of #16 ?

**Comment by snipe** [comment] 2015-07-27 22:08
Yep :)

**Closed by snipe** 2015-07-27 22:08 UTC
