### ISSUE TITLE
Auto-increment Issue

### ISSUE THREAD

**Issue by rich678** [snipe/snipe-it#3861] opened 2017-08-17 08:15 UTC
#### Expected Behavior (or desired behavior if a feature request)

Auto-increment continues as expected from last imported item and not only from last manually entered item.

-----

#### Actual Behavior

Auto-increment is not recognizing bulk imported items and continuing from last manual entry instead of continuing from where the last imported item ends.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.3 build 15 (g1bf34d7)

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment] 2017-08-22 21:16
Closing as duplicate of #3657, #3498, #3203

**Closed by snipe** 2017-08-22 21:16 UTC
