### ISSUE TITLE
Header Color Does Not Change With Setting

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#946] opened 2015-07-23 19:59 UTC
When you change the header color to red for instance, you end up with a barely visible red border around the header section. The expected behaviour would be to change the header colour in full so that darker logos become visible without adding a background to the image

 #476 

![snipeit header color](https://cloud.githubusercontent.com/assets/13473044/8860709/89dfb89a-3153-11e5-9655-b750cbed691e.png)

**Comment by snipe** [comment] 2015-07-23 20:00
I'm not able to reproduce this on the demo. 

<img width="739" alt="screen shot 2015-07-23 at 1 00 08 pm" src="https://cloud.githubusercontent.com/assets/197404/8860767/cc844274-313a-11e5-8d3c-8b2c0d33b462.png">

**Comment by dscherertfm** [comment] 2015-07-23 20:06
I downloaded the latest version, and this is what I'm seeing. I tried to clear the cache as well to no effect. I attempted to change the background colour in the demo to red and got the same result. Running Firefox 39 on Windows 8.1 Pro. Works fine in Chrome though.

**Comment by madd15** [comment] 2015-07-23 23:05
@snipe Firefox doesn't seem to render the inline `background: -webkit-linear-gradient(top,  {{{ Setting::getSettings()->header_color }}} 0%,{{{ Setting::getSettings()->header_color }}} 100%);`

**Comment by snipe** [comment] 2015-07-24 23:30
This is fixed in v2.0

**Closed by snipe** 2015-07-24 23:30 UTC
Labels: bug, frontend

**Comment by dscherertfm** [comment] 2015-07-25 00:18
That's what's up. You rock man. ?

On 24 Jul 2015 7:30 pm, snipe <notifications@github.com> wrote:

This is fixed in v2.0

-
Reply to this email directly or view it on GitHub<https://github.com/snipe/snipe-it/issues/946#issuecomment-124765433>.

CONFIDENTIALITY NOTICE: This electronic message contains information which may be legally confidential and/or privileged and does not in any case represent a firm TARGET FREIGHT MANAGEMENT bid or offer relating thereto which binds the sender without an additional express written confirmation to that effect. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error, and delete it. Thank you.

**Comment by snipe** [comment] 2015-07-25 00:19
![bctdptx](https://cloud.githubusercontent.com/assets/197404/8886992/2cdee6f4-3228-11e5-8d8f-10c1614110d1.gif)
