### ISSUE TITLE
error:Opening My license directory list while accessing license on dashboard.

### ISSUE THREAD

**Issue by ctacay** [snipe/snipe-it#4239] opened 2017-10-18 07:13 UTC
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
When opening a license link on dashboard it automatically opens the directory of licenses which is the folder of xampp folder under licences.
<img width="686" alt="snipe_lic1" src="https://user-images.githubusercontent.com/32893706/31705129-3f532664-b3f5-11e7-90c1-ced51f99cb5d.PNG">
<img width="446" alt="snipe_lic2" src="https://user-images.githubusercontent.com/32893706/31705133-4411c4ee-b3f5-11e7-9450-c3550b0bc2fe.PNG">

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ no] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  
Fresh Instakk
- Version of Snipe-IT you're running
snipe-it-4.0.11
- Version of PHP you're running
PHP/7.1.9
- Version of MySQL/MariaDB you're running
10.1.26-MariaDB
- What OS and web server you're running Snipe-IT on
Windows 10/ XAMPP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-10-18 07:34
Duplicate of #4031

**Closed by snipe** 2017-10-18 07:34 UTC

**Comment by AnandIndia** [comment] 2017-12-07 12:53
Fresh Install
snipe-it-4.1.5
PHP/am not sure
XAMPP control panel v3.2.2
windows 7/XAMPP
Manual installation
WITH DEBUG TURNED ON


licence page showing this is error when i click license tab
![2](https://user-images.githubusercontent.com/34304008/33716331-326156aa-db6f-11e7-81a0-d966f44a2dd7.png)

**Comment by purush44** [comment] 2017-12-21 10:35
Hello Snipe,

Even we are having the same issue, any solution for the above problem ?
Highly appreciated

**Comment by purush44** [comment] 2017-12-21 10:36
@ AnandIndia  Did you find any solution to solve the above issue mate ?

**Comment by purush44** [comment] 2017-12-26 06:40
Guys if you don't find any solution to get Licenses Page working for Snipe in XAMPP Server, then try using WAMP Server, it works without any issues

**Comment by agentbb** [comment] 2017-12-26 12:24
Edit "httpd-xampp.conf" and delete lines below,

https://pasteboard.co/GZZvLzv.png
