### ISSUE TITLE
Only Asset module not working

### ISSUE THREAD

**Issue by jamnabai** [snipe/snipe-it#6750] opened 2019-02-21 03:41 UTC
only asset module not working 
Whoops, looks like something went wrong.
(2/2) ErrorException
compact(): Undefined variable: operator (View: C:\inetpub\wwwroot\snipe-it\resources\views\hardware\index.blade.php)
install in iis manager
![asset module error code](https://user-images.githubusercontent.com/42636964/53142080-a7624280-35b8-11e9-87c2-c59469cd4447.PNG)

**Comment by snipe** [comment] 2019-02-21 04:17
Please see the documentation. 
https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

Additionally, please complete the issue template before submitting an issue moving forward.

Closing as duplicate of #6586.
https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues
https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

**Closed by snipe** 2019-02-21 04:17 UTC

**Comment by jamnabai** [comment] 2019-02-21 05:22
I tried lower php version also not working only php v7.3 working but asset module problem

And php v7.0 and 7.2 not connect database.

 

 

 

Best Regards,
 
Afzal Momin
-----------------------------------------------------------
Narsee Monjee Educational Trust's
Jamnabai Narsee School,
Mumbai - India.
Website:  <http://www.jns.ac.in> www.jns.ac.in
Tel: +91 22 26187575 / 7676 , Ext(168)
Cell: +91  8879068884
----------------------------------------------------------
