### ISSUE TITLE
Assigning/checking out assets to a location instead of a user

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1221] opened 2015-10-02 18:56 UTC
Hello,

I'm looking to use Snipe-IT for tracking the electronics inventory we have both in particular offices (which are checked out to particular users) as well as for tracking the electronics inventory on our trucks & trailers. With that said I have two questions that I hope you can help with! 

1. Is it possible for me to check-out assets to a location specifically instead of a user? 

The issue I am facing is that a given "user" may be assigned to a different truck/trailer (_location_) from week to week. Instead of having them haul of the electronics off of the trailer and into the new one they're moving to they simply switch vehicles/trailers as each trailer/truck combo has the same equipment on it.

2. Is it possible to run a _Location Report_ or something similar to that of a given user where I can see all assets checked out to that particular person?

Thanks! Keep up the awesome work, I really appreciate it!

**Comment by snipe** [comment] 2015-10-02 18:58
Closing as duplicate of #142 and #866

**Closed by snipe** 2015-10-02 18:58 UTC
Labels: duplicate
