### ISSUE TITLE
FEATURE REQUEST: Make it so a user can request assets online

### ISSUE THREAD

**Issue by nickmacwiz** [snipe/snipe-it#620] opened 2015-03-09 15:17 UTC
When a user logs in and sees add a request this item button in the actions area and when a person with checkout capability click on that user later they can see what the user has requested and can click the checkout button to checkout the requested items. 
![screenshot 2015-03-09 08 14 09](https://cloud.githubusercontent.com/assets/11078660/6557809/23fed59e-c635-11e4-8c1d-decc12e15f1b.png)

**Comment by snipe** [comment] 2015-03-12 20:45
This is already planned.

**Comment by dbierspb** [comment] 2015-03-17 03:00
This will likely be my favorite part -- can't wait to see it :D

**Comment by drahamim** [comment] 2015-04-15 17:50
Saw this (as I would also like this feature) and thought I would also note for when this is completed that It is marked as duplicate (but no note as to the original request) of  #12 so that they can be closed together.

**Comment by snipe** [comment] 2015-05-07 08:57
Closing as duplicate of #12

**Closed by snipe** 2015-05-07 08:57 UTC
Labels: duplicate
