### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by YCYee912** [snipe/snipe-it#491] opened 2015-02-04 00:39 UTC
@snipe, do you mean this? 
![composer](https://cloud.githubusercontent.com/assets/10839182/6032860/4adfaa86-ac49-11e4-8949-aaa0270fad02.png)

**Comment by snipe** [comment] 2015-02-04 00:40
No, the composer install has to come before the artisan install.

**Comment by YCYee912** [comment] 2015-02-04 00:44
or this? It seems i having some error on it..i tried to follow the instruction from your WIndows Installation doc.. however, I am totally newbie in this can't understand much..thanks for your teaching
![image](https://cloud.githubusercontent.com/assets/10839182/6032900/c16675c2-ac49-11e4-8285-8f4e7f0d6806.png)

**Comment by snipe** [comment] 2015-02-04 00:47
The composer error you're seeing is telling you what's wrong. You don't have the `fileinfo` extension loaded into your PHP [which is a requirement for using Snipe-IT](http://docs.snipeitapp.com/index.html).

Please see the [fileinfo usage and installation instructions](http://www.php.net/manual/en/fileinfo.installation.php):

> Windows users must include the bundled php_fileinfo.dll DLL file in php.ini to enable this extension.

That DLL file is bundeled with PHP 5.3.6 for example, you can find the files here: [PHP For Windows - Binaries and sources Releases](http://windows.php.net/download/). It should be already located in the `ext` subdirectory of your PHP installation. If not download it again from the said website (choose your PHP version) and place it into the extension directory.

You need to add the following line your `php.ini` then to activate it:

    extension=php_fileinfo.dll

That's the standard procedure to activate a PHP extension under windows. You can find more information about how to actiave a PHP extension here: [Installation of extensions on Windows](http://php.net/manual/en/install.windows.extensions.php). If you have problems to locate the php.ini file, please refer to the [PHP installation instructions - Installation on Windows systems](http://www.php.net/manual/en/install.windows.php).

Then re-run the composer installation and the artisan installation.

**Comment by YCYee912** [comment] 2015-02-05 13:31
![image](https://cloud.githubusercontent.com/assets/10839182/6060965/30755516-ad7e-11e4-9880-e2cf60583325.png)
thanks for you guidance, after i located the php_fileinfo.dll it manage to install and download some necessity..and then i got this..how to solve this?

**Comment by uberbrady** [comment] 2015-02-05 20:00
This looks like a temporary error in DNS resolution. You should be able to try again and it should work. Unless you have some kind of strange DNS server running that doesn't let you resolve hostnames.

If not, it seems to want you to install Git, but I don't think I had heard that one before - that's usually only if you want to *develop* on Snipe-IT - and you just want to *use* it, so it shouldn't be required.

**Comment by YCYee912** [comment] 2015-02-05 21:22
hmm.. i tried to re-run again it still prompt out the same issue..then i attempted to ignore it and install the php artisan..it came out this again. Am I missed out something??
![image](https://cloud.githubusercontent.com/assets/10839182/6069541/2cc4d1ac-adc0-11e4-9bd8-725ed6d4c80d.png)

**Comment by snipe** [comment] 2015-02-05 21:28
@YCYee912 Is it possible that your company network/firewall might be blocking the request for the DNS that composer is trying to access? You can't really ignore composer, it's what downloads and sets up all of the dependencies, so that last error is to be expected if you didn't run it.

**Comment by YCYee912** [comment] 2015-02-05 21:32
alright understand that..i re-run again and then i got this for few times..
![image](https://cloud.githubusercontent.com/assets/10839182/6069711/8abbe470-adc1-11e4-86d9-c1b082c35aed.png)

**Comment by snipe** [comment] 2015-02-05 21:37
What happens if you run composer without the dev dependencies? 

`php composer.phar install --no-dev`

**Comment by snipe** [comment] 2015-02-05 21:37
(I assume you're not going to be doing any development on Snipe-IT, just using it as an end-user, in which case you don't need the developer libraries.)

**Comment by YCYee912** [comment] 2015-02-05 21:40
erm..which file should i put in this?

**Comment by snipe** [comment] 2015-02-05 21:43
You don't put it in a file, you just add the `--no-dev` flag onto the composer command so that it knows not to load the developer libraries.

**Comment by snipe** [comment] 2015-02-05 21:45
(I'm not sure which command you use to try to run the composer install, since you're on windows, but whatever that command is, just add `--no-dev` to the end)

**Comment by YCYee912** [comment] 2015-02-05 21:47
is it like this?
![image](https://cloud.githubusercontent.com/assets/10839182/6069945/8c453dda-adc3-11e4-9843-00a3f7a37c48.png)

**Comment by snipe** [comment] 2015-02-05 22:05
Yep, that looks correct. In your `composer.json` file, can you reove the line that says:

`"mtdowling/classpreloader": "4.2.*",`

Then save the file and try re-running composer install?

**Comment by YCYee912** [comment] 2015-02-05 22:08
i couldn't find this in my composer.json...am i having the correct file? The following is my content in the file

{
	"name": "snipe/snipe-it",
	"description": "A free open source IT asset/license management system built in PHP on Laravel 4.1 and Bootstrap 3.",
	"keywords": ["framework", "laravel", "assets", "IT", "management"],
	"homepage": "http://snipeitapp.com/",
	"license": "AGPL-3.0",
	"support": {
		"issues": "https://github.com/snipe/snipe-it/issues",
		"source": "https://github.com/snipe/snipe-it"
	},
	"require": {
		"laravel/framework": "4.1.*",
		"cartalyst/sentry": "2.0.*",
		"barryvdh/laravel-debugbar": "1.x",
		"chumper/datatable": "dev-master",
		"bacon/bacon-qr-code": "dev-master",
		"intervention/image": "dev-master"
	},
	"require-dev": {
		"phpunit/phpunit": "*"
	},
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"pre-update-cmd": [

		],
		"post-update-cmd": [
			"php artisan optimize",
			"php artisan debugbar:publish"
		],
		"post-install-cmd": [
			"php artisan debugbar:publish"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist",
		"bin-dir": "bin"

	},
	"minimum-stability": "dev"
}

**Comment by snipe** [comment] 2015-02-05 22:12
No, no, you're right.

Try ADDING:

`"classpreloader/classpreloader": "1.0.2",`

ABOVE the 

`"laravel/framework": "4.1.",`

bit and save and re-run

**Comment by YCYee912** [comment] 2015-02-05 22:19
added same result. thought you said want to install without "dev"?

**Comment by snipe** [comment] 2015-02-05 22:29
Instead of 1.0.2 for that, use 1.2.0. If that works, I'll explain why it worked :)

**Comment by snipe** [comment] 2015-02-05 22:30
(you can run composer with or without the --no-dev flag this time)

**Comment by YCYee912** [comment] 2015-02-05 22:37
![image](https://cloud.githubusercontent.com/assets/10839182/6070803/9efa1a16-adca-11e4-952a-9202629d30e1.png)
New things came out.

**Comment by snipe** [comment] 2015-02-05 22:43
Can you try pulling the latest from the `develop` branch and installing that? I just pushed out something that should hopefully fix your issue

**Comment by snipe** [comment] 2015-02-05 22:44
It looks like there is a package dependency in the one of the libraries we use that relies on a package that is no longer around. It was taken over by someone else, but there are still references to it, that's why you're seeing that 404 error. I've just tried to force a replace in dependency manager so that it pulls the valid, maintained version

**Comment by YCYee912** [comment] 2015-02-05 22:56
okay..now is this means successful?
![image](https://cloud.githubusercontent.com/assets/10839182/6071101/52fea020-adcd-11e4-8751-c7bb1a6730c8.png)

**Comment by YCYee912** [comment] 2015-02-05 23:04
i assumed this is successful..and then i continue to the php artisan app:install..after following the instruction enter my name, email, p/w..i try to load on browser and it came out this..
![image](https://cloud.githubusercontent.com/assets/10839182/6071211/4e6d7062-adce-11e4-9f1b-4dc20aceab84.png)

**Comment by snipe** [comment] 2015-02-05 23:09
Yes, that means it worked! 

The second error listed in the common issues page: http://docs.snipeitapp.com/installation/common_issues.html

**Comment by YCYee912** [comment] 2015-02-05 23:14
Great, at least something works! 
I followed the instruction find the line 43 but its empty..
![image](https://cloud.githubusercontent.com/assets/10839182/6071335/c363df4a-adcf-11e4-969a-c4e9da5f7323.png)

**Comment by YCYee912** [comment] 2015-02-05 23:20
Happened the same thing after i run that two command
![image](https://cloud.githubusercontent.com/assets/10839182/6071420/a988cf6c-add0-11e4-9447-23790cfef03d.png)

**Comment by snipe** [comment] 2015-02-05 23:24
You were looking in the wrong config file for the app key, but you don't need to manually change it if you run the key generator artisan command. 

The PDO exception looks like the database you specified in your `database.php` file is refusing connections. Did you set up this database specifically for Snipe-IT, or did it already exist and you just created a new Snipe-IT database within it?

**Comment by YCYee912** [comment] 2015-02-05 23:26
i don't think I have already set up any database because i know nothing much about that :)
perhaps you can guide me on this.

**Comment by snipe** [comment] 2015-02-05 23:27
That's a bit out of scope for support for Snipe-IT, I'm afraid (plus I haven't run windows in 10 years), but google has the answers you seek: http://www.wikihow.com/Install-the-MySQL-Database-Server-on-Your-Windows-PC

**Comment by snipe** [comment] 2015-02-05 23:56
I haven't used XAMPP in a billion years, but if you click around in the configs, you should be able to find something that lets you set up a database, username, etc.

**Comment by snipe** [comment] 2015-02-05 23:59
I'm not sure what happens when you click on "Admin" next to MySQL in that screenshot - I assume it opens PhpMyAdmin or something. If so, you should be able to set up a DB and users using the info here: http://www.infosolutionsgoa.com/tutor/phpmyadmin-database-management.html

**Comment by snipe** [comment] 2015-02-06 00:02
(It should be noted that we're now offering hosted versions of Snipe-IT specifically to help with folks who don't have a lot of mysql/web app knowledge) http://snipeitapp.com/hosted.php

**Comment by YCYee912** [comment] 2015-02-06 00:17
alright let's say i have created a database for snipe, then how can i set it point to this database?

**Comment by snipe** [comment] 2015-02-06 00:19
You should be able to follow the instructions here: http://docs.snipeitapp.com/windows/README.html - starting with the "Configuring Snipe-IT" section. It shows you where to put your database info.

**Comment by YCYee912** [comment] 2015-02-06 00:22
erm..i saw your new codes..where should i paste it?

**Comment by snipe** [comment] 2015-02-06 00:23
New codes?

**Comment by YCYee912** [comment] 2015-02-06 00:24
http://snipeitapp.com/hosted.php this one

**Comment by snipe** [comment] 2015-02-06 00:29
I'm sorry, I don't understand the question. Go to the Windows installation docs, go to Configuring Snipe-IT and start with the number one, which tells you to copy the example database config and put your database credentials in there.

**Comment by YCYee912** [comment] 2015-02-06 00:40
okay, this is what in my start.php:

<?php

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| The first thing we will do is create a new Laravel application instance
| which serves as the "glue" for all the components of Laravel, and is
| the IoC container for the system binding all of the various parts.
|
*/

$app = new Illuminate\Foundation\Application;

/*
|--------------------------------------------------------------------------
| Detect The Application Environment
|--------------------------------------------------------------------------
|
| Laravel takes a dead simple approach to your application environments
| so you can just specify a machine name or HTTP host that matches a
| given environment, then we will automatically detect it for you.
|
*/

$env = $app->detectEnvironment(array(

    'local'		 	=> array('localhost','ycyee'),
    'staging' 		=> array('staging.localhost'),
    'production' 	=> array('localhost')
));

/*
|--------------------------------------------------------------------------
| Bind Paths
|--------------------------------------------------------------------------
|
| Here we are binding the paths configured in paths.php to the app. You
| should not be changing these here. If you need to change these you
| may do so within the paths.php file and they will be bound here.
|
*/

$app->bindInstallPaths(require __DIR__.'/paths.php');

/*
|--------------------------------------------------------------------------
| Load The Application
|--------------------------------------------------------------------------
|
| Here we will load the Illuminate application. We'll keep this is in a
| separate location so we can isolate the creation of an application
| from the actual running of the application with a given request.
|
*/

$framework = $app['path.base'].'/vendor/laravel/framework/src';

require $framework.'/Illuminate/Foundation/start.php';

/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
|
| This script returns the application instance. The instance is given to
| the calling script so we can separate the building of the instances
| from the actual running of the application and sending responses.
|
*/

return $app;

**Comment by snipe** [comment] 2015-02-06 00:44
That part is less important, since you're probably going to be running this in production mode. You need to copy the `app/config/production/database.example.php` to `app/config/production/database.php` and fill in the mysql section of the `app/config/production/database.php` config

**Comment by YCYee912** [comment] 2015-02-06 00:50
can i rename the "database.example.php" into "database.php" since it is in the same folder?
this is my content 

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | PDO Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => 'mysql',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => array(

        'sqlite' => array(
            'driver'   => 'sqlite',
            'database' => __DIR__.'/../database/production.sqlite',
            'prefix'   => '',
        ),

        'mysql' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'snipe',
            'username'  => 'ycyee',
            'password'  => '1234',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),

        'pgsql' => array(
            'driver'   => 'pgsql',
            'host'     => 'localhost',
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ),

        'sqlsrv' => array(
            'driver'   => 'sqlsrv',
            'host'     => 'localhost',
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'prefix'   => '',
        ),

    ),

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk have not actually be run in the databases.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => array(

        'cluster' => true,

        'default' => array(
            'host'     => '127.0.0.1',
            'port'     => 6379,
            'database' => 0,
        ),

    ),

);

**Comment by snipe** [comment] 2015-02-06 00:52
It's better to copy it and then just make your edits to `database.php`, so that you can revert back to the example if you mess something up, but it doesn't really matter.

**Comment by YCYee912** [comment] 2015-02-06 04:24
alright understand i that, regarding the "mcrypt_encrypt(): Size of key is too large for this algorithm" i have did accordingly to solution for common issues..still having the same problem..is that because of the database issue?

**Comment by snipe** [comment] 2015-02-06 09:36
No, it shouldn't be related. Keep the key at 32 characters in ` `'key' => 'whateveryouwanttoputhere'` in `app/production/app.php`. It should be a random string of numbers and letters, but no more than 32.

**Comment by YCYee912** [comment] 2015-02-06 14:50
so far so good..here's where i reached :)
![image](https://cloud.githubusercontent.com/assets/10839182/6081166/74204954-ae52-11e4-8563-3004049552bb.png)

**Comment by snipe** [comment] 2015-02-06 14:56
When run `php artisan install`, what's the output in your console?

**Comment by YCYee912** [comment] 2015-02-06 15:03
here it is
![image](https://cloud.githubusercontent.com/assets/10839182/6081369/dd5ff954-ae53-11e4-8eee-2f11ba0905b2.png)

**Comment by snipe** [comment] 2015-02-06 15:10
The tables don't exist because the install failed, and the error message in the install tells you what the problem is. Access denied for your database user, so it looks like you donked up something when setting up your database users in XAMPP.

**Comment by YCYee912** [comment] 2015-02-06 15:27
thanks again..now i manage to open the login page and then after login i see this
![image](https://cloud.githubusercontent.com/assets/10839182/6081880/ac8d5b06-ae57-11e4-81f5-d3ed97ab8d2a.png)

**Comment by snipe** [comment] 2015-02-06 23:32
That's definitely progress, but your browser shouldn't be pointing at `/public`, you should ste public as the webroot in your server settings. 

Also can you please grab the latest off of develop - I may have fixed the withTrashed issue

**Comment by YCYee912** [comment] 2015-02-06 23:46
installing your latest develop. Btw, i don't understand what "ste public as the webroot" means..could you be further explain on this?

**Comment by snipe** [comment] 2015-02-06 23:48
I'm not trying to be a dick here, but these are questions related to setting up web servers in general, which are really outside the scope of support here. A little googling will get you a long way. http://stackoverflow.com/questions/18902887/how-to-configuring-a-xampp-web-server-for-diffrent-root-directory

Unfortunately, I don't have time to help everyone figure out how to install and set up a web server. :(

**Comment by YCYee912** [comment] 2015-02-07 00:09
I am also sorry for asking such a stupid question, now im using your latest develop version. Everything works fine just only under the asset part i still facing the trash error(Deployed, Ready to Deploy, Pending and Un-Deployable.

Also, when i try to create a new user for the location part, am i able to modify the list?

**Comment by YCYee912** [comment] 2015-02-07 00:16
Hey, i found how to modify the location..

**Comment by snipe** [comment] 2015-02-07 19:18
Grab the latest release (1.2.3-beta) and make sure to run the commands listed in the release notes.

**Comment by YCYee912** [comment] 2015-02-08 03:47
Thanks for your sharing so much!! 

Now i can fully utilize the php tool. =D

**Comment by snipe** [comment] 2015-02-08 05:29
Glad you got it sorted!

**Closed by snipe** 2015-02-08 05:29 UTC
Labels: waiting on OP
