### ISSUE TITLE
Access to settings->edit settings became 500 error (docker image)

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#1722] opened 2016-02-05 02:42 UTC
before upgrade to 2.1.0-8, everything was OK. (previously v2.1.0-pre)
(have roll-back to 2.1.0-pre image, but no luck)

to enable debug message, what should I do?
(I know it can be change in app.php but I don't know how change it for docker image.)

thanks.

![image](https://cloud.githubusercontent.com/assets/12657496/12836467/26e095b6-cbf4-11e5-9e2c-f10e2eff2ae7.png)
![image](https://cloud.githubusercontent.com/assets/12657496/12836469/2be5ca54-cbf4-11e5-91d2-d51f836139c2.png)

**Comment by uberbrady** [comment] 2016-02-05 03:08
`docker exec -t -i your_docker_container bash` will get you a command prompt within your docker image. From there you can edit `app.php` - I think everything lives in `/var/www/html` if I remember correctly?

Definitely check out the last part of your log - `app/storage/logs` - you may see a stack trace that shows what's breaking.

**Comment by kt1024** [comment] 2016-02-05 03:39
logs as below.

<code>
<pre>
root@2a059e9d329e:/var/www/html/app/storage/logs# cat log-apache2handler-2016-02-05.txt
[2016-02-05 10:28:23] production.DEBUG: Authenticating user against database. [] []
[2016-02-05 10:28:23] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload('eyJpdiI6InlsMGp...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6InlsMGp...')
#2 /var/www/html/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
#3 /var/www/html/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Crypt::decrypt('eyJpdiI6InlsMGp...')
#4 [internal function]: Controllers\Admin\SettingsController->getEdit()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getEdit', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'getEdit')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
[2016-02-05 10:28:53] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2016-02-05 10:32:57] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload('eyJpdiI6InlsMGp...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6InlsMGp...')
#2 /var/www/html/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
#3 /var/www/html/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Crypt::decrypt('eyJpdiI6InlsMGp...')
#4 [internal function]: Controllers\Admin\SettingsController->getEdit()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getEdit', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'getEdit')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
root@2a059e9d329e:/var/www/html/app/storage/logs#
</pre>
</code>

**Comment by kt1024** [comment] 2016-02-05 06:22
this is after change 'debug' to true in app.php, seems had no difference.
<code>
<pre>
root@30dc5bfc53fe:/var/www/html/app/storage/logs# cat log-apache2handler-2016-02-05.txt
[2016-02-05 11:54:55] production.DEBUG: Authenticating user against database. [] []
[2016-02-05 14:17:17] production.DEBUG: Authenticating user against database. [] []
[2016-02-05 14:17:19] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload('eyJpdiI6InlsMGp...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6InlsMGp...')
#2 /var/www/html/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
#3 /var/www/html/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Crypt::decrypt('eyJpdiI6InlsMGp...')
#4 [internal function]: Controllers\Admin\SettingsController->getEdit()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getEdit', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'getEdit')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
root@30dc5bfc53fe:/var/www/html/app/storage/logs#
</pre>
</code>

**Comment by kt1024** [comment] 2016-02-05 08:19
update,:
add asset model will cause 500 error also, it was OK before and have 17 custom models:

<code>
<pre>
root@84b08054a428:/var/www/html/app/storage/logs# cat log-apache2handler-2016-02-05.txt
[2016-02-05 16:15:23] production.DEBUG: Authenticating user against database. [] []
[2016-02-05 16:15:40] production.DEBUG: Authenticating user against database. [] []
[2016-02-05 16:16:23] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list'' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDO->prepare('insert into `mo...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `mo...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `mo...', Array, Object(Closure))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `mo...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `mo...', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `mo...', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `mo...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/app/controllers/admin/ModelsController.php(139): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: Controllers\Admin\ModelsController->postCreate()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postCreate')
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#31 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`depreciation_id`, `eol`, `name`, `modelno`, `manufacturer_id`, `category_id`, `note`, `user_id`, `fieldset_id`, `updated_at`, `created_at`) values (0, 0, Cisco C2811C/K9, C2811C/K9, 6, 9, chinese version, 1, 13, 2016-02-05 16:16:23, 2016-02-05 16:16:23))' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `mo...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `mo...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `mo...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `mo...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `mo...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/app/controllers/admin/ModelsController.php(139): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: Controllers\Admin\ModelsController->postCreate()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postCreate')
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#30 {main} [] []
root@84b08054a428:/var/www/html/app/storage/logs#
</pre>
</code>

**Comment by snipe** [comment] 2016-02-11 20:20
I believe this is a duplicate of https://github.com/snipe/snipe-it/issues/1595

**Closed by snipe** 2016-02-11 20:20 UTC

**Comment by kt1024** [comment] 2016-02-16 08:16
@snipe @uberbrady so is there anything I can do right now? I've checked #1595 but doesn't get me out of this.

and I have not change the app key.  so I think is not 100% duplicated issue?

thanks.

**Comment by kt1024** [comment] 2016-02-16 09:07
updated to v2.1.0-24-ge5b2163 still no luck.
