### ISSUE TITLE
Export Downloads Two Identical Files with only 101 Results

### ISSUE THREAD

**Issue by rburkholder2305** [snipe/snipe-it#2658] opened 2016-09-21 20:05 UTC
#### Expected Behavior (or desired behavior if a feature request)

Export to CSV exports grid display to a single CSV.

-----

#### Actual Behavior

Exporting to CSV downloads two identical CSVs with top 101 results.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on: Ubuntu Linux 16.04.1; Apache version 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- If you're getting an error in your browser, include that error: no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Assets > List All > Export > CSV
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). Yes, Same issue.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database. No

**Comment by snipe** [comment] 2016-09-28 02:46
Duplicate of #1844

**Closed by snipe** 2016-09-28 02:46 UTC
Labels: bug
