### ISSUE TITLE
Custom Fields for Asset Models

### ISSUE THREAD

**Issue by conroy-d** [snipe/snipe-it#6213] opened 2018-09-18 16:35 UTC
Using hosted Snipe-IT.

I would like to be able to add a custom field to a model, and have that value apply to all assets with that model.

Specifically, an "End of Support" date rather than the EOL month-based field.  I understand that the EOL field has a particular reason it is month-based.

Juniper, Cisco, Palo Alto, Microsoft, all publish an "End of Support" date after which no updates, support contracts, etc. are available.  This is not an end of warranty date, or a calculation based on how long an asset is in service.

We would like to be able to report on which devices are End of Support during an upcoming time period and must be replaced.

We have custom fields we use for individual assets to track warranty or support contract expiration, but EOS is common for all assets of a given model.

**Comment by snipe** [comment] 2018-09-26 22:39
Duplicate of #4261

**Closed by snipe** 2018-09-26 22:39 UTC
