### ISSUE TITLE
Unable to Search by Username or Name in All Assets

### ISSUE THREAD

**Issue by TheVakman** [snipe/snipe-it#4198] opened 2017-10-11 11:02 UTC
#### Expected Behavior (or desired behavior if a feature request)
When viewing "All Assets", I used to be able to search by username or by the first/last name of the user. The expected behaviour is for the assets that are assigned or related to that user appear.

This is not functional for me since upgrading from 4.0.3 to 4.0.9.

-----

#### Actual Behavior
There are no matches. I can search any other field (asset tag, model, notes etc.) but the username nor first/last name is no longer working.

For me, this was previously working in 4.0.3 but is not working for me since 4.0.9. 
See below for more information. The SQL query that is shown to me by debug mode is also below.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade from 4.0.3 to 4.0.9
- Version of Snipe-IT you're running
4.0.9
- Version of PHP you're running
7.0.23
- Version of MySQL/MariaDB you're running
5.5.56-MariaDB
- What OS and web server you're running Snipe-IT on
CentOS 7.4.1708
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No errors.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
All Assets, when I am interacting with the search dialog box within the page.
- If a stacktrace is provided in the error, include that too.
Sadly, it is not. The Laravel.log nor my webserver logs have anything for this.
- Any errors that appear in your browser's error console.
No errors.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Yes, it is. 
*Look in People, find a username with assets assigned.
*Click Assets > All Assets.
*In the searchbox within this section, search for that username. The asset does not appear.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
This is the SQL query that occurs when I search for a username:
```select `assets`.* from `assets` left join `users` on `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = 'App\Models\User' left join `locations` on `locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = 'App\Models\Location' left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = 'App\Models\Asset' where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE '%SANITIZEDUSERNAME%' or `models`.`name` LIKE '%SANITIZEDUSERNAME%' or `models`.`model_number` LIKE '%SANITIZEDUSERNAME%') and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE '%SANITIZEDUSERNAME%') and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE '%SANITIZEDUSERNAME%' and `status_labels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE '%SANITIZEDUSERNAME%' and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%SANITIZEDUSERNAME%')) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE '%SANITIZEDUSERNAME%' and `locations`.`deleted_at` is null)) or (exists (select * from `assets` as `laravel_reserved_0` where `laravel_reserved_0`.`id` = `laravel_reserved_0`.`assigned_to` and (`users`.`first_name` LIKE '%SANITIZEDUSERNAME%' or `users`.`last_name` LIKE '%SANITIZEDUSERNAME%' or `users`.`username` LIKE '%SANITIZEDUSERNAME%' or `locations`.`name` LIKE '%SANITIZEDUSERNAME%' or `assigned_assets`.`name` LIKE '%SANITIZEDUSERNAME%') and `laravel_reserved_0`.`deleted_at` is null)) or `assets`.`name` LIKE '%SANITIZEDUSERNAME%' or `assets`.`asset_tag` LIKE '%SANITIZEDUSERNAME%' or `assets`.`serial` LIKE '%SANITIZEDUSERNAME%' or `assets`.`order_number` LIKE '%SANITIZEDUSERNAME%' or `assets`.`notes` LIKE '%SANITIZEDUSERNAME%' or `assets`.`_snipeit_mac_address_1` LIKE '%SANITIZEDUSERNAME%' or `assets`.`_snipeit_cope_3` LIKE '%SANITIZEDUSERNAME%') and `assets`.`deleted_at` is null order by `assets`.`created_at` asc limit 200 offset 0```

**Comment by diekmanu** [comment] 2017-10-11 12:58
Can you search by username in other views?
Is _snipeit_cope_3 a valid custom field?

Strange thing is that it was not working for me before v4.0.6. (#4020)

**Comment by TheVakman** [comment] 2017-10-11 13:11
Yes, in People (as an example, it works) but that's a very different query. 

Yes, that's a custom field on some of our assets.

**Comment by diekmanu** [comment] 2017-10-11 13:23
So it also works in Deployed, Pending, etc.?

**Comment by TheVakman** [comment] 2017-10-11 16:11
Sorry, I should rephrase, it doesn't work on any of the "asset" pages.

**Comment by Nothing4You** [comment] 2017-10-12 11:49
I'm having a similar issue, not sure if its's the same issue though on a modified 4.0.9: https://gist.github.com/Nothing4You/f79772c9d9d8863d20af080b89ca38a2

**Comment by TheVakman** [comment] 2017-10-17 19:22
Hmm, I'll upgrade to 4.10. I'll give that a shot.

**Comment by Nothing4You** [comment] 2017-10-17 19:24
Still not working on 4.0.10 for me.

**Comment by snipe** [comment] 2017-10-18 03:13
Duplicate of #4191

**Closed by snipe** 2017-10-18 03:13 UTC
Labels: bug

**Comment by TheVakman** [comment] 2017-10-20 02:02
Confirmed, this is fixed.
