### ISSUE TITLE
[Possible bug] Activity report stop working after purge

### ISSUE THREAD

**Issue by Diniver** [snipe/snipe-it#4411] opened 2017-11-09 10:57 UTC
Hi all,

I am not sure is it a bug and how exactly can explain it but I will do my best. Unfortunately, I cannot reproduce it in demo website due to deactivation of purge function.
So, this are my activity reports before purge and purge delete record
![01](https://user-images.githubusercontent.com/31882138/32601515-ce03c7f0-c53a-11e7-9a26-51332e694c2f.PNG)
![02](https://user-images.githubusercontent.com/31882138/32601519-d157cd70-c53a-11e7-8422-5705e8482cc1.PNG)
![03](https://user-images.githubusercontent.com/31882138/32601541-ec1263dc-c53a-11e7-9309-52aa728ff1e6.PNG)

After purge I can see my activity report on dashboard
![07](https://user-images.githubusercontent.com/31882138/32601623-2d3e9c0e-c53b-11e7-83d2-ff019822d755.PNG)

If I click on _view all_ I am not getting any results
![06](https://user-images.githubusercontent.com/31882138/32601659-53357f18-c53b-11e7-9b58-bb6d706f1bb3.PNG)

After refreshing 
![04](https://user-images.githubusercontent.com/31882138/32601689-6c55230e-c53b-11e7-867c-fa0c7699bbe7.PNG)

![05](https://user-images.githubusercontent.com/31882138/32601692-71173a08-c53b-11e7-940f-61f2b8fc509f.PNG)

Unfortunately, laravel.log stays empty. The only log message which I get is from chrome, showed above. 

Snipe-IT version | v4.1.3 build 48 (g74aa562)
PHP Version | 7.0.22-0ubuntu0.16.04.1
Laravel Version | 5.4.29

Last month I spoke with Snipe about that in chat but she said might be many things. Back then I was not aware what is causing this issue. Now I think is related with _purge_ system. Can someone try to reproduce?

**Comment by snipe** [comment] 2017-11-13 00:00
> Unfortunately, laravel.log stays empty. 

Are the permissions correct for your `storage/logs`?  Is there anything else in your `storage/logs` directory?

**Comment by snipe** [comment] 2017-11-13 00:01
(Also can you tell me what types of things you deleted and then purged so we can try to reproduce locally?)

**Comment by Diniver** [comment] 2017-11-13 09:30
all storage folders are with  775 permissions and the owner is apache user. The log itself is working but there isn't any logs regarding this problem (I deleted the content in the log file before purge).

Basicaly, I have purge a bit of everything assets, licences, users.... I have uploaded my purge deleted records in previous post.
[https://user-images.githubusercontent.com/31882138/32601541-ec1263dc-c53a-11e7-9309-52aa728ff1e6.PNG](url)

#Update#
If I continue making activities, after certain on point(depends of how many records are per page) it starts working again, but I still have those non working pages. Really weird.

**Comment by snipe** [comment] 2017-11-22 05:16
@Diniver can you click through on that all.js part in the Chrome debugger and show me what part of the JS it highlights?

**Comment by Diniver** [comment] 2017-11-22 10:01
This is what chrome is showing me:
[new 1.txt](https://github.com/snipe/snipe-it/files/1495416/new.1.txt)
It is really ugly code so I am not sure is it of any use.
I think I have managed to isolate the bug. It is related with delete and purged users. The code is checking where the item has been checked out but when the user is missing, it cannot find data and it goes bonkers.

**Comment by snipe** [comment] 2017-11-22 10:21
Yeah, that code would be minified, so it's very hard to read. 

I'll try to reproduce this by using bad user IDs and see if I can make it happen locally. If so, I'll have a fix out shortly.

**Comment by snipe** [comment] 2017-11-22 11:11
AHA. I think this is progress. I'll get it fixed on my end and then push something out to develop for you to test.

<img width="255" alt="screen shot 2017-11-22 at 2 33 10 am" src="https://user-images.githubusercontent.com/197404/33122948-8ffce084-cf2d-11e7-9430-8daa51c22e29.png">

**Comment by Diniver** [comment] 2017-11-22 11:12
I will be on holiday until Monday so I will report you then.

**Comment by snipe** [comment] 2017-11-22 14:18
I've only able to reproduce this if I manually (deliberately) mangle the data in the database. When I try a purge, it seems to be correctly deleting the associated join records, so not sure how to resolve that exactly. :-/

I have a fix for the breaking front-end stuff but it will still only show you blank lines where things have been deleted, versus actually removing the log entries from the database (which is what should be happening on purge.)

**Closed** 2017-11-23 02:34 UTC
Labels: not sure if bug

**Comment by RogerSik** [comment] 2020-01-14 15:34
We have this issue with a new fresh 4.8.0
