### ISSUE TITLE
Add 'Transfer user' feature instead of Checkin>checkout.

### ISSUE THREAD

**Issue by chaaza** [snipe/snipe-it#5346] opened 2018-04-12 03:48 UTC
#### Expected Behavior (or desired behavior if a feature request)

I only click transfer button to change the user of the deployed asset.

-----

#### Actual Behavior

I need to checkin the asset first then checkout again. 

-----

**Comment by snipe** [comment] 2018-04-12 03:51
Duplicate of #4719

**Closed by snipe** 2018-04-12 03:51 UTC
