### ISSUE TITLE
Asset not visible in asset usage report if asset name not set

### ISSUE THREAD

**Issue by pako-pl** [snipe/snipe-it#2345] opened 2016-07-28 13:00 UTC
The usage report for a component:

/admin/components/3/view

has the "Asset" column empty for assets that do not have "Asset name" set. It is an optional field and we only set "Asset tag" for our assets ("Asset tag" is a mandatory field). Perhaps this report should show "Asset tags" instead? Or use asset tag if an asset has an empty name?

**Comment by snipe** [comment] 2016-07-28 13:01
Duplicate of #2317

**Closed by snipe** 2016-07-28 13:01 UTC
