### ISSUE TITLE
Acceptance Signature Open Twice

### ISSUE THREAD

**Issue by samotelf** [snipe/snipe-it#5627] opened 2018-05-29 22:27 UTC
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When clicking to see the accepted asset signature the lightbox with the signature open twice, so when dismissing the preview, you have to click the backstage twice, and see the lightbox fade out twice.

**To Reproduce**

1. Go to '/hardware/1#history...'
2. Click on 'signature'
3. Signature Open but I have to click twice to dismiss 

**Expected behavior**
Lightbox should only open once, and be dismissed with a single click

**Screenshots**
None

**Server (please complete the following information):**
 - Snipe-IT Version - Version v4.4.1 - build 3636 (master)
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows / MacOS
 - Browser [e.g. chrome, safari] Firefox / Safari
 - Version [e.g. 22] ff60 / Safari 11.1

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **No Error**
- If a stacktrace is provided in the error, include that too.- **No**
- Any errors that appear in your browser's error console. - **No**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **Can't replicate error because demo does not send acceptance email** 
- Include any additional information you can find in `storage/logs` and your webserver's logs. - **N/A**

**Additional context**
- Is this a fresh install or an upgrade? - **Fresh install and upgrade with php upgrade.php**
- What OS and web server you're running Snipe-IT - **CentOS and Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Git clone to install and php upgrade.php to upgrade**
- Include what you've done so far in the installation, and if you got any error messages along the way.- **N/A**
- Indicate whether or not you've manually edited any data directly in the database - **No**

Issue similar to [https://github.com/snipe/snipe-it/issues/5616](url)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2018-05-29 22:34
Duplicate of #5616

**Closed by snipe** 2018-05-29 22:34 UTC
