### ISSUE TITLE
Asset CSV Import without Asset Tag

### ISSUE THREAD

**Issue by malte-exporo** [snipe/snipe-it#3559] opened 2017-05-10 09:33 UTC
#### Expected Behavior 
Hi there! Can anyone explain me, how i can do an Bulk Import (for Assets) without setting an Asset Tag. I would like to generate the Asset Tags while/after importing the assets. Otherwise the Import function would only work for the exchange between 2 Snipe-IT Systems... Is there anything i missed? How can i do this?

-----

#### Actual Behavior

CSV import is only possible with an existing Asset Tag.

**Comment by snug** [comment] 2017-05-15 02:09
I'm not sure if I completely understand your question, and I'm a SnipeIT beginner myself, but couldn't you generate the asset tag in excel?

The asset number is likely the primary key of the database, so you'll need one to import it.

As for only being able to migrate from two SnipeIT systems, I migrated from an Access system to SnipeIT and just copy pasted the stuff into the sample .csv that I downloaded from here:

https://snipe-it.readme.io/v3.6.2/docs/importing

**Comment by Jason-Weber-UC** [comment] 2017-05-15 02:55
I *think* what he is asking is, seeing as the system automatically generates the 'next available' asset tag when manually creating a new item; Can the system automatically do this when importing from a bulk CSV?
(It would be kinda handy)

**Comment by snipe** [comment] 2017-05-16 02:38
It does not currently do this - generating them in Excel is the easiest workaround.

**Comment by ebonweaver** [comment] 2017-06-07 18:29
+1 on this, I thought it was a bug that it was saying something was required that I told it to auto generate.

**Comment by snipe** [comment] 2017-08-25 10:39
Just realized this is a duplicate of #3559

**Closed by snipe** 2017-08-25 10:39 UTC
Labels: feature request

**Comment by JonathonReinhart** [comment] 2019-01-31 16:21
@snipe You closed this issue as a duplicate of itself.

AFICT there are three issues:
- #2521
- #3559 (this one)
- #3752

Can we consider re-opening one of these as a feature request?

I see that assigning the asset tags in Excel is the recommended workaround. Here are reasons I don't believe this is an acceptable long-term solution:
- It requires an external tool to manage something that Snipe-IT should be responsible for
- The asset tags don't have to match the configured prefix (#2521)
- In the case of importing into a database with existing data:
  - It's unclear whether or not duplicate asset tags are detected
  - It's unclear whether or not Snipe-IT will increment its internal counter past the set of imported items

**Comment by tomholovis** [comment] 2019-06-03 12:17
To add to the point made by @JonathonReinhart - I just came across this situation: 

- multiple users are adding equipment (a large order has arrived)
- I need to import a CSV of some other equipment. I can't generate the asset tag in Excel because by the time I import the CSV the first ones will probably be duplicated.

My work around is to wait until this evening and then import the CSV.
