### ISSUE TITLE
用户权限的问题，User permissions

### ISSUE THREAD

**Issue by cx6067682** [snipe/snipe-it#6200] opened 2018-09-14 04:11 UTC
默认用户只能查看分配给自己的资产，如果给于了资产查看编辑权限，则拥有了全部资产查看编辑权限，是否可以设置用户只能编辑查看属于自己的资产！
he default user can only view the assets assigned to him. If he has the right to view and edit the assets, he has the right to view and edit all the assets. Whether he can only edit and view his own assets?

**Comment by snipe** [comment] 2018-09-14 08:37
I don't understand what you mean. Can you provide screenshots for clarity please?

**Comment by huangshifang** [comment] 2018-09-14 08:58
![default](https://user-images.githubusercontent.com/41154731/45540544-51d27e80-b83f-11e8-87d0-3244f7f08d1b.png)
@cx6067682

**Comment by snipe** [comment] 2018-09-14 09:04
I don't know what I'm looking at. Please switch the language to English temporarily, so I can try to understand your issue.

**Comment by snipe** [comment] 2018-09-14 09:05
> The default user can only view the assets assigned to him.

Unless you assign them higher permissions, users will only be able to see their own assets. That's expected behavior. https://snipe-it.readme.io/docs/permissions

**Comment by cx6067682** [comment] 2018-09-14 09:13
The rights of ordinary users can only view assets under his name.




When I gave him an asset editor, I checked my authority.


He checked all the assets of the company.


But I just want this average user to view and edit only his own assets, not the entire company.




At 2018-09-14 15:37:19, "snipe" <notifications@github.com> wrote:


I don't understand what you mean. Can you provide screenshots for clarity please?

**Comment by cx6067682** [comment] 2018-09-14 09:16
Can the default user edit the assets allocated to him?





At 2018-09-14 16:05:19, "snipe" <notifications@github.com> wrote:


The default user can only view the assets assigned to him.

Unless you assign them higher permissions, users will only be able to see their own assets. That's expected behavior. https://snipe-it.readme.io/docs/permissions

**Comment by snipe** [comment] 2018-09-14 11:19
> Can the default user edit the assets allocated to him?

No, only folks allowed to edit assets can edit assets.

**Comment by cx6067682** [comment] 2018-09-17 03:08
> > 默认用户可以编辑分配给他的资产吗？
> 
> 不，只有允许编辑资产的人才能编辑资产。

给了他编辑资产权限，但是他可以编辑公司全部的资产了，我只想让他编辑属于自己资产的权限

**Comment by snipe** [comment] 2018-09-17 21:28
Again, I don't speak Chinese, so I don't know what I'm looking at in these screenshots

**Comment by snipe** [comment] 2018-09-26 22:42
Duplicate of #6049 (as far as I know)

**Closed by snipe** 2018-09-26 22:42 UTC

**Comment by cx6067682** [comment] 2018-09-28 03:29
在 2018-09-28 08:26:59，"xiyang203" <notifications@github.com> 写道：


@snipe In fact, in #6049 , we only solved the problem that importing Chinese characters could not correspond to the fields. Then I merged the problem of admin rights into this issue, so I think this issue is still unresolved and should not be closed.
事实上，在6049中，我们只解决了导入汉字无法对应字段的问题。 然后我将管理员权限问题合并到这个问题中，所以我认为这个问题仍然没有得到解决，不应该被关闭。

**Comment by cx6067682** [comment] 2018-10-15 07:05
我觉得资产系统在权限方面有很大的不足，要么权限过大，要么权限过小！例如A公司的人拥有了资产增加权限，则拥有了增加资产到B公司的权限！






在 2018-09-28 08:26:59，"xiyang203" <notifications@github.com> 写道：


@snipe In fact, in #6049 , we only solved the problem that importing Chinese characters could not correspond to the fields. Then I merged the problem of admin rights into this issue, so I think this issue is still unresolved and should not be closed.
事实上，在6049中，我们只解决了导入汉字无法对应字段的问题。 然后我将管理员权限问题合并到这个问题中，所以我认为这个问题仍然没有得到解决，不应该被关闭。
