### ISSUE TITLE
Search function on Status Label search page broken 

### ISSUE THREAD

**Issue by CC-Damo** [snipe/snipe-it#13103] opened 2023-05-30 14:26 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When using the search box on the status labels view in version v6.1.1-pre - build 10727 (master) the status is lost when searching. For example if the Status is 'In Stock - Built' and searching for the location of 'Leeds' Items that are not in that status are displayed as per the attached screenshot

### Reproduction steps

1. Login to Snipe
2. Visit the Assets -> Status label you wish to filter
3. Initially the correct status are returned
4. Use the search box to search for a location E.G Leeds
5. See that items are returned of all status instead of the filtered statuslabel
...

### Expected behavior

The status label should be left intact when using the search box on this view. Reverting back to commit cd6f6ee8ff resolves this issue. 

### Screenshots

![Snipe Search](https://github.com/snipe/snipe-it/assets/797051/486598fe-f068-4df4-8020-81f4ebecd36c)

### Snipe-IT Version

v6.1.1-pre - build 10727 (master)

### Operating System

CentOS 7.9

### Web Server

Apache

### PHP Version

8.0.28

### Operating System

Windows

### Browser

Google Chrome, Firefox, Edge

### Additional context

Upgrade from Version v6.1.1-pre build 10534 (g609b1646e) to v6.1.1-pre build 10727 (gf1b4bba3a)

Used debug tool and the SQL being executed between versions looks the same so assume its something to do with the model. 

Cleared cache, happening on multiple machines and browser versions

**Comment by snipe** [comment] 2023-06-08 17:10
Can you show me a link or screencast on the demo? I can't reproduce this there. Are you sure it's not finding it via the Default Location and Location (which is expected behavior)?

https://github.com/snipe/snipe-it/assets/197404/e3f66d9d-48c8-4551-a2b0-38171c28a54e

**Comment by quinadmin** [comment] 2023-08-11 12:31
I have exactly the same problem.

here is a screenshot of my ready to deploy assets with a sum um 44 assets:
![grafik](https://github.com/snipe/snipe-it/assets/31616630/60f5d7b5-c2c8-41f6-8836-e3f1fafca388)

Now I am searching for WD19S which should show up 5 assets:
![grafik](https://github.com/snipe/snipe-it/assets/31616630/47e303fc-4b68-47f1-bde4-fafeff85099a)

As you see it shows up 178 assets showing deployed assests too.

It seems the search goes over all assets and not the "ready to deploy" assets.

Now the fun fact: 
I cannot reproduce this in your demo at https://demo.snipeitapp.com

We did absolutly nothing than updating to v6.1.1 - build 10847 (master)

Do you have any hints whats on?

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by quinadmin** [comment] 2023-08-17 13:26
My Problem was fixed with v6.1.2
https://github.com/snipe/snipe-it/discussions/13460#discussioncomment-6729680


<blockquote><img src="https://opengraph.githubassets.com/11074ec8f99191039042e8fccedf506416971dedde952a77607f17fc0a2f47de/snipe/snipe-it/discussions/13460" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it/discussions/13460">Asset search goes over all assets · snipe/snipe-it · Discussion #13460</a></strong></div><div>Hi, I am not sure if its a bug or a error I made. When I select "all ready to deploy" Assets, an then do a search, it searches over all assets and not only about "ready to deploy" ones. I cannot re...</div></blockquote>

**Closed as completed** 2023-08-17 15:01 UTC
Labels: :no_entry_sign:  not a bug
