### ISSUE TITLE
Feature Request: Disable unused sections

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4286] opened 2017-10-23 15:29 UTC
#### Expected Behavior (or desired behavior if a feature request)

For smaller offices, it'd be nice to hide/disable unused sections (e.g. Licenses, Consumables, Components).

-----

#### Actual Behavior

All sections are present.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-10-24 01:33
It's something we're considering, but it gets a little tricky on the dashboard side of things, calculating the width of the grid boxes when there is an unknown number of modules. It's not impossible to do just tricky to make it not look like trash if you have some sections disabled.

**Comment by tbradsha** [comment] 2017-10-25 12:33
A simple solution might be to leave the boxes in place, and just de-link and grey them out? This would prevent confused users from clicking on them.

**Comment by snipe** [comment] 2017-10-26 03:14
I think this might be a duplicate of #1069

**Closed by snipe** 2017-10-26 03:14 UTC
Labels: feature request
