### ISSUE TITLE
V4 - Backups Area Broken

### ISSUE THREAD

**Issue by VanillaNinjaD** [snipe/snipe-it#3651] opened 2017-06-09 16:29 UTC
#### Expected Behavior (or desired behavior if a feature request)

Expect to be able to open the "Backups" area

-----

#### Actual Behavior

Whoops, looks like something went wrong.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

OS: Ubuntu Server 16.04 LTS
Apache: 2.4.18 (Ubuntu)
Snipe-IT: v4.0-latest develop
PHP: 7.0.18-0ubuntu0.16.04.1
Laravel: 5.4.20

Install Method: Manually upgraded since 2.1.0-pre

Whoops, looks like something went wrong.
2/2 ErrorException in ea3be525bed82c16ea2df0b4555c238e544c4cec.php line 30: Class 'Helper' not found (View: /var/www/snipeit_test/resources/views/settings/backups.blade.php)

    in ea3be525bed82c16ea2df0b4555c238e544c4cec.php line 30
    at CompilerEngine->handleViewException(object(FatalThrowableError), 1) in PhpEngine.php line 46
    at PhpEngine->evaluatePath('/var/www/snipeit_test/storage/framework/views/ea3be525bed82c16ea2df0b4555c238e544c4cec.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'path' => '/var/www/snipeit_test/storage/app/backups', 'files' => array(array('filename' => '2017-05-28-000002.zip', 'filesize' => '21.42MB', 'modified' => 1497025396), array('filename' => '2017-05-21-000001.zip', 'filesize' => '20.89MB', 'modified' => 1497025395), array('filename' => '2017-05-14-000001.zip', 'filesize' => '13.64MB', 'modified' => 1497025394), array('filename' => '2017-05-07-000001.zip', 'filesize' => '13.62MB', 'modified' => 1497025394), array('filename' => '2017-04-30-000001.zip', 'filesize' => '13.55MB', 'modified' => 1497025393), array('filename' => '2017-04-23-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025393), array('filename' => '2017-04-16-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025392), array('filename' => '2017-04-09-000001.zip', 'filesize' => '13.51MB', 'modified' => 1497025391), array('filename' => '2017-04-02-000002.zip', 'filesize' => '13.48MB', 'modified' => 1497025391), array('filename' => '2017-03-26-000002.zip', 'filesize' => '13.15MB', 'modified' => 1497025390), array('filename' => '2017-03-19-000001.zip', 'filesize' => '13.07MB', 'modified' => 1497025390), array('filename' => '2017-03-12-000001.zip', 'filesize' => '12.91MB', 'modified' => 1497025389), array('filename' => '2017-02-26-000001.zip', 'filesize' => '12.75MB', 'modified' => 1497025389), array('filename' => '2016-12-25-000007.zip', 'filesize' => '7.03MB', 'modified' => 1497025388)), 'snipeSettings' => object(Setting))) in CompilerEngine.php line 59
    at CompilerEngine->get('/var/www/snipeit_test/resources/views/settings/backups.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'path' => '/var/www/snipeit_test/storage/app/backups', 'files' => array(array('filename' => '2017-05-28-000002.zip', 'filesize' => '21.42MB', 'modified' => 1497025396), array('filename' => '2017-05-21-000001.zip', 'filesize' => '20.89MB', 'modified' => 1497025395), array('filename' => '2017-05-14-000001.zip', 'filesize' => '13.64MB', 'modified' => 1497025394), array('filename' => '2017-05-07-000001.zip', 'filesize' => '13.62MB', 'modified' => 1497025394), array('filename' => '2017-04-30-000001.zip', 'filesize' => '13.55MB', 'modified' => 1497025393), array('filename' => '2017-04-23-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025393), array('filename' => '2017-04-16-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025392), array('filename' => '2017-04-09-000001.zip', 'filesize' => '13.51MB', 'modified' => 1497025391), array('filename' => '2017-04-02-000002.zip', 'filesize' => '13.48MB', 'modified' => 1497025391), array('filename' => '2017-03-26-000002.zip', 'filesize' => '13.15MB', 'modified' => 1497025390), array('filename' => '2017-03-19-000001.zip', 'filesize' => '13.07MB', 'modified' => 1497025390), array('filename' => '2017-03-12-000001.zip', 'filesize' => '12.91MB', 'modified' => 1497025389), array('filename' => '2017-02-26-000001.zip', 'filesize' => '12.75MB', 'modified' => 1497025389), array('filename' => '2016-12-25-000007.zip', 'filesize' => '7.03MB', 'modified' => 1497025388)), 'snipeSettings' => object(Setting))) in View.php line 137
    at View->getContents() in View.php line 120
    at View->renderContents() in View.php line 85
    at View->render() in Response.php line 38
    at Response->setContent(object(View)) in Response.php line 225
    at Response->__construct(object(View)) in Router.php line 602
    at Router->prepareResponse(object(Request), object(View)) in Router.php line 559
    at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 30
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckPermissions.php line 28
    at CheckPermissions->handle(object(Request), object(Closure), 'superuser') in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 43
    at Authenticate->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CreateFreshApiToken.php line 49
    at CreateFreshApiToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForTwoFactor.php line 49
    at CheckForTwoFactor->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckLocale.php line 42
    at CheckLocale->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
    at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
    at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
    at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Router.php line 561
    at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
    at Router->dispatchToRoute(object(Request)) in Router.php line 498
    at Router->dispatch(object(Request)) in Kernel.php line 174
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 51
    at Debugbar->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForDebug.php line 25
    at CheckForDebug->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TrustProxies.php line 55
    at TrustProxies->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForSetup.php line 27
    at CheckForSetup->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
    at NosniffGuard->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
    at XssProtectHeader->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
    at FrameGuard->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
    at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
    at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
    at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Kernel.php line 149
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
    at Kernel->handle(object(Request)) in index.php line 58

1/2 FatalThrowableError in ea3be525bed82c16ea2df0b4555c238e544c4cec.php line 30: Class 'Helper' not found

    in ea3be525bed82c16ea2df0b4555c238e544c4cec.php line 30
    at include() in PhpEngine.php line 42
    at PhpEngine->evaluatePath('/var/www/snipeit_test/storage/framework/views/ea3be525bed82c16ea2df0b4555c238e544c4cec.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'path' => '/var/www/snipeit_test/storage/app/backups', 'files' => array(array('filename' => '2017-05-28-000002.zip', 'filesize' => '21.42MB', 'modified' => 1497025396), array('filename' => '2017-05-21-000001.zip', 'filesize' => '20.89MB', 'modified' => 1497025395), array('filename' => '2017-05-14-000001.zip', 'filesize' => '13.64MB', 'modified' => 1497025394), array('filename' => '2017-05-07-000001.zip', 'filesize' => '13.62MB', 'modified' => 1497025394), array('filename' => '2017-04-30-000001.zip', 'filesize' => '13.55MB', 'modified' => 1497025393), array('filename' => '2017-04-23-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025393), array('filename' => '2017-04-16-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025392), array('filename' => '2017-04-09-000001.zip', 'filesize' => '13.51MB', 'modified' => 1497025391), array('filename' => '2017-04-02-000002.zip', 'filesize' => '13.48MB', 'modified' => 1497025391), array('filename' => '2017-03-26-000002.zip', 'filesize' => '13.15MB', 'modified' => 1497025390), array('filename' => '2017-03-19-000001.zip', 'filesize' => '13.07MB', 'modified' => 1497025390), array('filename' => '2017-03-12-000001.zip', 'filesize' => '12.91MB', 'modified' => 1497025389), array('filename' => '2017-02-26-000001.zip', 'filesize' => '12.75MB', 'modified' => 1497025389), array('filename' => '2016-12-25-000007.zip', 'filesize' => '7.03MB', 'modified' => 1497025388)), 'snipeSettings' => object(Setting))) in CompilerEngine.php line 59
    at CompilerEngine->get('/var/www/snipeit_test/resources/views/settings/backups.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'path' => '/var/www/snipeit_test/storage/app/backups', 'files' => array(array('filename' => '2017-05-28-000002.zip', 'filesize' => '21.42MB', 'modified' => 1497025396), array('filename' => '2017-05-21-000001.zip', 'filesize' => '20.89MB', 'modified' => 1497025395), array('filename' => '2017-05-14-000001.zip', 'filesize' => '13.64MB', 'modified' => 1497025394), array('filename' => '2017-05-07-000001.zip', 'filesize' => '13.62MB', 'modified' => 1497025394), array('filename' => '2017-04-30-000001.zip', 'filesize' => '13.55MB', 'modified' => 1497025393), array('filename' => '2017-04-23-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025393), array('filename' => '2017-04-16-000001.zip', 'filesize' => '13.54MB', 'modified' => 1497025392), array('filename' => '2017-04-09-000001.zip', 'filesize' => '13.51MB', 'modified' => 1497025391), array('filename' => '2017-04-02-000002.zip', 'filesize' => '13.48MB', 'modified' => 1497025391), array('filename' => '2017-03-26-000002.zip', 'filesize' => '13.15MB', 'modified' => 1497025390), array('filename' => '2017-03-19-000001.zip', 'filesize' => '13.07MB', 'modified' => 1497025390), array('filename' => '2017-03-12-000001.zip', 'filesize' => '12.91MB', 'modified' => 1497025389), array('filename' => '2017-02-26-000001.zip', 'filesize' => '12.75MB', 'modified' => 1497025389), array('filename' => '2016-12-25-000007.zip', 'filesize' => '7.03MB', 'modified' => 1497025388)), 'snipeSettings' => object(Setting))) in View.php line 137
    at View->getContents() in View.php line 120
    at View->renderContents() in View.php line 85
    at View->render() in Response.php line 38
    at Response->setContent(object(View)) in Response.php line 225
    at Response->__construct(object(View)) in Router.php line 602
    at Router->prepareResponse(object(Request), object(View)) in Router.php line 559
    at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 30
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckPermissions.php line 28
    at CheckPermissions->handle(object(Request), object(Closure), 'superuser') in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 43
    at Authenticate->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CreateFreshApiToken.php line 49
    at CreateFreshApiToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForTwoFactor.php line 49
    at CheckForTwoFactor->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckLocale.php line 42
    at CheckLocale->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
    at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
    at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
    at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Router.php line 561
    at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
    at Router->dispatchToRoute(object(Request)) in Router.php line 498
    at Router->dispatch(object(Request)) in Kernel.php line 174
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 51
    at Debugbar->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForDebug.php line 25
    at CheckForDebug->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TrustProxies.php line 55
    at TrustProxies->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForSetup.php line 27
    at CheckForSetup->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
    at NosniffGuard->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
    at XssProtectHeader->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
    at FrameGuard->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
    at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
    at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
    at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Kernel.php line 149
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
    at Kernel->handle(object(Request)) in index.php line 58

**Comment by snipe** [comment] 2017-06-09 19:22
Hm... I actually can't reproduce that one. Can you tell me what's on/around line 30 of `/var/www/snipeit_test/storage/framework/views/ea3be525bed82c16ea2df0b4555c238e544c4cec.php`?

**Comment by snipe** [comment] 2017-06-09 19:23
(Also try clearing the contents of your views directory and reloading the page)

**Comment by snipe** [comment] 2017-06-09 19:45
Figured it out - should be fixed now, thanks!

**Closed by snipe** 2017-06-09 19:45 UTC
