### ISSUE TITLE
Processing a CSV gets stuck.

### ISSUE THREAD

**Issue by jrosen175** [snipe/snipe-it#5995] opened 2018-07-29 04:17 UTC
#### Please confirm you have done the following before posting your bug report:

- [:heavy_check_mark:] I have enabled debug mode 
- [:heavy_check_mark:] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When processing an imported CSV, the process freezes on "Processing" and does not move forward to import the data.

**To Reproduce**
1. Go to 'Import'
2. Click 'Process' on the CSV to import data from.
3. Click 'Import'
4. Page states that it is processing.
5. Page never advances.

**Expected behavior**
I expect to see a message saying that the import is complete. I also expect the page to have imported the data.

**Screenshots**
![error](https://user-images.githubusercontent.com/41134138/43362847-4f2ab744-92c2-11e8-817f-f829b9a14698.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: [e.g. Ubuntu, CentOS] RedHat
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: 7.1.19

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome and FireFox
 - Version [e.g. 22] Chrome (64.0.3282.140), FireFox (61.0.1)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A
 - OS: [e.g. iOS8.1] N/A
 - Browser [e.g. stock browser, safari] N/A
 - Version [e.g. 22] N/A

**Error Messages**
No error messages on the screen. The image attached has the Chrome console with the error it sees behind the scenes. Checked the Laravel.log file and it only had an error from June that has since been fixed.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. 
- Indicate whether or not you've manually edited any data directly in the database: no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by huangshifang** [comment] 2018-07-29 08:00
it look likes the same question with v4.6.2 ?

**Comment by dmeltzer** [comment] 2018-07-29 13:57
Can you see in the network tab what the response is for the imports/6 post?  Alternatively, what is added to storage/logs/laravel.log when you try to import?

**Comment by jrosen175** [comment] 2018-07-29 15:40
The response on imports/6 is just "Whoops, looks like something went wrong.". Here is the Laravel log file.
[laravel.log](https://github.com/snipe/snipe-it/files/2238908/laravel.log)

**Comment by dmeltzer** [comment] 2018-07-29 19:22
It looks like an issue with email settings.  Do you have email configured properly on your site?

**Comment by jrosen175** [comment] 2018-07-29 19:44
I left the email settings set as the default since I haven't allowed my mail server to accept relay information from my asset server yet. Why would the importer need to use the email settings?

**Comment by dmeltzer** [comment] 2018-07-29 19:45
The importer sends users that are imported with an email address an email with the generated password.

**Comment by jrosen175** [comment] 2018-07-29 19:47
I dont want users to have the ability to login. Is there a way around that setting?

**Comment by snipe** [comment] 2018-08-01 10:51
@jrosen175 leave their email address out of the import. That's the best you can do for now until we update the importer to let you decide whether or not to email the user.

**Comment by jrosen175** [comment] 2018-08-04 03:11
>@jrosen175 leave their email address out of the import. That's the best you can do for now until we update the importer to let you decide whether or not to email the user.

@snipe thanks for the response. I was able to successfully import the users without emails. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by snipe** [comment] 2018-08-04 03:39
There is another issue opened for this, so I'm going to close it as a duplicate even though this one came first, since it's more to the point of the actual thing that needs to be fixed. 

Closing as duplicate of #6042

**Closed by snipe** 2018-08-04 03:39 UTC
