### ISSUE TITLE
[Feature Request / Idea] Pre defined packages and package checkout.

### ISSUE THREAD

**Issue by MelonSmasher** [snipe/snipe-it#6357] opened 2018-10-23 14:30 UTC
Hi there, 

My co-worker and I were thinking of ways to expedite the checkout process when we were deploying many PCs to a lab. The idea of a pre defined hardware package came about. Essentially a group of hardware that would be deployed over and over again. When deploying a package Snipe would give you the asset tags and serial numbers of the hardware and you would deploy these assets, rather than picking the assets and checking them out. Within the package you would be able to set how the assets are checked out through variables.

For example lets say we had a PC package. We would select the PC model, and allow that to be checked out to a user or location. Then add other hardware to the package like a monitor model, keyboard model, and mouse model. We could set those to be automatically checked out to the parent PC at the time of checkout or to the user or location that the PC is being checked out to. Then when it is time to deploy an instance of this package a list of hardware is displayed to the Snipe user with asset tags and serial numbers and each piece of hardware is gathered and deployed, and the user or location variable is filled out at the time of checkout and the rest of the assets are automatically checked out based on the conditions set in the package.

Something of this nature would speed up the checkout process and leave less room for assets to be deployed without being checked out first. Please let me know if this makes no sense and I can try to explain it better.

**Comment by snipe** [comment] 2018-10-29 21:58
Duplicate of #563

**Closed by snipe** 2018-10-29 21:58 UTC
