### ISSUE TITLE
Checking out changes status

### ISSUE THREAD

**Issue by lodemps** [snipe/snipe-it#6686] opened 2019-02-05 18:52 UTC
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.8 - build 3959 (master)
 - OS: [e.g. Ubuntu, CentOS] WIndows 10
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
When checking out an asset to a user, there is no line available to change the Status.

**Describe the solution you'd like**
When an asset is checked out, the status would change to "Deployed", instead of staying in "Ready to Deploy".  Status could change automatically, or there could be a line to make a selection when completing the check out form, instead of having to go in and edit the asset separately.

**Describe alternatives you've considered**
We've looked at bypassing the check-out process altogether, and only editing the status with a custom field, but that doesn't allow us to assign it to a user

**Comment by tymik** [comment] 2019-02-06 10:21
confirmed, I got exactly the same issue today.
I am generally for changing status automatically to "deployed" by default (selecting by default from dropdown list) and allowing to change it on the list.
Of course this should be available also for bulk checkouts.

**Comment by lodemps** [comment] 2019-02-06 15:28
I am hoping that checking out an asset will change the status to "Deployed" only, as opposed to "Ready to Deploy (Deployed)"  Visually, it would be easier and more straightforward if the color was different, and the Status itself was changed, instead of adding a "Deployed" tag next to the Status. Currently, to accomplish this, we would have to create a new "Deployed" status, then manually edit the asset after checking it out to a user.

**Comment by ZephyriusOne** [comment] 2019-02-06 15:34
The color does change to Blue instead of Green when it's in a deployed state. I do agree that Ready to Deploy and Deployed should be separated, but I've learned to live with it.

I use the page "All Ready to Deploy" instead of "List All" when I want to only see assets still not assigned. That helps a bit when trying to just see assets available/in inventory. 

What you're looking for is more of a quality of life change, not so much an issue. Again, I agree it should be separated, but this is how it's intended for now. One day they may change it.

**Comment by snipe** [comment] 2019-02-16 20:06
This argument has been made before. We do it this way so that individual statuses are honored, while the state of the asset (checked in or out) is also conveyed. 
https://snipe-it.readme.io/docs/overview#section-status-labels

**Closed by snipe** 2019-02-16 20:06 UTC

**Comment by tymik** [comment] 2019-02-18 12:16
@snipe how about general usage assets? I have assets that are assigned to location, not user, so, from my perspective they should act the same way and they seem that they don't.
"Status labels" only mentions assignment to users and seems that it does not take locations into account.
