### ISSUE TITLE
password reset page: "Username" field should be labelled "Email"

### ISSUE THREAD

**Issue by cbbowman** [snipe/snipe-it#1161] opened 2015-09-09 17:31 UTC
On the password reset page, the "Username" field should be labelled "Email".
Submitting a username returns an error, while submitting the associated email address is successful.

**Comment by snipe** [comment] 2015-09-09 17:33
Email is not a required field anymore. 

I think this is a duplicate of https://github.com/snipe/snipe-it/issues/1130

**Closed** 2015-09-09 20:37 UTC
