### ISSUE TITLE
Checkin/Checkout email not sent if "Require users to confirm acceptance of assets in this category." not selected

### ISSUE THREAD

**Issue by el-capitano** [snipe/snipe-it#5876] opened 2018-07-18 09:12 UTC
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If you don't select the "Require users to confirm acceptance of assets in this category." inside the category, the "Send email to user on checkin/checkout." won't send emails.

**To Reproduce**
1. Go to 'Settings>Categories.'
2. Click on 'Any category to edit or create new'
3. Scroll down to 'Send email to user on checkin/checkout'

**Expected behavior**
The app should send email to end users even if the Require acceptance checkbox is not selected.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] XAMPP/Apache
 - PHP Version 7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2018-07-18 09:19
Duplicate of #5816

**Closed by snipe** 2018-07-18 09:19 UTC
