### ISSUE TITLE
Feature Request - Parent & Child Assets - Transact as Whole

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#3564] opened 2017-05-10 16:51 UTC
#### Feature Request

Have the ability to create parent and child assets for simple check in check out of asset kits. 

An iPad is an parent asset. 
An iPad charger is an accessory to the iPad. 
An iPad Case would also be an accessory to the iPad. 

      Standard operating procedure would be to check out the iPad and Charger together. 

Ability to "transact as whole" (kit including all assets in kit) or to not check out individual assets from a kit. 

Possibly add the ability to make the "Accessories" a child of a "Asset" so if you're checking out a laptop, it comes with a charger. 

-----

#### Actual Behavior

Currently only single assets/accessories exist and each item much be checked out individually. Looking to simplify the check in/out process.

-----

Version v3.6.4 build 12 (gf7e4fca)

**Comment by Matt1684** [comment] 2017-06-06 23:03
I am also interested in this type of behavior. Specifically I am interested in having a Parent asset tag that automatically applies the status to the child asset tags.

For Example:
Laptop Carts contain 20 laptops.
Teachers check whole carts out for their students throughout the day. Would like to be able to scan just one (parent) asset tag for the entire laptop cart and have the action be applied to all of the laptops (Child Assets) as well. It would be important to allow the child assets to be individually checked out as well since sometimes only a single laptop is taken rather than the whole cart.

Your software is amazing. Please keep up the good work!

**Comment by snipe** [comment] 2017-06-10 00:09
Closing as duplicate of #563

**Closed by snipe** 2017-06-10 00:09 UTC
Labels: feature request
