### ISSUE TITLE
Feature Request - Custom Fields for Licences

### ISSUE THREAD

**Issue by DerGemeine** [snipe/snipe-it#3670] opened 2017-06-14 12:59 UTC
Hey,

I would appreciate if licences could have custom fields as assets do. As with Sophos, Citrix and ESET, these have multiple modules (and most people are very sloppy when defining which exact modules the licences includes). Thus I would very much appreciate it to be seen in a future version :)

**Comment by JJLosier** [comment] 2017-09-22 14:18
What is the timeline for having this implemented?
Thank you

**Comment by snipe** [comment] 2017-09-22 19:01
It’s not currently on the short term roadmap.

**Comment by snipe** [comment] 2017-10-19 10:00
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:00 UTC
Labels: feature request
