### ISSUE TITLE
Custom fields and "advanced quick search"

### ISSUE THREAD

**Issue by Speed1** [snipe/snipe-it#6842] opened 2019-03-20 13:43 UTC
**Server (please complete the following information):**
 - v4.6.6
 - Container
 - Apache
 - 7.0.32-0ubuntu0.16.04.1

**Is your feature request related to a problem? Please describe.**
When I use the search in the "All Assets" view it searches always in all columns. When i use the advanced search I cannot filter for custom fields.

**Describe the solution you'd like**
I want to specify in the search the column where the search should search.   
For example `Location:Rome` or `Category:"Smoke generator"`   
This should work also for custom fields.

**Describe alternatives you've considered**
Actually I do a search, change the order of the columns and scroll down until I see all the Assets that I need.

**Additional context**

**Comment by eyalgett** [comment] 2019-03-26 11:51
sames as in here: https://github.com/snipe/snipe-it/issues/6427
still not resolved :(

**Comment by pvnick** [comment] 2019-03-28 15:16
Here is a screen recording of the problem: https://www.youtube.com/watch?v=ZKsQr_RU9nk

**Comment by eyalgett** [comment] 2019-05-28 07:51
still relevant, unresolved

**Comment by snipe** [comment] 2019-05-28 19:12
Duplicate of #4275

**Closed by snipe** 2019-05-28 19:12 UTC
