### ISSUE TITLE
Checkout Asset showing incorrect info for Assets currently checked out to this user for some users

### ISSUE THREAD

**Issue by kchagnon-snowbound** [snipe/snipe-it#6095] opened 2018-08-16 14:24 UTC
**Describe the bug**
When checking out an asset, when you select the user on the form it shows the "Assets currently checked out to this user" but the info is incorrect for some users.  Some assets that are checked out to a location randomly show as checked out to random user.

**To Reproduce**
1. From the All Assets click on an asset tag that has status "Ready to Deploy"
2. Click Actions->Checkout Asset
3. Click on user and choose user
4. The "Assets currently checked out to this user" window appears
5.  For random users this list shows random assets that have not been checked out to that user.  It seems to be with assets that have been checked out to a location.

**Expected behavior**
The "Assets currently checked out to this user" should only show the assets checked out to that user.

**Screenshots**
The "Correct assigned to.png" screenshot shows the report of assets checked out to user Jade Jen which was generated by going to People-> user Jade Jen->Print All Assigned.  This is correct.

The "incorrect.png" is a screenshot from the Checkout Asset page.  When I select user Jade Jen, the "Assets currently checked out to this user shows a number of additional assets that are not checked out to Jade Jen.  They are actually checked out to locations.  I have found this issue with at least three users so far.

![correct assigned to](https://user-images.githubusercontent.com/18011929/44214512-5a4f7080-a13e-11e8-90a1-a2487a1575d8.PNG)
![incorrect](https://user-images.githubusercontent.com/18011929/44214517-5cb1ca80-a13e-11e8-83d8-d9a719ec8f43.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3

**Comment by snipe** [comment] 2018-08-16 21:31
Duplicate of #6068

**Closed by snipe** 2018-08-16 21:31 UTC
