### ISSUE TITLE
v6.2.0 Column-reordering doesn't work as expected

### ISSUE THREAD

**Issue by Robert-Azelis** [snipe/snipe-it#13649] opened 2023-09-25 10:57 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi, early seen new feature for column-reordering, but it seems doesn't work as expected, after refresh site columns and data are mixed.

![image](https://github.com/snipe/snipe-it/assets/82208283/9dab2edd-3234-40bc-8f4c-d34ffb97554f)

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Column-reordering should keep changes after refresh site and not mix column name with data.

### Snipe-IT Version

Snipe-IT DEMO

### Operating System

Windows

### Web Server

Snipe-IT DEMO

### PHP Version

8.1.21

**Comment by snipe** [comment] 2023-09-25 11:01
You can try switching your `BS_TABLE_STORAGE` to `localStorage` and see whether or not that helps. We've been unable to reproduce this issue consistently. (It's also the reason we have refused to implement column sorting previously, despite all of the complaints that we didn't offer it.)

**Comment by snipe** [comment] 2023-09-25 11:04
Duplicate of #13640

**Comment by Robert-Azelis** [comment] 2023-09-25 11:04
it was tested on your Snipe-IT DEMO website https://demo.snipeitapp.com

**Closed by snipe** 2023-09-25 11:04 UTC

**Comment by snipe** [comment] 2023-09-25 12:08
I can't reproduce that on the demo. (If I could, I wouldn't have merged it)

**Comment by snipe** [comment] 2023-09-25 12:08
(Some browser info here would be helpful)
