### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'labels_width' 

### ISSUE THREAD

**Issue by nockeer** [snipe/snipe-it#4246] opened 2017-10-18 13:24 UTC
#### Expected Behavior (or desired behavior if a feature request)

During migration step such error shows: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'labels_width' 

-----

#### Actual Behavior

Full text of error: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'labels_width' (SQL: alter table `settings` add `labels_per_page` tinyint not null default '30', add `labels_width` decimal(6, 5) not null default '2,625', add `labels_height` decimal(6, 5) not null default '1', add `labels_pmargin_left` decimal(6, 5) not null default '0,21975', add `labels_pmargin_right` decimal(6, 5) not null default '0,21975', add `labels_pmargin_top` decimal(6, 5) not null default '0,5', add `labels_pmargin_bottom` decimal(6, 5) not null default '0,5', add `labels_display_bgutter` decimal(6, 5) not null default '0,07', add `labels_display_sgutter` decimal(6, 5) not null default '0,05', add `labels_fontsize` tinyint not null default '9', add `labels_pagewidth` decimal(7, 5) not null default '8,5', add `labels_pageheight` decimal(7, 5) not null default '11', add `labels_display_name` tinyint not null default '0', add `labels_display_serial` tinyint not null default '1', add `labels_display_tag` tinyint not null default '1')

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: 4.0.13
- Version of PHP you're running: 5.6.31
- Version of MySQL/MariaDB you're running: 10.1.25-MariaDB
- What OS and web server you're running Snipe-IT on: Windows 8.1 with XAMPP (64 bit everything)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: "LOG.error: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'labels_width'' in C:\xamp\htdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:105"
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: On Snipe-IT Pre-Flight page i clicked Next: Create Database Tables
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Yes, but they are tied with browser version
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by nockeer** [comment] 2017-10-18 13:28
Additional info: In error description default values are with coma. In migration files default values are with dots.

I attached log files with full stack.
[laravel-2017-10-18.log](https://github.com/snipe/snipe-it/files/1394756/laravel-2017-10-18.log)

**Comment by snipe** [comment] 2017-10-18 13:29
Duplicate of #4002

**Closed by snipe** 2017-10-18 13:29 UTC
