### ISSUE TITLE
Apply custom fields to Components

### ISSUE THREAD

**Issue by TheKamakaZi** [snipe/snipe-it#5513] opened 2018-05-10 12:39 UTC
**Server (please complete the following information):**
 - Snipe-IT Version: v4.1.11-pre
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version: 7.1.13

**Is your feature request related to a problem? Please describe.**
Users in my organisation swaps phones while retaining their numbers/SIMs. With this in mind, I would like to append the PIN/PUK custom fields to the SIM (listed as a component), rather than to the phone (asset) itself.

**Describe the solution you'd like**
The ability to add custom fields to components.

**Describe alternatives you've considered**
PINs & PUKs are currently being tracked in a worksheet, which isn't ideal as the number of users grows.

**Additional context**
N/A

**Comment by snipe** [comment] 2018-05-11 03:03
Duplicate of https://github.com/snipe/snipe-it/issues/4261

**Closed by snipe** 2018-05-11 03:03 UTC
