### ISSUE TITLE
500 Error - Creating Asset

### ISSUE THREAD

**Issue by proczero** [snipe/snipe-it#1872] opened 2016-03-22 15:16 UTC
#### Expected Behavior (or desired behavior if a feature request)
To create the asset like it worked in the past.

-----
#### Actual Behavior
I am not sure if this is an actual software or server issue. I have not touched the machine in a while, one of our users reported that this was happening when adding a Asset. I verified on multiple accounts that this was the case. Upgraded a few packages on the server and then updated the SnipeIT software, still nothing.

"Ouch.
Server Error: 500 (Internal Server Error)
What does this mean?
Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.
Perhaps you would like to go to our home page?"

**With Debug on:**
ErrorException (E_RECOVERABLE_ERROR)
HELP
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsTo::associate() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in /var/www/snipe-it-master/app/controllers/admin/AssetsController.php on line 104 and defined

public function associate(Model $model)
{
$this->parent->setAttribute($this->foreignKey, $model->getAttribute($this->otherKey));

-----
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Snipe-IT version	v2.1.0-41-g6d810a9
Ubuntu 14.04.4 LTS (VM)
Installed via install.sh
Error provided above
Error occurs on /hardware/create page
No manual edits were made to DB

app/storage/logs output for log-apache2handler-2016-03-22.txt:

#0 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php(203): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', '/var/www/snipe-...', 203, Array)
#1 /var/www/snipe-it-master/app/controllers/admin/AssetsController.php(104): Illuminate\Database\Eloquent\Relations\BelongsTo->associate(NULL)
#2 [internal function]: Controllers\Admin\AssetsController->postCreate()
#3 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#4 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#5 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#6 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#9 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/snipe-it-master/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipe-it-master/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/snipe-it-master/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []

**Comment by snipe** [comment] 2016-03-22 17:04
It looks like there's something wring with your asset model. The line that's erring is:

```
$asset->model()->associate(Model::find(e(Input::get('model_id'))));
```

It's not finding a model with whatever model_id is being passed during that create process. Does it happen when you pick any asset model from the dropdown at random? Or just specific ones?

**Comment by proczero** [comment] 2016-03-22 17:11
I tried different models before but was not recording the output, here is one from a different model from before. This error seems to appear on all the ones I have tested thus far. 

$input=Input::all();
 
        $rules=$asset->validationRules();
        if($asset->model->fieldset)
        {
          foreach($asset->model->fieldset->fields AS $field) {
            $input[$field->db_column_name()]=$input['fields'][$field->db_column_name()];
            $asset->{$field->db_column_name()}=$input[$field->db_column_name()];
          }

**Comment by snipe** [comment] 2016-03-22 17:12
Can you tell me if you're getting a browser error on that create page, specifically when you select a model from the dropdown list?

**Comment by proczero** [comment] 2016-03-22 17:13
I have found one asset model that does work. But I am unsure of what separates it from the rest as unique beyond name.

**Comment by snipe** [comment] 2016-03-22 21:51
Can you tell me if you're getting a browser error on that create page, specifically when you select a model from the dropdown list?

**Comment by proczero** [comment] 2016-03-23 12:44
Sorry, I just saw this. There is not browser or warning of any kind generated on the create asset page when I select a model. The error occurs as soon as I hit Enter or click the Submit button.

It may be worth noting that all of my model types have assets assigned to them and have working in the past. Nothing was changed to my knowledge, certain models simply stopped working without warning.

**Comment by snipe** [comment] 2016-03-23 19:13
You can see how unlikely it is that it suddenly stopped working with no one changing anything tho, right? 

When you say there are no bowser errors, you're checking the debugging console in your browser, correct? These aren't errors you would see unless you were seeking them out.

**Comment by davidking727** [comment] 2016-03-26 01:12
I sometimes get the same error, when uploading bulk assets and users. After a couple of tries, it works

**Comment by snipe** [comment] 2016-03-26 01:12
@davidking727 without error logs, there is literally nothing I can do with that information.

**Comment by proczero** [comment] 2016-03-29 15:11
Sorry for the delay I have been out of the office terribly sick.

Is there a way to put this ticket on hold? I want to try something with SSLs. Back story (This worked before but maybe something happened). We have a wildcard cert on our domain that I applied to the server, unfortunately to allow certain individuals access to it we had to change it in a way that the cert was broken but still applied. I have a feeling this could be causing some irregular behavior throughout the system so I would like to clear that issue before having anyone else jump through hoops, but would also like to come back to this issue if it remains unresolved after these changes. Would that be alright?

**Comment by jebbhb** [comment] 2016-04-15 00:01
Hi, i've found something similar.
I get the same error, but this only happens to me when the asset Im trying to create has custom fields.
The custom fields do not appear when I select the model, so at the end, when I submit for the creation process, there's the error.

**Comment by snipe** [comment] 2016-04-15 00:04
@jebbhb Yes, you mentioned, but until you answer my questions in that ticket, we cannot help you.

**Comment by MOD-LonnieJones** [comment] 2016-04-27 16:51
@jebbhb 
I have a similar situation to yours.  When viewing the error code I get:
`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - https://192.168.1.24//hardware/models/81/custom_fields?_token=j9I6jZVzQoS04s84ICzzQBXti6mwnaJAErx4ONts
6
create (653,9)`

`HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - https://192.168.1.24//api/statuslabels/6/deployable`

Within Chrome there is more descriptions to what is occurring:

create:653 
jquery-latest.js:9631 GET https://192.168.1.24//hardware/models/74/custom_fields?_token=uTijI4KfphEWnUiBKaOscJ2WNShm7Zaxt4ioBL0R 404 ()send @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176jQuery.(anonymous function) @ jquery-latest.js:9322(anonymous function) @ create:635jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309jQuery.event.trigger @ jquery-latest.js:4550(anonymous function) @ jquery-latest.js:5260jQuery.extend.each @ jquery-latest.js:383jQuery.fn.jQuery.each @ jquery-latest.js:136jQuery.fn.extend.trigger @ jquery-latest.js:5259clazz.triggerChange @ select2.min.js:1067clazz.onSelect @ select2.min.js:2276clazz.selectHighlighted @ select2.min.js:1723(anonymous function) @ select2.min.js:748(anonymous function) @ select2.min.js:651jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309
create:653 6
jquery-latest.js:9631 GET https://192.168.1.24//api/statuslabels/6/deployable 404 ()send @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176user_add @ create:657(anonymous function) @ create:649jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309jQuery.event.trigger @ jquery-latest.js:4550(anonymous function) @ jquery-latest.js:5260jQuery.extend.each @ jquery-latest.js:383jQuery.fn.jQuery.each @ jquery-latest.js:136jQuery.fn.extend.trigger @ jquery-latest.js:5259clazz.triggerChange @ select2.min.js:1067clazz.onSelect @ select2.min.js:2276clazz.selectHighlighted @ select2.min.js:1723(anonymous function) @ select2.min.js:748(anonymous function) @ select2.min.js:651jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309

I think there might be an issue with my install though.  If there hasn't been a suggestion for a Windows installer then I would like to suggest one or possibly make one.

**Comment by markjorissen** [comment] 2016-05-04 10:12
I've got the same problem, when adding an Asset which is using custom fields it displays Error 500.. When removing the custom fields everything works fine. To bad, i'm using custom fields to add some important information, CPU, GPU speed etc.... Is there a fix for this? We would like to use Snip-IT in our company.

**Comment by MOD-LonnieJones** [comment] 2016-05-04 15:51
The roundabout way, I've figured to do it by using the notes section. It works for most things.  It does remove the ability to sort or filter by the custom column but at least the data is there. If you are doing something a bit fancier, you also won't be able to properly parse the data. You would have to export, format, and then parse.

**Comment by markjorissen** [comment] 2016-05-09 09:42
Snipe-IT version	v2.1.0-55-g701c16f
PHP Version	5.5.9-1ubuntu4.16
Laravel Version	4.2.17
Extra info about our server.... 

Yeah, but the workarround is very time consuming... Would love to see this function working! Otherwise I have to look for another system like GLP :(

**Comment by lonlyboy** [comment] 2016-05-27 14:20
I just confirmed the issue too.  If you use Customer Fields it errors out.  I removed custom fields and I can add assets with no problems.   Something to do with how custom fields are interfaced into the assets.

**Comment by jebbhb** [comment] 2016-05-27 15:40
@snipe help me out with this one .....
The error that I got was that I had an IP address set in /app/config/production/app.php ('url' parameter) but it was different from the IP address that I have to access Snipe .... something about networking.

I don't know if it solves your issue, but at least mine does.

**Comment by snipe** [comment] 2016-08-18 20:23
The only reason it should error out if you're using custom fields is if the URL in your APP_URL setting doesn't match your actual URL.

Does https://192.168.1.24//api/statuslabels/6/deployable actually exist? (It looks like you might have a trailing slash on your app URL there, which shouldn't be there.)

**Closed by snipe** 2016-08-18 20:23 UTC
Labels: waiting on OP
