### ISSUE TITLE
issue while uploading my Assets

### ISSUE THREAD

**Issue by manusolano777** [snipe/snipe-it#2351] opened 2016-07-29 08:12 UTC
Hai,
Hope you are in good health.
Mam i have installed new version of snipeit (V3). i have problem while am uploading my assets. I have created the .csv file with heads _(Name,  Email,  Username,   Item Name,  Category,   Model Name, Manufacturer,   Model Number,   Serial Number,  Asset Tag,  Location,   Notes,  Purchase Date,  Purchase Cost,  Company Status, Warranty,   Supplier,)_. Everything except _warranty_ is updating correctly.

If possible can you help me to solve this issue.

**Comment by snipe** [comment] 2016-07-29 09:44
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by manusolano777** [comment] 2016-07-30 05:56
- Version of Snipe-IT you're running?
_Snipe-IT version	v3.0-ebc74a65
PHP Version	5.5.12
Laravel Version	5.2.39_
What OS and web server you're running Snipe-IT on?
_Windows Server 2008_
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_Manual_

**Comment by snipe** [comment] 2016-07-30 05:59
Can you show me what your warrantee column looks like in your CSV?

**Comment by manusolano777** [comment] 2016-07-30 06:03
![error](https://cloud.githubusercontent.com/assets/18734573/17268511/6238e228-5649-11e6-8e91-acf7e5f564e3.png)

**Comment by dmeltzer** [comment] 2016-07-30 11:39
Hi,

The column name should actually be "Warranty months", not "Warranty".  That is a mistake in the documentation (Or the code, depending on how you look at it).

**Comment by manusolano777** [comment] 2016-08-01 16:09
Thanks for info but still my purchase cost is not coming correct..

**Comment by snipe** [comment] 2016-08-01 17:26
@manusolano777 if your assets are already imported, it will skip them (not update), so that may be why you're not seeing any change.

**Comment by manusolano777** [comment] 2016-08-01 17:44
I have uploaded my .csv file except "purchase price" everything imported successfully. can you help me solve the issue???? 
![error](https://cloud.githubusercontent.com/assets/18734573/17303297/b547ec70-583d-11e6-871a-6818e9ca0eeb.png)

**Comment by dmeltzer** [comment] 2016-08-04 04:17
I think #2396 will fix this as well, it seems like php on windows handles issues with number_format differently.

**Comment by manusolano777** [comment] 2016-08-04 14:27
Can you help me what should i do to solve this issue??? please help me....

**Comment by dmeltzer** [comment] 2016-08-17 04:09
There are a number of changes to the importer merged into the `develop` branch in the last few days that may fix this.  If you are able, could you give this a try and see if it fixes things for you?

**Comment by dnwlmz** [comment] 2017-04-13 10:44
I seem to be having the same issue, but with the Serial Number

**Closed** 2017-04-13 22:30 UTC
