### ISSUE TITLE
Feature Request: Custom Asset Tag for each Category

### ISSUE THREAD

**Issue by volephuxuan** [snipe/snipe-it#1215] opened 2015-10-01 10:18 UTC
I want to have custom asset tag for each category
Example: computers have tagged PC, servers have tagged SRV, laptops have LAP
When I create new asset and select model for new asset, the custom tag will appear on Asset Tag field.
Is it possible to auto increase the Asset ID with custom format like PC001,PC002,PC003,SRV001,SRV002,...?
Thanks.

**Comment by fpalmcrantz** [comment] 2015-10-02 21:37
It's a good suggestion. The company I work for also use semantic names for labels/tags so I would love to see this make it as a feature

**Comment by vabue** [comment] 2015-11-21 11:11
:+1:

**Comment by snipe** [comment] 2015-11-25 07:59
Agreed, duplicate of #964.

**Closed by snipe** 2015-11-25 07:59 UTC
Labels: under consideration
