### ISSUE TITLE
error when trying to view deleted assets

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#510] opened 2015-02-11 14:47 UTC
Pretty sure I have no deleted assets but when trying to view them I get the following error

![image](https://cloud.githubusercontent.com/assets/10247644/6148926/05566e8e-b1d3-11e4-87a2-d05b9dfbb7a7.png)

**Comment by snipe** [comment] 2015-02-11 21:23
Hrm... I can't reproduce that one locally.

**Comment by snipe** [comment] 2015-02-11 21:53
Fixed in 342a8b81afb2060a128d0667acc15fa5caafc2ea

**Closed by snipe** 2015-02-11 21:53 UTC
