### ISSUE TITLE
Department field for users

### ISSUE THREAD

**Issue by victoriapak** [snipe/snipe-it#3421] opened 2017-03-14 07:13 UTC
#### Expected Behavior (or desired behavior if a feature request)

add a department field, or create a custom field, for users

-----

#### Actual Behavior

no field exists

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment] 2017-03-14 15:40
Closing as duplicate of #1954

**Closed by snipe** 2017-03-14 15:40 UTC
Labels: feature request

**Comment by dantothebert** [comment] 2018-01-11 06:18
First off, this asset management system is absolutely wonderful. I cannot say how much hope this brings to me in being able to keep track of things. Thank you.

Having the Department field is fantastic, however I agree it is a bit backwards with the company field.  We also want departments managers to help keep track of inventory.  We do not want department managers to be managing assets for other departments, but only their own.
Use case: Large team of 10+ people all sharing devices. The team manager can check in/check out devices to their employees. All team members can see who has what device.  Makes it very easy to see what's going on.  Helps IT manager as they no longer have to worry about 100's or 1000's of devices, they can let it be micromanaged. 

Suggestions if this is going to be built out. Adding an option for the asset to be "shareable" so that department managers can check this and assign the asset to a user not on their team.  My suggestion would be to add a Department called "Shared Assets" and let people be a part of their own department AND the Shared Assets department.  That way users could see all the devices that are shared and can either contact the person that is using the device if they would like to borrow it, or alternatively browse through devices that are in stock under the shared asset department.

The workflow would be simple for the end user.  If you do not want the device to be shared, you simply would not make that device a part of the "Shared Assets" department.  All users could have access to the "Shared Assets" department, so they could use that as a place to rent devices. I'm sure IT would typically manage those devices, however you could train users to look at what Department the device is in so they can contact that department manager to acquire the device.

Thanks,
Dan
