### ISSUE TITLE
How to "check-in" Components?

### ISSUE THREAD

**Issue by proweb01** [snipe/snipe-it#2878] opened 2016-11-03 15:29 UTC
#### Expected Behavior (or desired behavior if a feature request)

When "Checking out" a component to an asset, I would expect to be able to later "check-in" that component if things change. For example: I add a video card to a machine. Later, we decide to remove that video card and give to someone else. Or, a machine has 16Gb of RAM - but later, we want to reduce it to 8Gb and give the other stick to another laptop that needs it. Bad examples, but the best I could come up with.

-----

#### Actual Behavior

No option to remove or check-in the component

-----

#### Please confirm you have done the following before posting your bug report:

- [No ] I have enabled debug mode
- [Yes ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on - Windows Server 2012 R2, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- If you're getting an error in your browser, include that error - No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Component page and/or asset page under Components tab
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by epic990** [comment] 2016-11-03 15:38
Only thing u can do is to delete component and make new :) same happened when i made in mine asset and when  u delete it it will be removed from asset but when u go to asset and check components section there will be just '0' in right corner instead no result like in other sections :).

**Comment by proweb01** [comment] 2016-11-08 16:44
Are there any plans in a near future revision to add this ability to check in components? Now, I am going to have to delete all of my components and recreate them as assets, even though they don't quite fit in the asset category. Lots of manual work.

**Comment by snipe** [comment] 2016-11-08 16:49
Yes, there are plans to add this feature.

**Comment by snipe** [comment] 2016-11-22 22:14
Closing as duplicate of #2855

**Closed by snipe** 2016-11-22 22:14 UTC

**Comment by yguvvala** [comment] 2017-01-25 21:27
Is there an update to this feature build?

**Comment by snipe** [comment] 2017-01-25 22:43
When there is an update, we will post it to the original issue (#2855)
