### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by hctclyerly** [snipe/snipe-it#5407] opened 2018-04-20 20:01 UTC
#### Expected Behavior (or desired behavior if a feature request)

When I check out a license to an asset that it is checked out to the asset only

-----

#### Actual Behavior

When I check out a license to an asset that is already assigned to a user, it tags the asset and the user. Then when I check in the asset, the licenses are still checked out to the user.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
no
- Version of Snipe-IT you're running
4.2
- Version of PHP you're running
7.0
- Version of MySQL/MariaDB you're running
MySQL version 10.1.30
- What OS and web server you're running Snipe-IT on
Ubuntu Linux 16.04.3 and Apache version 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no error, just not expected results
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
no error, just not expected results
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
no error, just not expected results
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
yes checking the asset does not check in the license
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cor315** [comment] 2018-05-09 04:31
Same issue here.  You have to check in the asset before checking out the license to that asset.  Otherwise the license will be checked out to the user and the asset.  Then if you check in the asset, the license will still be checked out to the user.  Even if you check out the asset to another user.  Very annoying.

This is also happening is version 4.3.0

**Comment by cslucian** [comment] 2018-05-14 06:41
#5524

**Comment by cor315** [comment] 2018-06-26 06:40
Any update on this?

**Comment by snipe** [comment] 2018-07-25 09:34
Duplicate of #5155

**Closed by snipe** 2018-07-25 09:34 UTC
