### ISSUE TITLE
Upgrading from 4.3.0 - 4.4.1

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#5577] opened 2018-05-22 17:43 UTC
While attempting to upgrade from 4.3.0 to 4.4.1 performed the following but received an error at php artisan migrate command.

Steps:
Copied over the following files from previous installation:

1. .env file located in the C:\wamp\www\snipe-it
2. OAuth keys located in the C:\wamp\www\snipe-it\storage 
3. Folders in public/uploads directory located in the C:\wamp\www\snipe-it\public\uploads
4. Folders in storage/private_uploads directory located in C:\wamp\www\snipe-it\storage\private_uploads

Ran the following commands
composer install --no-dev --prefer-source
composer dump-autoload
php artisan migrate  (Received Error)
php artisan config:clear
php artisan config:cache

Ran to attempt to clear error:
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

Received error again.

![2018-05-22_11-34-22](https://user-images.githubusercontent.com/31219479/40380085-406483b2-5db5-11e8-9f88-fbf71bbf8d26.jpg)

**Comment by snipe** [comment] 2018-05-22 20:26
Duplicate of #5575

**Closed by snipe** 2018-05-22 20:26 UTC
