### ISSUE TITLE
error while clicking hardware option

### ISSUE THREAD

**Issue by BATHIVINOD2** [snipe/snipe-it#6547] opened 2018-12-30 16:11 UTC
#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
whenever I click on the hardware option am getting the error "Whoops, looks like something went wrong."

**To Reproduce**

**Expected behavior**
I expected to open hardware page what i have see in demo page
**Screenshots**
![2018-12-30_20-38-22](https://user-images.githubusercontent.com/27993980/50548904-6c0f5b80-0c7a-11e9-82f9-729ec547899e.png)
![2018-12-30_20-41-02](https://user-images.githubusercontent.com/27993980/50548905-6ca7f200-0c7a-11e9-88a2-f9820f3dd462.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.6
 - OS: [e.g. Ubuntu, CentOS] : windows server 2016 datacentre
 - Web Server: [e.g. Apache, IIS] : IIS
 - PHP Version : 7.3.0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] : chrome and ie
 - Version [e.g. 22] : chrome : 71

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
(2/2) ErrorExceptioncompact(): Undefined variable: operator (View: C:\inetpub\wwwroot\snipe-it\resources\views\hardware\index.blade.php)
--
in Builder.php line 1229
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\\inetpub\\wwwroot\\snipe-it\\storage\\framework\\views/1af8e7af68c3eb76505b1fdb721ef685b8a9373a.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\inetpub\\wwwroot\\snipe-it\\resources\\views/hardware/index.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' =>object(Setting)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

- If a stacktrace is provided in the error, include that too. : no stacktrace available
- Any errors that appear in your browser's error console. : no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. :no 
- Include any additional information you can find in `storage/logs` and your webserver's logs. : no

**Additional context**
- Is this a fresh install or an upgrade? : Fresh install
- What OS and web server you're running Snipe-IT on : windows server 2016 datacentre
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : manual installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database : not edited

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2019-01-03 19:15
Duplicate of #6547, #6540, and #6522. Please downgrade your version of PHP to 7.1.3 or 7.2.

**Closed by snipe** 2019-01-03 19:15 UTC

**Comment by ZephyriusOne** [comment] 2019-01-09 14:12
Why are we downgrading PHP? All that is needed is to define the variable "Operator" or to just comment out the line that using "compact()". I did this and it is working fine for me now. 

I went through a day of hell yesterday upgrading my Snipe-IT install using PHP 7.3...not about to repeat this again to downgrade. Why not just follow best practice as the below article states?

> "compact() is a function in PHP that creates an array of values from a list of variable names. If an undefined variable is specified, the resulting array will not contain an index for that variable. This could cause some unexpected behavior due to missing indexes and some scenarios that are difficult to debug.
> 
> Starting in PHP 7.3, a notice will be triggered when an undefined variable is passed to compact() to help with identify such situations."

**Comment by Reedawn13** [comment] 2019-02-25 06:24
# Thanks @ZephyriusOne! Your method got it working for me after unsuccessfully downgrade it! 

To add to it, the file location is - (xampp directory)\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query

**Comment by orko99** [comment] 2019-03-14 05:42
@Reedawn13 Could you please share your solution?

**Comment by snipe** [comment] 2019-03-14 05:44
@orko99 - they already did:

> Thanks @ZephyriusOne! Your method got it working for me after unsuccessfully downgrade it!

https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

**Comment by zendesopan1992** [comment] 2020-01-29 12:45
@ZephyriusOne You are rock man !! I applied your solution and everything works fine for me .
Thanks
