### ISSUE TITLE
IE 11 Import button not available

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5657] opened 2018-06-05 10:38 UTC
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
In Internet Explorer 11 is the import button for csv files not available. 
The browser is blank (grey

**To Reproduce**
1. Go to 'Import'

**Expected behavior**

**Screenshots**
![import_error](https://user-images.githubusercontent.com/28959963/40969420-210572f2-68b8-11e8-8358-d46c582e202e.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version : 4.2.0 3497 
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7.1

**Desktop (please complete the following information):**
 - OS: Windows 10 1709
 - Browser: IE
 - Version: 11

**Comment by snipe** [comment] 2018-06-06 01:41
@dmeltzer can you take a look?

**Comment by snipe** [comment] 2018-06-06 20:26
Duplicate of #4973

**Closed by snipe** 2018-06-06 20:26 UTC
