### ISSUE TITLE
stuck on Whoops, looks like something went wrong. 

### ISSUE THREAD

**Issue by D2rkZ3r0** [snipe/snipe-it#5787] opened 2018-07-07 12:55 UTC
Hi Snipe , 
I'm trying to install snipe-it-4.4.1<first install> on wamp and follow steps but i get same result tuck on 
http://localhost/setup/migrate? 
and display this massage :
Whoops, looks like something went wrong.

**Comment by D2rkZ3r0** [comment] 2018-07-07 13:08
(3/3) QueryExceptionSQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index' (SQL: alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`))
--
in Connection.php (line 647)
at Connection->runQueryCallback('alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`)', array(),object(Closure))in Connection.php (line 607)
at Connection->run('alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`)', array(), object(Closure))in Connection.php (line 450)
at Connection->statement('alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`)')in Blueprint.php (line 86)
at Blueprint->build(object(MySqlConnection), object(MySqlGrammar))in Builder.php (line 239)
at Builder->build(object(Blueprint))in Builder.php (line 148)
at Builder->table('action_logs', object(Closure))in Facade.php (line 221)
at Facade::__callStatic('table', array('action_logs', object(Closure)))in 2018_05_14_215229_add_indexes.php (line 21)
at AddIndexes->up()in Migrator.php (line 359)
at Migrator->Illuminate\Database\Migrations\{closure}()in Migrator.php (line 365)
at Migrator->runMigration(object(AddIndexes), 'up')in Migrator.php (line 177)
at Migrator->runUp('C:\\wamp\\www\\snipe-it\\database\\migrations/2018_05_14_215229_add_indexes.php', 2, false)in Migrator.php (line 146)
at Migrator->runPending(array('C:\\wamp\\www\\snipe-it\\database\\migrations/2018_05_14_215229_add_indexes.php', 'C:\\wamp\\www\\snipe-it\\database\\migrations/2018_05_14_223646_add_indexes_to_assets.php', 'C:\\wamp\\www\\snipe-it\\database\\migrations/2018_05_14_233638_denorm_counters_on_assets.php', 'C:\\wamp\\www\\snipe-it\\database\\migrations/2018_05_16_153409_add_first_counter_totals_to_assets.php'), array('pretend' => false, 'step' => false))in Migrator.php (line 95)
at Migrator->run(array('C:\\wamp\\www\\snipe-it\\database\\migrations'), array('pretend' => false, 'step' => false))in MigrateCommand.php (line 69)
at MigrateCommand->fire()
at call_user_func_array(array(object(MigrateCommand), 'fire'), array())in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php (line 87)
at BoundMethod::callBoundMethod(object(Application), array(object(MigrateCommand), 'fire'), object(Closure))in BoundMethod.php (line 31)
at BoundMethod::call(object(Application), array(object(MigrateCommand), 'fire'), array(), null)in Container.php (line 539)
at Container->call(array(object(MigrateCommand), 'fire'))in Command.php (line 182)
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php (line 252)
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php (line 167)
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php (line 946)
at Application->doRunCommand(object(MigrateCommand), object(ArrayInput), object(BufferedOutput))in Application.php (line 248)
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php (line 148)
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php (line 141)
at Application->call('migrate', object(Collection), null)in Kernel.php (line 220)
at Kernel->call('migrate', array('--force' => true))in Facade.php (line 221)
at Facade::__callStatic('call', array('migrate', array('--force' => true)))in SettingsController.php (line 253)
at SettingsController->getSetupMigrate()
at call_user_func_array(array(object(SettingsController), 'getSetupMigrate'), array())in Controller.php (line 55)
at Controller->callAction('getSetupMigrate', array())in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(SettingsController), 'getSetupMigrate')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 35)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**Comment by EarlRamirez** [comment] 2018-07-10 19:08
@D2rkZ3r0 this is a duplicate to #5654  and #5612

**Comment by snipe** [comment] 2018-07-12 23:55
Closing as duplicate of #5654 and #5612

**Closed by snipe** 2018-07-12 23:55 UTC
