### ISSUE TITLE
Feature Request - Attach Files to Asset Model

### ISSUE THREAD

**Issue by worthy92** [snipe/snipe-it#4018] opened 2017-09-26 11:16 UTC
Is it possible to be able to upload a document to an Asset Model? For example, we have a certain model of Radio (Walkie-Talkie) and would like to upload the user guide for this particular model. At the minute it seems we have to upload the document to each individual asset.

Thanks.

**Comment by snipe** [comment] 2017-09-29 23:23
Duplicate of #1832

**Closed by snipe** 2017-09-29 23:23 UTC
