### ISSUE TITLE
BULK CHECK OUT CONSUMABLES / QUANTITY FIELD

### ISSUE THREAD

**Issue by chaaza** [snipe/snipe-it#5200] opened 2018-03-14 01:50 UTC
#### Expected Behavior (or desired behavior if a feature request)

I want to checkout more than one value of the consumables. For example, 2 pencils, 3 papers and more.

-----

#### Actual Behavior

If I want to checkout more, I need to checkout one by one. And if I have to checkout 10 pencils, I need to click 10 times. Very tiring. Need to have bulk check out or quantity field to checkout. How?

-----

**Comment by chaaza** [comment] 2018-03-15 02:49
@snipe

**Comment by snipe** [comment] 2018-03-15 02:51
Duplicate of #5176

**Closed by snipe** 2018-03-15 02:51 UTC
