### ISSUE TITLE
Change font color in login page

### ISSUE THREAD

**Issue by KARTHIKEYANINDIRAN** [snipe/snipe-it#6723] opened 2019-02-15 12:37 UTC
**Server (please complete the following information):**
 - Snipe-IT Version **4.6.6**
 - OS: [e.g. Ubuntu, CentOS] **RHEL 7**
 - Web Server: [e.g. Apache, IIS]  **Apache**
 - PHP Version **5**

**Is your feature request related to a problem? Please describe.**
I am not sure this is a feature request or not. Please tell me where to change font color for login page fonts. Custom CSS is use for changing colors for dashboard and sidebar like after login. I need to change font color in login page. Particularly "**Please login**" content.

**Describe the solution you'd like**
Nil

**Describe alternatives you've considered**
Please give option for login page color and fonts color in settings

**Additional context**
Nil

**Comment by snipe** [comment] 2019-02-16 19:58
As mentioned previously, you have to use the Custom CSS in your Admin Settings > Branding. Custom CSS is respected on the login page.

Closing as duplicate of #6706

**Closed by snipe** 2019-02-16 19:58 UTC
