### ISSUE TITLE
option to add custom field in Accessories

### ISSUE THREAD

**Issue by pmsudhi** [snipe/snipe-it#1689] opened 2016-01-27 07:08 UTC
It would be nice to have an option to add custom fields to Accessories also. many times, though we don't need to track these items, we may need to store some associated information.

**Comment by vabue** [comment] 2016-01-27 15:38
:+1:

Custom fields would fit even manufacturers, suppliers, locations and manintenances!

**Comment by SylentBobNJ** [comment] 2016-02-16 19:24
+1 to this feature request.  Would love to add, for example, printer models certain toner is associated with, etc.  Additionally, cloning consumables to keep this information but update order numbers, costs, etc. when supplies are replenished.

**Comment by ultimatee** [comment] 2016-12-15 00:17
+1.
This would make the software expandable in a huge way.
Say I could add this feature to my installation (not good enough of a programmer to add to the project :) .. is there a way to extend the software without modifying the core / breaking the updates?
(e.g Like OCMod for Opencart)

**Comment by snipe** [comment] 2016-12-15 00:51
No, you would have to modify the core at this point. We're exploring ways to make the system a little more modular, but we're not there yet. API comes first.

**Comment by danpospisil** [comment] 2017-07-11 16:47
+1 - we would love to track MAC addresses for LAN adapters - we had to declare these things as "Assets" but it seem not logically correct since we don't care about them that much - we just need to know what MAC address drop in our network after the adapter is lost / stolen...

**Comment by sidiabale** [comment] 2017-09-10 00:01
+1. We took it for granted that custom fields were globally available but surprisingly that's not the case!
@snipe Any idea when this will be implemented?

**Comment by snipe** [comment] 2017-09-13 22:22
@sidiabale not in the upcoming v4 release. It's not currently on the short-term roadmap

**Comment by sidiabale** [comment] 2017-09-14 00:38
@snipe Thanks for the update. Too bad that it's not yet on the short-term roadmap... :(

**Comment by snipe** [comment] 2017-10-19 10:01
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:01 UTC
Labels: feature request
