### ISSUE TITLE
How to fitler assets and print their labels

### ISSUE THREAD

**Issue by ovizii** [snipe/snipe-it#3466] opened 2017-03-29 11:47 UTC
Not sure if this is not a feature yet or if I can't find it but could someone point me towards it if its possible? 

What I am looking for is a way to say go to Snipe IT => Assets => filter for all assets of i.e. asset category: Desktops then print labels for all assets in this category.

**Comment by snipe** [comment] 2017-03-29 12:34
You can try searching on "Desktop", but that's the only option at this time.

Closing as duplicate of #1728

**Closed by snipe** 2017-03-29 12:34 UTC
