### ISSUE TITLE
Features Request: Contract Management for Various category

### ISSUE THREAD

**Issue by andreasoc** [snipe/snipe-it#5515] opened 2018-05-10 16:33 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 4.2
 - OS: [e.g. Ubuntu, CentOS]Windows
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1

our company needs a database where to enter contracts related to telephone operators, energy supplier, technical assistance with the various suppliers where you can enter at least:
contract start date
contract expiration date
expected notice of withdrawal date
cancellation methods (pec, etc.)
specific alert for contract expiry notice
specific alert for notification, expected notice of withdrawal date

for example
contract for my Energy Company 
start 01/05/2018
end 01/05/2019
withdrawal requested 3 months before 
via pec
alert x end date
alert x withdrawal requested 3 months before
thanks to all

**Comment by snipe** [comment] 2018-05-11 03:00
Duplicate of #5345, covered by https://github.com/snipe/snipe-it/pull/5322

**Closed by snipe** 2018-05-11 03:00 UTC

**Comment by andreasoc** [comment] 2018-06-07 08:15
1. Hi @snipe , i read the https://github.com/snipe/snipe-it/pull/5322 it does not seem that the requests coincide or maybe there are not all the details that I wrote, can it be?
2. i want to collaborate for translate , how to ? 
thanks

**Comment by andreasoc** [comment] 2018-06-11 12:51
Hi 
any update for this request ? 
thanks

**Comment by thameerakn** [comment] 2019-05-27 03:57
Hi,

Is this added to the new release 4.6? Would like to have this feature as it will help to add Maintenance  agreements.

Thanks
