### ISSUE TITLE
Send User Credentials agaian

### ISSUE THREAD

**Issue by chrstmnn** [snipe/snipe-it#4659] opened 2017-12-20 15:10 UTC
It would be nice, if there was a button to send the user's credentials again via mail.

**Comment by snipe** [comment] 2017-12-20 16:11
Passwords are hashed on the server - there is no way to send a password once it's saved.

**Comment by snipe** [comment] 2017-12-20 16:12
Duplicate of #4166

**Closed by snipe** 2017-12-20 16:12 UTC
