### ISSUE TITLE
A specific asset fails to display its 'view asset' page

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2940] opened 2016-11-17 16:12 UTC
#### Expected Behavior (or desired behavior if a feature request)
This is just on one particular asset, out the blue, but possibly linked to the user somehow.

Click on asset tag to view it and the asset information screen is displayed.

-----

#### Actual Behavior

It loads part of the page then displays an exception error. The partly displayed page is not styled.

FatalErrorException in c23e1f397081f08a96f5b7244cfad1110445da61.php line 673:

Call to a member function fullName() on null

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6
- What OS and web server you're running Snipe-IT on - IIS8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error. 

Whoops, looks like something went wrong.

1/1

FatalErrorException in c23e1f397081f08a96f5b7244cfad1110445da61.php line 673:

Call to a member function fullName() on null

1. in c23e1f397081f08a96f5b7244cfad1110445da61.php line 673

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - http://snipeit/hardware/1042/view

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - none different to what I've shown.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No.

**Comment by snipe** [comment] 2016-11-18 05:20
Is there anything unusual about that asset? Was it deleted or anything?

**Comment by snipe** [comment] 2016-11-18 05:21
Also, can you show me the lines around 23e1f397081f08a96f5b7244cfad1110445da61.php line 673? A few above and a few below.

**Comment by diekmanu** [comment] 2016-11-18 06:45
Renaming/removing the file in /storage/framework/views won't help?

**Comment by rozowykubek** [comment] 2016-11-21 08:09
that bug for me shows up after "signature" was enabled.
it usually happens after asset was "signed" by the user and when you try to edit and saves settings that bug kicks in.

I have written about that in another topic concerning sig_filename

**Comment by mmcleod82** [comment] 2016-11-21 11:43
Lines 670 - 676:

```
<?php else: ?>
                                <del><?php echo e($log->target->showAssetName()); ?></del>
                              <?php endif; ?>
                            <?php elseif(($log->action_type=='accepted') || ($log->action_type=='declined')): ?>
                                    <?php echo e($log->item->assigneduser->fullName()); ?>

                            <?php else: ?>

**Comment by mmcleod82** [comment] 2016-11-21 11:50
As regards anything unusual, this particular asset was checked out to a manually created user, FirstName 'Snipe' , LastName 'test', Could just be a coincidence or there's something it doesn't like about the user somehow. It hasn't been deleted.

**Comment by mmcleod82** [comment] 2016-11-21 11:51
rozowykubek - the scenario you described tests out fine at my end.

**Comment by rozowykubek** [comment] 2016-11-21 12:58
>rozowykubek - the scenario you described tests out fine at my end.


Actually that's bad but first part of your scenario matches mine that is "checked out to user".
Although once it happened after asset was checked in.

Do you have signature feature enabled when it happens  ? cause I don't have that issue with signature turned off ( fresh installation -  2 users nothing more )

**Comment by snipe** [comment] 2016-11-22 02:59
@mmcleod82 Can you find the DB record with that entry in the action_logs table?

**Comment by mmcleod82** [comment] 2016-11-23 14:06
yes I've found the DB records for that asset - what are you interested in?

**Comment by mmcleod82** [comment] 2016-11-23 14:23
![capture1](https://cloud.githubusercontent.com/assets/19797176/20565174/55c05798-b188-11e6-8c02-a1689b602c1f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19797176/20565178/586a2870-b188-11e6-81d1-dffd767c3882.PNG)

**Comment by snipe** [comment] 2016-11-23 14:24
Can you tell if it's the update that it's choking on?

**Comment by mmcleod82** [comment] 2016-11-23 15:06
Well, when I've seen this happen once before, it chokes during checking in (it does checkin though), then on subsequent attempts to view the asset.

**Comment by dmeltzer** [comment] 2016-11-24 00:56
the line with id 4472 looks like the culprit to me.  It has a target_id set, but not a target type...

**Comment by dmeltzer** [comment] 2016-11-24 01:03
Does changing the target_type on that line to App\Models\User fix it for you?  It's a missing line in ViewAssetsController, I'll need to do something to retrofit it, but this should fix future issues.

```
diff --git a/app/Http/Controllers/ViewAssetsController.php b/app/Http/Controllers/ViewAssetsController.php
index 6febfd5..acbe21b 100755
--- a/app/Http/Controllers/ViewAssetsController.php
+++ b/app/Http/Controllers/ViewAssetsController.php
@@ -379,6 +379,7 @@ class ViewAssetsController extends Controller
         }

         $logaction->target_id = $findlog->target_id;
+        $logaction->target_type = User::class;
         $logaction->note = e(Input::get('note'));
         $logaction->updated_at = date("Y-m-d H:i:s");

```

**Comment by dmeltzer** [comment] 2016-11-24 16:03
Well, that's a different bug actually.  I can't reproduce what you are seeing here..

**Comment by mmcleod82** [comment] 2016-11-24 16:10
ok, shall I just try changing the target_type on that line to App\Models\User anyway?

If not, is there anything dirty you can do allow it to display?

**Comment by dmeltzer** [comment] 2016-11-24 16:27
You can try changing the target type, but I don't think it will fix this issue...  

I can see why an issue would appear if the checkout was declined, but it doesn't look like that is in your table.

**Comment by dmeltzer** [comment] 2016-11-24 16:30
Oh yes, now I see.  Changing the target type will fix it.  Those lines are only hit if we don't have a target.

**Comment by mmcleod82** [comment] 2016-11-24 16:41
Yes, setting the target_type worked. What might of caused it not to be set then do you think?

**Closed** 2016-11-28 17:01 UTC
Labels: bug
