### ISSUE TITLE
Unable to click on assets assigned to user

### ISSUE THREAD

**Issue by kayfoon** [snipe/snipe-it#4962] opened 2018-02-05 06:12 UTC
#### Expected Behavior (or desired behavior if a feature request)

When a user logs in and is presented with the view 
"Assets assigned to (user)"
They are unable to click on the tag/model/item/asset to go directly to the details of that asset.

Anyway to make this clickable and link directly to the asset?
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  fresh
- Version of Snipe-IT you're running  v4.1.10 build 3249 (g8d3a214) 
- Version of PHP you're running  7.0.27
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by CronKz** [comment] 2018-02-05 09:48
Take a look at #4624

**Comment by kayfoon** [comment] 2018-02-05 13:59
Thanks very much CronKz, just one more issue getting random + + padding after the change (screenshot attached) any ideas what might be causing this?

Thanks again
![1](https://user-images.githubusercontent.com/26534370/35808130-f1a0a51e-0ad8-11e8-9f3e-7b01ebdd33c8.png)

**Comment by snipe** [comment] 2018-02-05 19:22
Duplicate of #4624

**Closed by snipe** 2018-02-05 19:22 UTC
