### ISSUE TITLE
Setting column preferences not persisting after closing browser

### ISSUE THREAD

**Issue by katha757** [snipe/snipe-it#5161] opened 2018-03-06 22:20 UTC
#### Expected Behavior (or desired behavior if a feature request)

When choosing what columns to display, the columns should persist after closing and reopening the browser on the same computer.

-----

#### Actual Behavior

After hiding some columns, I close and reopen browser and the columns will be visible again.  Closing and reopening tab keeps column preference.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running - Version v4.1.10 - build 3249 (master)
- Version of PHP you're running - PHP Version 7.1.9
- Version of MySQL/MariaDB you're running - 10.1.26-MariaDB
- What OS and web server you're running Snipe-IT on - Server 2012 R2/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - All Assets, Asset Table, Columns
- If a stacktrace is provided in the error, include that too. - NA
- Any errors that appear in your browser's error console. - NA
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  - Not reproducible
- Include any additional information you can find in `storage/logs` and your webserver's logs. - NA
- Include what you've done so far in the installation, and if you got any error messages along the way. - NA
- Indicate whether or not you've manually edited any data directly in the database - NA

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-03-07 01:20
Duplicate of #5014. This has already been fixed.

**Closed by snipe** 2018-03-07 01:20 UTC
