### ISSUE TITLE
[FEATURE Request] License Models

### ISSUE THREAD

**Issue by CornyMaster** [snipe/snipe-it#4114] opened 2017-10-02 20:44 UTC
I would like it better if there could be the possibility to model licenses like assets.
If I buy an additional license, it should not appear as a separate license but increase the number of available licenses. However, the purchase of the license should still be visible.

**Comment by snipe** [comment] 2017-10-02 21:59
Duplicate of #3488

**Closed by snipe** 2017-10-02 21:59 UTC
