### ISSUE TITLE
Mail Recieved while checkin/ Checkout of items. Spacing issue in OUTLOOK.

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#6031] opened 2018-08-02 08:06 UTC
Snipe-IT Version 4.4.0
OS: Windows Server 2016
Web Server: IIS
PHP Version 5.56

When check-in/checkout any assets. We have a problem table spacing where there is a lot of gap between them. I see the space is good in Mobile App or Web browser.

I am currently using Outlook 2013/2016. I can see lot of space. 

Please checkin / checkout.
Go to Outlook in windows.
Check the mail from Snipe it Management.

Screen shoot
![email50](https://user-images.githubusercontent.com/16305213/43570626-6f7c1c4c-9658-11e8-999f-775ed35c26d5.JPG)

The Image is 50% zoom below. because I did it to cover the more details in the snapshot for your reference.
If that is 100% zoom by default only Brand log and Asset consumes the space for remaining, I have to scroll down till the end. 
You can see a lot of space between the Asset tag to serial to Ram to Many more details.
And also Asset.

Users will get fed up in scrolling down till end.

**Comment by EarlRamirez** [comment] 2018-08-02 10:56
@mahesh2471990 looks like this is a duplicate to #5969

**Comment by snipe** [comment] 2018-08-02 16:28
Duplicate of #5969

**Closed by snipe** 2018-08-02 16:28 UTC
