### ISSUE TITLE
Feature Request - More Fields for Software Licenses

### ISSUE THREAD

**Issue by jghanlon** [snipe/snipe-it#2411] opened 2016-08-08 23:15 UTC
#### Expected Behavior (or desired behavior if a feature request)

ADD: Field and Column for Manufacturer (pull from existing list for Assets)
ADD: Field for OS or Platform (ex: OS X, Win 10, Linux, etc.)
ADD: Fields or Pulldown: UPGRADE, FULL, RENEWAL

---
#### Actual Behavior

is feature request - behavior does not exist

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - 3.0
- What OS and web server you're running Snipe-IT on - WinServer2012
- What specific Snipe-IT page you're on - 
  /admin/licenses
  /admin/licenses/1/edit
- Indicate whether or not you've manually edited any data directly in the database - NO

**Comment by henryp007** [comment] 2016-08-09 21:07
This would be useful :+1:

**Comment by dmeltzer** [comment] 2016-08-17 04:02
Manufacturer has been added to the latest develop.  I'm not 100% convinced that OS and license type are not better handled as custom fields, will let others weigh in on that.

**Comment by jghanlon** [comment] 2016-08-17 20:31
Thanks!  
I'll test adding in custom fields for other items.

Additional Fields to consider:
-- Website of the manufacturer with hyperlink
-- Checkbox for "Has Dongle"
-- Activation or Registration Code (or maybe Serial Number 2)
-- Checkbox for "Must deactivate license before uninstalling"

**Comment by jghanlon** [comment] 2016-08-19 15:48
-- Checkbox for "Requires license server"
-- URL for "license server address"

**Comment by sjlaird** [comment] 2016-08-25 10:08
Hi, here are the improvements that I'd really like:

- I would like to be notified of expired, not just expiring licenses. Options to set an email  weekly/monthly report of expired and expiring licenses would be good.  

- The ability to set different thresholds per license would also be handy as some licenses are easy to renew and some may have to go through a lengthy approval cycle.

- It would also be great if there could be some history included that can be included for license renewal. At the moment we are thinking of using the comment field.

- The ability for the license records to hold attachments for licenses that require key files.

- The inclusion of custom fields for licenses (I am missing the option to record the operating system the the software is for or the version number of the software)

------------
I might even be worth having a rethink on what you want the license section to do. The license are really just one aspect of a software asset. It might be worth giving the option to track software as an asset than can be tied in to the license section

**Comment by erik-burgess** [comment] 2016-10-03 18:22
In addition to the previously mentioned items, here are a few other things I that I would like to see: 

- Serial Number be optional. Some. Not all applications have a serial number, but we're tracking who has licenses. 

- Perpetual License (Checkbox). Some licenses you buy, and it's good for the duration of the life of the product version. Sure, I could pick some arbitrary date in say 2100, but that's no the most convenient option. 

- is Site License (Checkbox). This option would not limit me to a set seat number, but I could continue to add users as needed as the "Site" is covered. Just because everyone CAN have the license, it doesn't mean that I don't want to track who does or doesn't have it.

**Comment by snipe** [comment] 2017-10-19 10:00
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:00 UTC
Labels: feature request

**Comment by greycell** [comment] 2017-11-15 14:42
I haven't seen this mentioned -- I'd like to see the ability to mark a license as monthly/annual/perpetual for costing purposes. And perhaps whether it's auto-renew.

I haven't figured out a good way of handling this. Perhaps I should enter a new license for each monthly renewal.
