### ISSUE TITLE
All Export document problem with Thai Language (UTF8)

### ISSUE THREAD

**Issue by 9xmen007** [snipe/snipe-it#1687] opened 2016-01-27 03:01 UTC
At first I would like to say "Big Thank you "  for your powerful apps.

Now I implement system successfully. and have some issue.

When I try to export any report with all format. It problem with text encoding in Thai Language. I attached an example for issue.

Thank you again!
![capture](https://cloud.githubusercontent.com/assets/16876727/12602555/da97ac94-c4dc-11e5-9663-6e424021576a.PNG)

**Comment by uberbrady** [comment] 2016-01-27 03:14
I was working on a similar problem.

Can you attach the .csv file here, so I can look at it? If there's nothing secret in your export.

If not, can you open your .csv file in a text editor and just replace with 'X' the data that you don't want shared?

If you'd prefer to email me personally a copy of the .csv, we can arrange that too.

**Comment by snipe** [comment] 2016-01-27 03:15
I think this is a duplicate of #1023

**Comment by 9xmen007** [comment] 2016-01-27 03:22
@uberbrady  this my csv.

https://app.box.com/s/qyt7ryf9te799gh28egf8gu5v6otujgz

**Comment by 9xmen007** [comment] 2016-01-27 03:30
Problem resolve;

I open csv file with notepad++ and change encoding from  utf8+bom  to utf8.
and now can open with excel normally.  

Thank you.
![untitled](https://cloud.githubusercontent.com/assets/16876727/12603010/f6f30b00-c4e0-11e5-9f8d-9d7fc7c5e788.png)

**Comment by uberbrady** [comment] 2016-01-27 03:31
@9xmen007 Thank you!

And that sounds like a great solution, at least a workaround.

Does this also look correct to you? (I'm sorry, I don't speak or read Thai at all, so I'm just going by looking at it visually).

![screen shot 2016-01-26 at 7 29 06 pm](https://cloud.githubusercontent.com/assets/36335/12603006/36a46786-c463-11e5-8c2a-1f81e626e9d7.png)

**Comment by uberbrady** [comment] 2016-01-27 03:32
Can you also upload the 'fixed' version? It sounds like we may have to start adding BOM markers to our export files...

**Comment by 9xmen007** [comment] 2016-01-27 03:35
@uberbrady  This correct format for my language.

I send you file with remove bom

https://app.box.com/s/w9f3i93o9bj8wyvkyjzpfssycy5ctn8j

**Comment by uberbrady** [comment] 2016-01-27 03:43
Excellent, thank you.

What's actually happening is that you're *adding* a BOM - I can see it at the start of the file - 

```
od -t x1 ~/Downloads/report.1.csv |head -1
0000000    ef  bb  bf  41  73  73  65  74  20  54  61  67  2c  e0  b8  9c
```

(`EF BB BF` is the Byte-Order Marker, the BOM)

This probably makes it so that Excel doesn't panic about the UTF8 that's in the file. Super strange though. Still doesn't work on the Mac, though - but that's Microsoft's fault, not anyone else's (it's a known problem).

**Closed** 2016-01-27 03:51 UTC
