### ISSUE TITLE
Full Multiple Companies Support V3 Problems

### ISSUE THREAD

**Issue by sousa43** [snipe/snipe-it#2206] opened 2016-06-28 15:47 UTC
#### Expected Behavior (or desired behavior if a feature request)

When select company on asset the users without permissions, on company "A" should not see assets company "B"

-----

#### Actual Behavior

The normal user can see assets of all companies and make requests.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.0-32-gba25972
- What OS and web server you're running Snipe-IT on: Ubuntu Server 14.04 Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- Any errors that appear in your browser's error console: no
- Confirm whether the error is [reproduceable on the demo](https://v3.snipeitapp.com): Yes
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by RobMSP** [comment] 2016-07-14 12:19
I have seen a similar issue in the v3.0.0.-dev-4 on https://v3.snipeitapp.com 

A user created for a specific company who is given permission to view people and assets can see some items belonging to other companies in the list view, however if they attempt to click on the actual item it gives and error.

I suspect the issue is related to when pulling a list of assets its not filtering by the company.

This broken behavior is seen in : 
Request-able Assets
Assets 

Seems to work fine in: 
People
Consumables
Accessories
Licenses

I also noticed that despite given access to 'components' my company specific user does not have components in the menu list.

**Comment by sousa43** [comment] 2016-07-18 11:53
Yes People works.
On accessories, when i change the company and save, snipe-it don't save the change and don't have error.
The same problem on licenses and consumibles and on components and requestable assets.

Sorry for my english.

**Comment by wcormier** [comment] 2016-07-25 14:24
This is a deal breaker for me currently.

I need assets to be only viewable by their companies.

**Comment by sousa43** [comment] 2016-07-25 15:10
Me too

**Comment by wcormier** [comment] 2016-07-25 15:28
Yea, I did noticed that it seems to be working everywhere except for the assets themselves.

**Comment by snipe** [comment] 2016-07-26 02:47
Can any of you pull down the latest from the develop branch and see if that fixes it?

**Comment by sousa43** [comment] 2016-07-26 08:44
Yes i can,

**Comment by dmeltzer** [comment] 2016-07-26 11:49
Hello,

I'm having trouble making that issue occur, can you give a few more steps to repeat it?

Also, when it doedsn't change the company, do you get redirected to the asset view page with the green success message? Or does it return you back to the edit page with no message at all.

**Comment by sousa43** [comment] 2016-07-26 12:09
Hello yes when i change the company on the asset i get redirected to the asset view page with the green success message but don't change the company.

**Comment by dmeltzer** [comment] 2016-07-26 12:11
are you changing the company as a "super admin" or as an admin for the company?

**Comment by sousa43** [comment] 2016-07-26 12:17
yes

**Comment by dmeltzer** [comment] 2016-07-26 12:46
Sorry, yes it was a super admin or yes it was a company-scope admin?

I'm still having trouble reproducing this, any chance you could give a few more steps? I've tried in both cases... As a company level admin you shouldn't be able to change the company.  If you are an admin not assigned to any company there is currently a bug that lets you, but you'd have to go out of your way to get to the page where you could do so.  As a super admin it works just fine for me.  I'm sure that the problem does exist, I just can't see where :)

**Comment by sousa43** [comment] 2016-07-26 12:56
I create a normal user on company A and i create various assets of company B.
The normal user on company A supposedly can't see the assets on company B.
On the version 3 the normal user can see assets on the both companys.
On the development version is ok
but when i try to change the company on already created asset and save the page gos to the asset page with the green message but dont change the company.

Sorry my english :)

**Comment by dmeltzer** [comment] 2016-07-26 13:01
So, if Asset 1 is belongs to company B, and you change it to company a, a few questions:
- What are the permissions on the person changing the asset from company to company?
- Is the asset checked out when trying to do so?
- Can you maybe attach a screenshot? Of the edit page the the view page before and after.  I'm just having trouble making it break.

**Comment by sousa43** [comment] 2016-07-26 13:23
Ok, i have one asset on company A and is not cheked out, and i whant to change to company B, i go to edit asset and change de company and hit save.
The page go to asset list and apears the green message, but stays on company A

**Comment by sousa43** [comment] 2016-07-26 13:43
And now when i create a new asset and select company B and hit save the company change to A (default company)

**Comment by wcormier** [comment] 2016-07-26 15:10
Assets seem to be listing properly now for the company website, but requestable assets are showing all companies.

**Comment by sousa43** [comment] 2016-07-26 15:19
the requestables don't distinguish the companies

**Comment by dmeltzer** [comment] 2016-08-04 00:26
Is everything working as expected here now?

**Comment by sousa43** [comment] 2016-08-04 08:29
Hi, yes all is working as expected.

**Closed** 2016-10-29 14:27 UTC
