### ISSUE TITLE
Add custom field for URL also for licenses

### ISSUE THREAD

**Issue by davidschmidt88** [snipe/snipe-it#6387] opened 2018-11-02 14:09 UTC
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.5 build 3915 (gc7596e774)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 18.04 64bit
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2.10

**Is your feature request related to a problem? Please describe.**
No, it would be nice to be able to have custom fields also for license items. That way I could add a link to the software vendor where I need to renew the license.

**Describe the solution you'd like**
See above, just the ability to have custom fields the same way as for assets.

**Describe alternatives you've considered**
Workaround at the moment is a non cliccable link in eg comment field.

Hi, I really like the tool already. This would round up a need I encounter atm.
Thanks

**Comment by snipe** [comment] 2018-11-03 00:10
Duplicate of #4261

**Closed by snipe** 2018-11-03 00:10 UTC
