### ISSUE TITLE
Unable to delete a category

### ISSUE THREAD

**Issue by cis4smack** [snipe/snipe-it#4222] opened 2017-10-16 17:48 UTC
#### Expected Behavior (or desired behavior if a feature request)

Trying to delete categories that are empty. 

-----

#### Actual Behavior

When trying to delete a empty category I get an error.

` Error: This category is currently associated with at least one model and cannot be deleted. Please update your model to no longer reference this category and try again.`
  

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Upgrade from 3.6.4
Version 4.0.9
Version PHP 5.6.31
5.5.56-MariaDB
Centos 7 and Apache
Before upgrade install.sh then git clone upgrade path to new version.
WITH DEBUG TURNED ON,  Just the error message posted above.

**Comment by snipe** [comment] 2017-10-17 03:40
I can't reproduce this. Are you certain the category isn't associated with a model?

**Comment by cis4smack** [comment] 2017-10-17 20:04
Yeap, I cleared the cache. Is there a SQL query I can try to see if maybe it shows up like that just not in from the website? Seems odd.

**Comment by snipe** [comment] 2017-10-18 03:06
You'd have to reassign those models then - models can't exist without categories. You can use the bulk edit tool on models to change them to a different category.

**Closed by snipe** 2017-10-18 03:06 UTC
