### ISSUE TITLE
Custom fields at Licenses & Accessories

### ISSUE THREAD

**Issue by kevinouw** [snipe/snipe-it#4259] opened 2017-10-19 09:45 UTC
#### Expected Behavior (or desired behavior if a feature request)

Custom fields at License to add for example Costcenters and also at Accessories

-----

#### Actual Behavior

At my work we would like to add Custom fields to Licenses and A

-----

**Comment by snipe** [comment] 2017-10-19 10:01
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:01 UTC
