### ISSUE TITLE
Feature Request: Scheduled LDAP Sync and Backup

### ISSUE THREAD

**Issue by gsoyka** [snipe/snipe-it#2432] opened 2016-08-11 14:02 UTC
#### Expected Behavior (or desired behavior if a feature request)
It would be nice to be able to schedule a daily or weekly LDAP sync and backup through the web interface.  If it's possible to do at the command line via cron, that would work as well.
-----

**Comment by stevecookms** [comment] 2016-08-11 19:44
I second that!

**Comment by mattgann** [comment] 2016-08-11 22:47
Agreed

**Comment by snipe** [comment] 2016-08-11 22:50
This is a duplicate of #1348

**Closed by snipe** 2016-08-11 22:50 UTC
