### ISSUE TITLE
Asset history tracking

### ISSUE THREAD

**Issue by ultimatee** [snipe/snipe-it#3647] opened 2017-06-08 08:01 UTC
We want to track the movements of the assets (location, status, one custom field). Is there a built-in way to do that? We can also query the database from outside snipe, but there seems to be no way to know which asset attribute has changed.

 Also the asset_logs database table is empty, only the action_logs holds data?

- Version of Snipe-IT you're running: 3.6.5. build 1
- What OS and web server you're running Snipe-IT on: Linux 2.6.32 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh

**Comment by snipe** [comment] 2017-06-08 23:32
We don't currently provide granular history on which fields have changed for an asset.

**Comment by snipe** [comment] 2017-06-08 23:33
Closing as duplicate of #2596

**Closed by snipe** 2017-06-08 23:33 UTC
