### ISSUE TITLE
🕵🏼‍♂️ Custom field search returns no result

### ISSUE THREAD

**Issue by koolk** [snipe/snipe-it#6297] opened 2018-10-04 19:16 UTC
#### Expected Behavior (or desired behavior if a feature request)

 **_Custom field search should return results based on the criteria entered._**

#### Actual Behavior

**_Searching a term that is present in the custom field of an asset, returns no result when searched._**

#### Please confirm you have done the following before posting your bug report:

- [**_YES_** ] I have enabled debug mode 
- [ **_YES_** ] I have read [checked the Common Issues page]

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? _**Fresh Install**_
- Version of Snipe-IT you're running **_4.6.4_**
- Version of PHP you're running **_7_**
- Version of MySQL/MariaDB you're running **_MariaDB_**

- What OS and web server you're running Snipe-IT on **_Ubuntu 16.04 + Apache_**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **_install.sh_**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **_Searching using the magnifying glass on the all assets page_**

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **_Yes, same issue exists in demo version on snipeitapp site. I created the field set "test" with the custom field "unit" using list box. After editing one of the assets to show the "GREAT4" list item, I went on to search "GREAT4" however no results are returned._**

- Indicate whether or not you've manually edited any data directly in the database **_No_**

**Comment by snipe** [comment] 2018-10-04 22:31
Duplicate of #4275

**Closed by snipe** 2018-10-04 22:31 UTC
