### ISSUE TITLE
Exact date for end of warranty instead of inputting months

### ISSUE THREAD

**Issue by jpaolosy** [snipe/snipe-it#6111] opened 2018-08-22 05:20 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 4.5
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version 7

**Is your feature request related to a problem? Please describe.**
In the company I'm working for, all computer are leased from a third party supplier, cost management thing. It would be best if we could input when the exact date is for the end of warranty or lease for the assets. 

**Describe the solution you'd like**
Instead of putting in months figure in the warranty field, an exact date field will be used.
This will be used as exact information for as to when the warranty or end of lease for a particular asset.

**Comment by snipe** [comment] 2018-08-22 05:51
Duplicate of #5925

**Closed by snipe** 2018-08-22 05:51 UTC
