### ISSUE TITLE
checkout accessories to a location

### ISSUE THREAD

**Issue by shafrax** [snipe/snipe-it#792] opened 2015-05-07 08:41 UTC
it would be nice to have option to checkout accessories (multiple quantity) to a location.

for example. 
in my office there is a training room with 25 computer and i want checkout 25 Mouse or keyboard to this room.

**Comment by snipe** [comment] 2015-05-07 17:17
Closing as duplicate of #142

**Closed by snipe** 2015-05-07 17:17 UTC
Labels: duplicate
