### ISSUE TITLE
php upgrade.php

### ISSUE THREAD

**Issue by VitorinoDF** [snipe/snipe-it#5759] opened 2018-06-29 12:34 UTC
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
**_When running the command php upgrade.php the following messages appear at the end when migrating tables

In Connection.php line 647:

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index
' (SQL: alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`))

In PDOStatement.php line 107:

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index'

In PDOStatement.php line 105:

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index_**

**Server (please complete the following information):**
 - Snipe-IT Version - v4.2.0 build 3479 (gbf74bb1)
 - OS: Windows Server 2012 R2 Standard
 - Web Server: Wampserver 3.1.0
 - PHP Version 7.1.9

Never had any issues with upgrading before, there was no change to the databases manually.

Thanks

**Comment by snipe** [comment] 2018-07-06 02:38
Duplicate of #5628

**Closed by snipe** 2018-07-06 02:38 UTC
