### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by BrandonWandon** [snipe/snipe-it#5711] opened 2018-06-14 12:54 UTC
#### Expected Behavior (or desired behavior if a feature request)

Created an Administrators group, that has all permissions granted. Users in this group need all permissions granted

-----

#### Actual Behavior

Users in this group have no permissions at all

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running Version v4.4.1 - build 3636 (master)
- Version of PHP you're running 7.0
- Version of MySQL/MariaDB you're running 5.5
- What OS and web server you're running Snipe-IT on Microsoft Windows Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by BrandonWandon** [comment] 2018-06-14 13:07
I just noticed that if I manually set one of the users' permissions to grant on everything and save, then change back to inherit, it seems to work, but the inherit isn't working by default

**Comment by tantonw** [comment] 2018-06-18 21:15
I have this issue as well.  New SnipeIT install v4.4.1 running on PHP 7.1 and MariaDB 10.2.  When "permissions" is NULL in the database, which is default for LDAP imported users, then permissions that should be inherited from groups are not applied.  If permissions are saved directly at the user level, the "permissions" field is updated to a regular permissions JSON string, and permissions work correctly.  I think the necessary fix is to make permissions inheritance handle NULL user-level permissions correctly, and/or change the LDAP importer to add in a default permissions JSON when importing, which is what happens when using the "create new" user button.

This is the DB after LDAP import, and group permission inheritance doesn't work:

>select id,permissions,ldap_import from users where id=97661;

| id    | permissions | ldap_import |

| 97661 | NULL        |           1 |


This is after clicking the "Save" button on the edit user permissions screen, and group permission inheritance works properly:

>select id,permissions,ldap_import from users where id=97661;

| id    | permissions | ldap_import |

| 97661 | {"superuser":"0","admin":"0","reports.view":"0","assets.view":"0","assets.create":"0","assets.edit":"0","assets.delete":"0","assets.checkin":"0","assets.checkout":"0","assets.audit":"0","assets.view.requestable":"0","accessories.view":"0","accessories.create":"0","accessories.edit":"0","accessories.delete":"0","accessories.checkout":"0","accessories.checkin":"0","consumables.view":"0","consumables.create":"0","consumables.edit":"0","consumables.delete":"0","consumables.checkout":"0","licenses.view":"0","licenses.create":"0","licenses.edit":"0","licenses.delete":"0","licenses.checkout":"0","licenses.keys":"0","components.view":"0","components.create":"0","components.edit":"0","components.delete":"0","components.checkout":"0","components.checkin":"0","users.view":"0","users.create":"0","users.edit":"0","users.delete":"0","models.view":"0","models.create":"0","models.edit":"0","models.delete":"0","categories.view":"0","categories.create":"0","categories.edit":"0","categories.delete":"0","departments.view":"0","departments.create":"0","departments.edit":"0","departments.delete":"0","statuslabels.view":"0","statuslabels.create":"0","statuslabels.edit":"0","statuslabels.delete":"0","customfields.view":"0","customfields.create":"0","customfields.edit":"0","customfields.delete":"0","suppliers.view":"0","suppliers.create":"0","suppliers.edit":"0","suppliers.delete":"0","manufacturers.view":"0","manufacturers.create":"0","manufacturers.edit":"0","manufacturers.delete":"0","depreciations.view":"0","depreciations.create":"0","depreciations.edit":"0","depreciations.delete":"0","locations.view":"0","locations.create":"0","locations.edit":"0","locations.delete":"0","companies.view":"0","companies.create":"0","companies.edit":"0","companies.delete":"0","self.two_factor":"0","self.api":"0"} |           1 |

**Comment by tantonw** [comment] 2018-06-18 21:41
More information... for me this issue only appears when adding users to groups using the "bulk edit" option.  The single-user edit page updates the permissions JSON when saving, but the bulk-edit page does not.  That's how users can wind up assigned to groups but still have NULL permissions from the ldap importer.

**Comment by snipe** [comment] 2018-07-25 10:15
I think this is a duplicate of #5558

**Closed by snipe** 2018-07-25 10:15 UTC
Labels: :hand: bug, :woman_technologist: ready for dev
