### ISSUE TITLE
Feature request: Custom Fields for Users

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3955] opened 2017-09-13 09:09 UTC
#### Desired Behavior

It would be great to be able to add custom fields to users, so that for example the date of joining the Company and other user-related stuff could be stored. Right now I believe only notes can be used for that purpose.

Thanks

**Comment by 08solsticegxp** [comment] 2017-09-13 21:39
I would like to add to this and just say, Ability to add custom fields on everything.

**Comment by scraane** [comment] 2017-09-15 08:41
+1

**Comment by Diniver** [comment] 2017-09-19 12:09
Would be great feature and it will make it really flexible.

**Comment by snipe** [comment] 2017-10-19 10:03
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:03 UTC
Labels: feature request
