### ISSUE TITLE
Bulk Check-in

### ISSUE THREAD

**Issue by davidmatthews85** [snipe/snipe-it#6164] opened 2018-09-07 09:21 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment] 2018-09-07 09:29
Duplicate of #6057

**Closed by snipe** 2018-09-07 09:29 UTC

**Comment by davidmatthews85** [comment] 2018-09-07 09:31
Server (please complete the following information):

    Snipe-IT Version  **- v4.6.4**
    OS: [e.g. Ubuntu, CentOS] - **Ubuntu 18.04**    
    Web Server: [e.g. Apache, IIS] **Apache**
    PHP Version **7.1.20**

Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
**Feature request**

Describe the solution you'd like
A clear and concise description of what you want to happen.
What I've noticed there is a Bulk Checkout feature although not a Bulk Check-in feature and this would be a useful feature for not just ourselves but other users. :)

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.
Manually checking-in individual assets

Additional context
Add any other context or screenshots about the feature request here.

Love what your doing :)

We are using snipe as our IT Asset Manager and its a life saver and helps us keep track on who has booked out assets.
