### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by thwr** [snipe/snipe-it#5249] opened 2018-03-23 14:50 UTC
#### Expected Behavior (or desired behavior if a feature request)
Allow license seats to have their own license keys. It does not matter much if you only use MAK-styled keys, but if you have a piece of software which requires a separate key per installation.

-----

#### Actual Behavior
Not possible. Maybe related to #3488

**Comment by snipe** [comment] 2018-03-29 11:39
Duplicate of #4729

**Closed by snipe** 2018-03-29 11:39 UTC
