### ISSUE TITLE
Creating a new asset checked out to a location remains unassigned

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4664] opened 2017-12-20 20:30 UTC
#### Expected Behavior (or desired behavior if a feature request)

On the Create Asset page, if I select "Main Office" as the location to which the new asset is checked out to, it should save as such.

-----

#### Actual Behavior

The asset remains unassigned when saving it. I can subsequently check the asset out to a location.

-----
#### Provide answers to these questions:

-Is this a fresh install or an upgrade? Upgrade
-Version of Snipe-IT you're running v4.1.9 - build 3128 (master)

**Comment by snipe** [comment] 2017-12-20 20:33
Duplicate of #4652

**Closed by snipe** 2017-12-20 20:33 UTC
