### ISSUE TITLE
Feature Request: Checkout Consumable to Asset

### ISSUE THREAD

**Issue by connor2337** [snipe/snipe-it#5046] opened 2018-02-19 18:45 UTC
#### Expected Behavior (or desired behavior if a feature request)

Would like to see the same function added to assets and licenses (checkout to asset, user, or location), added to consumables. e.g Checkout 'Xerox Black Toner' to 'Xerox Front Desk Printer'. As it sits right now, we're simply checking our consumables to whoever puts in the "We're out of toner!" ticket, which doesn't allow for great reporting on which machines are using what.
We're running " v4.1.11-pre - build 3307 (master) ", in a docker container, running on CentOS

-----

#### Actual Behavior

Right now (as far as I'm aware), you can only check out Consumables to Users

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-02-20 01:59
Duplicate of #4946

**Closed by snipe** 2018-02-20 01:59 UTC
