### ISSUE TITLE
make a print form when asset is checkedout

### ISSUE THREAD

**Issue by Veljko4GH** [snipe/snipe-it#6858] opened 2019-03-26 08:16 UTC
#### Expected Behavior 

With the emails and AD integration it is great, but people should be able when taking equipment to sign a peace of paper so they know that they are responsible for it. 

I work in factory of 600 people and most of them have some kind of IT equipment, but they often do not have mail or AD user at all. 

This should be a very simple print form, maybe even on one page two copies. One for the IT , and one for the user. 

Data on the form: 

asset tag
asset name
Model
Model no
Category
checkout to
Note. 
Issued by - signature
Issued to  - signature

Regards,
Veljko

**Comment by gilesytheking** [comment] 2019-03-28 08:22
This is a nice idea. There is already an option "require signature" in General Settings. I have tested this function, but have not yet found its purpose. 

What you are suggesting could link together with this existing option.

**Comment by gilesytheking** [comment] 2019-03-28 09:06
Currently If you enable "Require users to confirm acceptance of assets in this category." on the asset category and also enable "Require Signature" in General Settings, an email will be sent to the user which will include a link to accept the asset. Upon logging into their account they will be presented with a signature box to accept the asset.

I agree here that there should be an alternative signature acceptance method. I have already been thinking about a solution to this.

- A signature acceptance box on the checkout page or during the checkout process. 
- The signature is then captured digitally when the asset is issued to employee/user and can then be added to the asset checkout confirmation email. 
- Possibly add an option to print the acceptance email/confirmation if the user doesn't have an email account

I would be better to keep all signatures within the asset system rather than having a separate paper trail, but I understand that not all users will have email access

**Comment by Veljko4GH** [comment] 2019-04-03 11:23
Thanks for the tip Gilesytheking, I use snipe it for a year and i know most of the features it has and has not. 
Unfortunately the work flow with mails and "digital signature" does not work for me.  I need to have possibility to print sign the papers the old fashion way. 

PS: I saw similar discussion in #4651 maybe this issue is redundant...

**Comment by snipe** [comment] 2019-05-06 15:54
Duplicate of #3750.

**Closed by snipe** 2019-05-06 15:54 UTC
