### ISSUE TITLE
Error when enabling debug mode

### ISSUE THREAD

**Issue by srazer** [snipe/snipe-it#5962] opened 2018-07-25 19:46 UTC
#### Please confirm you have done the following before posting your bug report:

- [Error when trying ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When setting APP_DEBUG=true I get an error in laravel.log. I do get the warning that debug mode is enabled.
[2018-07-25 15:42:44] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
[2018-07-25 15:42:46] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
[2018-07-25 15:42:52] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  

**To Reproduce**
1. Set APP_DEBUG=true in .env file
2. Run php artisan config:cache
3. Log in
4. See error in laravel.log and no debug bar

**Expected behavior**
Debug mode should work

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 - build 3866
 - OS: [e.g. Ubuntu, CentOS] Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.1.14

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari]  Chrome, IE

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
[2018-07-25 15:42:44] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
[2018-07-25 15:42:46] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
[2018-07-25 15:42:52] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
Server 2016 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
NA
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2018-07-25 21:56
Duplicate of #4296

**Closed by snipe** 2018-07-25 21:56 UTC
