### ISSUE TITLE
Deleted Assets

### ISSUE THREAD

**Issue by macpacadmin** [snipe/snipe-it#557] opened 2015-02-25 00:12 UTC
Hi,

When selecting "Deleted" under "Asset" menu the following error is displayed

Trying to get property of non-object (View: /var/www/html/snipeit/app/views/backend/hardware/index.blade.php)

![image](https://cloud.githubusercontent.com/assets/11169483/6362245/de50e3c8-bcef-11e4-8e1f-f7568deb2f13.png)

**Comment by snipe** [comment] 2015-02-25 00:27
Please see the Getting Help documentation. http://snipeitapp.com/documentation/getting-help/

**Comment by macpacadmin** [comment] 2015-02-25 00:37
My apologies

Version of Snipe-IT you’re running: v1.2.5
What OS and web server you’re running this on: ubuntu 14.10 apache 2.4.10
If you’re getting an error in your browser, include that error: as above
If a stacktrace is provided in the error, include that too.: as above
Include any additional information you can find in app/storage/logs: N/A

**Comment by snipe** [comment] 2015-02-25 00:38
You pulled this from the release tag, or from develop/master?
Is this a new install? Is the data seed data or production data?

**Comment by macpacadmin** [comment] 2015-02-25 00:44
master using -v switch

New install

Production Data

**Comment by snipe** [comment] 2015-02-25 00:44
Have you deleted any assets? (And did you seed the database before you added production data?)

**Comment by macpacadmin** [comment] 2015-02-25 00:47
Database was fresh MySQL and seeded as per install instructions found

http://snipeitapp.com/documentation/installing-on-linuxosx/

Step 6

I created a test asset and deleted this asset as a test

**Comment by snipe** [comment] 2015-02-25 00:49
Hm, that def shouldn't be happening. Can you pull from develop instead? We did have a bug in the seeder that caused an error on the deleted page. I think the fix for that is still in develop tho

**Comment by snipe** [comment] 2015-02-25 00:50
(The problem is, if you seeded with the broken on, it won't un-break it.)  Can you manually delete the seed data just in case that's what happened?

**Comment by snipe** [comment] 2015-02-25 00:51
(You'll need to run migrations if you pull from develop btw - a few new features are in the cooker)

**Comment by macpacadmin** [comment] 2015-02-25 00:52
Is there a method in which I can identify which is the broken version and which is currently working.

In addition the seed was completed roughly 4 hours ago

**Comment by snipe** [comment] 2015-02-25 00:53
Seed from master is broken, seed from develop shouldn't be. If you can just delete the seed data manually from the DB (not mark it as deleted, but actually delete the rows), it will help with troubleshooting.

**Comment by snipe** [comment] 2015-02-25 00:54
Re-seeding the database will wipe out whatever production data you have in there tho, so make sure you backup the db beforehand.

**Comment by macpacadmin** [comment] 2015-02-25 01:11
Re-Seeded database - Test delete with factory supplied data. Issue Dissapears

Imported old Data back in from Database - Issue reappears

**Comment by snipe** [comment] 2015-02-25 01:12
Okay, when you create a new test record and delete it, does the issue re-appear? 

What I'm trying to determine is if the bad seed is what's at play here, or if there's something else. If it's the bad seed data, that's an easy enough fix, just by manually deleting them from the database, leaving the rest of your production data alone.

**Comment by snipe** [comment] 2015-02-25 01:13
"when you create a new test record and delete it, does the issue re-appear?" <-- without importing the backed up data, I mean. Just with the clean seed.

**Comment by macpacadmin** [comment] 2015-02-25 01:17
clean seed works

I created test data, checked item in - Checked item back out 

Checked Delete

Deleted assets displays correctly - no error

**Comment by snipe** [comment] 2015-02-25 01:18
Okay, so it sounds like your issue is due to the bad seed data that's been resolved on develop. Can you manually delete the seed records from the database? (Do you know how, do you have access, etc?)

**Comment by snipe** [comment] 2015-02-25 01:19
(manually delete the ones in the backed up database I mean, so you can restore your production data and not lose anything.)

**Comment by macpacadmin** [comment] 2015-02-25 01:22
I have the access, slightly lacking in the know how area - Any tips?

**Comment by snipe** [comment] 2015-02-25 01:26
Sure thing. The seeder should have created 12 assets, and since they are created first, they should be rows 1-12 in the assets table. To confirm that, execute the following SQL:

`select * from assets where id < 14;`

You should see 12 dummy assets, and one legitimate asset from your production data. Confirm that the dummy data has ids 1-12, and once you have confirmed that, execute:

`delete from assets where id < 13;`

**Comment by macpacadmin** [comment] 2015-02-25 01:39
Completed - Resolved

Steps followed as below
Reseeded by running: php artisan db:seed
I restored backup database (database with issue)
Ran instructions as provided above which has solved the issue

I now have my original Test data happily displaying with no error. Production data is intact also


Thanks Snipe appreciated!!

**Comment by snipe** [comment] 2015-02-25 01:41
Excellent, glad to hear it. Sorry about the seeding glitch. Someone brought it to our attention last week and we fixed it right away, but haven't merged it into master just yet. Glad you're all sorted. :)

![tumblr_njp02uyilt1s373hwo1_400](https://cloud.githubusercontent.com/assets/197404/6363333/571ce9c2-bc4c-11e4-9ab6-879f4bfec487.gif)

**Closed** 2015-02-25 01:41 UTC
Labels: not sure if bug
