### ISSUE TITLE
Unaccepted Asset Report

### ISSUE THREAD

**Issue by leebaggaley** [snipe/snipe-it#5772] opened 2018-07-03 15:39 UTC
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When checking out assets that require acceptance the email with the link is working and the link to accept with signature is working but the unaccepted assets report isnt updating. Only noticed this from when I updated last week

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Unaccepted Assets'

**Expected behavior**
The report used to work correctly but now doesnt seem to update with unaccepted assets
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version Version v4.4.2 - build 3666 (master)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache2
 - PHP Version 7.0.30-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome & Edge

**Comment by mainstayit** [comment] 2018-07-05 09:17
We are seeing the same behaviour as well.

We can work around currently by running the activity report and then manually filtering.

Server:
Snipe-IT version | v4.4.2 build 3666 (gaa5003d29)
OS: [e.g. Ubuntu, CentOS] Debian
Web Server: [e.g. Apache, IIS] Apache2
PHP Version | 7.0.27-0+deb9u1

Desktop (please complete the following information):
OS: [e.g. iOS] Windows 10
Browser [e.g. chrome, safari] Chrome

**Comment by leebaggaley** [comment] 2018-07-05 09:30
Thanks @mainstayit, we have a considerable amount of checkouts happening daily and it's difficult to keep on top, i'll try your suggestion to query out from the activity report. Hopefully it's a simple bug that can be easily fixed as manually querying the data will be time consuming

**Comment by leebaggaley** [comment] 2018-07-05 09:36
Is there a way to run the activity report for all records? Currently limited to the rows per page filter, set at max 500 but I have 6000 records to filter :(

**Comment by tilldeeke** [comment] 2018-07-13 14:46
I have a question to clarify the function of the "Unaccepted Assets"-Report.
What exactly did it show previously? 

1) Assets, that the user neither accepted nor rejected (the user never clicked the link in the email, for example)
2) Assets that the user actively rejected (the user clicked the link and selected "I decline")

This is not entirely clear to me from reading the source code.

**Comment by leebaggaley** [comment] 2018-07-13 15:11
Hi @tilldeeke, That's a very good question lol. The report showed all assets that were still in the pending state AFAIK, as soon as the end user accepted and signed for the asset they would disappear from the list. Im not too sure if they remained in the list after declining acceptance, I never tested that part

**Comment by snipe** [comment] 2018-07-17 04:05
This was caused by a bug where the "pending" status wasn't being recorded. Should be fixed on develop now and will be in the next release.

**Closed by snipe** 2018-07-17 04:05 UTC
Labels: :hand: bug, :woman_technologist: ready for dev

**Comment by ChristophAuch** [comment] 2021-02-10 13:52
I have the same problem, in our instance the report unaccepted assets is empty, although there should be at least one test asset in it. The error occurs on version 4.9.2 and on version 5.1.1.

I tried to assign the asset to myself and clicked decline in the mail and set the signature. In the dashboard the asset also appears as declined, but not in the report as expected.

**Comment by antonioderrico** [comment] 2021-02-11 15:08
same issue here. fresh installation with version 5.1.1 and the 'Unaccepted Assets' is empty.
