### ISSUE TITLE
Locations are hard to use

### ISSUE THREAD

**Issue by goetzk** [snipe/snipe-it#1013] opened 2015-08-04 00:54 UTC
I'm not sure if this is due to be fixed in a future release but we're finding locations hard to use.

After creating a location and assigning assets to it its almost impossible to figure out which assets are in the location.
* Asset view doesn't mention location name, only address. For example Level 1 and level 2 are our location names and the address is identical because both are the same building
* Assets can't be searched by sublocation (at least, it isn't working for us)
* Locations page doesn't allow linking to its assets, see also #1012

**Comment by snipe** [comment] 2015-08-06 12:02
"Asset view doesn't mention location name, only address. For example Level 1 and level 2 are our location names and the address is identical because both are the same building"

Not sure what you mean here. The location name is what's displayed in the asset view.

<img width="849" alt="screen shot 2015-08-06 at 4 59 00 am" src="https://cloud.githubusercontent.com/assets/197404/9111058/ec147a10-3bf7-11e5-9da9-af642b1e9695.png">
<img width="1038" alt="screen shot 2015-08-06 at 4 59 07 am" src="https://cloud.githubusercontent.com/assets/197404/9111057/ec14068e-3bf7-11e5-9d38-666edae37ffe.png">

"Assets can't be searched by sublocation (at least, it isn't working for us)" - Again, not sure what you mean here. The sub-location's name is what's searched on.

<img width="1020" alt="screen shot 2015-08-06 at 5 00 41 am" src="https://cloud.githubusercontent.com/assets/197404/9111086/40e0882c-3bf8-11e5-9106-dc313b5a010f.png">
<img width="843" alt="screen shot 2015-08-06 at 5 01 14 am" src="https://cloud.githubusercontent.com/assets/197404/9111087/40f25cfa-3bf8-11e5-8148-d220aec39b20.png">

"Locations page doesn't allow linking to its assets, see also" - dupe of #1012

**Comment by goetzk** [comment] 2015-08-10 00:09
Sorry, I'll try and clarify.

For *Asset view doesn't mention location name" I'm talking about http://snipeserver/hardware/123/view .  the location isn't mentioned by name on that page, and the address is only there once its checked out to someone (as the address displayed is that of the person the asset has been checked out too, not the location of the asset).

For "Assets can't be searched by sublocation" it looks like I was searching a category of asset not 'all assets' so there was nothing to display when i searched.

**Closed** 2015-11-04 08:14 UTC
Labels: open discussion
