### ISSUE TITLE
Custom Field across assets/searchable

### ISSUE THREAD

**Issue by jamesharding26** [snipe/snipe-it#7079] opened 2019-05-27 15:57 UTC
**Server (please complete the following information):**
 - v4.6.18
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version  7.2

**Is your feature request related to a problem? Please describe.**
I'm looking to use Snipe-it for asset management of the hard drives we have at our film post facility. It's as important for us to track the film or project the asset is related to as it is the actual asset itself. The only way I can see to assign an asset to a film is to use a custom field. 

The issue with this is three fold, firstly it doesn't span across all assets and has to be added to fieldsets each time. For us it's a non negotiable piece of data

Second issue is you can't seem to search a custom field uniquely. I can search for model by using the advanced search box and typing in the model field. This doesn't seem to work for custom fields, it's as if it's not indexed? I can use the general search but this is less intuitive.

Thirdly adding film to the database of options means going into the fieldset and changing the list of choices. I'd like it to be much easier for people to add films to the database than going there.

**Describe the solution you'd like**
Ideally a custom field would span all assets like the asset id. It's a piece of data that we need tied to all assets, or at least the vast majority.

**Describe alternatives you've considered**
I've considered using preexisting fields like 'supplier' or 'manufacturer' but this seems counter-intuitive and robs me of the ability to record this data. I also tried assigning the film as an 'asset model' but this had it's own nightmare of problems

**Additional context**
Any thoughts would be very welcome indeed, this is a great product and I'd like to make it work for our task, a bespoke piece of software would be expensive (like filemaker). Although alternative freeware would be very welcome too.

**Comment by snipe** [comment] 2019-05-28 19:11
Duplicate of #4275

**Closed by snipe** 2019-05-28 19:11 UTC
