### ISSUE TITLE
Sign acceptance directly in check out process

### ISSUE THREAD

**Issue by chrstmnn** [snipe/snipe-it#4515] opened 2017-11-23 18:42 UTC
#### Expected Behavior (or desired behavior if a feature request)

In the checkout process it would be nice if a user can accept and sign the acceptance directly. Our Helpdesk uses a tablet on which a signature could be made very easily on checking out.
After that a copy of the EULA with date, time and signature should be sent to the user via mail.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Comment by snipe** [comment] 2017-11-27 21:11
Duplicate of #3330

**Closed by snipe** 2017-11-27 21:11 UTC
