### ISSUE TITLE
Asset images

### ISSUE THREAD

**Issue by thedaftbadger** [snipe/snipe-it#1229] opened 2015-10-07 09:56 UTC
Just a thought :smile:  ....

we sometimes have assets in for repair and like to store images against particular assets to document wear & tear, etc.

What about adding images with a date stamp as an attachment against an asset.
This could also be done as part of logging maintenance against an asset.

We find this is particularly handy when marking assets as disposed to give a visual record of why they have been disposed.

**Comment by snipe** [comment] 2015-10-07 12:17
How is that different than asset file uploads?

**Comment by thedaftbadger** [comment] 2015-10-07 12:58
I guess it inst but it would be good to have a light-box option for images uploaded rather than having to download them. Also maybe a date stamp would be good :smiley:

**Comment by snipe** [comment] 2015-10-09 21:30
I think that's a duplicate of https://github.com/snipe/snipe-it/issues/1053

**Closed** 2015-10-09 21:30 UTC
