### ISSUE TITLE
List of all assets is empty after upgrading

### ISSUE THREAD

**Issue by hbrecht** [snipe/snipe-it#5494] opened 2018-05-07 09:47 UTC
#### Expected Behavior (or desired behavior if a feature request)

List of all assets shows all assets.

-----

#### Actual Behavior

List of all assets is empty. Browser console shows:
TypeError: can't assign to property "fieldIndex" on "[": not an object bootstrap-table.min.js:7:628

I found something similar in the common issues section, but this says to check APP_URL which is correct

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
  see above, APP_URL is correct

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade

- Version of Snipe-IT you're running
v4.3.0 - build 3559 (master)

- Version of PHP you're running
7.0

- Version of MySQL/MariaDB you're running
MariaDB10.1

- What OS and web server you're running Snipe-IT on
Debian 9.4 with apache 2.4

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Upgrade was done with php upgrade.php

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 no error shown in browser, just in JS console:
TypeError: can't assign to property "fieldIndex" on "[": not an object bootstrap-table.min.js:7:628

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware -> list of all assets

- If a stacktrace is provided in the error, include that too.
Do you want the JS stack trace here?

- Any errors that appear in your browser's error console.
TypeError: can't assign to property "fieldIndex" on "[": not an object bootstrap-table.min.js:7:628

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No

- Include any additional information you can find in `storage/logs` and your webserver's logs.
Nothing unfortunately

- Include what you've done so far in the installation, and if you got any error messages along the way.
We are using this since 1.5 years in different versions

- Indicate whether or not you've manually edited any data directly in the database
No!

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by hbrecht** [comment] 2018-05-08 06:17
In my case it does not look like a timeout problem since the empty list appears immediatly. I only have some 50+ assets in the db :)

**Comment by hbrecht** [comment] 2018-05-15 07:57
Problem still exists after upgrade to v4.3.0 - build 3586 (master)

**Comment by hbrecht** [comment] 2018-07-09 12:15
Problem still exists after upgrade to v4.4.2 - build 3666 (master)

**Comment by hbrecht** [comment] 2018-07-31 13:03
Problem still exists after upgrade to v4.6.3 - build 3866 (master)

**Comment by MysterAitch** [comment] 2018-09-02 23:52
I've just started experiencing this on a system installed/setup this afternoon (Ubuntu 16.04 git clone / install.sh). It worked fine before, with the change between before/after being only the defining of additional custom fields. 

**Digging a little further, it appears that it is reproducible by including a custom field which contains brackets (`()`) within the name.**

Specifically, removing the relevant field from the fieldset allows the page to show correctly and re-adding it triggers the stack-trace below. 

I had a very brief attempt at reproducing this on the demo server without luck. Perhaps @hbrecht could comment on whether the brackets symptoms can be reproduced on their installation?

```
TypeError: can't assign to property "fieldIndex" on "[": not an object bootstrap-table.min.js:7:628
	f <redacted>/js/bootstrap-table.min.js:7:628
	o.prototype.initTable <redacted>/js/bootstrap-table.min.js:7:10367
	BootstrapTable.prototype.initTable <redacted>/js/extensions/cookie/bootstrap-table-cookie.js:294:9
	o.prototype.init <redacted>/js/bootstrap-table.min.js:7:7451
	BootstrapTable.prototype.init <redacted>/js/extensions/mobile/bootstrap-table-mobile.js:91:9
	BootstrapTable.prototype.init <redacted>/js/extensions/cookie/bootstrap-table-cookie.js:279:9
	o <redacted>/js/bootstrap-table.min.js:7:2730
	a.fn.bootstrapTable/< <redacted>/js/bootstrap-table.min.js:8:22036
	each <redacted>/js/dist/all.js:1:24007
	each <redacted>/js/dist/all.js:1:22664
	a.fn.bootstrapTable <redacted>/js/bootstrap-table.min.js:8:21727
	<anonymous> <redacted>/hardware:819:9
	u <redacted>/js/dist/all.js:2:18035
	o/</c< <redacted>/js/dist/all.js:2:18340
```

**Comment by hbrecht** [comment] 2018-09-03 06:52
Yes, I just wanted to confirm: It was double quotes. As in 
Screen size (")
Worked before :-)

**Comment by hbrecht** [comment] 2018-11-02 08:20
Not sure - we removed the double quotes from our fields and did not add them again to avoid any issues.

**Comment by jwhulette** [comment] 2018-11-02 13:14
@snipe  I'm unable to reproduce on v5 Dev, unless i'm looking at the wrong spot. This issue may have been resolved with updating the JS libraries for V5.

<img width="663" alt="all_assets____snipe-it_demo" src="https://user-images.githubusercontent.com/4930051/47917328-8649da80-de7f-11e8-8eee-459bb857e817.png">

**Closed** 2018-11-02 19:03 UTC
Labels: :hand: bug, :woman_technologist: ready for dev
