### ISSUE TITLE
Asset confirmation link

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3595] opened 2017-05-19 18:43 UTC
#### Expected Behavior (or desired behavior if a feature request)

When a user clicks the link sent to confirm receipt of an asset, they are directed to Snipe-IT which prompts them to login, and then directs them to the page to accept/reject the asset.

-----

#### Actual Behavior

When a user clicks the link, they are directed to login, once complete they are dropped at the dashboard. From here a user has to return to their email and click the link again to be brought to the device confirmation page.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.5**
- What OS and web server you're running Snipe-IT on **Server 2012 R2, IIS 8.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- Indicate whether or not you've manually edited any data directly in the database **None**

**Comment by snipe** [comment] 2017-05-19 21:37
Closing as duplicate of #577

**Closed by snipe** 2017-05-19 21:37 UTC
