### ISSUE TITLE
[Bug] License history view

### ISSUE THREAD

**Issue by kenpachi13** [snipe/snipe-it#471] opened 2015-01-23 03:08 UTC
When clicking on the license which is assigned already to a person or asset, it throws an error.

![image](https://cloud.githubusercontent.com/assets/10649463/5870352/a10917cc-a306-11e4-87a2-81fc9bd5a572.png)

![image](https://cloud.githubusercontent.com/assets/10649463/5869195/0710d86e-a2f0-11e4-9307-fac15d002925.png)
he

**Comment by kenpachi13** [comment] 2015-01-23 03:16
version 1.2.2

**Comment by snipe** [comment] 2015-01-23 03:42
Shit, sorry about that. I'll fix tonight.

**Comment by kobie-chasehansen** [comment] 2015-01-23 05:32
@kenpachi13 - may want to blur your serial number out.

**Comment by kenpachi13** [comment] 2015-01-23 05:50
@kobie-chasehansen thanks...removed the serial already. :)

**Comment by kobie-chasehansen** [comment] 2015-01-23 15:58
Got this same error when clicking on a ready to deploy asset .

**Comment by snipe** [comment] 2015-01-23 23:10
Hm, I'm unable to reproduce this... This is from the Licenses listing page?

**Comment by kobie-chasehansen** [comment] 2015-01-23 23:16
I got it on newly created assets on my assets page. Old assets open fine.

**Comment by snipe** [comment] 2015-01-23 23:19
Can you tell me what you did when you created the new asset? Did you assign it to someone during creation, what was the status, etc.

**Comment by kobie-chasehansen** [comment] 2015-01-23 23:23
Not assigned and ready to deploy was how I loaded it.

**Comment by snipe** [comment] 2015-01-23 23:37
@kobie-chasehansen okay, was able to repro using your use case, thank you. 

@kenpachi13 - still can't reproduce yours tho. What screen is that?

**Comment by kenpachi13** [comment] 2015-01-23 23:49
@snipe can you reproduce already?
yes the license is assigned to someone (asset and person)

**Comment by snipe** [comment] 2015-01-23 23:51
@kenpachi13 no, cannot reproduce. You created the license and added x seats, and then checked out the license to a person?

**Comment by kenpachi13** [comment] 2015-01-23 23:53
@snipe yes created the license. checkout > assign to "Asset" > Checkout to "User"

**Comment by snipe** [comment] 2015-02-04 18:26
@kenpachi13 

So I'm clear, your workflow is:
1) save a new license
2) from the licenses listing page, click on checkout
3) Assign the new license to a specific asset
4)  Go to that specific asset and check it out to a user

Do I have that right?

**Comment by kenpachi13** [comment] 2015-02-04 23:05
@snipe yes. that's right.
then view the License history, this is where the error occurs.

**Comment by snipe** [comment] 2015-02-09 00:55
Can you check v1.2.3 just released and tell me if your issue is resolved?

**Closed** 2015-02-09 05:56 UTC
Labels: bug, intermediate, ready

**Comment by kenpachi13** [comment] 2015-02-09 06:00
resolved already.
thanks @snipe

**Comment by snipe** [comment] 2015-02-09 06:06
Glad to hear it!
