### ISSUE TITLE
BARCODE and QR CODE IMAGES NOT SHOW - incorrect path

### ISSUE THREAD

**Issue by viviojack** [snipe/snipe-it#2828] opened 2016-10-27 13:40 UTC
#### Expected Behavior (or desired behavior if a feature request)

I would like the program did see images correctly.

---
#### Actual Behavior

Currently the program does not show pictures of the bar codes or qr codes.
If I check the missing image path, I can see that the current location is: _**http://snipe-it/hardware/5/qr_code**_ 

If I really do I check on the file system image is not contained in this folder
but in **_/var/www/snipeit/public/uploads/barcodes_**
#### Please confirm you have done the following before posting your bug report:
- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:

Snipe-IT Version : 3.4
OS : Ubuntu 15.10
Installed by install.sh
The page that show this isse it's : http://snipe-it/hardware/bulkedit
I have configured the "http://snipe-it/" in the apache2 folder under sites-avaible on file snipeit.conf as virtual host

Here some screenshot 

![2016-10-27 15_59_52-start](https://cloud.githubusercontent.com/assets/23100299/19770418/744cb8ac-9c5f-11e6-9a6c-b46c1b81cf1a.png)

The result : 
![image](https://cloud.githubusercontent.com/assets/23100299/19770481/b86bae12-9c5f-11e6-9676-1090028931e4.png)

And this is the link page from the image :

![image](https://cloud.githubusercontent.com/assets/23100299/19770507/d247edd2-9c5f-11e6-960a-a17d457e17b5.png)

**Comment by snipe** [comment] 2016-10-27 21:54
> Currently the program does not show pictures of the bar codes or qr codes.
If I check the missing image path, I can see that the current location is: http://snipe-it/hardware/5/qr_code

> If I really do I check on the file system image is not contained in this folder
but in /var/www/snipeit/public/uploads/barcodes

That's expected behavior. http://snipe-it/hardware/5/qr_code points to a script that creates an image file locally (in the barcodes directory) if it doesn't already exist.

What do you see when you go to http://snipe-it/hardware/5/qr_code in a browser directly? (Make sure debugging is turned on, so you can see any errors that might arise.) Also check the permissions of your `public/uploads/barcodes` directory.

**Comment by viviojack** [comment] 2016-10-28 11:39
Hy snipe ,
If i try to see the link "http://snipe-it/hardware/5/qr_code' the result is this : 
![image](https://cloud.githubusercontent.com/assets/23100299/19805177/21f9e700-9d13-11e6-981f-195bf4513a57.png)

In the meanwhile in this page the Debug it's not call ( at the bottom of the page there is not the Debug Toolbar even if it's turn on ).
The Public folder and all the subfolder are 777 , I gave them permission to remove any privileges problems .

**Comment by snipe** [comment] 2016-10-29 13:28
Please tail the log file while you access the image directly to see if any errors are generated.

**Comment by peckeltw** [comment] 2016-12-01 12:16
Same issue for me which can be fixed by creating the barcodes folder and giving ownership to user docker

`$:/var/www/html/public/uploads# mkdir barcodes`
`$:/var/www/html/public/uploads# chown -R docker barcodes/`

**Closed** 2016-12-01 12:16 UTC
Labels: not sure if bug

**Comment by Braintelligence** [comment] 2016-12-04 21:08
Thank you! Had the same problem with the docker image!

**Comment by ibettison** [comment] 2018-04-06 15:29
Just traced this through Chrome Developer tools (F12) and it looks like there is a bug in the path. I've had to make changes to the code to insert **http://** and remove **'snipe-it'** from the image src path. I have access to the qrCode as you can see from the attached after I altered the html.

![image](https://user-images.githubusercontent.com/2972546/38429367-0ac4f930-39b6-11e8-84fd-c0aaec403b78.png)

This is the corrected code -
`<img src="http://--servername--/hardware/3/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">`

This is the original code -
`<img src="--servername--\snipe-it/hardware/3/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">`

The original code adds the base url and returns the image src link as-
'http://--servername--/hardware/--servername--/snipe-it/hardware/3/qr_code'

I hope this helps you to resolve the bug.

**Comment by snipe** [comment] 2018-04-06 23:09
@ibettison this is not a bug, as far as we are aware. What do you have in your .env as your APP_URL? The code itself uses:

```
@if  ($snipeSettings->qr_code=='1')
                 <img src="{{ config('app.url') }}/hardware/{{ $asset->id }}/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">
```

So if your APP_URL is incorrect, for example missing the http/https protocol, your image url will be broken.
