### ISSUE TITLE
Feature Request: Able to check consumables out to asset and or location.

### ISSUE THREAD

**Issue by Mynty100** [snipe/snipe-it#5101] opened 2018-02-26 04:01 UTC
#### Expected Behavior (or desired behavior if a feature request)

When Checking out a Consumable item we would like to be able to also be able to checkout the item out to a Asset and or a Location. For example: Printer Toner. A large number of people use the printer/s and so Checking the toner out to the printer (asset) and or the Location wouldn't hurt either.

-----

#### Actual Behavior

Currently only able to assign consumables to a user. This is not ideal.

-----

Thanking you,

https://snipe-it.readme.io/docs/getting-help

**Comment by cslucian** [comment] 2018-02-26 09:20
Issue #4582 refers to the same thing.

Best Regards

**Comment by snipe** [comment] 2018-02-26 20:51
Duplicate of #4582

**Closed by snipe** 2018-02-26 20:51 UTC
