### ISSUE TITLE
Currency bug - switches between currency after saving

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1454] opened 2015-12-07 12:55 UTC
If i set a specific currency like Danish Krone (kr) (should be DKK if we are talking the unique code for the currency) after saving it's set to Swedish Krone because they both have the same way ot writing the denomination. Both use "kr". Would be more appropricate to have the system use unique codes pr country/currency like DKK, SEK, NOK (all uses kr but are unique) rather than the "kr" postfix.

**Comment by swoopdk** [comment] 2015-12-07 13:04
Forgot to mention it's from the docker_enhancement branch i saw this problem.

**Comment by brianjking** [comment] 2015-12-07 14:10
@swoopdk I believe this is a dupe of https://github.com/snipe/snipe-it/issues/1383 as a known issue that will be fixed.

**Comment by swoopdk** [comment] 2015-12-07 14:22
@brianjking you are correct it would seem. 

Hopefully we can get it to be referenced regardless of the symbol used and by some unique id instead :)

**Closed** 2015-12-09 09:10 UTC
