### ISSUE TITLE
Feature Request: Custom Fields Checkbox Option

### ISSUE THREAD

**Issue by molldk** [snipe/snipe-it#2391] opened 2016-08-03 11:03 UTC
It would be nice to be able to make a custom field as a checkbox option.

**Comment by snipe** [comment] 2016-08-03 13:24
Hi @molldk - I believe we already have a ticket open for additional form element options for custom fields. It's def on the roadmap.

**Comment by snipe** [comment] 2016-08-09 21:12
Duplicate of #1960

**Closed by snipe** 2016-08-09 21:12 UTC
