### ISSUE TITLE
Urgent Feature Request:: Allow qty to be selected when checking out for accessories / consumables

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4449] opened 2017-11-15 03:52 UTC
A valid but power feature request where multiple qty is assigned to the same user for accessories & consumables. Currently, the only way is to check it out to the user multiple times. 

Hence Please add qty field in consumables/accessories on the checkout screen. (by default the qty field should state 1)

**Comment by snipe** [comment] 2017-11-15 06:15
Duplicate of #2796

**Closed by snipe** 2017-11-15 06:15 UTC
