### ISSUE TITLE
compact(): Undefined variable:operator / Manufacturers

### ISSUE THREAD

**Issue by liepinshw** [snipe/snipe-it#6551] opened 2019-01-03 13:08 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
"Whoops, looks like something went wrong." returned while accessing **SETTINGS--> MANUFACTURERS** or any section under **ASSETS**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Manufasturers'
3. Page with message "Whoops, looks like something went wrong." is returned

**Expected behavior**
Manufacturer tab is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/46347765/50639889-c9055d00-0f6b-11e9-9868-f8175b94b668.png)

**Server (please complete the following information):**
 - Snipe-IT Version: **v4.6.6 build 3926 (g1a10aa0dd)**
 - OS: **Windows 10, v1709 Os Build 16299.785**
 - Web Server: **Apache 2.4.37**
 - PHP Version: **7.3.0**

**Desktop (please complete the following information):**
 - OS: **Windows 10, v1709 Os Build 16299.785**
 - Browser: **chrome**
 - Version: **Version 71.0.3578.98 (Official Build) (64-bit)**

_--**Smartphone (please complete the following information):**
 -- Device: [e.g. iPhone6]
 -- OS: [e.g. iOS8.1]
 -- Browser [e.g. stock browser, safari]
 -- Version [e.g. 22]_

**Error Messages**
**Whoops, looks like something went wrong.**

(1/1) ErrorExceptioncompact(): Undefined variable: manufacturers
--
in ManufacturersController.php line 39
at HandleExceptions->handleError(8, 'compact(): Undefined variable: manufacturers', 'C:\\XAMPP\\htdocs\\snipeit\\app\\Http\\Controllers\\ManufacturersController.php', 39, array())
at compact('manufacturers')in ManufacturersController.php line 39
at ManufacturersController->index()
at call_user_func_array(array(object(ManufacturersController), 'index'), array())in Controller.php line 55
at Controller->callAction('index', array())in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(ManufacturersController), 'index')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

- The error is NOT reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- **This is this a fresh install**. 
- What OS and web server you're running Snipe-IT on
**OS: Windows 10, v1709 Os Build 16299.785, Apache, xampp-win32-7.3.0-0-VC15**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**manual install**
- Include what you've done so far in the installation, and if you got any error messages along the way.
**Lot of issues, mainly because of curve_hands.dll _(2 vhosts configuration)_.**
- Indicate whether or not you've manually edited any data directly in the database
No, I have not, but significant was the fact that in "Pre-Flight & Setup", step 2 I received an error, cannot recall what exactly, but when I repeated the Pre-Flight & Setup, step 2 returned "that there's nothing to migrate if your migrations have already completed". After first fail I saw that tables are created.

**Comment by liepinshw** [comment] 2019-01-03 13:11
I've seen similar issue with "ASSETS", I'll try to downgrade php to v7.0.x

**Comment by snipe** [comment] 2019-01-03 19:14
Duplicate of #6547, #6540, and #6522. Please downgrade your version of PHP.

**Closed by snipe** 2019-01-03 19:14 UTC

**Comment by liepinshw** [comment] 2019-01-04 09:45
Yep, works like charm with php 7.0.33.
Just taught this may be slightly different and pay attention to manufacturers section.
