### ISSUE TITLE
Generate Backup Link error  on version v2.0.6-54

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1425] opened 2015-12-01 15:40 UTC
hi,

whenever i click on Generate Backup icon the it redirect me to user profile page.

kind regards

**Comment by christopherbox** [comment] 2015-12-01 19:00
I can confirm this as well with the same build.

**Comment by snipe** [comment] 2015-12-01 19:45
Duplicate of #1415

**Closed by snipe** 2015-12-01 19:45 UTC
Labels: duplicate
