### ISSUE TITLE
Missing columns (ID, Company) from view after refresh site

### ISSUE THREAD

**Issue by Robert-Azelis** [snipe/snipe-it#10616] opened 2022-02-05 19:28 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After upgrade system to latest version 5.3.8, noticed that if I select columns (ID, Company) to show then after refresh site they disappear from view. It looks that information about columns (ID, Company) not set in cache.
As I checked problem is with file _snipe-it/public/js/dist)/**bootstrap-table.js**_
In my Prod env. rewerted this file to previous version and everything is working as should be.

Please review last changes in this file and fix problem.

### Reproduction steps

1. Open table view assets or people (or other one)
2. Select ID and Company columns to show
3. Refresh site

### Expected behavior

Selected columns set to view should be visible after refresh site.

### Screenshots

![image](https://user-images.githubusercontent.com/82208283/152655622-cb52778c-d6d4-4ae0-819f-e3a6598160c2.png)
![image](https://user-images.githubusercontent.com/82208283/152655666-9a24a10e-27c7-436f-83fe-42ecae97afd2.png)
![image](https://user-images.githubusercontent.com/82208283/152655735-86b65ab1-54a0-406a-a40f-d91438c2e5c8.png)

### Snipe-IT Version

5.3.8

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Google Chrome, MS Edge

**Comment by jacobsenj** [comment] 2022-02-22 11:41
Seems to be related to https://github.com/snipe/snipe-it/issues/9289

**Comment by AlexanderWPapyrus** [comment] 2022-02-22 12:05
Hi,
There's already a ticket for this @dev
https://github.com/snipe/snipe-it/issues/10482 
#10482

**Comment by snipe** [comment] 2022-03-01 08:26
Closing as duplicate of #10482

**Closed by snipe** 2022-03-01 08:26 UTC
