### ISSUE TITLE
Bulk Check in

### ISSUE THREAD

**Issue by jimender2** [snipe/snipe-it#6144] opened 2018-08-29 16:55 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
We can check multiple items out but I can not check multiple in.  I want to be able to scan multiple barcodes and be able to check them in.

**Describe the solution you'd like**
Essentially I want a reverse of the bulk checkout feature.

**Describe alternatives you've considered**
Tried making a python program to do this but it would not connect to the server.

**Additional context**

**Comment by StevenJohnson1214** [comment] 2018-08-30 16:09
I'd write it in php/jquery and put in a password protected directory or include the appropriate lines of code that utilize the authentication module built into Snipe. This is what I did to create a bulk software check out system. Just test out your queries in MySQL first, should pretty straight forward from there.

When you refer to checking them in by bar code, that doesn't seem like a "bulk" process...
How do you want this feature to work?
Have a screen where you can scan one bar code after the next and it just checks them in?

If so, I'd create a screen with a text box that's auto focused that posts to a checkin.php
Then have the checkin.php have the queries to Update the asset status to have no owner/assignee.
However, this would by pass the log/history of the asset, so you have to write in extra lines of code to account for that if desired.

**Comment by jimender2** [comment] 2018-08-31 12:38
How would I go about finding the code of the bulk checkin page? I would assume that I could then just modify the existing code to have it go to no user.

Thank you for the reply @StevenJohnson1214

**Comment by snipe** [comment] 2018-09-07 09:29
Duplicate of #6057

**Closed by snipe** 2018-09-07 09:29 UTC
