### ISSUE TITLE
cannot access myip/hardware

### ISSUE THREAD

**Issue by michaelangelo1991** [snipe/snipe-it#6627] opened 2019-01-24 02:03 UTC
#### I cannot acces http://myip/hardware   ---on snipe it

(what you expect to happen goes here)

-----

#### Please help me!!!

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- New install of SnipeIT on Windows via Wampp
- SnipeIT versin 4.6.7
- Version of PHP 7.3.1
- My SQL version is 5.7.24
- Microsoft windows 10 pro / wamp 3.1.7
![image](https://user-images.githubusercontent.com/46981453/51649390-33377d80-1fbf-11e9-95a5-f371fe6d1a13.png)

**Comment by snipe** [comment] 2019-01-24 02:04
Hi there - If you're seeing the error "Whoops. Something went wrong" with no other output on the screen and a status code of 500, you'll need to [enable debug mode](https://snipe-it.readme.io/docs/getting-help#section-step-1-enable-debug-mode).

![screen shot 2018-05-16 at 4 14 10 pm](https://user-images.githubusercontent.com/197404/40149158-045ca800-5927-11e8-9e62-1a9c6545e2c1.png)

There are many reasons why you might trigger a 500 error (misconfigured `.env` file, etc), but we won't be able to help you unless you can provide us with a stacktrace, either by [enabling debug mode](https://snipe-it.readme.io/docs/getting-help#section-step-1-enable-debug-mode), or by [looking in your app logs](https://snipe-it.readme.io/docs/getting-help#section-step-3-check-your-app-and-server-logs), located at `storage/logs/laravel.log`.

### To enable debug mode:

- Open your .env file and change `APP_DEBUG=false` to `APP_DEBUG=true`
- From the command line at your Snipe-IT project root, run `php artisan config:clear`

It is quite literally impossible for us to be able to assist you with a 500 "Whoops" error without additional information. The stack trace tells us where the error is occurring, and what might have triggered it.

When debug is enabled, you'll see a long stack trace on your screen:

![screen shot 2018-05-16 at 4 18 08 pm](https://user-images.githubusercontent.com/197404/40149193-3a24ed1c-5927-11e8-9bb6-61d908aa7daa.png)

In order to be able to see what's happening on your install (what specific errors you're triggering), we need the entire stack trace from that page, or as much of the app error log as is possible.

#### Paste Only, Please!
When opening/updating a Github issue and providing the stack trace, please copy+paste the errors into the Github issue. Do not attach them as files. If you're not familiar with GH Markdown, we'll reformat it for you to make it more readable.

If for some reason you cannot enable debug but you have access to the app logs, the easiest way to provide us with ONLY the relevant information (which will make it easier for us to troubleshoot your issue), is to tail the log file and then trigger the error.


### Tailing a Log File in Linux/OSX:

Type the following into a Linux command line prompt from your Snipe-IT project root:

```
 tail -f storage/logs/laravel.log
```

Then trigger the error again, which would give you output like this:

<img width="1389" alt="screen shot 2018-05-16 at 4 35 28 pm" src="https://user-images.githubusercontent.com/197404/40149213-4cdeea5c-5927-11e8-8c38-1f9734a6e6cf.png">


Or you can tail it and output the relevant information into a file:

```
 tail -f storage/logs/laravel.log > snipe-logfile.txt
```

### Tailing the Log File on IIS:

To tail a log file on IIS, you can use Powershell:

```
Get-Content C:\inetpub\wwwroot\snipe-it\storage\logs\laravel.log -Wait
```

If you're not comfortable with Powershell, see the other options available to Windows users at [this StackOverflow article](https://serverfault.com/questions/7263/convenient-windows-equivalent-to-tail-f-logfile).

Then copy and paste the contents of that file into the Github issue. (Remember, don't attach it, paste it in.) **Be sure to redact any personal or sensitive data before including it in Github.** Information such as database passwords, email passwords, app keys, etc should NEVER be exposed on Github.

## Once your issue is resolved, do not forget to turn debugging OFF, or you could expose sensitive information about your system!

(If you need to bookmark this information for easy access, it can be found [in the Snipe-IT documentation here](https://snipe-it.readme.io/docs/whoops).)

**Comment by michaelangelo1991** [comment] 2019-01-24 02:45
![image](https://user-images.githubusercontent.com/46981453/51650953-1e5de880-1fc5-11e9-8ae8-042ac367ca5e.png)

**Comment by michaelangelo1991** [comment] 2019-01-24 02:45
i see the error, what can i do sir? Thanks

**Comment by snipe** [comment] 2019-01-24 04:37
First off, I'm not a sir. 

Secondly, you have to downgrade your version of PHP. Snipe-IT v4 requires PHP >= 5.6.4, PHP < 7.3, [per the requirements documentation](https://snipe-it.readme.io/docs/requirements).

https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

Closing as duplicate of #6586.

**Closed by snipe** 2019-01-24 04:37 UTC

**Comment by michaelangelo1991** [comment] 2019-01-24 05:10
Thank you. :) :) :)
