### ISSUE TITLE
turning off asset types

### ISSUE THREAD

**Issue by arsenal818** [snipe/snipe-it#4500] opened 2017-11-21 19:03 UTC
Hi, is there a way to turn off asset types if not in use? For example, I'm not interested using "Consumables" can I turn that off and not to display from the menu? Also, the other way around can I add custom asset type? 

thanks.

**Comment by snipe** [comment] 2017-11-21 19:08
This is not currently possible. Closing as duplicate of #2442

**Closed by snipe** 2017-11-21 19:08 UTC
