### ISSUE TITLE
Rename Custom Fields

### ISSUE THREAD

**Issue by schannall** [snipe/snipe-it#1927] opened 2016-04-06 11:28 UTC
#### Renaming Custom Fields does not Work

It would be nice to have the possibility to rename custom Fields (without loosing data), but I did not find a way to do so - am I just stupid/blind or is this not possible ATM?

- Version of Snipe-IT you're running
2.1.0

Thanks in advance,

Jonas

EDIT: and it also seems to not be possible to Remove a Field from a custom Fieldset.

**Comment by snipe** [comment] 2016-04-06 19:40
Duplicate of #1684

**Closed by snipe** 2016-04-06 19:40 UTC
