### ISSUE TITLE
Inventory Check Out Error

### ISSUE THREAD

**Issue by kagashe** [snipe/snipe-it#4491] opened 2017-11-20 13:35 UTC
#### Expected Behavior (or desired behavior if a feature request)

Be able to check out an asset against a location instead of a user.

-----

#### Actual Behavior

Error screen

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?               
Fresh Install                      
- Version of Snipe-IT you're running
Version v4.1.4 build 173 (gba38b84)                                       
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
MySQL 5.6
- What OS and web server you're running Snipe-IT on
Ubuntu 16 with Apache version 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/srv/users/serverpilot/apps/laravel5/app/Http/Controllers/AssetsController.php', 466, array('request' => object(AssetCheckoutRequest), 'assetId' => '1373', 'asset' => object(Asset), 'target' => null))in AssetsController.php (line 466)
--
at AssetsController->postCheckout(object(AssetCheckoutRequest), '1373')
at call_user_func_array(array(object(AssetsController), 'postCheckout'), array(object(AssetCheckoutRequest), 'assetId' => '1373'))in Controller.php (line 55)
at Controller->callAction('postCheckout', array(object(AssetCheckoutRequest), 'assetId' => '1373'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'postCheckout')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
error appears after clicking checkout on asset checkout.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Confirmed reproducable on Demo system.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Haven't had any error messages so far.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cornwella** [comment] 2017-11-20 15:08
Chiming in that we're seeing the same occurrence and error here when attempting to check out an Asset to a Location on `4.1.4 build 173 (gba38b84)`. I've tested it both with a newly generated asset and a newly generated Location; both return the same message.

Checking out to users works as intended.

```
(1/1) ErrorExceptionTrying to get property of non-object
--
in AssetsController.php (line 466)
at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/var/www/snipeit/app/Http/Controllers/AssetsController.php', 466, array('request' =>object(AssetCheckoutRequest), 'assetId' => '2', 'asset' => object(Asset), 'target' => null))in AssetsController.php (line 466)
at AssetsController->postCheckout(object(AssetCheckoutRequest), '2')
```

**Comment by snipe** [comment] 2017-11-21 20:36
> Confirmed reproducable on Demo system.

Can you provide instructions on how to reproduce on the demo?

**Comment by snipe** [comment] 2017-11-21 20:36
Aha - I think I see what's happening. If you de-select the pre-selected asset from the "checkout to asset" option on the checkout form, does it still throw that error?

**Comment by cornwella** [comment] 2017-11-21 21:14
Aw geez. Yep, that solves it in our case, and assigns it to the Location correctly. 
Didn't even notice it defaulted to an asset there.

**Comment by snipe** [comment] 2017-11-21 21:43
That's on us, not you. It's a UI bug, for sure. I'm working on a fix now - should be on develop in an hour or so.

**Comment by snipe** [comment] 2017-11-21 22:25
This is the UI flow I'm working on now to fix this issue and the clunky UI of checkout to user/location/asset.

![checkout-selector-buttons](https://user-images.githubusercontent.com/197404/33100032-c8f26e10-cec7-11e7-9bf7-0ec941e37cd4.gif)

**Comment by snipe** [comment] 2017-11-21 23:46
This PR should fix this issue.
https://github.com/snipe/snipe-it/pull/4501

You can also view it on the develop site: https://develop.snipeitapp.com `admin`/`password`

**Comment by snipe** [comment] 2017-11-21 23:48
Derp. I lied, it's not merged yet. :P You can check it out locally though if you want to pull down the `features/improved_checkout_ui_and_4491_fix` branch :D

**Comment by cornwella** [comment] 2017-11-22 00:16
That is super slick. I love the new checkout toggles! This project has such fantastic dev support.

**Comment by snipe** [comment] 2017-11-22 00:19
Careful, I might quote you on that for our website :D 

Did you get a chance to test it out at all, or are you just basing that off the gif? (It's merged into develop now, so you can test it on the develop demo using the credentials above if you don't want to check out a non-release branch)

**Comment by cornwella** [comment] 2017-11-22 00:23
I tested it on the develop server; I'll pull it into our install first thing tomorrow morning!

**Closed** 2017-11-22 00:26 UTC
Labels: bug, javascript, ui
