### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by Canceltodebug** [snipe/snipe-it#1747] opened 2016-02-10 15:57 UTC
Error 500 when trying to generate backup.

![image](https://cloud.githubusercontent.com/assets/16987693/12952469/79079e34-d00e-11e5-8df0-1b66842750c9.png)

Have created a config.php file in /schickling/backup folder with difference. Have added explicit paths and no difference. The backup file is not being created at all.

![image](https://cloud.githubusercontent.com/assets/16987693/12952588/dfc7b492-d00e-11e5-9449-5f0b48fd12c5.png)

Running on Win2008 R2 (2012 was too much of a pain to work with)

**Comment by snipe** [comment] 2016-03-31 04:42
I think this is a duplicate of https://github.com/snipe/snipe-it/issues/1483

**Closed by snipe** 2016-03-31 04:42 UTC
