### ISSUE TITLE
Granting access for multiple companies

### ISSUE THREAD

**Issue by UpulSS** [snipe/snipe-it#5284] opened 2018-03-29 09:09 UTC
#### Expected Behavior (or desired behavior if a feature request)

Hi,

In my case, I have few companies such as

Company A
Company B
Company C
Company D and one user is responsible for assets belongs to more than one company.

In example, user **John** is responsible to maintain assists of Company **B** & **D** while user **Clement** from Company **C** need to view _**all assists of all companies**_.

I tried changing departments, groups, locations, companies in “Version v4.1.14 - build 3382”, but no success. Can you please anyone help me or guide me to accomplish my requirement.

-----

#### Actual Behavior

As per my example, **John** can view assets belongs only to the company, where he attached.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running - Version v4.1.14 - build 3382
- Version of PHP you're running - 5.6.31
- Version of MySQL/MariaDB you're running - 5.7.19 (MySQL), 10.2.8 (MariaDB)
- What OS and web server you're running Snipe-IT on - WAMP Version 3.1.0 - 64bit
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- Any errors that appear in your browser's error console. - No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs. - No
- Include what you've done so far in the installation, and if you got any error messages along the way. - No
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-03-29 09:15
Duplicate of #3520

**Closed by snipe** 2018-03-29 09:15 UTC
