### ISSUE TITLE
empty list in assets page if non superadmin.

### ISSUE THREAD

**Issue by meisaputra** [snipe/snipe-it#5874] opened 2018-07-18 08:37 UTC
#### Please confirm you have done the following before posting your bug report:

- [ v ] I have enabled debug mode 
- [ v ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
super admin create assets, but another login users cannot see that assets.

**To Reproduce**
1. create assets as a superadmin and save
2. logout then login as users
3. go to "asset > list all"
4. empty list...

**Expected behavior**
i expect user can see assets created by superadmin

**Screenshots**
![screenshot-bendara com-2018 07 18-15-14-47- user](https://user-images.githubusercontent.com/1065415/42868833-8a2c2224-8a9d-11e8-9bd9-05f8f7e54865.png)
![screenshot-bendara com-2018 07 18-15-13-02- superadmin](https://user-images.githubusercontent.com/1065415/42868834-8a628b66-8a9d-11e8-959f-d7311e571b22.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.5.0 build 3701 (gbf1e742df)
 - OS: Ubuntu
 - Web Server: Apache on nginx (not sure)
 - PHP Version 5.6.36

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version 67.0.3396.99

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
`[08:27:40] LOG.error: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dh_dh_assets.company_id' in 'where clause'' in /home/k7634046/public_html/duniahalal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77`
- If a stacktrace is provided in the error, include that too.
`Stack trace:
#0 /home/k7634046/public_html/duniahalal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('select count(*)...', Array)
#1 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Connection.php(319): Doctrine\DBAL\Driver\PDOConnection->prepare('select count(*)...')
#2 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select count(*)...', Array)
#3 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#4 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#5 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1706): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#6 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#7 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2025): Illuminate\Database\Query\Builder->get(Array)
#8 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1953): Illuminate\Database\Query\Builder->aggregate('count', Array)
#9 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->count()
#10 /home/k7634046/public_html/duniahalal/app/Http/Controllers/Api/AssetsController.php(274): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 /home/k7634046/public_html/duniahalal/app/Http/Controllers/Api/AssetsController.php(274): Illuminate\Database\Eloquent\Builder->count()
#12 [internal function]: App\Http\Controllers\Api\AssetsController->index(Object(Illuminate\Http\Request))
#13 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#14 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#15 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\AssetsController), 'index')
#16 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#17 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#18 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#21 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /home/k7634046/public_html/duniahalal/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/k7634046/public_html/duniahalal/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/k7634046/public_html/duniahalal/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/k7634046/public_html/duniahalal/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/k7634046/public_html/duniahalal/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/k7634046/public_html/duniahalal/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/k7634046/public_html/duniahalal/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/k7634046/public_html/duniahalal/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/k7634046/public_html/duniahalal/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /home/k7634046/public_html/duniahalal/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /home/k7634046/public_html/duniahalal/public/index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}`
- Any errors that appear in your browser's error console. **NO**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **NO**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
`[2018-07-18 08:27:40] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dh_dh_assets.company_id' in 'where clause'' in /home/k7634046/public_html/duniahalal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77`

**Additional context**
- Is this a fresh install or an upgrade? **fresh install**
- What OS and web server you're running Snipe-IT on **ubuntu**
- What method you used to install Snipe-IT **softaculous in cpanel**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Just follow the instruction on installation**
- Indicate whether or not you've manually edited any data directly in the database **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2018-07-18 09:16
Duplicate of #5874

**Closed by snipe** 2018-07-18 09:16 UTC
