### ISSUE TITLE
snipe advanced search

### ISSUE THREAD

**Issue by simonknowit** [snipe/snipe-it#5785] opened 2018-07-06 11:46 UTC
- [-] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have identified a bug in the snipe advanced search.
When searching for a specific model no. we get all sorts of dif. Hardware.
I cannot seem to figure out why.
The search should only pass the model no. rows, but it does not seem to work at all.

**To Reproduce**
-

**Expected behavior**
The search should only pass the model no. rows, but it does not seem to work at all.

**Screenshots**
n/a

**Server (please complete the following information):**
Azur PaaS service

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Error Messages**
n/a

**Additional context**
n/a

**Comment by snipe** [comment] 2018-07-12 23:59
Please reproduce this on the demo and give us the specific terms you're searching on.

**Comment by snipe** [comment] 2018-07-25 11:35
Duplicate of #4275

**Closed by snipe** 2018-07-25 11:35 UTC
