### ISSUE TITLE
Reports Warranty based 

### ISSUE THREAD

**Issue by andreasoc** [snipe/snipe-it#5936] opened 2018-07-23 16:29 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
If i must to program to  buy or renew,  all PCs with the warranty expiring in the next 1 mounth, or 2 or 3 etc.. i can't .. I must create and download a report and order by expiring date.. 
This features is useful for assets and license.

**Describe the solution you'd like**
An report with the possibility filter by months of warranty expiring... 

thanks

**Comment by snipe** [comment] 2018-07-24 20:45
That's a little trickier than it seems, unfortunately, since the warranty expiration is calculated based on the purchase date and the associated warranty length, it's not a field we can easily sort on in the database.

**Comment by snipe** [comment] 2018-07-24 20:48
Duplicate of #5905

**Closed by snipe** 2018-07-24 20:48 UTC
Labels: :heart: feature request, :woman_technologist: ready for dev

**Comment by andreasoc** [comment] 2018-07-25 08:17
I hope it will be deployed, this 'features' is central for this type of software.
thanks :)
