### ISSUE TITLE
Assign to user not working on /hardware/#/edit view

### ISSUE THREAD

**Issue by dkmansion** [snipe/snipe-it#3933] opened 2017-09-08 04:17 UTC
Hi @snipe 
#### Expected Behavior (or desired behavior if a feature request)
**When editing an asset record and expecting to update the "checkout to" value, after changing "status" to "ready to deploy" the "Checkout to" field should be made visible to assign the asset to a user.**  

![image](https://user-images.githubusercontent.com/5826629/30195310-883b8a9a-940d-11e7-8bb4-48e08192bd31.png)

-----

#### Actual Behavior

![image](https://user-images.githubusercontent.com/5826629/30195270-4a840808-940d-11e7-8e3e-e688c67089e7.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.6**
- What OS and web server you're running Snipe-IT on **RHEL 7, apache 2.4**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
**install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
**None**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  
**http://domain.com/hardware/{id}/edit**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
**none**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). 
**YES screenshots for broken issue are from https://demo.snipeitapp.com/hardware/108/edit  and screenshot for successful is from https://demo.snipeitapp.com/hardware/create this is the same behavior I see in my local production, and dev instance of Snipe-IT 3.6.6**

In my local copy the checkout asset to user path as a work around is avialable
![image](https://user-images.githubusercontent.com/5826629/30195812-e5c2f59c-9410-11e7-8cea-03f91ead9573.png)

When updating other information like location etc for the asset being able to checkout the asset on the same page would be ideal.

Thanks greatly for looking into this.

BTW doesn't seem to be a permissions issue since I have replicated the same issue with Super user, as well as other permission groups on my local.

**Comment by snipe** [comment] 2017-09-08 20:05
I'm unable to reproduce this on the demo. When I select Ready to Deploy, the user menu appears, as expected.

<img width="745" alt="screen shot 2017-09-08 at 1 04 11 pm" src="https://user-images.githubusercontent.com/197404/30229330-4b73d908-9496-11e7-98c6-71926a888b04.png">

**Comment by snipe** [comment] 2017-09-08 20:07
Actually, I take that back - it works on new asset creation, but not on edit. I'm looking into it, but we may not fix it for the v3x versions, just in upcoming v4.

**Comment by snipe** [comment] 2017-09-08 20:21
In looking at the code, I think that's done intentionally. We don't really want you to use editing as a way to checkin/checkout, since we have other triggers (additional validation, alerts, etc( that have to happen when you checkin/checkout. You can create an asset as assigned to someone, but once it exists, you're meant to use the checkin/checkout process to change assignments.

**Closed by snipe** 2017-09-08 20:21 UTC
Labels: bug
