### ISSUE TITLE
Test Api Unauthorization

### ISSUE THREAD

**Issue by Glory15817631828** [snipe/snipe-it#4525] opened 2017-11-27 10:33 UTC
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

1.After create API token, I want to use  test API of hardware by curl
2.the token is created by shell(php artisan passport:client --personal)
3.here is my example:
curl -i http://localhost/snipe-it-4.1.3/public/api/v1/users -H "Authorization: Bearer nP3bPcoD1mk9Rxql88ZPrNlo8UuCLwEbS0TFgwLO" -H "Content-Type: application/json"
-----

#### Actual Behavior

(what actually happens goes here)
 Redirecting to <a href="http://localhost/snipe-it-4.1.3/public/login">http://localhost/snipe-it-4.1.3/public/login</a>.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by glureau** [comment] 2017-11-27 12:36
Maybe a duplicate of my issue (with a bit of research) : https://github.com/snipe/snipe-it/issues/4514
Btw, generally you should avoid to copy-paste the api key even if it's a temporary one ;)

**Comment by snipe** [comment] 2017-11-27 20:59
Duplicate of  #4514

**Closed by snipe** 2017-11-27 20:59 UTC
