### ISSUE TITLE
On Debian prerequisites are not properly set up by snipeit.sh

### ISSUE THREAD

**Issue by mileskjeller** [snipe/snipe-it#1563] opened 2016-01-03 22:20 UTC
Script requires/calls on apache2, mysql-server and curl, but these need to be installed through apt (apt-get) manually before you can run the installation script. Even though the installation script appears to set up pre-requisites

**Comment by merid14** [comment] 2016-01-04 02:00
Can you tell me what version of debian you are running?

**Comment by mileskjeller** [comment] 2016-01-04 03:36
Debian Stable (Jessie/8)

Walter wrote:

**Comment by merid14** [comment] 2016-01-04 15:38
was this a fresh install?

**Comment by mileskjeller** [comment] 2016-01-04 18:35
Yes, brand new install specifically to install Snipe-IT on.
CLI only, no desktop

Walter wrote:

**Comment by merid14** [comment] 2016-01-05 00:36
Did you use the minimum, net or full installer? sorry i'm not sure what they are called for debian. I'm just trying to reproduce the same issues you are having so that i have something to work from. Thanks again for your help on this.

**Comment by mtucker6784** [comment] 2016-01-05 13:11
Hey guys, so I'll spin this up on a Debian box. Are you on Jessie / Wheezy?

**Comment by mtucker6784** [comment] 2016-01-05 14:06
Ok, replicated. I'll tweak the script here and see if I can get a PR going in the next day or two.

**Comment by merid14** [comment] 2016-01-05 14:08
Thanks @mtucker6784

**Comment by mtucker6784** [comment] 2016-01-05 17:11
No problem, thanks for all your work on the installer as well, @merid14.  I'm really excited that the few lines of (very rudimentary) code I created waaaaaay back have come such long way!

I updated the installer: PR #1583

**Comment by merid14** [comment] 2016-01-05 17:19
Progress is exciting! :wink:

**Comment by snipe** [comment] 2016-01-06 03:27
Is this issue resolved then?

**Comment by merid14** [comment] 2016-01-07 14:53
I think it needs to be tested again with PR #1588 just to make sure its working correctly. Probably need @mileskjeller to test for us once the PR is merged. @mtucker6784?

**Comment by mtucker6784** [comment] 2016-01-07 15:10
I would be all in if @mileskjeller is willing to test the revised install script on their Debian box.  However, the issue itself is <b>most likely resolved</b> with #1588. I would love anyone else trying it though to confirm.

**Comment by raumkraut** [comment] 2016-01-11 15:24
I just tried running the ```snipeit.sh``` script from PR #1588, as root, on a fresh barebones Jessie VM:
```./snipeit.sh: line 155: sudo: command not found```

Debian doesn't install or enable sudo by default, but a quick ```apt-get install sudo```, and the script (after re-downloading, see below) seemed happy to run as root. I certainly got a working install out of it.

--

As a further note, I'd suggest that the script should start with ```set -e```. That will make it exit as soon as any command fails. Otherwise, it tries to do everything whatever happens, which in my case included rm'ing the snipeit.sh script itself!

**Comment by mtucker6784** [comment] 2016-01-11 21:40
Thanks @raumkraut , I was under the impression that sudo was available if the root password was not specified during the Debian install process (not sure if that's 100% accurate, OR if it's safe to assume people even do that though.) I'll add that as a part of an install to cover the bases.

I'll look at appending #!/bin/bash -e, too, as I don't think it'd affect CentOS installs either.

**Comment by raumkraut** [comment] 2016-01-12 11:27
It seems you are correct about sudo. From what I can tell, Debian will install and enable sudo if 1) you don't specify a root password during install, or 2) you select a desktop install.
But I've been in the habit of always setting a root password when asked, so have had no sudo on my server VMs. Perhaps its time for me to start reading install instructions again! :)

And FWIW, I've seen that it's preferable to use an explicit `set -e` rather than put it in the shebang line, as it will then still take effect if someone does `$ bash ./snipeit.sh`.

**Comment by merid14** [comment] 2016-01-15 19:09
@raumkraut @mtucker6784 `set -e` will affect the installer. There are non-life threatening errors in there that are more of a pain in the butt to write error reporting for than just ignore. (yes i know any error should be bad and handled but I'm lazy) I'm not the best programer out there so if you have an easier way to handle the exceptions i'd love to learn. so my vote is to keep the `set -e` out of the script at least for now. The installer does remove the install files but that's kinda to keep people from running it multiple times and create bigger issues.

**Comment by raumkraut** [comment] 2016-01-15 22:46
If there are single commands that it's okay for them to fail, then you can append `|| true` to prevent the script exiting. Or if there's a big block of failable commands, you could `set +e` before and `set -e` again afterward (because `-` enables an option and `+` switches it off again, go figure).
Using those, at least it would then be explicit what is allowed to fail.

**Comment by merid14** [comment] 2016-01-20 03:41
Ok Thanks for that @raumkraut I'll look at adding that to the installer. As for the sudo issue, @mtucker6784 we could probably remove sudo from each individual line as the script should detect that it is running as root.

**Closed** 2017-10-17 19:31 UTC
Labels: bug, install.sh
