### ISSUE TITLE
Feature Request: add help text or description to custom text field 

### ISSUE THREAD

**Issue by k-boy** [snipe/snipe-it#2426] opened 2016-08-10 16:37 UTC
#### Expected Behavior (or desired behavior if a feature request)

It will be nice to have the ability to add help text or field description to a custom text field with reg expression. 
Since select options is not available now for custom fields, using a text field with reg expression should allow adding field description of the allowed words or values in the custom field.

---

**Comment by snipe** [comment] 2017-09-13 22:24
This was a duplicate of #1677, and will be available in the upcoming v4

**Closed by snipe** 2017-09-13 22:24 UTC
Labels: feature request
