### ISSUE TITLE
Feature Request: Virtual Assets

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#666] opened 2015-03-16 23:12 UTC
Right now, I have found a way using the existing system to more or less add our Virtual Machines as 'Virtual Assets' using an asset tag starting with 'v-12345678' as an example.

However, when I go to add one of our Remote Desktop CALs and tag it to both the asset and the user who the CAL is assigned to, it tells me "Error: The asset you are trying to associate with this license is owned by somene other than the person selected in the assigned to dropdown."

Ideally, I would like to be able to tag all of my RDS CALs to our virtualized Terminal Server, but have each seat in the license checked out to a different user.

Is it possible to patch and/or add this in a future version?

**Comment by snipe** [comment] 2015-03-18 00:43
I believe this is a duplicate of #589

**Closed by snipe** 2015-03-18 00:43 UTC
Labels: advanced, backend, enhancement, under consideration
