### ISSUE TITLE
Signature Page Question / G Suite Integration Request

### ISSUE THREAD

**Issue by dshadbolt** [snipe/snipe-it#4976] opened 2018-02-06 19:00 UTC
#### Expected Behavior (or desired behavior if a feature request)

Good Afternoon,  

I'm currently employed with a school district and we are looking into implementing this system to help replace our mountains of excel spreadsheets.  Concerning signatures when we deploy a device to a student.  Is it required that they have an account to sign/accept that device?  I know that we will need to create an account for each student, but I was looking to reduce the number of steps for our students.

Also, is it possible to check in about the status of Google Suite integration? I saw an issue was submitted that turned into a feature request, but it kind of stalled there.  Our kids would probably honestly only use the account to accept/sign for the device if needed.  So it would be awesome to just sign-in using the their Google account.

 
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.1.11
- Version of PHP you're running 7.1.11
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on Ubuntu Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-02-13 03:18
Hi @dshadbolt - please do try to keep issues separate (posting one GH issue for each unrelated topic). It just helps us keep track of what features are being asked about, what's been fixed/added, etc. :)

Re: asset acceptance without login, this is a duplicate of #577.
Re: Google OAuth - this is a duplicate of #238.

**Closed by snipe** 2018-02-13 03:18 UTC
