### ISSUE TITLE
Option for adding separate serial number for components items and check out to asset

### ISSUE THREAD

**Issue by akhilptz** [snipe/snipe-it#5986] opened 2018-07-27 09:59 UTC
**Server :**
 - Snipe-IT Version 4.6.3
 - OS:Ubuntu 16.04
 - Web Server:Apache/2.4.18
 - PHP Version: 7.2.6

**Is your feature request related to a problem? Please describe.**
Example: We have a type of hard disk with 10 numbers. Currently, we have the option to enter one serial number for the entire 10 hard disks but don't have the option to individually enter the serial number of these 10 hard disks and don't have the option to check out the individual components with its serial number to an asset.

**Describe the solution you'd like**
Add option to enable additional serial number field and when the component is going to check out select the component with its serial number.
![snipe-it-comp1](https://user-images.githubusercontent.com/25217439/43314808-b8590c96-91b1-11e8-8dee-194e80037f8e.jpg)
![snipe-it-comp2](https://user-images.githubusercontent.com/25217439/43314811-b88bbe70-91b1-11e8-89a8-b4c570bdb009.jpg)

**Comment by snipe** [comment] 2018-07-27 10:01
Related to #3408

**Comment by akhilptz** [comment] 2018-07-27 10:13
Not related to #3408. This is for components. The case #3408 is also a required feature.

**Comment by tilldeeke** [comment] 2018-08-01 15:08
If you want to track the hard drives individually, you could create them as assets. 🤔
(Since assets already can be checked out to assets themselves, and already contain serial numbers).
You would also be able to see which hard drives are assigned to which asset, since you could just filter the "All Assets" view by their category (Hard Disk Drive).

If we were to add a serial number to components, what would separate them from being assets? (excluding the "component" name of course)

**Comment by akhilptz** [comment] 2018-08-02 07:48
Then what is the difference between an asset and a component? A component should be under the category components for the ease of tracking. The serail# for the component is not made mandatory. Add an option for adding the serial field. If this column option is available then it can be useful for the required snipe-it user others can continue without this.

**Comment by EarlRamirez** [comment] 2018-08-02 11:01
@akhilptz I agree with @tilldeeke, if a component serial number becomes mandatory then there are a number of us who will have to fabricate one where our components do not have a serial number so having the flexibility of not having this field mandatory benefits the community at large.

**Comment by akhilptz** [comment] 2018-08-03 12:19
Don't want to make the serial number mandatory. What is the purpose of the current serial number field in components? For 10 quantity there is only one serial number field.

In my opinion, each component should be trackable with its serial number if it available.

**Comment by EarlRamirez** [comment] 2018-08-03 12:44
@akhilptz it depends on the use case for example, if you want to track individual monitors you will add each monitor as a component then check it out to an asset. At the same time you don't need it as an asset because it will not have a name or sent for maintenance, etc. It depends on the use case

**Comment by akhilptz** [comment] 2018-08-06 06:04
@EarlRamirez let say we have 20 keyboards with the same model and I want to track it with the serial number. If I make it as an asset the asset page list all these 20 keyboards. If I make it as a component then it can be list only one item and inside it will list all 20 with the serial number and it will easy to locate and manage.

**Comment by EarlRamirez** [comment] 2018-08-06 09:08
@akhilptz  I understand as I mention we all have different _use case_when you have 20 keyboards and 20 serials as one I believe things start to get messy. This is why there are different categories but again _use case_ so if that works for you, awesome.

**Comment by akhilptz** [comment] 2018-08-10 07:50
@EarlRamirez I have added the items under asset but there an asset tag is mandatory there. So, if possible please consider this feature. This will be a great help to me and also for others. Thank you

**Comment by snipe** [comment] 2018-08-16 21:33
I think this is actually a duplicate of #4421

**Closed by snipe** 2018-08-16 21:33 UTC
Labels: :heart: feature request
