### ISSUE TITLE
Seperate Asset Tag for Different Companies and Making Manufacturer & Supplier common to Assets, Consummable, License, accessories and components.

### ISSUE THREAD

**Issue by mailatbijoy** [snipe/snipe-it#5867] opened 2018-07-17 10:22 UTC
**Server (please complete the following information):**
 - Snipe-IT Version : v4.2.0 build 3497 (g590938f)
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7.0.25-0ubuntu0.16.04.1

**Is your feature request related to a problem? Please describe.**
It is not a problem, It is an advantage to the system.

**Describe the solution you'd like**
It will be good if we are able to add a manufacturer or supplier without specifying category like asset/cons/comp/license.
Option to set separate asset tag for assets belongs to different companies [Administrators handling multiple Locations as well as companies will help this]

**Describe alternatives you've considered**
NA

**Additional context**
Nil

**Comment by EarlRamirez** [comment] 2018-07-17 10:37
@mailatbijoy one way around the Asset tags is to have it done manually, it is not the most feasible but it can be an interim solution, I believe that there was a feature request for this but will have to check and see.  For the first question I will have to be behind my laptop to verify and or check that out to get a better understanding.

**Comment by mailatbijoy** [comment] 2018-07-17 11:52
Manual Feed of Asset tag is possible but automatic selection/Increment of ASSET TAG against different company while creating new item will be a good feature.

**Comment by snipe** [comment] 2018-07-18 09:35
These are two different issues from what I can tell, and they should be created as two separate issues here in Github. 

The asset tag request is a duplicate of #3914.

> It will be good if we are able to add a manufacturer or supplier without specifying category like asset/cons/comp/license.

I don't really know what you mean here. We don't ask for category for supplier/manufacturer, as manufacturers and suppliers could cross multiple categories. (Apple for hardware and for software, for example.)

**Closed by snipe** 2018-07-18 09:35 UTC
