### ISSUE TITLE
Feature Request: Per company asset numbering

### ISSUE THREAD

**Issue by matwest92** [snipe/snipe-it#4158] opened 2017-10-05 14:05 UTC
Hi,
Our business is split into 4 different companies and such all have different assets, so instead of running different instances of the same sofware, would it be possible to ask for the ability have per company asset numbering with auto-incrementing?

Thanks 👍

**Comment by faxesystem** [comment] 2017-10-18 14:57
I already asked for it [here](https://github.com/snipe/snipe-it/issues/1758). This would really be a nice feature since we have offices in different locations.

**Comment by snipe** [comment] 2017-11-22 05:54
Duplicate of #1758

**Closed by snipe** 2017-11-22 05:54 UTC
Labels: ♥ feature request
