### ISSUE TITLE
 Can not checkout next asset in software license

### ISSUE THREAD

**Issue by paulo1624** [snipe/snipe-it#4459] opened 2017-11-15 20:11 UTC
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install
- Version of Snipe-IT you're running? 4.1.4
- Version of PHP you're running? 7.1.11
- Version of MySQL/MariaDB you're running? 15.1
- What OS and web server you're running Snipe-IT on? Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error? Debug turned on, but no error appeared in browser.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error? unable to check-out next asset on software licenses, the available numbers of software is not deducted after checkout for the next asset.
- If a stacktrace is provided in the error, include that too.
![image](https://user-images.githubusercontent.com/32555803/32857823-2ab0c1b2-ca84-11e7-9345-07bd4a15b955.png)

- Any errors that appear in your browser's error console.
![image](https://user-images.githubusercontent.com/32555803/32857796-0ac3621a-ca84-11e7-8c19-de9196922fbe.png)

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-11-15 20:13
Duplicate of #4413

**Closed by snipe** 2017-11-15 20:13 UTC
