### ISSUE TITLE
Double Manufacturer when choosing Model

### ISSUE THREAD

**Issue by CronKz** [snipe/snipe-it#4785] opened 2018-01-10 13:15 UTC
#### Expected Behavior (or desired behavior if a feature request)

"Desktops: Dell OptiPlex (#5040 (MRR81))"

-----

#### Actual Behavior

"Desktops: Dell DellOptiPlex (#5040 (MRR81))"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - YES
1. https://demo.snipeitapp.com/hardware/create
2. Choose Model - voila.

**Comment by ckinsler** [comment] 2018-01-10 14:13
I was able to reproduce this on the demo sandbox, but don't see this bug on my production system (v4.1.9 - build 3128 (master)

**Comment by snipe** [comment] 2018-01-10 14:14
Duplicate of #4663

**Closed by snipe** 2018-01-10 14:14 UTC
