### ISSUE TITLE
Assets graph resizing

### ISSUE THREAD

**Issue by fluxX04** [snipe/snipe-it#3406] opened 2017-03-13 07:57 UTC
#### Expected Behavior (or desired behavior if a feature request)

Resizing the assets graph on the dashboard side correct on window resizing

-----

#### Actual Behavior

Assets graph dosen't resize correct, see image (image taken on full screen).

![snipe](https://cloud.githubusercontent.com/assets/9272277/23845705/ff107796-07c9-11e7-9024-67b024bf1cf9.PNG)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Newest, v3.6.4
- What OS and web server you're running Snipe-IT on
Debian 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git clone, manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Dashboard
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Is reproduceable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment] 2017-03-14 16:08
Duplicate of #2514

**Closed by snipe** 2017-03-14 16:08 UTC
