### ISSUE TITLE
[Feature Request] Unique Auto Increment Asset Tags per Company [multi-tenant]

### ISSUE THREAD

**Issue by fordster78** [snipe/snipe-it#4810] opened 2018-01-12 21:53 UTC
#### Expected Behavior (or desired behavior if a feature request)
Asset tags are unique to each company (prefix) and increments from 1, which is set when creating a new company. e.g. ABC company gets tag of ABC00001 and XYZ Company gets a tag of XYZ00001
-----

#### Actual Behavior

Can create a prefixed asset tag, but it is not unique to each company. e.g. Company1 has asset tag of test00001 and company2 has a tag of test00002.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh
- Version of Snipe-IT you're running v4.1.10-pre build 3185 (g5b15a2f)
- Version of PHP you're running 7.1.1
- Version of MySQL/MariaDB you're running MariaDB
- What OS and web server you're running Snipe-IT on Xampp for Windows
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-01-16 05:34
Duplicate of #3286

**Closed by snipe** 2018-01-16 05:34 UTC
