### ISSUE TITLE
Bulk edit asset custom fields

### ISSUE THREAD

**Issue by j-da** [snipe/snipe-it#5493] opened 2018-05-07 06:51 UTC
**Server (please complete the following information):**
 - Snipe-IT Version: v4.3.0 - build 3559 (master)
 - OS: Ubuntu 16.04.4 LTS
 - Web Server: Apache2
 - PHP Version: v7.0.28

**Is your feature request related to a problem? Please describe.**
We recently switched from using excel documents for asset tracking to SnipeIT and it has already been a massive help. At the end of the month someone from the accounting department invoices the asset(s) to the company the asset is assigned to. To help track this I created 2 custom fields in SnipeIT, invoice date and invoice number. To update those custom fields right now the only way seems to be to do this one by one, manually editing each asset and updating the values. 

It would be very helpful if bulk edit of custom fields was possible.

**Describe the solution you'd like**
Make it possible to bulk edit custom fields assigned to an asset model.

**Describe alternatives you've considered**
I've considered using the API for this and writing an application that allows the person from the accounting department to perform updates, but it seems like a more elegant solution if it was possible from within the web app itself.

**Additional context**

**Comment by EarlRamirez** [comment] 2018-05-09 01:48
@j-da an interim solution would be to update this in a CSV and reimport into Snipe-IT.

**Comment by gizzmojr** [comment] 2018-05-10 18:46
This the same as #3054 ?

**Comment by j-da** [comment] 2018-05-14 11:00
Yes it is, sorry. I guess I should have done a more thorough search.

**Comment by snipe** [comment] 2018-07-25 09:42
Duplicate of #3054

**Closed by snipe** 2018-07-25 09:42 UTC
Labels: :heart: feature request, :woman_technologist: ready for dev
