### ISSUE TITLE
How to remove permission group from user

### ISSUE THREAD

**Issue by rodriguesjpmunch** [snipe/snipe-it#6418] opened 2018-11-12 07:47 UTC
#### Expected Behavior (or desired behavior if a feature request)

I would like to remove permission groups I have added to a user. No button to deselect or remove. 

-----

#### Actual Behavior

Unable to remove the added group from a user

-----

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running: v4.6.4 - build 3885 (master)
- What OS and web server you're running Snipe-IT on - Ubuntu 18.04.1 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Git Clone
![image](https://user-images.githubusercontent.com/42966640/48333570-9cfee700-e660-11e8-8c34-33882e7b749b.png)

**Comment by rodriguesjpmunch** [comment] 2018-11-12 10:57
Yeah that's what I thought, but for some reason the highlighted selection does not want to de-select that group. 
Any other ideas? 
Tried Chrome and IE with no luck. 
![image](https://user-images.githubusercontent.com/42966640/48343237-88c7e380-e67a-11e8-956c-89d0cbfb975f.png)

**Comment by Jarli01** [comment] 2018-11-20 13:00
I just tested on 4.6.6 build 3926 and had no issues. Try clearing your history and cache.

**Comment by rodriguesjpmunch** [comment] 2018-11-20 13:36
Cache cleared no luck.
Updated Chrome fixed issue
Thanks for the trouble of testing.
Keep up the good work, thanks for the hard effort.

**Comment by rodriguesjpmunch** [comment] 2018-11-20 13:37
Correction, when CTRL click to remove the highlight and viewing the users permission the group still shows on his name;
![image](https://user-images.githubusercontent.com/42966640/48777047-2efa9580-ecda-11e8-8ef6-bcea513100a0.png)

![image](https://user-images.githubusercontent.com/42966640/48777061-3883fd80-ecda-11e8-88e6-23d54818d406.png)

**Comment by Jarli01** [comment] 2018-11-20 14:03
Did you hit save?

**Comment by rodriguesjpmunch** [comment] 2018-11-21 05:13
Jip, the green button at the bottom. Except if the button does not work. 
I can change the permission group and click save and it works, but just can't remove it with CTRL + click and then save.

**Comment by snipe** [comment] 2018-12-06 01:32
@rodriguesjpmunch are you on a Mac or a PC? On Mac, it's command+click to select/deselect.

**Comment by rodriguesjpmunch** [comment] 2018-12-06 10:53
Windows. So I hold Control in and click on the assigned permission group then the highlight disappeared, then I click on Save but it does not remove it.

**Comment by figureone** [comment] 2018-12-08 01:12
I believe the problem is: once a user is assigned a group, you cannot unassign all groups (i.e., the user must have at least one group). When you try to deselect all groups and save, the field will not be changed (perhaps a validation rule ignores saving the field if it has no value?)

**Comment by snipe** [comment] 2018-12-08 01:14
@figureone Ah, okay - I think I know what's happening here. Thanks for the extra insight!

**Comment by viclou** [comment] 2019-01-21 10:33
Same issue with FD#9042; let me know how to handle ;)

**Comment by rodriguesjpmunch** [comment] 2019-01-21 11:53
Still need to find a resolution.

**Comment by rodriguesjpmunch** [comment] 2019-01-31 05:02
Spot on. Would be nice to remove the permission if not needed. Would just like the default permission to be applied when importing users.

**Comment by patit72** [comment] 2019-01-31 14:15
Same behaviour on 4.6.7

**Comment by snipe** [comment] 2019-02-13 07:40
Duplicate of #6061

**Closed by snipe** 2019-02-13 07:40 UTC

**Comment by BoltUp7** [comment] 2023-07-05 20:04
The ticket you linked doesn't have a resolution. Only the proposed solution above that isn't working.
