### ISSUE TITLE
Feature Request: Overwrite Assets

### ISSUE THREAD

**Issue by faxesystem** [snipe/snipe-it#4578] opened 2017-12-06 08:46 UTC
#### Expected Behavior (or desired behavior if a feature request)

When creating an asset with an already used asset tag the user should be asked if he wants to overwrite the existing asset or if auto increment should auto choose a new asset tag instead of just getting the message to choose another asset tag.

-----

#### Actual Behavior

User gets asked to use another asset tag when the asset tag is already used.

-----

**Comment by snipe** [comment] 2017-12-08 05:21
I don't think the ability to overwrite an asset_tag is a good idea - way too prone to mistakes.

**Comment by faxesystem** [comment] 2017-12-11 14:29
So maybe a question tell the user that this asset tag already exists and if it should be overwritten. If the user chooses overwrite there could come a second "do you really want to do that" question. This way assets won't be overwritten accidentally.

**Comment by snipe** [comment] 2017-12-12 07:03
This is a duplicate of your previous ticket, #4577

**Closed by snipe** 2017-12-12 07:03 UTC
Labels: ♥ feature request
