### ISSUE TITLE
Feature Request: Custom Field Lists

### ISSUE THREAD

**Issue by henryp007** [snipe/snipe-it#2417] opened 2016-08-09 21:09 UTC
In a future version would it be possible to add custom drop down menus ? For example in the custom fields section instead of choosing number  or text as an input could you choose list and then specify what to include on the list.

Thanks :+1:

**Comment by snipe** [comment] 2016-08-09 21:11
Duplicate of #1960

**Closed by snipe** 2016-08-09 21:11 UTC
