### ISSUE TITLE
Manually checkout to users?

### ISSUE THREAD

**Issue by hiiambo** [snipe/snipe-it#434] opened 2014-12-29 13:26 UTC
Is it possible to manually enter users into the asset field? I have far too many users to import manually since AD sync isn't work yet and honestly they don't all need their own account. It doesn't seem like it's possible to just type in a name for deployment - is there any way to tweak it so that it allows it?

**Comment by snipe** [comment] 2015-01-22 23:27
This is effectively a duplicate of #165 I think.

**Closed by snipe** 2015-01-22 23:27 UTC
Labels: enhancement, intermediate, planned, ready
