### ISSUE TITLE
Broken Character Encoding when exporting the data

### ISSUE THREAD

**Issue by euankr** [snipe/snipe-it#2311] opened 2016-07-25 04:58 UTC
#### Expected Behavior
exported data from assets, users, etc., as csv, txt, excel should have readable text in it.

-----

#### Actual Behavior
if it contains any other characterset like Korean, Japanese and Chinese, it just brokes
-----

#### Please confirm you have done the following before posting your bug report:

- [V] I have enabled debug mode
- [V] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.0-17-gca5d3e3
- What OS and web server you're running Snipe-IT on Ubuntu 14.02, AWS EC2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). it does not happen in demo site
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. no
- Indicate whether or not you've manually edited any data directly in the database no

**Comment by snipe** [comment] 2016-07-25 09:17
Pretty sure this is a duplicate issue, but afk so can't find the original

**Comment by snipe** [comment] 2016-07-27 23:02
Duplicate of https://github.com/snipe/snipe-it/issues/1023

**Closed by snipe** 2016-07-27 23:02 UTC
