### ISSUE TITLE
Licenses page does not work properly

### ISSUE THREAD

**Issue by cagcak** [snipe/snipe-it#4199] opened 2017-10-11 15:08 UTC
#### Expected Behavior (or desired behavior if a feature request)

Regular table view like https://demo.snipeitapp.com/licenses 

-----

#### Actual Behavior

Index of /licenses

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Y - Is this a fresh install or an upgrade? 
Y - Version of Snipe-IT you're running
PHP 7.1.6 (VC14 X86 32bit thread safe) + PEARVersion of PHP you're running
MariaDB 10.1.24
- Windows 10 & ApacheFriends XAMPP Version 7.1.6
- manual installation
- WITH DEBUG TURNED ON: production.ERROR: Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. p20sm15111022wma.0 - gsmtp
- no manuel edit database action

**Comment by snipe** [comment] 2017-10-11 21:10
Duplicate of #4031

**Closed by snipe** 2017-10-11 21:10 UTC

**Comment by cagcak** [comment] 2017-10-12 07:56
I am still having the issue. I've already read the [#4031](https://github.com/snipe/snipe-it/issues/4031). Here is the log I got:

> `[2017-10-11 13:35:49] production.ERROR: Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. p20sm15111022wma.0 - gsmtp
#45 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\xampp\htdocs\snipe-IT\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\CheckForSetup.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 C:\xampp\htdocs\snipe-IT\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#80 C:\xampp\htdocs\snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#81 C:\xampp\htdocs\snipe-IT\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#82 {main}  `

**Comment by AnandIndia** [comment] 2017-12-07 11:49
Seriously am having same issues, I can't find the solution.

**Comment by snipe** [comment] 2017-12-07 12:02
@AnandIndia The solution was outlined in the previous ticket. 


> My guess is that XAMPP has some override for /licenses. Unfortunately that's a XAMPP issue, and not a Snipe-IT issue, so I'm not sure what to suggest. Maybe try to override that with an Alias, for example https://gist.github.com/ralphcrisostomo/4974674#file-httpd-conf-L42
