### ISSUE TITLE
Feature Request: Roles and permission

### ISSUE THREAD

**Issue by simsokleang** [snipe/snipe-it#1112] opened 2015-08-24 03:22 UTC
Hello,
I noticed that there's only few permission i can assign to users/groups.
Is it too much if I ask for more permission?

Ex: My IT team is separated into groups such as Support group, System group, etc...
They're responding to difference job. Admin permission is too much for them.
I only want them to create or delete assets/licenses/report, and assign them "read only" permission on People/Group.

I wish to have roles for "Asset", "License", "People", "Report", and each role will have permission "Create", "Delete", "Read", "Deny".

Thanks,
Sokleang.

**Comment by snipe** [comment] 2015-08-26 09:01
This seems like a duplicate of https://github.com/snipe/snipe-it/issues/1097

**Closed** 2015-11-04 13:19 UTC
Labels: duplicate, under consideration
