### ISSUE TITLE
I wanted to know if there is an option in Consumables to check out a large number to a user 

### ISSUE THREAD

**Issue by jnaroz** [snipe/snipe-it#4898] opened 2018-01-23 18:50 UTC
i have an inventory of new Gift cards and i want to use the Consumables menu to keep tack of it .  currently it works fin but i have to check out card by card . is there an option where i can check out 500 cards at the same time to the same user .  i just do nit want to click 500 times . please let me know . 
This is a really good product . thank you

**Comment by snipe** [comment] 2018-01-24 13:32
Duplicate of #1820

**Closed by snipe** 2018-01-24 13:32 UTC
