### ISSUE TITLE
Issue Accepting EULA

### ISSUE THREAD

**Issue by ryan-1982** [snipe/snipe-it#3182] opened 2017-01-12 15:00 UTC
Hi,

I have pretty much finished implementing Snipe-IT and have run into an issue with regards to accepting the emailed EULA ("I have read and agree to the terms of use, and have received this item" link) at the end of "confirm asset delivery" email. When I click the link from the email accepting the EULA I get directed to the Snipe-IT login page. When I successfully authenticate it takes me to the dashboard instead of actually accepting the asset/EULA. Note... if a user is already logged in and then clicks the link to accept the asset/EULA it goes directly to the expected page (working as intended).

Ubuntu 16.04.1
Snipe-IT Version v3.6.3 build 15 (g1bf34d7)

If more details are required I can do my best to get them.

Thanks,

Ryan

**Comment by snipe** [comment] 2017-01-12 15:05
Duplicate of #2303

**Closed by snipe** 2017-01-12 15:05 UTC

**Comment by TMIsnipeIT** [comment] 2017-03-22 11:47
I have checked the "Asset acceptance" in my super admin Settings.
But on Assigning the asset to the user, there is no response through email that asset was assigned to particular user. Already when i have assigned 'ready to deploy' option to the user, still i am not getting mail from the Snipe IT to the user email ID.

Please inform further settings what should do for the email processing to the user and also asset acceptance signature by the user.
please inform this as soon as possible.
Thank you.
