### ISSUE TITLE
Snipeit displaying apache default page after installing with install script.

### ISSUE THREAD

**Issue by pmzhou** [snipe/snipe-it#5690] opened 2018-06-10 12:44 UTC
![screenshot from 2018-06-10 16-43-04](https://user-images.githubusercontent.com/10725833/41201689-75df4d16-6ccd-11e8-8bc2-18088f43537b.png)
- [ Yes] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Install a VM (Ubuntu 16 xenial) - bridged adapter
2. Download the install script and run it
3. Try accessing snipe

**Server (please complete the following information):**
 - Snipe-IT Version : v4.4.1
 - OS: Ubuntu 16 Xenial
 - Web Server: Apache
 - PHP Version : 7.1.17

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Browser : Opera / Firefox

**Error Messages**
**When trying to access SnipeIT i get the default apache page.**

**Comment by snipe** [comment] 2018-06-10 15:08
What's the URL you're trying to access it with?

**Comment by sokeada** [comment] 2018-06-11 01:48
I faced the the same issue. Normally in the older version, after finished everything, i just type the ip address or my server, the browser will directly me to http://server-hostname/setup page but with a fresh install of newer version from 4.4, when i browse it, i only see the apache page.

**Comment by EarlRamirez** [comment] 2018-06-11 14:48
@sokeada are you also using Ubuntu? I have literally tested over a dozen installations and I have not experienced this, the only difference is CentOS was used, will try with Ubuntu and report back, below is what virtual host looks like
<VirtualHost *:80>
ServerAdmin webmaster@localhost
    <Directory /var/www/html/snipeit/public>
        Allow From All
        AllowOverride All
        Options +Indexes
   </Directory>
    DocumentRoot /var/www/html/snipeit/public
    ServerName snipe-it.localdomain
        ErrorLog /var/log/httpd/snipeIT.error.log
        CustomLog /var/log/httpd/access.log combined
</VirtualHost>

**Comment by pmzhou** [comment] 2018-06-12 04:42
I am running in a virtual box ubuntu 16. I destroyed my box and restarted. I ran in the same error and disabled default site then got it up and running.

Thanks.
________________________________

**Comment by sokeada** [comment] 2018-06-20 04:29
@EarlRamirez yes i'm running Ubuntu, thanks for the tips, i will double check it.

**Comment by ts0384** [comment] 2018-07-03 19:29
We are having the same problem. Just loaded up new Ubuntu Server 18.04 and ran the download. Says everything is ready but keeps defaulting to default site. Tried running these commands but different make a difference: 

a2dissite default
a2dissite default-ssl
apachectl graceful

I have to admit it's been a minute since messing with Apache so not sure what I am missing. Thanks

**Comment by EarlRamirez** [comment] 2018-07-16 03:51
@ts0384, @sokeada and @pmzhou are you all running Ubuntu 18, it appears that the default.conf in Ubuntu 18 is very dominant, hence the reason why you once experienced seeing the default home page after the snipeit site was created and apache was reloaded.

Will poke around more to find the root cause of this behaviour, with that said, this is not a Snipe-IT issue but more on at the OS level; therefore, I believe that this issue can be closed.

**Comment by EarlRamirez** [comment] 2018-07-31 18:53
This was resolve with #5998 PR which was merged into the develop branch

**Comment by ts0384** [comment] 2018-10-01 11:54
We never went back and tried a current flavor of linux. We just stuck to
the older version so I'm not sure if it was ever fixed.

**Closed** 2018-10-01 21:28 UTC
Labels: :no_entry_sign:  not a bug

**Comment by davidschmidt88** [comment] 2018-10-23 13:33
Hi, I just installed latest version with the script on a newly created Ubuntu VM 18.04.1 server.
Trying to debug the issue tomorrow!

**Comment by EarlRamirez** [comment] 2018-10-23 14:05
Not too certain what issue you are having, can you create a new issue since this was already closed? We will be happy to help you resolve your issue.

**Comment by davidschmidt88** [comment] 2018-10-24 06:56
Sure, done: https://github.com/snipe/snipe-it/issues/6360
