### ISSUE TITLE
Alert and Email notification are not working

### ISSUE THREAD

**Issue by Timotheus87** [snipe/snipe-it#5317] opened 2018-04-06 14:05 UTC
Hello,

i have a problem with the alert and email notification.

I've added 13 pieces of a printer cartridge for testing. The minimum number of cartridges has been set to 10 pieces. However, if I issue more than three copies, the alarm will not be activated and there will be no email alert as well.
![snipeit](https://user-images.githubusercontent.com/37864774/38425487-487565fa-39b4-11e8-9b77-0d680fd2eb40.PNG)

At the top right on the alarm symbol there is still talk of 13 remaining cartridges.

**Comment by snipe** [comment] 2018-04-06 23:00
Do you have the cron set up to send you email notifications?

**Comment by Timotheus87** [comment] 2018-04-09 06:33
Yes.

**Comment by Timotheus87** [comment] 2018-04-10 09:52
After using the command "sudo /usr/bin/php /var/www/snipeit/artisan snipeit:inventory-alerts" manually, i finally got an email notification.

But the current QTY is wrong and doesn't count down. The remaining QTY should be 8 instead of 13, because i already issued 5 pieces.

**Comment by 5quirrel** [comment] 2018-04-23 04:01
I have the same issue. The alerts qty doesn't seem to take in to account consumed items. You can test this by modifying the total.

**Comment by 5quirrel** [comment] 2018-06-12 01:55
This problem is reproducible in the demo instance...

![image](https://user-images.githubusercontent.com/12634129/41265557-faca7d9c-6e31-11e8-894a-4a5c0d30a68a.png)

Laserjet Paper is on 0 and not flagging
Laserjet Toner is reporting 9 remaining where it should be 6

@snipe it looks like this issue was reported as #4901 and fixed by the user?

**Closed** 2018-07-12 23:49 UTC
Labels: :clock10:  waiting on OP
