### ISSUE TITLE
Checkin Component

### ISSUE THREAD

**Issue by sousa43** [snipe/snipe-it#2818] opened 2016-10-26 16:07 UTC
#### Expected Behavior (or desired behavior if a feature request)
Chekin component from asset
Ex: remove memory from a laptop and add to ready to deploy or broken

-----

#### Actual Behavior

Its not possible to remove component from asset

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.5
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Install.sh

**Comment by snipe** [comment] 2016-10-26 17:17
Duplicate of #1902

**Closed by snipe** 2016-10-26 17:17 UTC
