### ISSUE TITLE
Asset Models - Actions - Create Asset bug

### ISSUE THREAD

**Issue by B3RN0UT** [snipe/snipe-it#3093] opened 2016-12-22 09:44 UTC
#### Expected Behavior (or desired behavior if a feature request)

While clicking on the Asset Models name in the Asset Models overview I would like to create directly an Asset.

-----

#### Actual Behavior

Doing the following in the Asset Models Overview will not create a new Asset:
Asset Models -> Click on the name of "Asset Models" -> Actions -> Create Asset
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on: debian: 8.6 apache: 2.4.10 (Debian)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Asset Models - Actions - Create Asset
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: Yes, reproducable

**Comment by snipe** [comment] 2016-12-22 09:46
Duplicate of #3086

**Closed by snipe** 2016-12-22 09:46 UTC
