### ISSUE TITLE
Users unable to login

### ISSUE THREAD

**Issue by dhajrizi** [snipe/snipe-it#2911] opened 2016-11-11 13:32 UTC
#### Expected Behavior (or desired behavior if a feature request)

Hi there,

I'm facing the same issue with LDAP. Currently, users has been imported successfully but none of them are able to login with domain account. 

-----

#### Actual Behavior

Error: The username or password is incorrect.

error log: 

[2016-11-11 13:37:49] production.DEBUG: LDAP is enabled.  
[2016-11-11 13:37:49] production.DEBUG: Local auth lookup complete  
[2016-11-11 13:37:49] production.DEBUG: Binding user to LDAP.  
[2016-11-11 13:37:49] production.DEBUG: Local user xxxxxx exists in database. Authenticating existing user against LDAP.  
[2016-11-11 13:37:49] production.DEBUG: User xxxxxx did not authenticate correctly against LDAP. Local user was not updated.  
[2016-11-11 13:37:49] production.DEBUG: Authenticating user against database.  
[2016-11-11 13:37:50] production.DEBUG: Local authentication failed. 

Attached is LDAP Config settings.
![image](https://cloud.githubusercontent.com/assets/23400768/20216541/8dabb3ee-a81b-11e6-9456-0ace9ae1df48.png)

Thanks a lot for support

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

System info:

Snipe-IT version	v3.4.0
PHP Version	5.5.38
Laravel Version	5.2.45
Windows 2012 R2, IIS

**Comment by JExactly** [comment] 2016-11-11 13:41
try changing your filter to `&(cn=*)` and if you are not using TLS, disable your ldap SSL cert validation.

Also, I would remove the `@domain` at the end of your ldap bind username

**Comment by dhajrizi** [comment] 2016-11-11 14:13
I changed the filter, I'm not using TLS and removed @domian (with @domain
Test LDAP Fails and I had to add it back). Still no luck, users unable to
login.

any other clue?

thank you

**Comment by JExactly** [comment] 2016-11-11 14:37
what are you running snipeit on? linux, windows?

**Comment by dhajrizi** [comment] 2016-11-11 14:39
Windows 2012 R2 Std, IIS v8.5.96000.16384

**Comment by dhajrizi** [comment] 2016-11-11 14:43
with current filter, when I try to sync users this error appears.

ErrorException in Ldap.php line 264:
ldap_search(): Search: Bad search filter

**Comment by JExactly** [comment] 2016-11-11 14:56
I don't use TLS so that should be the only big difference, and I bind to my top level OU where all my users are nested under. My filter  filters for anything with a CN, and I also filter for active user accounts only.
maybe this will help:
![image](https://cloud.githubusercontent.com/assets/14076881/20218914/d3084546-a7f4-11e6-9a17-9c866a8c7293.png)

**Comment by dhajrizi** [comment] 2016-11-11 15:15
Ok, I'll try again in Monday,

Thanks a lot, I appreciate it.

Regards,
Driton.

**Comment by snipe** [comment] 2016-11-12 03:53
Closed as duplicate of #2904

**Closed by snipe** 2016-11-12 03:53 UTC
