### ISSUE TITLE
Email Language Bug

### ISSUE THREAD

**Issue by SjamonDaal** [snipe/snipe-it#5774] opened 2018-07-04 14:08 UTC
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The email language is defined by the administrator that preforms an action and not by the language of the receiver of the email.
When a admin has set the system to English the user who has set the system to Dutch receives a English email.

**To Reproduce**
Login as admin and set language to English.
Checkout asset to a user that doen't have the language set to English.

The user receives a English email.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.2 - build 3656
 - OS: Debian
 - Web Server: Apache
 - PHP Version: 7.2

**Comment by snipe** [comment] 2018-07-06 01:35
Duplicate of #5554

**Closed by snipe** 2018-07-06 01:35 UTC
