### ISSUE TITLE
companies are not showing

### ISSUE THREAD

**Issue by ahmadsss** [snipe/snipe-it#4654] opened 2017-12-20 07:54 UTC
#### Expected Behavior (or desired behavior if a feature request)

after creating a company it should show in company page

-----

#### Actual Behavior

shows nothing

-----

#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade? FRESH
Version of Snipe-IT you're running - v4.1.8 - build 3106 (master)
Version of PHP you're running - PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Version of MySQL/MariaDB you're running - Server version: 5.7.20-0ubuntu0.16.04.1 (Ubuntu)
What OS and web server you're running Snipe-IT on - Ubuntu 16.0.4 Server version: Apache/2.4.18 (Ubuntu)
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Company Page
If a stacktrace is provided in the error, include that too. 
Any errors that appear in your browser's error console.
[07:47:00] LOG.error: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets.assets.company_id' in 'where clause' in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:

Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. NO

Include any additional information you can find in app/storage/logs and your webserver's logs.
[2017-12-14 14:24:36] production.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:

Include what you've done so far in the installation, and if you got any error messages along the way. no errors in installation None
Indicate whether or not you've manually edited any data directly in the database - none

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2017-12-20 11:19
Duplicate of #4639

**Closed by snipe** 2017-12-20 11:19 UTC
