### ISSUE TITLE
Existing Custom Field Data Overwritten Upon Model Number Change

### ISSUE THREAD

**Issue by ckinsler** [snipe/snipe-it#4777] opened 2018-01-10 03:24 UTC
#### Expected Behavior (or desired behavior if a feature request)

When editing an existing asset and changing its model number (to correct an error), any existing custom fields assigned (that are common between model fieldsets) should have their data preserved instead of being blanked

-----

#### Actual Behavior

When changing an asset model number, all custom fields as part of the new model's fieldset are being blanked, erasing current data contained within them.  If a user doesn't notice this and hits save, the custom field data is blanked in the database.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh

- Version of Snipe-IT you're running
 v4.1.9 - build 3128 (master)

- Version of PHP you're running
PHP 7.0.22

- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.30-MariaDB

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.3 x64, Apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://[URL]/hardware/[ID]/edit

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes, confirmed on: https://demo.snipeitapp.com/hardware/3/edit (Changed Asset #211904681 Model from Macbook Pro 13" to 'Mak Model' which both have the 'company' fieldset on them.  Original company name custom field had "test custom field", and was blanked after model change

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A
- Indicate whether or not you've manually edited any data directly in the database
N/A

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-01-10 04:15
Duplicate of #2195

**Closed by snipe** 2018-01-10 04:15 UTC
