### ISSUE TITLE
Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found

### ISSUE THREAD

**Issue by wxnarwhal** [snipe/snipe-it#7235] opened 2019-07-08 20:49 UTC
#### Expected Behavior (or desired behavior if a feature request)

I expect the web interface to load in a browser

-----

#### Actual Behavior

I attempted an upgrade, and later a fresh install of Snipe-IT that results in an HTTP 500 error.  When I turn on debug I see:

(1/1) FatalThrowableErrorClass 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found
--
in ProviderRepository.php line 208
at ProviderRepository->createProvider('PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider')in ProviderRepository.php line 144

When I did a clean install of Snipe-IT in a Virtual machine it seemed to install without issue, I got to the "Pre-flight" setup page.  Following the migration instructions of importing my database and copying config, public, storage, .env and when I run "php artisan migrate" I get the same error in the migration script.

$ php artisan migrate

In ProviderRepository.php line 208:
                                                                       
  Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found  

So I suspect its an issue with upgrading or the migration of my backups.  I don't actually know how to see my old version of Snipe-IT since it is now broken and the web interface won't load.  I have access to all of the files if there is some place I can look.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? both
- Version of Snipe-IT you're running v4.7.5
- Version of PHP you're running

$ php -v
PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

- Version of MySQL/MariaDB you're running

$ mysql -V
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

- What OS and web server you're running Snipe-IT on

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

$ apache2 -v
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-04-03T13:22:37

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

pull from git and manual install

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(1/1) FatalThrowableErrorClass 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found
--
in ProviderRepository.php line 208
at ProviderRepository->createProvider('PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider')in ProviderRepository.php line 144
at ProviderRepository->compileManifest(array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider', 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Hashing\\HashServiceProvider', 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Pipeline\\PipelineServiceProvider', 'Illuminate\\Queue\\QueueServiceProvider', 'Illuminate\\Redis\\RedisServiceProvider', 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\Translation\\TranslationServiceProvider', 'Illuminate\\Validation\\ValidationServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Eduardokum\\LaravelMailAutoEmbed\\ServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Carbon\\Laravel\\ServiceProvider', 'PragmaRX\\Google2FALaravel\\ServiceProvider', 'Rollbar\\Laravel\\RollbarServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Tightenco\\Ziggy\\ZiggyServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'Tightenco\\Ziggy\\ZiggyServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'App\\Providers\\SettingsServiceProvider', 'App\\Providers\\ValidationServiceProvider', 'App\\Providers\\MacroServiceProvider'))in ProviderRepository.php line 61
at ProviderRepository->load(array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider', 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Hashing\\HashServiceProvider', 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Pipeline\\PipelineServiceProvider', 'Illuminate\\Queue\\QueueServiceProvider', 'Illuminate\\Redis\\RedisServiceProvider', 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\Translation\\TranslationServiceProvider', 'Illuminate\\Validation\\ValidationServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Eduardokum\\LaravelMailAutoEmbed\\ServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Carbon\\Laravel\\ServiceProvider', 'PragmaRX\\Google2FALaravel\\ServiceProvider', 'Rollbar\\Laravel\\RollbarServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Tightenco\\Ziggy\\ZiggyServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'Tightenco\\Ziggy\\ZiggyServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'App\\Providers\\SettingsServiceProvider', 'App\\Providers\\ValidationServiceProvider', 'App\\Providers\\MacroServiceProvider'))in Application.php line 561
at Application->registerConfiguredProviders()in RegisterProviders.php line 17
at RegisterProviders->bootstrap(object(Application))in Application.php line 213
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php line 162
at Kernel->bootstrap()in Kernel.php line 146
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 

any page

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

no I haven't

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2019-07-15 20:04
What happens when you run a `composer install`, and/or the commands detailed here: https://snipe-it.readme.io/docs/common-issues#section-quick-tip-handy-commands

**Comment by snipe** [comment] 2019-07-17 00:53
Duplicate of #7180

**Closed by snipe** 2019-07-17 00:53 UTC
