### ISSUE TITLE
Feature Request - Asset Acceptance, resend mail/ send remainder

### ISSUE THREAD

**Issue by dyefox** [snipe/snipe-it#4943] opened 2018-01-31 08:14 UTC
#### Expected Behavior (or desired behavior if a feature request)

Option to mass/bulk/single resend email remainder to users about unaccepted assets

-----

#### Actual Behavior

Unaccepted Assets only visible in reports, no interaction?

-----

**Comment by jeffclay** [comment] 2018-02-21 17:51
Hi, I'm just wondering approximately where this stands in the priority list on being developed. 

Thank you for the great solution and all the time spent making it!

**Comment by grimstoner** [comment] 2018-03-27 07:50
+1

**Comment by goludiaOH** [comment] 2018-03-27 21:06
Would love this feature - right now having to run the unaccepted assets report, download it then copy all the names to a reminder email (that comes from a person rather than the snipe tool itself) is a hassle.  Not only that, but then the person has to find the old email hoping they didn't delete it from so long ago in order to accept.  If they can't locate that email then there is not an easy way to resend it to them.

**Comment by snipe** [comment] 2018-04-17 02:50
Duplicate of #2294

**Closed by snipe** 2018-04-17 02:50 UTC
Labels: :heart: feature request, :woman_technologist: ready for dev
