### ISSUE TITLE
Feature Request: Add Custom Field to Consumables

### ISSUE THREAD

**Issue by Myrskyvaris** [snipe/snipe-it#4143] opened 2017-10-04 16:10 UTC
#### Expected Behavior (or desired behavior if a feature request)

I'd like to be able to add a field to consumables to indicate which machine a particular consumable is intended for.

(Unless you can already and I just missed it!)

Thank you.

**Comment by snipe** [comment] 2017-10-19 10:02
Duplicate of #4261

**Closed by snipe** 2017-10-19 10:02 UTC
