### ISSUE TITLE
FR - Ability to check out accessory to an asset or location

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#5534] opened 2018-05-14 15:04 UTC
**Server (please complete the following information):**
 - Snipe-IT Version : v4.3.0 - build 3586 (master)
 - OS: CentOS 7

**Is your feature request related to a problem? Please describe.**
Requesting the ability to check out accessories to an asset or location rather than only to a person.

**Describe the solution you'd like**
Additional checkout to options from the accessories checkout page.

**Describe alternatives you've considered**
Creating everything as an asset, and then checking out everything to the "asset kit".

**Comment by snipe** [comment] 2018-05-16 22:56
Duplicate of #5140

**Closed by snipe** 2018-05-16 22:56 UTC

**Comment by closterfield** [comment] 2019-01-31 13:08
Is there any possibility for selecting the check out date in accessories and consumables. as by default its taking the current date of checkout. For example if a user check out the accessories dtd 08.01.2019 and he make an entry dt 31.01.2019, so when i check out its taking the current date i.e 31.01.2019 not 08.01.2019, as there is no options for selecting the date... is there any possibility of implementing this???

**Comment by tymik** [comment] 2019-02-06 12:58
@closterfield i think you should find appropriate issue in already opened or create new one (if not found) for your case - this ticket is about different functionality and is already closed.
