### ISSUE TITLE
Request/Question - Generate a printable form for borrowing asset record with signature

### ISSUE THREAD

**Issue by IVCH5264** [snipe/snipe-it#6862] opened 2019-03-27 06:30 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS:  CentOS 6.5
 - Web Server: Apache
 - PHP Version 6

Is it anywhere that we can integrated the asset delivery email content with their signature ? I think most of us that will need to keep/ past a record (Digital or physical) for audit.

I'm not sure that is it the existing system included or not. Please let me know if the system already have this brilliant feature.

Thanks a lot

**Comment by snipe** [comment] 2019-03-28 04:07
Duplicate of #4651

**Closed by snipe** 2019-03-28 04:07 UTC
