### ISSUE TITLE
Auto-incrementing IDs not working

### ISSUE THREAD

**Issue by jmochnick** [snipe/snipe-it#3409] opened 2017-03-13 18:12 UTC
Expected Behavior (or desired behavior if a feature request)

The asset ID should move up by 1 each time a new asset is created.

Actual Behavior

Assets are stuck on a certain number, we have to manually change the ID each time now

Please confirm you have done the following before posting your bug report:

[ x ] I have enabled debug mode
[ x ] I have read checked the Common Issues page
Please provide answers to these questions before posting your bug report:

v3.6.3 build 15 (g1bf34d7)
RHEL 6.7, Apache
install.sh
No errors
Import is disabled in demo
At one time two users were in the system making an asset, and one finished creating an asset before the other. So, when the second user tried creating the asset, it failed and said the asset ID already exists. Since then, the ID's have not been going up incrementally. We've had that scenario before where two users try to create an asset under the same ID, but this is the first time we have not been able to correct it.

**Comment by snipe** [comment] 2017-03-14 16:00
Duplicate of #3203

**Closed by snipe** 2017-03-14 16:00 UTC
