### ISSUE TITLE
Asset tag field drop down

### ISSUE THREAD

**Issue by akhilptz** [snipe/snipe-it#6030] opened 2018-08-02 08:01 UTC
Snipe-IT Version 4.6.3
OS:Ubuntu 16.04
Web Server:Apache/2.4.18
PHP Version: 7.2.6

This is not a bug but it will help to add the asset tag without re-entering the tag if it is already entered. Now it works like: if we enter a tag that already used then it validated only when we save then we need to go back and enter the new tag again and also we need to check what is the last tag we entered. So if it shows in drop down when we enter then we can enter the unique tag with remembering the previous one.

**Comment by EarlRamirez** [comment] 2018-08-02 10:52
@akhilptz there is an _auto increment_ option for asset tag, this might be something that may help you out. If I understand this correctly, you want to be able to see what tags are already in use, are your tags unique? If yes, _auto increment_ will be your option, if not, it will be a bit tricky.

What is your expectation, let's say that you have 100 assets do you expect to see all tag or as you type the number of _drop down_ will reduce as it searches through the tags?

This looks like a duplicate to #6014.

**Comment by akhilptz** [comment] 2018-08-02 11:38
@EarlRamirez we have two companies and we are using separate tag labels for companies like for company 1 tag starts like XXX-001 and company 2 YYY-001 so the auto-increment is not the option for me.
We want to display the drop-down in fixed size window with a scrollbar. The best example is our asset model selection.

**Comment by akhilptz** [comment] 2018-08-02 11:41
@EarlRamirez I think the case #6014 is same.

**Comment by EarlRamirez** [comment] 2018-08-02 13:03
@akhilptz that is correct it is a duplicate also wanted to touch on the details that are required when raising an issue, there are currently two categories _bug report_ and _feature request_ when these templates are completed we do not have to solicit feedback to obtain the pertinent information to assist you more efficiently. Therefore, in the future complete the template and provide all the information as possible.

**Comment by snipe** [comment] 2018-08-02 16:28
Duplicate of #6014

**Closed by snipe** 2018-08-02 16:28 UTC

**Comment by akhilptz** [comment] 2018-08-03 12:25
@snipe why you closed this and #6014 case. Both the cases don't get an answer.

**Comment by EarlRamirez** [comment] 2018-08-03 12:41
@akhilptz #6014 is still opened.
