### ISSUE TITLE
when a new asset is a checkout/check-in, email alert is not coming to admin'e email id

### ISSUE THREAD

**Issue by arun767** [snipe/snipe-it#5798] opened 2018-07-10 06:16 UTC
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
when a new asset is a checkout/check-in, email alert is not coming to admin'e email id

**Expected behavior**
test mails are coming
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : 4.4.2
 - OS: Ubuntu 16.04
 - Web Server:apache2v 2.4.18
 - PHP Version - v7

**Desktop (please complete the following information):**

**Comment by snipe** [comment] 2018-07-10 23:14
I believe this is a duplicate of #5470

**Closed by snipe** 2018-07-10 23:14 UTC
