### ISSUE TITLE
Register old asset

### ISSUE THREAD

**Issue by fchambos** [snipe/snipe-it#6468] opened 2018-11-29 09:05 UTC
#### Expected Behavior (or desired behavior if a feature request)

I had old asset because we change an old ASM to Snipe-IT.
I create an asset (29/11/2018) 
When I deploy this asset to a people whit a past date (ex : 10/10/2017),
 in history of this asset we see deployed action with 29/11/2018 as date.
Same thing with checkin.

-----

#### Actual Behavior

I hope in history see the date I choose when I register Checkin and checkout.

Thank you so much for your help.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh Install
- Version of Snipe-IT you're running / v4.6.5 build 3915 (gc7596e774)
- Version of PHP you're running / 7.2.10-0ubuntu0.18.04.1
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on / Ubuntu Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2018-12-06 00:17
Duplicate of #5105

**Closed by snipe** 2018-12-06 00:17 UTC
