### ISSUE TITLE
Checking out items from user's page tabs

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5863] opened 2018-07-17 08:13 UTC
Current version 4.5

Hi, tried to search but not sure if there are similar requests. If yes, please do merge this request.

If possible, would like to have the option to check out assets and accessories from user's page tab.

People -> Selected User -> click either Assets / Licenses / Accessories / Consumables -> Check out to user item that belongs to each tab.

![image](https://user-images.githubusercontent.com/38576928/42804532-ea869ea0-89db-11e8-814c-bca576c722ff.png)

Perhaps similar field like the one currently available in bulk check out where you can find the Assets to check out to the user? 

Even though currently there is option to do bulk check out which is limited to Assets, but I am sure Snipe-IT will improve to include Accessories and etc as well in the future; at times we go to each of the user's own profile to make changes but there is no option to checkout anything from user's page.

**Comment by snipe** [comment] 2018-07-17 08:15
Duplicate of #5587

**Closed by snipe** 2018-07-17 08:15 UTC
