### ISSUE TITLE
[Feature Request] Checkout to Location

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2585] opened 2016-09-09 00:43 UTC
#### Expected Behavior (or desired behavior if a feature request)

Feature Request:
Ability to checkout assets to a location rather than a user.

My Scenario:
In my organization, many of our assets are assigned to the building or dept, and the "User" is typically tracked by way of the location and not a specific staff member.

Example:
We have PCs that are available to the public. Lets say we have a branch/company called WO. The PC internal name / what the staff also calls it is WOPAC1 (WO Public Access Computer 01). This PC is on the desk with all the other PACs in the first slot, with a label WOPAC1.

We in our current system, call that "User" WOPAC1, as that is the location which will always be a static location.

Checking out to Locations would be far better for our organization.

I mentioned this in gitter, and it was mentioned that it may be implemented in the next few months, however, I did not find a post on here about it, so wanted to add it for posterity.

-----

#### Actual Behavior

Can currently only checkout asset to Users.

-----

**Comment by victoriapak** [comment] 2016-09-09 02:55
Some info on this at https://github.com/snipe/snipe-it/issues/512
Does that help?

**Comment by snipe** [comment] 2016-09-09 02:59
Duplicate of #142

**Closed by snipe** 2016-09-09 02:59 UTC
