### ISSUE TITLE
Feature Request: Update a consumables total in a simple topup maner.

### ISSUE THREAD

**Issue by Mynty100** [snipe/snipe-it#5463] opened 2018-05-02 04:00 UTC
#### Expected Behavior (or desired behavior if a feature request)

The ability to top up a consumable. 
With printer toner. We have 2 in stock. We check 2 out and order 2 more. Just top up the consumable. 

-----

#### Actual Behavior

Having to edit the Total field. This number getting very large. and seems like it could be handled better.

-----

I realize this is an 'asset' manager not focusing on so much the other features. But this would truly be a god send.

Thanking you,
Mynty.

**Comment by snipe** [comment] 2018-05-02 04:26
Duplicate of #5173

**Closed by snipe** 2018-05-02 04:26 UTC
