### ISSUE TITLE
Multiple company access in permission groups

### ISSUE THREAD

**Issue by Robert-Azelis** [snipe/snipe-it#9621] opened 2021-05-24 09:28 UTC
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.5 build 6055
 - OS: Windows Server 2016
 - Web Server: ISS
 - PHP Version 7.4.13

**Is your feature request related to a problem? Please describe.**
If multiple company option is enabled, only superuser has perimsion access to all companies. 

**Describe the solution you'd like**
Would be great to move this option to permission groups and manage access there. 
Much better will be also add to which companies relevant group should has access.

**Additional context**
![Multi Company access](https://user-images.githubusercontent.com/82208283/119327378-315f5100-bc83-11eb-89ba-b4d2bb7d76da.png)

**Comment by kcoyo** [comment] 2021-07-07 04:25
@Robert-Azelis Are you able to make this work with just users? Company admins can share users assigned to different companies.  More details in #9595.

**Comment by bveina** [comment] 2021-07-21 14:44
this is a valuable use case, we have some IT managers who are hired as half time in two companies, right now in order for them to see all the items i either have to make them super admins or make them two accounts. this would be super useful.

**Comment by jovibroz** [comment] 2021-09-30 22:03
This is a much needed feature. 

I think of it as basic folders permissions on a server. I couldn't live without it :) 

Just give me the different companies as selectable check boxes when setting up the permissions for the user. 
Just like folders.
Just like heaven.

**Comment by snipe** [comment] 2023-03-19 02:23
Duplicate of #8477

**Closed by snipe** 2023-03-19 02:23 UTC
