### ISSUE TITLE
Asset Changed Column to show Object Name instead of Object ID

### ISSUE THREAD

**Issue by matc** [snipe/snipe-it#6069] opened 2018-08-10 17:45 UTC
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 build 3866 (g3de1de9dc)
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache 
 - PHP Version 7.0.31

**Is your feature request related to a problem? Please describe.**
This feature request is related to when an asset is updated.  A few months ago, you added a great new feature in the `Changed` column in an asset and the activity report to show the previous status/model/location/etc of an asset. Unforunately it only shows the id of the object, rather than the object itself. 

**Describe the solution you'd like**
It would be amazing if the `Changed` column showed the name of the object, rather than the id. For example; instead of showing the asset was previously `status_id: 2`, it instead showed it's status was: `Inventory`.

**Describe alternatives you've considered**
The workaround for now has been to constantly have a second tab open with the Statuses/Locations/Models list showing the ID number for reference. 

**Additional context**
I have checked on the Demo version on demo.snipeitapp.com and verified the behavior is the same. Image attached. 
<img width="1607" alt="screen shot 2018-08-10 at 10 41 54 am" src="https://user-images.githubusercontent.com/3361683/43972731-2f7f2250-9c8a-11e8-83c5-e458c10ef257.png">

Please let me know if there is anything else I can provide to help with this feature request. 

Thanks for all your work!
Mat

**Comment by smksar** [comment] 2018-08-12 13:56
I've requested the same #5822 and snipe mentioned it has always been on the roadmap just no timeline attached to it.. v5. 0 maybe? =D

**Comment by jaredgaut** [comment] 2018-08-14 23:27
+1 would love to see this change. When researching issues the name of status_id, location_id, etc would be more useful than ID number.

**Comment by snipe** [comment] 2018-08-15 02:15
Duplicate of #5822

**Closed by snipe** 2018-08-15 02:15 UTC
