### ISSUE TITLE
Default values for custom fields

### ISSUE THREAD

**Issue by DavidGuder** [snipe/snipe-it#3296] opened 2017-02-13 12:45 UTC
Hi there,

for improving usibility of snipe-it further more i was wondering if it is possible or planned to implement default values in custom fields?

In our case it would be nice to have the basic address of our ftp server (ftp://snipe-it.xxx.yy/) preassigned in every asset that has this cusom field. 
The benefit is here that you just need to add the rest of the path which would make things much easier.

Maybe we are not the only ones with this request but i couldn't find any similar case by searching.

We are running snipe-it v3.5.2 on ubuntu server 16.04

Cheers and thanks
David

**Comment by snipe** [comment] 2017-10-11 22:02
Duplicate of #3296

**Closed by snipe** 2017-10-11 22:02 UTC
