### ISSUE TITLE
Can't use category name of a deleted category

### ISSUE THREAD

**Issue by DamianosS** [snipe/snipe-it#1018] opened 2015-08-05 09:30 UTC
Can't use a deleted category name any more. Example:
- created category "Phone"  (several accessories belong to this category)
- created category "Phones" (no assets or accessories belong to this category)
- deleted successfully the category "Phones"
- tried to rename category "Phone" to "Phones": got the error message: "The name has already been taken."

**Comment by DamianosS** [comment] 2015-08-05 09:33
Using version v1.2.8-26

**Comment by balticer** [comment] 2015-08-05 12:00
Asset Models also affected by this behaviour. I'm using latest 2.0 branch.

**Comment by madd15** [comment] 2015-08-05 12:20
This is by design as the app uses soft-deletes, Models has a `View Deleted` button and categories doesn't have one just yet.

Viewing deleted models will allow you to restore the models you have deleted.

**Comment by DamianosS** [comment] 2015-08-05 12:27
Well, this behavior would lead over time to a pile of unused zombie records that nobody needs. I would assume that unused records could be deleted or at least their primary keys would be overwritten with random data that does not conflict with real names.

**Comment by kobie-chasehansen** [comment] 2015-08-05 13:24
I'm curious why you would want to delete anything (besides users) in an asset tracking system. Wouldn't you want the data for future audits/reference?

**Comment by DamianosS** [comment] 2015-08-05 14:02
I don't want to delete anything - please look into the first entry of this thread.

**Comment by snipe** [comment] 2015-08-05 20:57
Fixed in 2.0

**Closed by snipe** 2015-08-05 20:57 UTC
