### ISSUE TITLE
CSV Import corrupt cyrillic symbols

### ISSUE THREAD

**Issue by RDCuser** [snipe/snipe-it#2769] opened 2016-10-12 10:41 UTC
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Successful import of user and asset written in cyrillic.
-----

#### Actual Behavior

(what actually happens goes here)

User and asset imported, but user' name and surname imported as '???????' if it contain cyrillic (russian) symbols.

Example file, contains 1 record.
[test.zip](https://github.com/snipe/snipe-it/files/524133/test.zip)
   
-----

#### Please confirm you have done the following before posting your bug report:

- [1] I have enabled debug mode
- [1] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT: v3.5.0-beta2-53-g87f50df 
- Windows Server 2012 R2, also tried Ubuntu Server 16.04 + Apache + MySQL
- Manual installation
- No errors in browser
- No stacktrace is provided
- No errors in browser's error console.
- Import doesnt work in demo (https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Did not manually edited any data directly in the database

**Comment by RDCuser** [comment] 2016-10-12 13:31
Not sure it's a snipe-it problem but i test it on different platforms with no luck. Would be awesome if someone try to import sample file with cyrillic (rus) text.

**Comment by snipe** [comment] 2016-10-12 21:11
Duplicate of #2740

**Closed by snipe** 2016-10-12 21:11 UTC
